Repository near/nearcore, pull requests merged in 2018-12, with the labels that each got.

#101 Add Misbehaviour trait
  core/txflow/src/dag/mod.rs
  core/txflow/src/dag/reporter.rs
Labels: testing

#132 Starting reworking node code, starting with cli. #121
  Cargo.toml
  node/cli2/Cargo.toml
  node/cli2/res/default_chain.json
  node/cli2/src/chain_spec.rs
  node/cli2/src/lib.rs
Labels: enhancement

#133 Initial code for spawning the network #121
  Cargo.toml
  node/cli2/Cargo.toml
  node/cli2/src/chain_spec.rs
  node/cli2/src/lib.rs
  node/network2/Cargo.toml
  node/network2/src/lib.rs
  node/network2/src/protocol_config.rs
Labels: enhancement

#138 Remove network2
  Cargo.toml
  node/cli2/Cargo.toml
  node/cli2/src/lib.rs
  node/network2/Cargo.toml
  node/network2/src/lib.rs
  node/network2/src/protocol_config.rs
Labels: enhancement

#142 Some network-related code cleanup
  node/cli/src/lib.rs
  node/network/src/io.rs
  node/network/src/lib.rs
  node/network/src/network_handler.rs
  node/network/src/protocol.rs
  node/service/src/lib.rs
  test-utils/node/src/main.rs
Labels: enhancement

#145 Making network code more flexible
  core/beacon/src/authority.rs
  core/beacon/src/types.rs
  core/chain/src/lib.rs
  core/primitives/src/traits.rs
  node/beacon-chain-handler/Cargo.toml
  node/beacon-chain-handler/src/importer.rs
  node/beacon-chain-handler/src/lib.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli2/Cargo.toml
  node/cli2/src/lib.rs
  node/client/src/chain.rs
  node/client/src/lib.rs
  node/network/src/io.rs
  node/network/src/network_handler.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  node/service/src/lib.rs
  node/service/src/produce_blocks.rs
  node/service/src/test_utils.rs
  test-utils/node/src/main.rs
Labels: enhancement

#152 Remove node/client and node/service. Thin down node/network. This is how everything should look like without TxFlow.
  Cargo.toml
  core/wasm/src/memory.rs
  core/wasm/src/prepare.rs
  node/cli/Cargo.toml
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
  node/cli2/Cargo.toml
  node/cli2/res/default_chain.json
  node/cli2/src/chain_spec.rs
  node/cli2/src/lib.rs
  node/client/Cargo.toml
  node/client/src/chain.rs
  node/client/src/import_queue.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/client/src/tx_pool.rs
  node/network/Cargo.toml
  node/network/src/io.rs
  node/network/src/lib.rs
  node/network/src/network_handler.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  node/runtime/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/produce_blocks.rs
  node/service/src/test_utils.rs
  node/src/main.rs
  scripts/run_clippy.sh
  test-utils/devnet/Cargo.toml
  test-utils/devnet/src/main.rs
  test-utils/node/Cargo.toml
  test-utils/node/src/main.rs
  tests/test_rpc_cli.rs
Labels: enhancement

#192 Prepare code for integrating with TxFlow #191
  core/primitives/src/traits.rs
  core/primitives/src/types.rs
  core/txflow/Cargo.toml
  core/txflow/src/dag/message/testing_utils.rs
  core/txflow/src/lib.rs
  core/txflow/src/testing_utils.rs
  core/txflow/src/txflow_task/fake_network.rs
  node/beacon-chain-handler/src/importer.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
  node/cli/src/test_utils.rs
  node/network/src/message.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  test-utils/devnet/src/lib.rs
Labels: enhancement

#255 Task for converting transactions to payloads
  core/primitives/src/types.rs
  core/txflow/src/adapters/mod.rs
  core/txflow/src/adapters/transaction_to_payload.rs
  core/txflow/src/lib.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/src/service.rs
  node/cli/src/test_utils.rs
  node/network/src/test_utils.rs
Labels: consensus

#266 Interface consensus through adapters
  core/txflow/src/adapters/mod.rs
  core/txflow/src/adapters/receipt_transaction_to_payload.rs
  core/txflow/src/adapters/signed_transaction_to_payload.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/cli/src/test_utils.rs
  node/network/src/protocol.rs
  node/network/src/test_utils.rs
  node/network/tests/integration_test.rs
Labels: consensus

#267 Communicate gossip with the network
  Cargo.toml
  core/txflow/src/lib.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/consensus/Cargo.toml
  node/consensus/src/adapters/gossip_to_network_message.rs
  node/consensus/src/adapters/mod.rs
  node/consensus/src/adapters/receipt_transaction_to_payload.rs
  node/consensus/src/adapters/signed_transaction_to_payload.rs
  node/consensus/src/lib.rs
  node/consensus/src/passthrough.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  node/network/tests/integration_test.rs
  test-utils/devnet/Cargo.toml
  test-utils/devnet/src/lib.rs
Labels: consensus

#281 Control signal for TxFlow
  core/beacon/Cargo.toml
  core/primitives/src/traits.rs
  core/txflow/Cargo.toml
  core/txflow/src/dag/mod.rs
  core/txflow/src/txflow_task/beacon_witness_selector.rs
  core/txflow/src/txflow_task/fake_network.rs
  core/txflow/src/txflow_task/mod.rs
Labels: consensus

#302 Compute consensus and output it into the channel
  core/txflow/src/dag/message/generated_tests.rs
  core/txflow/src/dag/message/group.rs
  core/txflow/src/dag/message/group_approvals.rs
  core/txflow/src/dag/message/mod.rs
  core/txflow/src/dag/message/testing_utils.rs
  core/txflow/src/dag/mod.rs
  core/txflow/src/dag/reporter.rs
  core/txflow/src/txflow_task/beacon_witness_selector.rs
  core/txflow/src/txflow_task/fake_network.rs
  core/txflow/src/txflow_task/mod.rs
Labels: consensus, enhancement

#307 TestNet. Assemble Authority+Network+TxFlow
  core/txflow/src/txflow_task/mod.rs
  node/beacon-chain-handler/Cargo.toml
  node/beacon-chain-handler/src/authority_handler.rs
  node/beacon-chain-handler/src/lib.rs
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/consensus/Cargo.toml
  node/consensus/src/adapters/gossip_to_network_message.rs
  node/consensus/src/adapters/mod.rs
  node/consensus/src/lib.rs
  node/consensus/src/passthrough.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/tests/integration_test.rs
Labels: testnet

#312 Fixed #311
  node/consensus/src/passthrough.rs
Labels: bug, consensus
