Repository near/nearcore, pull requests merged in 2019-03, with the labels that each got.

#724 Block production should be able to unlock pending blocks
  node/alphanet/src/lib.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/consensus/src/passthrough.rs
  node/coroutines/src/client_task.rs
  node/http/src/api.rs
  node/network/src/protocol.rs
  node/shard/src/lib.rs
Labels: bug, testnet

#742 Fixes #740. BlockProducerKeyFile should be stored entirely in b58
  core/primitives/src/signature.rs
  core/primitives/src/signer.rs
Labels: bug

#775 Fixes #771: Correct death row tracking in Trie
  Cargo.lock
  core/storage/src/trie/mod.rs
  node/configs/src/client.rs
  node/configs/src/devnet.rs
  node/devnet/Cargo.toml
  node/devnet/src/lib.rs
Labels: bug

#796 Remove compiled-in chain spec files. Refactor how ChainSpec is used.
  core/wasm/runtest/src/lib.rs
  node/configs/res/default_chain.json
  node/configs/res/poa_testnet_chain.json
  node/configs/src/chain_spec.rs
  node/configs/src/client.rs
  test-utils/testlib/src/alphanet_utils.rs
  test-utils/testlib/src/generate_test_spec.rs
Labels: housekeeping

#798 Use short syntax for default
  core/mempool/src/payload_gossip.rs
  core/nightshade/src/nightshade.rs
  core/nightshade/src/nightshade_task.rs
  core/primitives/src/beacon.rs
  core/primitives/src/chain.rs
  core/primitives/src/network.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  node/beacon/src/authority.rs
  node/network/src/message.rs
Labels: housekeeping

#800 Increase latency of the CI tests, multiple CI runners compete for the…
  tests/test_alphanet.rs
Labels: enhancement

#807 Typo in PoA config
  node/configs/src/lib.rs
Labels: bug
