Repository near/nearcore, pull requests merged in 2019-01, with the labels that each got.

#327 Speeding up CI
  .gitlab-ci.yml
  node/runtime/src/lib.rs
  scripts/waitonserver.sh
Labels: housekeeping

#328 Improvements for Authority #308
  core/beacon/src/authority.rs
  core/beacon/src/types.rs
  node/beacon-chain-handler/src/authority_handler.rs
  node/cli/src/chain_spec.rs
  node/cli/src/service.rs
  node/consensus/src/adapters/signed_transaction_to_payload.rs
  node/http/src/types.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  node/runtime/benches/bench.rs
  node/runtime/src/lib.rs
Labels: housekeeping

#389 Carving out some code that will go into Client
  Cargo.lock
  Cargo.toml
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/client/Cargo.toml
  node/client/res/default_chain.json
  node/client/src/chain_spec.rs
  node/client/src/lib.rs
  node/src/lib.rs
  test-utils/chain-spec-builder/Cargo.toml
  test-utils/chain-spec-builder/src/main.rs
  test-utils/devnet/Cargo.toml
  test-utils/devnet/src/bin/devnet.rs
  test-utils/devnet/src/lib.rs
  tests/test_rpc_cli.rs
Labels: testnet

#392 Disable flaky integration test, see #391.
  tests/test_rpc_cli.rs
Labels: bug

#397 Merge authority handler into producer. Disable importer, because it was broke…
  core/beacon/src/authority.rs
  core/txflow/src/txflow_task/mod.rs
  node/beacon-chain-handler/src/authority_handler.rs
  node/beacon-chain-handler/src/lib.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/src/service.rs
  node/client/src/chain_spec.rs
  node/client/src/lib.rs
Labels: testnet

#407 Master fix
  core/beacon/src/authority.rs
Labels: bug

#423 Replace chain with client in network layer
  Cargo.lock
  core/primitives/src/signer.rs
  node/beacon-chain-handler/src/producer.rs
  node/cli/src/service.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/network/Cargo.toml
  node/network/src/lib.rs
  node/network/src/protocol.rs
  node/network/src/test_utils.rs
  node/network/tests/integration_test.rs
  node/runtime/benches/bench.rs
  node/runtime/src/lib.rs
  node/runtime/src/test_utils.rs
  test-utils/chain-spec-builder/src/main.rs
Labels: testnet

#436 Major refactoring of the node
  Cargo.lock
  Cargo.toml
  core/primitives/src/traits.rs
  core/primitives/src/types.rs
  core/txflow/src/dag/message/mod.rs
  core/txflow/src/txflow_task/beacon_witness_selector.rs
  node/beacon-chain-handler/src/producer.rs
  node/beacon/Cargo.toml
  node/beacon/src/authority.rs
  node/beacon/src/lib.rs
  node/beacon/src/types.rs
  node/cli/Cargo.toml
  node/cli/src/lib.rs
  node/cli/src/service.rs
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/configs/Cargo.toml
  node/configs/res/default_chain.json
  node/configs/src/authority.rs
  node/configs/src/chain_spec.rs
  node/configs/src/client.rs
  node/configs/src/devnet.rs
  node/configs/src/lib.rs
  node/configs/src/network.rs
  node/configs/src/rpc.rs
  node/consensus/Cargo.toml
  node/consensus/src/lib.rs
  node/coroutines/Cargo.toml
  node/coroutines/src/control_builder.rs
  node/coroutines/src/importer.rs
  node/coroutines/src/lib.rs
  node/coroutines/src/producer.rs
  node/devnet/Cargo.toml
  node/devnet/src/bin/devnet.rs
  node/devnet/src/lib.rs
  node/http/Cargo.toml
  node/http/src/types.rs
  node/network/Cargo.toml
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/network/src/test_utils.rs
  node/runtime/Cargo.toml
  node/runtime/src/chain_spec.rs
  node/runtime/src/lib.rs
  node/runtime/src/test_utils.rs
  node/src/lib.rs
  node/src/main.rs
  scripts/run_clippy.sh
  test-utils/chain-spec-builder/Cargo.toml
  test-utils/chain-spec-builder/src/main.rs
  test-utils/devnet/Cargo.toml
  test-utils/devnet/src/bin/devnet.rs
  test-utils/devnet/src/lib.rs
  test-utils/node/Cargo.toml
  test-utils/node/src/main.rs
  tests/test_rpc_cli.rs
Labels: testnet

#444 Fixing receipts rollover. Removing unnecessary spawning
  core/primitives/src/signer.rs
  core/wasm/runtest/src/lib.rs
  node/configs/src/authority.rs
  node/configs/src/chain_spec.rs
  node/configs/src/client.rs
  node/configs/src/lib.rs
  node/configs/src/network.rs
  node/configs/src/rpc.rs
  node/consensus/src/adapters/receipt_transaction_to_payload.rs
  node/consensus/src/adapters/transaction_to_payload.rs
  node/consensus/src/passthrough.rs
  node/coroutines/src/importer.rs
  node/coroutines/src/producer.rs
Labels: testnet

#460 Working testnet
  Cargo.lock
  core/chain/Cargo.toml
  core/chain/src/lib.rs
  core/primitives/src/types.rs
  core/txflow/src/dag/message/testing_utils.rs
  core/txflow/src/dag/mod.rs
  core/txflow/src/testing_utils.rs
  core/txflow/src/txflow_task/fake_network.rs
  core/txflow/src/txflow_task/mod.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/configs/res/testnet_chain.json
  node/configs/src/client.rs
  node/consensus/src/passthrough.rs
  node/coroutines/src/control_builder.rs
  node/coroutines/src/importer.rs
  node/coroutines/src/producer.rs
  node/devnet/src/lib.rs
  node/network/Cargo.toml
  node/network/src/message.rs
  node/network/src/protocol.rs
  node/network/src/service.rs
  node/runtime/src/lib.rs
  node/testnet/Cargo.toml
  node/testnet/src/lib.rs
Labels: testnet

#470 Add instructions how to launch TestNet locally
  README.md
Labels: testnet

#486 Collect logs into FinalTransactionResult for given get_transaction_info
  core/transaction/src/lib.rs
  nearlib/test/integration.test.js
  node/http/src/api.rs
  node/http/src/types.rs
  node/shard/src/lib.rs
Labels: transaction

#487 Fix that passthrough consensus didn't start from last beacon block
  node/consensus/src/passthrough.rs
  node/devnet/src/lib.rs
Labels: bug
