Repository near/nearcore, pull requests merged in 2019-10, with the labels that each got.

#1312 New networking API
  Cargo.lock
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/tests/bug_repros.rs
  chain/client/tests/process_blocks.rs
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/src/codec.rs
  chain/network/src/lib.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  chain/network/tests/announce_account.rs
  chain/network/tests/peer_handshake.rs
  chain/network/tests/routing.rs
  core/crypto/src/signature.rs
  core/primitives/src/utils.rs
  near/tests/run_nodes.rs
Labels: needs: rebase

#1452 Sodiumoxide vulnerability fix
  Cargo.lock
  core/crypto/Cargo.toml
  core/primitives/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/runtime/Cargo.toml
Labels: autorebase

#1450 Add a check into Runtime to compare input and output balances
  near/src/runtime.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/verifier/src/lib.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: autosquash

#1483 Clutch for #1481
  core/store/src/trie/update.rs
  runtime/runtime/src/lib.rs
Labels: automerge

#1455 [Fees estimation] Add contract method to correlate CPU usage and gas
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/test-contract/res/large_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/large_payload
  runtime/runtime-params-estimator/test-contract/res/medium_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/medium_payload
  runtime/runtime-params-estimator/test-contract/res/small_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/small_payload
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: automerge

#1478 Make verbose more flexible
  near/src/main.rs
Labels: automerge

#1477 Enable coredumps in run_docker.sh
  Dockerfile
  scripts/run_docker.sh
Labels: automerge

#1496 Use information returned from runtime for reward calculation
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/tests/challenges.rs
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/proposals.rs
  chain/epoch_manager/src/reward_calculator.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/types.rs
  core/primitives/src/block.rs
  core/primitives/src/sharding.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  genesis-tools/genesis-populate/src/lib.rs
  near/src/runtime.rs
  near/src/shard_tracker.rs
  test-utils/state-viewer/src/main.rs
Labels: automerge

#1495 minimum sized docker image
  Dockerfile
  Dockerfile.prod
  Makefile
Labels: automerge

#1403 Proper check for transaction history validation
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/client.rs
  chain/client/tests/process_blocks.rs
  chain/jsonrpc/tests/rpc_transactions.rs
Labels: automerge

#1493 Dont panic for check balance
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  core/primitives/src/errors.rs
  near/src/runtime.rs
  runtime/runtime/src/lib.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#1437 pytest for remote node
  pytest/Pipfile
  pytest/Pipfile.lock
  pytest/lib/cluster.py
  pytest/lib/gcloud.py
  pytest/requirements.txt
  pytest/scripts/create_instance_pool.sh
  pytest/scripts/delete_instance_pool.sh
  pytest/tests/sanity/block_production.py
  pytest/tests/sanity/remote.py
  rust-toolchain
Labels: automerge

#1512 Remove some unnecessary unsafe code
  chain/chain/src/error.rs
  chain/client/src/client.rs
  chain/network/src/codec.rs
Labels: automerge

#1513 Handle head method for status check
  chain/jsonrpc/src/lib.rs
Labels: automerge

#1528 recover system coredump by Misha for minimize docker image
  Dockerfile.prod
Labels: automerge

#1497 Move rewards to runtime
  core/primitives/src/errors.rs
  core/store/src/trie/update.rs
  near/src/runtime.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#1527 Fix a dependency
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/signature.rs
Labels: automerge

#1529 update rust-toolchain
  Cargo.lock
  Cargo.toml
  async-utils/src/lib.rs
  chain/chain/src/chain.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/lib.rs
  rust-toolchain
  test-utils/testlib/src/user/rpc_user.rs
Labels: automerge

#1530 Fix some warnings
  core/primitives/src/hash.rs
  core/primitives/src/views.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/nibble_slice.rs
  core/store/src/trie/update.rs
  genesis-tools/genesis-populate/src/lib.rs
  near/src/config.rs
  near/src/runtime.rs
  near/src/shard_tracker.rs
  test-utils/state-viewer/src/main.rs
  test-utils/testlib/src/actix_utils.rs
Labels: automerge

#1541 Bump near-vm-* to 0.3.1
  Cargo.lock
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-runtime-fees/README.md
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/README.md
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
Labels: automerge

#1531 working coredump for docker
  Dockerfile.prod
  Makefile
  scripts/nodelib.py
Labels: automerge

#1532 Update dependencies
  Cargo.lock
  Cargo.toml
  async-utils/Cargo.toml
  chain/chain/src/test_utils.rs
  chain/chunks/Cargo.toml
  chain/client/Cargo.toml
  chain/client/tests/chunks_management.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/proposals.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/client/Cargo.toml
  chain/jsonrpc/client/src/message.rs
  chain/network/Cargo.toml
  chain/pool/Cargo.toml
  core/crypto/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  near/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/loadtester/Cargo.toml
  test-utils/loadtester/src/main.rs
  test-utils/state-viewer/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: automerge

#1462 Genesis csv to Genesis json tool + key generator
  Cargo.lock
  Cargo.toml
  chain/network/src/types.rs
  core/crypto/src/signature.rs
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-csv-to-json/res/test_accounts.csv
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
  genesis-tools/genesis-csv-to-json/src/main.rs
  genesis-tools/genesis-csv-to-json/src/serde_with.rs
  genesis-tools/keypair-generator/Cargo.toml
  genesis-tools/keypair-generator/src/main.rs
  near/src/config.rs
Labels: automerge

#1544 Rpc transaction routing
  Cargo.lock
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/reward_calculator.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
  chain/jsonrpc/tests/rpc_transactions.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  chain/pool/src/lib.rs
  chain/telemetry/src/lib.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  core/store/benches/trie_bench.rs
  near/tests/tx_propagation.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/rpc_tx_forwarding.py
  test-utils/testlib/src/node/process_node.rs
  test-utils/testlib/src/node/runtime_node.rs
  test-utils/testlib/src/node/thread_node.rs
  test-utils/testlib/src/user/rpc_user.rs
Labels: automerge

#1557 Fix some issues related to genesis and running nodes
  chain/jsonrpc/src/lib.rs
  genesis-tools/genesis-csv-to-json/res/test_accounts.csv
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
  scripts/nodelib.py
Labels: automerge

#1563 fix a few queries which was work for only one node by aggregate
  conf/grafana-dashboard.json
Labels: automerge

#1564 Cargo bug workaround
  Cargo.lock
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/publish.sh
Labels: automerge

#1565 Fix bad test in near-vm-logic
  runtime/near-vm-logic/tests/test_miscs.rs
Labels: automerge

#1567 adding genesis tools for stakewars into dockerfile
  Dockerfile
  Dockerfile.prod
  Makefile
Labels: automerge

#1568 Fix unused return values in serialization
  core/crypto/src/signature.rs
Labels: automerge

#1566 Update borsh to 0.2.9
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/epoch_manager/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/network/Cargo.toml
  core/crypto/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  genesis-tools/genesis-populate/Cargo.toml
  near/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: automerge

#1569 update bootnode ip
  scripts/start_testnet.py
Labels: automerge

#1583 do not remove docker build to avoid sudo
  .gitignore
  Makefile
Labels: automerge

#1562 Improve genesis tools
  genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
  genesis-tools/keypair-generator/src/main.rs
  near/Cargo.toml
  scripts/nodelib.py
Labels: automerge

#1584 Code ownership for genesis tools
  CODEOWNERS
Labels: automerge

#1517 Network update
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/types.rs
  chain/network/tests/peer_handshake.rs
  chain/network/tests/routing.rs
  near/tests/run_nodes.rs
Labels: automerge
