Repository near/nearcore, pull requests merged in 2019-04, with the labels that each got.

#825 InMemorySigner should not have a default constructor
  core/nightshade/benches/bench.rs
  core/nightshade/src/fake_network.rs
  core/primitives/src/signer.rs
  node/beacon/src/beacon_chain.rs
  node/client/benches/client_bench.rs
  node/configs/src/client.rs
  node/devnet/src/lib.rs
  node/runtime/src/system.rs
Labels: housekeeping

#834 Reorganize crypto primitives
  core/mempool/src/lib.rs
  core/mempool/src/payload_gossip.rs
  core/nightshade/benches/bench.rs
  core/nightshade/src/fake_network.rs
  core/nightshade/src/nightshade.rs
  core/nightshade/src/nightshade_task.rs
  core/nightshade/src/testing_utils.rs
  core/nightshade/src/verifier.rs
  core/primitives/benches/bls.rs
  core/primitives/src/beacon.rs
  core/primitives/src/block_traits.rs
  core/primitives/src/chain.rs
  core/primitives/src/consensus.rs
  core/primitives/src/crypto/aggregate_signature.rs
  core/primitives/src/crypto/group_signature.rs
  core/primitives/src/crypto/mod.rs
  core/primitives/src/crypto/signature.rs
  core/primitives/src/crypto/signer.rs
  core/primitives/src/lib.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  node/beacon/src/beacon_chain.rs
  node/client/benches/client_bench.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/configs/src/authority.rs
  node/configs/src/chain_spec.rs
  node/coroutines/src/client_task.rs
  node/devnet/src/lib.rs
  node/http/src/types.rs
  node/runtime/src/lib.rs
  node/runtime/src/state_viewer.rs
  node/runtime/src/system.rs
  node/runtime/src/test_utils.rs
  node/shard/src/lib.rs
  test-utils/keygen/src/main.rs
  test-utils/testlib/src/alphanet_utils.rs
Labels: enhancement, housekeeping

#830 Optional account
  .gitlab-ci.yml
  core/mempool/src/lib.rs
  core/mempool/src/payload_gossip.rs
  core/nightshade/benches/bench.rs
  core/nightshade/src/fake_network.rs
  core/nightshade/src/nightshade.rs
  core/nightshade/src/nightshade_task.rs
  core/nightshade/src/testing_utils.rs
  core/primitives/src/block_traits.rs
  core/primitives/src/consensus.rs
  core/primitives/src/crypto/signer.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/transaction.rs
  node/alphanet/src/lib.rs
  node/beacon/src/beacon_chain.rs
  node/client/benches/client_bench.rs
  node/client/src/lib.rs
  node/client/src/test_utils.rs
  node/configs/src/chain_spec.rs
  node/configs/src/client.rs
  node/consensus/src/passthrough.rs
  node/coroutines/src/client_task.rs
  node/devnet/src/lib.rs
  node/http/src/api.rs
  node/http/src/server.rs
  node/network/src/protocol.rs
  node/runtime/src/system.rs
  node/runtime/src/test_utils.rs
  node/shard/src/lib.rs
  test-utils/testlib/src/alphanet_utils.rs
  test-utils/testlib/src/node_user.rs
  tests/test_alphanet.rs
  tests/test_alphanet_command_line.rs
  tests/tests_custom_handler.rs
Labels: testnet

#842 Regression test for asserting througput tps
  test-utils/testlib/src/alphanet_utils.rs
  test-utils/testlib/src/node_user.rs
  tests/test_alphanet.rs
  tests/test_alphanet_command_line.rs
  tests/test_alphanet_tps_regression.rs
  tests/tests_custom_handler.rs
Labels: testing

#844 Studio version {0.1.6, 0.1.7} -> 0.1.8
  ops/deploy_alphanet.sh
  ops/local_alphanet.sh
  ops/update_studio.sh
Labels: housekeeping

#848 Prepare testlib for more Nodes/Users and to be used for load testing
  node/alphanet/src/lib.rs
  node/devnet/src/lib.rs
  test-utils/testlib/src/alphanet_utils.rs
  test-utils/testlib/src/lib.rs
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/node/process_node.rs
  test-utils/testlib/src/node/remote_node.rs
  test-utils/testlib/src/node/thread_node.rs
  test-utils/testlib/src/node_user.rs
  test-utils/testlib/src/test_helpers.rs
  test-utils/testlib/src/test_locks.rs
  test-utils/testlib/src/user/mod.rs
  test-utils/testlib/src/user/rpc_user.rs
  test-utils/testlib/src/user/thread_user.rs
  tests/test_alphanet.rs
  tests/test_alphanet_command_line.rs
  tests/test_alphanet_tps_regression.rs
  tests/tests_custom_handler.rs
Labels: housekeeping, testing

#850 Generating and executing transactions in bulk
  test-utils/testlib/src/lib.rs
  test-utils/testlib/src/sampler.rs
  test-utils/testlib/src/transactions_executor.rs
  test-utils/testlib/src/transactions_generator.rs
Labels: testing

#851 Node observer
  test-utils/testlib/src/lib.rs
  test-utils/testlib/src/nodes_monitor.rs
Labels: testing

#853 Load tester entry point
  Cargo.lock
  Cargo.toml
  test-utils/loadtester/Cargo.toml
  test-utils/loadtester/src/main.rs
  test-utils/testlib/src/node/remote_node.rs
Labels: testing

#861 Load tester that can exercise remote or local testnet
  Cargo.lock
  node/configs/src/chain_spec.rs
  ops/deploy_alphanet.sh
  ops/local_alphanet.sh
  test-utils/loadtester/Cargo.toml
  test-utils/loadtester/src/main.rs
  test-utils/testlib/src/nodes_monitor.rs
  test-utils/testlib/src/transactions_executor.rs
  test-utils/testlib/src/transactions_generator.rs
  test-utils/testlib/src/user/rpc_user.rs
Labels: testing

#870 Make load testing more asynchronous
  Cargo.lock
  ops/deploy_alphanet.sh
  test-utils/loadtester/README.md
  test-utils/loadtester/src/main.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/node/process_node.rs
  test-utils/testlib/src/node/remote_node.rs
  test-utils/testlib/src/transactions_executor.rs
  test-utils/testlib/src/user/mod.rs
  test-utils/testlib/src/user/rpc_user.rs
Labels: testing, testnet

#883 Test that checks whether a node can catchup
  tests/test_catchup.rs
Labels: testing
