Repository near/nearcore, pull requests merged in 2020-02, with the labels that each got.

#2085 Move sysinfo fix from staging
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/info.rs
Labels: automerge

#2045 Add keccak native support
  Cargo.lock
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/config.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/test-contract/src/lib.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/ext.rs
  tools/rpctypegen/core/Cargo.toml
  tools/rpctypegen/macro/Cargo.toml
Labels: automerge

#2089 Update wasmer to 13.1
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
Labels: automerge

#2131 Release docker build
  scripts/docker-release.sh
Labels: automerge

#2127 feat(rpc): allow rpc to specify finality in query
  Cargo.lock
  chain/client/src/types.rs
  chain/client/src/view_client.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/query_client.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/tests/rpc_query.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  core/primitives/src/rpc.rs
  core/primitives/src/views.rs
  near/tests/stake_nodes.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/rpc_finality.py
Labels: P1, RPC, misterwhite

#2002 Disable codecov status check
  .gitlab-ci.yml
Labels: automerge

#2114 Nightly log on gcloud and cross reference test <> run
  nightly/nightly.py
  nightly/run_nightly.sh
Labels: automerge

#2142 Fix(Runtime): Fix and refactor StorageUsageConfig
  runtime/near-runtime-fees/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/tests/test_storage_usage.rs
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
Labels: runtime

#2161 Move nightly runner to separate repo
  nightly/README.md
  nightly/nightly.py
  nightly/requirements.txt
  nightly/run_nightly.sh
Labels: automerge

#1876 Block production summary in 100 node
  near/src/lib.rs
  pytest/Pipfile
  pytest/Pipfile.lock
  pytest/lib/cluster.py
  pytest/lib/utils.py
  pytest/requirements.txt
  pytest/tests/delete_remote_nodes.py
  pytest/tests/sanity/lightclnt.py
  pytest/tests/stress/hundred_nodes/100_node_block_production.py
  pytest/tests/stress/hundred_nodes/README.md
  pytest/tests/stress/hundred_nodes/block_chunks.py
  pytest/tests/stress/hundred_nodes/collect_logs.py
  pytest/tests/stress/hundred_nodes/create_gcloud_image.py
  pytest/tests/stress/hundred_nodes/create_prometheus_targets.py
  pytest/tests/stress/hundred_nodes/start_100_nodes.py
  pytest/tests/stress/hundred_nodes/watch_fork.py
Labels: automerge

#2188 fix(runtime): Fix empty method_names bug
  Cargo.lock
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/utils.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
Labels: bug, runtime

#2178 Avoid panic while panicking because of actix isn't running
  Cargo.lock
  Cargo.toml
  core/primitives/src/test_utils.rs
Labels: automerge

#2155 feat(runtime): Validate incoming receipts
  core/primitives/src/errors.rs
  near/src/runtime.rs
  runtime/runtime/src/lib.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: runtime

#2201 fix: Fixing nightly python tests
  chain/chain/src/store.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  nightly/nightly.txt
  pytest/lib/cluster.py
  pytest/lib/lightclient.py
  pytest/lib/utils.py
  pytest/tests/sanity/block_production.py
  pytest/tests/sanity/block_sync.py
  pytest/tests/sanity/lightclnt.py
  pytest/tests/sanity/one_val.py
  pytest/tests/sanity/skip_epoch.py
  pytest/tests/sanity/staking1.py
  pytest/tests/sanity/staking2.py
  pytest/tests/sanity/staking_repro1.py
  pytest/tests/sanity/staking_repro2.py
  pytest/tests/sanity/state_sync1.py
Labels: automerge

#2203 fix: Fix pytest after log to stderr
  .gitignore
  pytest/lib/cluster.py
Labels: automerge

#2109 Expose genesis config and records via RPC
  Cargo.lock
  chain/chain/src/chain.rs
  chain/client/tests/challenges.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/client/Cargo.toml
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/client/src/message.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/test_utils.rs
  chain/jsonrpc/tests/http_query.rs
  chain/jsonrpc/tests/rpc_query.rs
  chain/jsonrpc/tests/rpc_transactions.rs
  chain/jsonrpc/tests/test_utils.rs
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/account.rs
  core/primitives/src/block.rs
  core/primitives/src/challenge.rs
  core/primitives/src/lib.rs
  core/primitives/src/merkle.rs
  core/primitives/src/network.rs
  core/primitives/src/receipt.rs
  core/primitives/src/rpc.rs
  core/primitives/src/serialize.rs
  core/primitives/src/sharding.rs
  core/primitives/src/telemetry.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
  genesis-tools/genesis-populate/src/lib.rs
  genesis-tools/genesis-populate/src/main.rs
  near/src/config.rs
  near/src/lib.rs
  near/src/runtime.rs
  near/tests/stake_nodes.rs
  near/tests/sync_nodes.rs
  near/tests/sync_state_nodes.rs
  test-utils/loadtester/src/main.rs
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/src/main.rs
  test-utils/testlib/src/lib.rs
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/node/process_node.rs
  test-utils/testlib/src/node/runtime_node.rs
  test-utils/testlib/src/node/thread_node.rs
  test-utils/testlib/src/runtime_utils.rs
  test-utils/testlib/src/standard_test_cases.rs
  tests/test_cases_runtime.rs
  tests/test_errors.rs
  tools/restaked/src/main.rs
Labels: RPC

#2211 fix: Disabling some tests + small fixes
  chain/client/tests/cross_shard_tx.rs
  nightly/nightly.txt
  pytest/tests/sanity/state_sync2.py
  pytest/tests/sanity/state_sync_routed.py
Labels: automerge
