Repository near/nearcore, pull requests merged in 2020-08, with the labels that each got.

#3069 Change download size message
  neard/src/config.rs
Labels: automerge

#3083 fix(ci): Fix for docker release tag name
  scripts/docker-release.sh
Labels: automerge

#3087 fix(ci): Fixed typo in the release scripts for docker
  scripts/docker-release.sh
Labels: automerge

#3082 feat(indexer): NEAR Indexer can init configs
  Cargo.lock
  Cargo.toml
  chain/indexer/README.md
  chain/indexer/src/lib.rs
  chain/telemetry/Cargo.toml
  chain/telemetry/src/lib.rs
  neard/Cargo.toml
  neard/src/main.rs
  tools/indexer/example/Cargo.toml
  tools/indexer/example/src/configs.rs
  tools/indexer/example/src/main.rs
Labels: enhancement, indexer

#3103 pytest: refactor mocknet load_testing_helper to track the nonce locally
  pytest/lib/account.py
  pytest/tests/mocknet/load_testing_helper.py
Labels: automerge

#3057 test: add extra stats to cross_shard_tx
  chain/client/src/test_utils.rs
  chain/client/tests/bug_repros.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/consensus.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/process_blocks.rs
Labels: automerge

#3091 fix(runtime-params-estimator): disable rocksdb thread in it
  Cargo.lock
  chain/chain/Cargo.toml
  chain/client/Cargo.toml
  core/store/Cargo.toml
  core/store/src/db.rs
  neard/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
Labels: automerge

#3150 fix: Removing flakiness from staking tests
  pytest/tests/sanity/staking2.py
Labels: automerge

#3154 fix: correctly verify gas price
  chain/client/tests/process_blocks.rs
  core/primitives/src/block.rs
Labels: automerge

#3171 fix(test): state_sync3
  nightly/tests_for_nayduck.txt
  pytest/tests/sanity/state_sync3.py
Labels: automerge

#3174 fix: Fine tune cross_shard_tx constants for the nayduck runners
  chain/client/tests/cross_shard_tx.rs
  nightly/tests_for_nayduck.txt
Labels: automerge

#3182 fix: Disabling seals to unblock CI
  chain/chunks/src/lib.rs
Labels: automerge

#3181 fix: Do not broadcast blocks to prevent stalling until the node is sy…
  chain/client/src/client.rs
Labels: automerge

#3168 fix: enforce block sync for archival nodes
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  chain/client/src/sync.rs
  nightly/tests_for_nayduck.txt
  pytest/tests/sanity/block_sync_archival.py
Labels: automerge

#3199 fix(chunks): refactor `receipts_recipient_filter` to avoid excessive calls to `account_id_to_shard_id`
  chain/chunks/src/lib.rs
  chain/client/tests/challenges.rs
Labels: automerge

#3200 fix(test): fix some tests that failed due to disabling seals
  chain/chain/src/store_validator/validate.rs
  chain/chunks/src/lib.rs
  chain/client/tests/catching_up.rs
Labels: automerge

#3159 fix: Batch edges on routing table sync
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/tests/cache_edges.rs
  nightly/nightly.txt
  pytest/tests/stress/saturate_routing_table.py
Labels: automerge

#3214 fix: Final touch to (almost) remove flakiness from cross_shard_tx
  chain/client/src/client.rs
  chain/client/tests/cross_shard_tx.rs
Labels: automerge

#3209 Fix(controlled_edge_nonce) Increase nonce above 1000
  pytest/tests/sanity/controlled_edge_nonce.py
Labels: automerge

#3016 fix: Use both version and oldest_supported version
  chain/network/src/peer.rs
  chain/network/src/types.rs
  core/primitives/src/version.rs
  neard/res/genesis_config.json
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/spec/network/handshake.py
Labels: automerge

#3127 feat(client): Extended query to be able to refer to the genesis and the earliest [oldest] available blocks
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/types.rs
  chain/client/src/view_client.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/query_client.rs
  chain/indexer/src/streamer/streamer.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/tests/rpc_query.rs
  chain/jsonrpc/tests/rpc_transactions.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  core/primitives/src/rpc.rs
  core/primitives/src/types.rs
  neard/tests/rpc_nodes.rs
  neard/tests/stake_nodes.rs
  test-utils/testlib/src/user/rpc_user.rs
Labels: automerge

#3218 doc(indexer): Added a list of our projects that use NEAR Indexer to serve as examples
  chain/indexer/README.md
Labels: automerge

#3236 feat(indexer): Extend the NEAR Indexer API with an ability to communicate the starting point of streaming
  Cargo.lock
  chain/indexer/Cargo.toml
  chain/indexer/README.md
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/streamer.rs
  tools/indexer/example/Cargo.toml
  tools/indexer/example/src/configs.rs
  tools/indexer/example/src/main.rs
Labels: automerge, indexer

#3234 fix: Bump runtime crates version to 2.0.0
  Cargo.lock
  runtime/CHANGELOG.md
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-standalone/Cargo.toml
  runtime/runtime/Cargo.toml
Labels: automerge

#3237 feat(jsonrpc): Added configuration to the RPC payload size limit
  chain/jsonrpc/src/lib.rs
Labels: automerge

#3117 fix(script): a single non interactive script to run emu-cost on ci
  runtime/runtime-params-estimator/emu-cost/ci.sh
  runtime/runtime-params-estimator/emu-cost/run.sh
Labels: automerge

#3240 fix: Update ProtocolVersionMismatch layout in tests
  pytest/lib/messages/network.py
  pytest/lib/peer.py
  pytest/tests/sanity/controlled_edge_nonce.py
  pytest/tests/spec/network/handshake.py
Labels: automerge

#3210 fix(network_drop_package): Process was starving
  pytest/lib/proxy.py
  pytest/requirements.txt
  pytest/tests/sanity/network_drop_package.py
Labels: automerge

#3248 fix(mocknet): use the chain itself to measure bps and tps
  .gitignore
  pytest/lib/data.py
  pytest/lib/mocknet.py
  pytest/requirements.txt
  pytest/tests/mocknet/load_testing.py
  pytest/tests/mocknet/load_testing_helper.py
Labels: automerge

#3258 fix: (almost) Fix test_highload
  nightly/tests_for_nayduck.txt
  test-utils/testlib/src/user/mod.rs
  test-utils/testlib/src/user/rpc_user.rs
  test-utils/testlib/src/user/runtime_user.rs
  tests/test_tps_regression.rs
Labels: automerge

#2940 feat(rosettarpc): Data API implementation
  CODEOWNERS
  Cargo.lock
  Cargo.toml
  chain/rosetta-rpc/CHANGELOG.md
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/README.md
  chain/rosetta-rpc/rosetta.cfg
  chain/rosetta-rpc/src/adapters.rs
  chain/rosetta-rpc/src/config.rs
  chain/rosetta-rpc/src/consts.rs
  chain/rosetta-rpc/src/errors.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/models.rs
  chain/rosetta-rpc/src/utils.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  core/runtime-configs/src/lib.rs
  deny.toml
  neard/Cargo.toml
  neard/src/config.rs
  neard/src/lib.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
Labels: automerge
