Repository near/nearcore, pull requests merged in 2020-12, with the labels that each got.

#3666 feat(version): include the protocol version in the version command
  neard/src/main.rs
Labels: SRE

#3667 fix(build): fix failing action for mac osx build
  .github/workflows/mac_binary.yml
Labels: SRE, automerge

#3640 fix(chunk): address some suboptimalities in shards manager
  chain/chunks/src/lib.rs
Labels: automerge

#3669 Change code owners for network
  CODEOWNERS
Labels: automerge

#3652 fix: cache epoch validators
  chain/chunks/src/lib.rs
  chain/client/src/client_actor.rs
  chain/epoch_manager/src/lib.rs
  neard/src/runtime.rs
Labels: automerge

#3673 fix(typo): docker image typo fir for nightly
  Dockerfile.nightly
Labels: SRE, automerge

#3676 fix: fix 12 -> 13 migration
  neard/src/migrations.rs
Labels: automerge

#3668 feat(indexer): Exposed full list of StateChanges for a given block via view client
  Cargo.lock
  chain/chain/src/store.rs
  chain/client/src/lib.rs
  chain/client/src/types.rs
  chain/client/src/view_client.rs
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/fetchers.rs
  chain/indexer/src/streamer/types.rs
  core/primitives/src/types.rs
  tools/indexer/example/src/main.rs
Labels: automerge, indexer

#3703 fix(runtime): Bump runtime and VM version to `2.3.0`
  Cargo.lock
  runtime/CHANGELOG.md
  runtime/near-evm-runner/Cargo.toml
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-runtime-utils/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-standalone/Cargo.toml
  runtime/runtime/Cargo.toml
Labels: automerge

#3622 fix(network): avoid unnecessary verification of sync data
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/process_blocks.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  chain/network/tests/infinite_loop.rs
  chain/network/tests/peer_handshake.rs
  chain/network/tests/runner/mod.rs
  chain/network/tests/stress_network.rs
  core/primitives/src/network.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/types.rs
  neard/src/lib.rs
  neard/src/runtime.rs
Labels: automerge

#3692 fix(chain): reject old blocks right away
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/tests/process_blocks.rs
Labels: automerge

#3689 fix(chunks): Validate partial encoded chunk header signatures exactly once
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/tests/challenges.rs
  core/primitives/src/utils.rs
Labels: automerge

#3616 fix(tool): fix runtime-params-estimator #3601
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/testbed_runners.rs
Labels: automerge

#3710 fix(chunks): Do not apply a block until we have all its missing chunks
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/missing_chunks.rs
  chain/client/src/client.rs
  chain/client/tests/challenges.rs
  chain/client/tests/process_blocks.rs
  core/primitives/src/sharding.rs
Labels: automerge

#3715 fix(chunks & network): Remove some unnecessary cloning
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/network/src/codec.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  core/primitives/src/utils.rs
Labels: automerge

#3721 fix(download-genesis): increase the maximum size of the genesis size
  neard/src/config.rs
Labels: SRE

#3726 fix(test): fix test_inflation
  chain/network/src/peer_manager.rs
  neard/tests/stake_nodes.rs
Labels: automerge

#3736 print the number of headers/blocks remaining to sync
  chain/client/src/info.rs
Labels: automerge

#3744 feat: EVM internal bench
  Cargo.lock
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/benches/bench.rs
  runtime/near-evm-runner/benches/benches/cryptozombies.rs
  runtime/near-evm-runner/benches/benches/mod.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
Labels: EVM, benchmark, enhancement, testing

#3741 change codeowners for jsonrpc
  CODEOWNERS
Labels: automerge

#3749 change codeowners for EVM runtime
  CODEOWNERS
Labels: EVM, enhancement

#3727 fix(jsonrpc): Updated rpc_errors_schema.json
  chain/jsonrpc/res/rpc_errors_schema.json
Labels: automerge

#3738 add performance metrics feature
  Cargo.lock
  Cargo.toml
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/view_client.rs
  chain/jsonrpc/Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/test_utils.rs
  chain/telemetry/Cargo.toml
  chain/telemetry/src/lib.rs
  neard/Cargo.toml
  neard/src/main.rs
  tools/indexer/example/src/configs.rs
  utils/near-performance-metrics-macros/Cargo.toml
  utils/near-performance-metrics-macros/src/lib.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/actix.rs
  utils/near-performance-metrics/src/lib.rs
  utils/near-performance-metrics/src/process.rs
  utils/near-performance-metrics/src/stats.rs
Labels: automerge

#3735 fix: shutdown neard when the client protocol version is too old
  chain/client/src/client.rs
  chain/client/tests/process_blocks.rs
Labels: automerge

#3761 disable performance-stats feature by default
  utils/near-performance-metrics/src/actix.rs
  utils/near-performance-metrics/src/actix_disabled.rs
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/lib.rs
  utils/near-performance-metrics/src/stats_disabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3704 Fixes in ecrecover, parse_meta_tx, eip-712 and enable meta tx
  Cargo.lock
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/src/utils.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
  runtime/near-vm-errors/src/lib.rs
Labels: EVM, bug, enhancement

#3722 expand the CryptoZombies tests
  test-utils/testlib/src/standard_evm_cases.rs
  tests/test_cases_runtime.rs
Labels: EVM, enhancement, testing
