Repository near/nearcore, pull requests merged in 2020-11, with the labels that each got.

#3551 feat(jsonrpc): Per method error tracking on prometheus
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
Labels: RPC, SRE, automerge

#3531 refactor: Upgraded crypto dependencies
  Cargo.lock
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/crypto/Cargo.toml
  core/crypto/src/hash.rs
  core/crypto/src/signature.rs
  core/crypto/src/test_utils.rs
  core/primitives/Cargo.toml
  deny.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
Labels: automerge

#3560 feat: Added nightly features to parallel tests (#3538)
  scripts/parallel_run_tests.py
  scripts/testlib.py
Labels: automerge

#3572 fix(typo): docker release script for nightly
  scripts/docker-release.sh
Labels: SRE, bug

#3558 Upgrade to OpenEthereum 2.6.8 (Istanbul support)
  Cargo.lock
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/interpreter.rs
  runtime/near-evm-runner/src/lib.rs
  runtime/near-evm-runner/src/near_ext.rs
Labels: EVM, dependencies, enhancement, housekeeping

#3575 Added --no-ansi flag to disable coloring and ansi chars in logging
  neard/src/main.rs
Labels: SRE, automerge

#3581 feat(evm): EVM standard borsh args + refactoring
  runtime/near-evm-runner/src/builtins.rs
  runtime/near-evm-runner/src/evm_state.rs
  runtime/near-evm-runner/src/lib.rs
  runtime/near-evm-runner/src/near_ext.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/src/utils.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-vm-errors/src/lib.rs
  test-utils/testlib/src/standard_test_cases.rs
Labels: EVM, housekeeping

#3564 fix(evm): precompile evm gas use based on input, logic from openethereum
  runtime/near-evm-runner/src/builtins.rs
  runtime/near-evm-runner/src/lib.rs
  runtime/near-evm-runner/src/near_ext.rs
  runtime/near-evm-runner/src/pricer.rs
  runtime/near-runtime-fees/src/lib.rs
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
Labels: EVM

#3571 Fix(evm): no genesis change after evm change, no matter protocol-feature-evm enabled or not
  Cargo.lock
  Cargo.toml
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/lib.rs
  core/primitives/src/version.rs
  deny.toml
  neard/Cargo.toml
  neard/res/genesis_config.json
  neard/src/config.rs
  neard/src/runtime.rs
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/builtins.rs
  runtime/near-evm-runner/src/pricer.rs
  runtime/near-evm-runner/tests/failures.rs
  runtime/near-evm-runner/tests/utils.rs
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-runtime-fees/src/lib.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/evm_estimator.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/lib.rs
  test-utils/testlib/src/standard_evm_cases.rs
  test-utils/testlib/src/standard_test_cases.rs
  tests/test_cases_runtime.rs
  tests/test_cases_testnet_rpc.rs
Labels: EVM

#3592 fix(test): Use all the cpus on the machine for running parallel tests…
  scripts/flaky_test_check.py
  scripts/parallel_coverage.py
  scripts/parallel_run_tests.py
  scripts/testlib.py
Labels: SRE, automerge

#3595 Upgrade to OpenEthereum 2.7.2
  Cargo.lock
  chain/epoch_manager/Cargo.toml
  core/primitives/Cargo.toml
  deny.toml
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/interpreter.rs
  runtime/near-evm-runner/src/near_ext.rs
  runtime/near-vm-errors/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: EVM, dependencies, enhancement, housekeeping

#3602 cleanup(tests): delete obsolete regression tests and parallel_run_testing script
  runtime/runtime/tests/test_regression.rs
  scripts/parallel_run_tests.py
Labels: SRE

#3610 fix(Increase historgram levels up to 30)
  chain/jsonrpc/src/metrics.rs
  core/metrics/src/lib.rs
Labels: SRE, automerge

#3605 Change per column rocksdb block cache size from 180mb to 32mb
  core/store/src/db.rs
Labels: automerge

#3550 fix(rpc): return Err when client actor has detected syncing
  chain/client/src/client_actor.rs
Labels: RPC, SRE

#3603 fix(storage): 14 -> 15 migration
  core/store/src/migrations.rs
Labels: automerge

#3624 Fix the CryptoZombies test
  runtime/near-evm-runner/tests/build/zombieAttack.bin
Labels: EVM, bug, testing

#3625 fix(primitives): Clarified the error message for the lacking balance
  core/primitives/src/errors.rs
Labels: automerge

#3629 fix: add fallback for git version
  neard/src/main.rs
Labels: automerge

#3630 refactor (indexer): Move receipt_execution_outcomes to IndexerChunkView from StreamerMessage. Bump Indexer version to 0.5.0
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/types.rs
  tools/indexer/example/src/main.rs
Labels: automerge, indexer

#3636 feat (indexer): Extend IndexerConfig to be available to turn off requirement the node to be fully synced before streaming. Update Indexer example
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/mod.rs
  tools/indexer/example/src/main.rs
Labels: automerge, indexer

#3631 Removed the no-color flag and added a log_color bool in the config.json
  chain/client/src/info.rs
  core/chain-configs/src/client_config.rs
  core/chain-configs/src/lib.rs
  neard/src/config.rs
  neard/src/main.rs
Labels: SRE, automerge

#3647 fix(Add neard to release scripts)
  Dockerfile
  scripts/binary-release.sh
  scripts/run_docker.sh
Labels: SRE, donotmerge

#3633 [EVM] Add tests for all EVM precompiles
  runtime/near-evm-runner/tests/build/StandardPrecompiles.abi
  runtime/near-evm-runner/tests/build/StandardPrecompiles.bin
  runtime/near-evm-runner/tests/contracts/StandardPrecompiles.sol
  test-utils/testlib/src/standard_evm_cases.rs
  tests/test_cases_runtime.rs
Labels: EVM, enhancement, testing

#3659 fix(rosetta-rpc): Fixed aggressive data polling leading to view-client unavailability
  chain/rosetta-rpc/src/utils.rs
Labels: automerge
