Repository near/nearcore, pull requests merged in 2020-10, with the labels that each got.

#3441 fix(test): block_chunk_signature.py
  pytest/tests/sanity/block_chunk_signature.py
Labels: automerge

#3445 fix(test): epoch_switches.py
  pytest/tests/sanity/epoch_switches.py
Labels: automerge

#3442 fix(rpc): include method as label in rpc request total metric
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
  core/metrics/src/lib.rs
Labels: RPC, SRE, automerge, enhancement

#3425 fix(test): start_from_genesis.py
  pytest/tests/adversarial/start_from_genesis.py
Labels: automerge

#3436 feat(indexer): Add receipts to execution outcome in streamer
  Cargo.lock
  chain/client/src/lib.rs
  chain/client/src/types.rs
  chain/client/src/view_client.rs
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/streamer.rs
Labels: automerge, enhancement, indexer

#3451 feat(near-crypto): Export Secp256K1PublicKey and ED25519PublicKey
  core/crypto/src/lib.rs
  core/crypto/src/signature.rs
Labels: automerge

#3454 fix: fetching chunks from peers that track shard and stress.py improv…
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/chunks_management.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  nightly/tests_for_nayduck.txt
  pytest/lib/cluster.py
  pytest/lib/proxy.py
  pytest/tests/stress/stress.py
Labels: automerge

#3453 fix(rosetta-rpc): fixed rosetta.cfg to be compatible with the latest rosetta-cli
  chain/rosetta-rpc/rosetta-localnet.cfg
  chain/rosetta-rpc/rosetta.cfg
  chain/rosetta-rpc/src/lib.rs
Labels: automerge

#3452 fix(rosetta-rpc): fixed duplicates by transaction identifier in /block Data API
  Cargo.lock
  chain/rosetta-rpc/CHANGELOG.md
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator1_receipt_processing_transaction.snap
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator2_action_receipt_gas_reward_transaction.snap
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__validators_update_transaction.snap
  chain/rosetta-rpc/src/models.rs
  chain/rosetta-rpc/src/utils.rs
Labels: automerge

#3466 feat(indexer): Add local receipt to corresponding execution outcome whenewher possible
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/streamer.rs
Labels: indexer

#3469 fix(script): estimate.sh in other crate dir cause genesis-populate built with wrong feat
  runtime/runtime-params-estimator/estimate.sh
Labels: automerge

#3479 fix(typo): downloading genesis instead of config
  neard/src/config.rs
Labels: SRE, automerge

#3459 feat: Refactor Config out of Runtime
  core/runtime-configs/src/lib.rs
  genesis-tools/genesis-populate/src/lib.rs
  neard/src/runtime.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime-standalone/src/lib.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  runtime/runtime/tests/test_regression.rs
  test-utils/testlib/src/node/runtime_node.rs
  test-utils/testlib/src/runtime_utils.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#3491 fix(indexer): Correct command in README
  chain/indexer/README.md
Labels: automerge, indexer

#3463 feat(chain): Versioned ShardChunkHeader
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator/validate.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chain/tests/simple_chain.rs
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/challenges.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/process_blocks.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  core/primitives/benches/serialization.rs
  core/primitives/src/block.rs
  core/primitives/src/block_header.rs
  core/primitives/src/sharding.rs
  core/primitives/src/syncing.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/validator_signer.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  core/store/src/migrations.rs
  core/store/src/migrations/v6_to_v7.rs
  core/store/src/migrations/v8_to_v9.rs
  genesis-tools/genesis-populate/src/lib.rs
  neard/res/genesis_config.json
  neard/src/lib.rs
  neard/src/migrations.rs
  neard/src/runtime.rs
  neard/tests/economics.rs
  neard/tests/sync_nodes.rs
  pytest/lib/messages/block.py
  pytest/lib/messages/network.py
  pytest/tests/sanity/block_chunk_signature.py
  pytest/tests/sanity/network_drop_package.py
  pytest/tests/sanity/proxy_simple.py
  pytest/tests/sanity/sync_chunks_from_archival.py
  test-utils/state-viewer/src/main.rs
  test-utils/state-viewer/src/state_dump.rs
Labels: automerge

#3498 Update CODEOWNERS
  CODEOWNERS
Labels: automerge

#3513 refactor(indexer): Attach local receipt to chunk. Remove local_receipts field from StreamerMessage
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/errors.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/streamer.rs
  chain/indexer/src/streamer/types.rs
  chain/indexer/src/streamer/utils.rs
Labels: automerge, indexer

#3519 fix(migrations): Use ShardChunkV1 in migration_12_to_13
  neard/src/migrations.rs
Labels: automerge

#3528 fix(chunks) - backwards compatible automatic forwarding of parts to shard trackers
  Cargo.toml
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/process_blocks.rs
  chain/network/Cargo.toml
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  core/primitives/Cargo.toml
  core/primitives/src/sharding.rs
  core/primitives/src/version.rs
  neard/Cargo.toml
  neard/src/runtime.rs
  neard/tests/stake_nodes.rs
  pytest/lib/messages/block.py
  pytest/lib/messages/network.py
Labels: automerge

#3540 Add labels to rpc processing time historgram.
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
  core/metrics/src/lib.rs
Labels: RPC, SRE, automerge

#3542 Upgrade to OpenEthereum 2.6.2
  ATTRIBUTIONS.md
  Cargo.lock
  core/crypto/src/signature.rs
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/near_ext.rs
Labels: EVM, dependencies, enhancement, housekeeping
