Repository near/nearcore, pull requests merged in 2021-07, with the labels that each got.

#4425 feat(github): added stale bot configuration to clean up obsolete PRs and Issues
  .github/stale.yml
Labels: S-automerge, T-SRE

#4387 fix(rpc): avoid null response in sandbox rpc
  chain/jsonrpc-primitives/src/types/sandbox.rs
Labels: S-automerge

#4406 test(sandbox): add sandbox pytest to nightly suite
  nightly/complete_nayduck_set.txt
  nightly/nightly.txt
  nightly/tests_for_nayduck.txt
Labels: S-automerge

#4424 Get rid of internal call in `EncodedShardChunk`
  core/primitives/src/sharding.rs
Labels: C-housekeeping, S-automerge

#4437 pytest: make run_handshake handle unsolicited Block messages
  pytest/lib/peer.py
Labels: S-automerge

#4427 feat(cli): Implemented the download config method to the init command
  chain/indexer/src/lib.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  tools/indexer/example/src/configs.rs
Labels: S-automerge, T-SRE

#4453 feat(cli): Added ability to specify `--boot-nodes` option to the init command
  chain/indexer/src/lib.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  tools/indexer/example/src/configs.rs
Labels: S-automerge, T-SRE

#4456 chore: modify stale bot configuration
  .github/stale.yml
Labels: S-automerge

#4457 fix: typos
  docs/architecture.md
Labels: S-automerge

#4038 feat: improve visibility for runtime performance
  Cargo.lock
  runtime/runtime/Cargo.toml
  runtime/runtime/src/lib.rs
Labels: S-automerge

#4426 fix(test): test vm standalone script test with wasmer1
  runtime/near-vm-runner-standalone/src/script.rs
Labels: S-automerge

#4458 doc: add documentation on issue labels
  CONTRIBUTING.md
Labels: S-automerge

#4477 bug(build): removed unused RUST_OPTIONS env var
  Makefile
Labels: S-automerge, T-SRE

#4483 bug(build): remove `CARGO_PROFILE_RELEASE_DEBUG` env vars for debug b…
  Makefile
Labels: C-housekeeping, S-automerge, T-SRE

#4442 Update to rocksdb dependency to 0.16.0
  Cargo.lock
  chain/indexer/Cargo.toml
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/db/v6_to_v7.rs
  deny.toml
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#4439 doc: fix typo in cost estimator readme
  runtime/runtime-params-estimator/emu-cost/README.md
Labels: S-automerge

#4476 chore: add matklad to params-estimator codeowners
  CODEOWNERS
Labels: S-automerge

#4481 refactor: remove needless rayon pool setup in the estimator
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#4429 store: cancel background RocksDB tasks before closing the database
  core/store/src/db.rs
Labels: S-automerge

#4467 Gas metering cost measurements
  runtime/near-vm-runner/src/prepare.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#4487 Remove unneccesarry ‘INFO’ prefix from log messages
  pytest/lib/mocknet.py
  pytest/tests/mocknet/load_testing.py
  pytest/tests/mocknet/outage.py
Labels: S-automerge

#4486 pytest: remove contract building from deploy_call_smart_contract test
  pytest/tests/contracts/deploy_call_smart_contract.py
Labels: S-automerge

#4472 primitives: remove `LOWER_STORAGE_COST_CONFIG` global
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4491 Add cython to pytest requirements
  pytest/requirements.txt
Labels: A-python-test

#4498 Fix order of regression constants
  runtime/runtime-params-estimator/src/cases.rs
Labels: A-params-estimator, S-automerge

#4444 Store restored receipts in the storage
  core/primitives/src/version.rs
  core/store/src/db.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#4504 feat(build): Added param-estimator and genesis-populate to the Makefile for nightly and stable releases to store artifacts
  Makefile
  codecov.yml
Labels: S-automerge, T-SRE

#4508 typo(Makefile): fixed the runtime-params-estimator typo
  Makefile
Labels: S-automerge, T-SRE

#4506 Makefile: make sure LTO is enable in release builds
  Makefile
Labels: S-automerge

#4484 chore: delete all unused/obsolete/deprecated script in the scripts dir
  codecov.yml
  scripts/__init__,py
  scripts/build_wasm.sh
  scripts/create_service.py
  scripts/near-kcov-runtime.Dockerfile
  scripts/near-test-runtime.Dockerfile
  scripts/near.service.template
  scripts/start_localnet.py
  scripts/start_staging_testnet.py
  scripts/start_stakewars.py
  scripts/start_testnet.py
  scripts/stop.py
Labels: C-housekeeping, S-automerge, T-SRE

#4503 pytests: fix blob cleanup introduced in previous commit
  pytest/lib/utils.py
Labels: S-automerge

#4510 Makefile: add `neard` target which just buids neard binary
  Makefile
Labels: S-automerge

#4495 Add a flag to run a separate http server for exporting Prometheus metric on a different address
  chain/jsonrpc/src/lib.rs
  neard/src/cli.rs
Labels: S-automerge

#4499 fix(test): fix adversarial build of neard
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#4516 fix: fix nightly param estimator build
  Makefile
Labels: S-automerge

#4488 refactor: switch to pure-rust wasm parser for test
  Cargo.lock
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/error_cases.rs
  runtime/near-vm-runner/src/tests/invalid_contracts.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#4512 fix(runtime): revert implicit account creation on account deletion
  core/primitives/src/version.rs
  integration-tests/tests/test_cases_runtime.rs
  pytest/tests/sanity/upgradable.py
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/test_async_calls.rs
  test-utils/testlib/src/fees_utils.rs
  test-utils/testlib/src/runtime_utils.rs
  test-utils/testlib/src/standard_test_cases.rs
Labels: S-automerge

#4511 refactor(runtime): use wasmparser instead of always depend on wasmer 0.x
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
Labels: S-automerge

#4518 fix: tidy test checks everything, and not only one dir
  integration-tests/tests/tidy.rs
Labels: S-automerge

#4522 Use protocol version of the latest block instead of protocol version of the genesis block when dumping state
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/src/state_dump.rs
Labels: S-automerge

#4523 exit gracefully if no arguments are provided to `state-viewer`
  test-utils/state-viewer/src/main.rs
Labels: S-automerge

#4519 nayduck: update scheduler address in the ‘Requset a run’ script
  nightly/nayduck.py
Labels: S-automerge

#4502 Report the earliest available block in the status response
  chain/chain/src/store.rs
  chain/client/src/client_actor.rs
  core/primitives/src/views.rs
Labels: S-automerge

#4507 Disable LTO in release builds
  Cargo.toml
Labels: S-automerge

#4532 fix(sandbox): add `--release` to Makefile for `sandbox-release`
  Makefile
Labels: S-automerge

#4533 pytest: fix sandbox test
  nightly/complete_nayduck_set.txt
  nightly/nightly.txt
  nightly/tests_for_nayduck.txt
  pytest/tests/sandbox/patch_state.py
Labels: S-automerge

#4536 nayduck: remove ‘basic’ test since it’s not a thing
  nightly/nightly.txt
Labels: S-automerge

#4528 fix(test): remove rpc routing tests
  nearcore/tests/rpc_nodes.rs
Labels: S-automerge

#4545 refactor: drop unneeded `derive(Serialize)`
  chain/chain/src/test_utils.rs
  chain/network/src/routing.rs
  chain/network/src/types.rs
  core/primitives/src/block.rs
  core/primitives/src/challenge.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/receipt.rs
  core/primitives/src/sharding.rs
  core/primitives/src/sharding/shard_chunk_header_inner.rs
  core/primitives/src/syncing.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
Labels: S-automerge

#4551 Remove `protocol_feature_evm` mention from emu-cost/README.md
  runtime/runtime-params-estimator/emu-cost/README.md
Labels: S-automerge

#4535 fix(runtime): Fix validator stake host function
  chain/client/tests/process_blocks.rs
  runtime/runtime/src/ext.rs
Labels: S-automerge

#4549 refactor: use clap3 in parameter estimator & standalone runner
  Cargo.lock
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4563 fix: use the right Rust version in param-estimator dockerfile
  runtime/runtime-params-estimator/emu-cost/Dockerfile
Labels: S-automerge

#4448 feat(runtime): borsh deserialized wasmer 0.x
  Cargo.lock
  core/primitives/src/version.rs
  core/store/src/migrations.rs
  deny.toml
  nearcore/src/lib.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: S-automerge

#4571 refactor: drop obsolete contract runtime benchmarks
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/benches/bench.rs
Labels: S-automerge

#4572 nayduck: reset terminal colour when done printing the message
  nightly/nayduck.py
Labels: S-automerge

#4576 cleanup(tests): the create_prometheus_targets.py is obsolete and unused
  pytest/tests/stress/hundred_nodes/create_prometheus_targets.py
Labels: S-automerge

#4573 Move 'standard_test_cases' to 'integration-tests'
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/tests/standard_cases/main.rs
  integration-tests/tests/standard_cases/rpc.rs
  integration-tests/tests/standard_cases/runtime.rs
  test-utils/testlib/src/lib.rs
Labels: S-automerge

#4578 cleanup(readme): rename the remove.md to README.md to be visible from…
  pytest/README.md
Labels: C-enhancement, S-automerge

#4579 cleanup(version): move master version to 0.0.0 instead of 1.2.0
  Cargo.lock
  nearcore/Cargo.toml
  neard/Cargo.toml
  neard/src/main.rs
Labels: C-enhancement, S-automerge, T-SRE

#4539 pytest: add scripts/check_pytest.py checking if tests are listed
  scripts/check_pytests.py
Labels: S-automerge

#4583 pytest: document why bridge checks for Go
  pytest/lib/bridge.py
Labels: S-automerge

#4584 pytest: add a pre-commit check testing if all pytests are enabled
  .buildkite/pipeline.yml
  nightly/complete_nayduck_set.txt
Labels: S-automerge

#4585 fix(rpc): fix the implementation of `get_block_proof` for light client
  chain/chain/src/chain.rs
Labels: S-automerge

#4586 nayduck: remove --run_type flag; it’s never used by anything
  nightly/nayduck.py
Labels: S-automerge

#4580 doc: add CHANGELOG.md and update CONTRIBUTING.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: S-automerge

#4590 nayduck: make nayduck.py a library; support `./` in scripts/check_*.py
  nightly/nayduck.py
  scripts/__init__.py
  scripts/check_nightly.py
  scripts/check_pytests.py
  scripts/nayduck.py
Labels: S-automerge, T-nodeX

#4591 pytest: fix backward_compatible.py test when run on NayDuck
  pytest/tests/sanity/backward_compatible.py
Labels: S-automerge, T-nodeX

#4593 nayduck: add argument to `read_tests_from_file` defining how files are read
  scripts/nayduck.py
Labels: S-automerge, T-nodeX

#4594 nightly: rework nightly/*.txt test lists; include all in nightly.txt
  nightly/TODO-disabled-4552.txt
  nightly/complete_nayduck_set.txt
  nightly/expensive.txt
  nightly/nightly.txt
  nightly/pytest-adversarial.txt
  nightly/pytest-contracts.txt
  nightly/pytest-sanity.txt
  nightly/pytest-spec.txt
  nightly/pytest-stress.txt
  nightly/pytest.txt
  nightly/sandbox.txt
  nightly/tests_for_nayduck.txt
  scripts/check_nightly.py
  scripts/check_pytests.py
  scripts/nayduck.py
Labels: T-nodeX

#4608 nightly: fix saturate_routing_table test description
  nightly/TODO-disabled-4552.txt
  nightly/pytest-sanity.txt
  nightly/pytest-stress.txt
Labels: S-automerge, T-nodeX

#4609 nightly: enable three of the passing tests
  nightly/TODO-disabled-4552.txt
  nightly/pytest-sanity.txt
Labels: S-automerge, T-nodeX
