Repository near/nearcore, pull requests merged in 2021-09, with the labels that each got.

#4759 pytest: fuzz: don’t capture output
  pytest/tests/runtime/fuzz.py
Labels: S-automerge, A-benchmark, T-nodeX

#4754 refactor(jsonrpc-primitives): use more appropriate identifiers around changes-related RPC structs
  chain/jsonrpc-primitives/src/types/changes.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#4768 Revert "pytest: fuzz: enable parallelism (#4755)"
  pytest/tests/runtime/fuzz.py
Labels: S-automerge, A-CI, T-nodeX

#4770 refactor(jsonrpc-primitives): ensure impl Deserialize on all public jsonrpc-related types
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/light_client.rs
  chain/jsonrpc-primitives/src/types/network_info.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/sandbox.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc-primitives/src/types/transactions.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  core/primitives/src/sharding.rs
  core/primitives/src/views.rs
Labels: S-automerge

#4769 refactor(jsonrpc-primitives): deduplicate BlockReference
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/changes.rs
  chain/jsonrpc-primitives/src/types/config.rs
  integration-tests/tests/nearcore/rpc_error_structs.rs
  integration-tests/tests/nearcore/rpc_nodes.rs
Labels: S-automerge

#4772 refactor(jsonrpc-primitives): impl Display instead of ToString for RpcError
  chain/jsonrpc-primitives/src/errors.rs
Labels: S-automerge

#4774 chore: remove stale references to near-runtime-utils
  core/primitives/src/errors.rs
Labels: S-automerge

#4748 high level changes for how split state will be triggered in sync and catch up
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
  chain/epoch_manager/src/lib.rs
  core/primitives/src/errors.rs
  core/primitives/src/shard_layout.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  pytest/tests/sanity/state_sync1.py
Labels: S-automerge

#4749 refactor(core, primitives): ContractCode getters
  core/primitives-core/src/contract.rs
  core/primitives/src/views.rs
  core/store/src/lib.rs
  integration-tests/src/node/mod.rs
  integration-tests/tests/runtime/state_viewer.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/cache.rs
  runtime/runtime/src/genesis.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer/mod.rs
  test-utils/state-viewer/src/main.rs
Labels: S-automerge

#4640 feat: allow computing a subset of costs in the estimator
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/ext_costs_generator.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/runtime_fees_generator.rs
  runtime/runtime-params-estimator/src/testbed_runners.rs
Labels: S-automerge

#4732 chore: Add MIT and Apache licenses and update crate licenses
  LICENSE-APACHE
  LICENSE-MIT
  chain/pool/Cargo.toml
  core/crypto/Cargo.toml
  core/metrics/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime/Cargo.toml
  tools/rpctypegen/core/Cargo.toml
  tools/rpctypegen/macro/Cargo.toml
Labels: S-automerge

#4782 chore: update codeowners
  CODEOWNERS
Labels: S-automerge

#4773 chore(near-primitives): document why FunctionCallPermission::receiver_id != AccountId
  core/primitives-core/src/account.rs
Labels: S-automerge

#4762 make chunk_extra referenced by shard_uid instead of shard_id
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/src/lib.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/shard_layout.rs
  core/store/src/trie/shard_tries.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/adapter.rs
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/src/main.rs
  tools/restored-receipts-verifier/src/main.rs
Labels: S-automerge

#4794 refactor: reword error msg for reporting transactions failing for requiring full-access keys
  core/primitives/src/errors.rs
Labels: S-automerge

#4750 refactor(chain, core, genesis-tools, nearcore, neard): use more PathBuf and Path
  chain/indexer/src/streamer/mod.rs
  chain/network/src/peer_store.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  genesis-tools/genesis-csv-to-json/src/main.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  genesis-tools/keypair-generator/src/main.rs
  integration-tests/src/node/process_node.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  neard/src/cli.rs
  neard/src/main.rs
  runtime/runtime-params-estimator/src/stats.rs
  test-utils/loadtester/src/main.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/state-viewer/src/main.rs
  test-utils/store-validator/src/main.rs
  tools/restaked/src/main.rs
  tools/restored-receipts-verifier/src/main.rs
Labels: S-automerge

#4796 feat: pass environment variables to docker
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4730 chore: bump borsh version
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/client/Cargo.toml
  chain/epoch_manager/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/pool/Cargo.toml
  core/account-id/Cargo.toml
  core/account-id/fuzz/Cargo.toml
  core/crypto/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  deny.toml
  genesis-tools/genesis-populate/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/loadtester/Cargo.toml
  test-utils/runtime-tester/fuzz/Cargo.lock
  test-utils/state-viewer/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: S-automerge

#4763 Fix(test): gas usage changed due to wat parse slightly different
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests/error_cases.rs
Labels: S-automerge

#4599 fix: remove potential panic with profile data fmt
  core/primitives-core/src/profile.rs
Labels: S-automerge

#4781 refactor: use external crate for displaying tracing spans
  Cargo.lock
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner-standalone/src/tracing_timings.rs
  runtime/near-vm-runner/README.md
Labels: S-automerge

#4804 Add a RwLock to tries in NightshadeRuntime
  core/store/src/trie/shard_tries.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4793 fix(chain): fix block ordinal to block hash map
  chain/chain/src/store.rs
  core/primitives/src/version.rs
  core/store/src/migrations.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/lib.rs
Labels: S-automerge

#4790 fix(profile): deserialization fail would panic, avoid it. Fix 4786
  core/primitives-core/src/profile.rs
Labels: S-automerge

#4810 Add test for creating invalid subaccount
  integration-tests/tests/standard_cases/main.rs
  integration-tests/tests/standard_cases/runtime.rs
  test-utils/testlib/src/runtime_utils.rs
Labels: A-testing

#4808 pytest: add more to README.md
  pytest/README.md
Labels: S-automerge, T-nodeX

#4809 pytest: add cython back to requirements
  pytest/requirements.txt
Labels: S-automerge

#4795 feat: lower data receipt cost
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  nearcore/res/runtime_configs/116.json
  runtime/runtime-params-estimator/costs.txt
Labels: A-transaction-runtime

#4797 implement split states
  Cargo.lock
  chain/chain-primitives/src/error.rs
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/sync.rs
  chain/epoch_manager/src/lib.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  core/primitives/Cargo.toml
  core/primitives/src/shard_layout.rs
  core/primitives/src/syncing.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#4812 Adding ScenarioBuilder
  test-utils/runtime-tester/README.md
  test-utils/runtime-tester/src/lib.rs
  test-utils/runtime-tester/src/scenario_builder.rs
Labels: S-automerge

#4816 NayDuck has it’s own domain now \o/
  scripts/nayduck.py
Labels: S-automerge

#4817 refactor ShardTries
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/split_state.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4811 fix: make `param-estimator --docker` work with default additional-acc…
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4823 chore: update rust version
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain
Labels: S-automerge

#4714 Apply state parts in separate actor
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/tests/query_client.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/network/runner.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4836 chore: don't hide Cargo.lock from diff
  .gitattributes
Labels: S-automerge

#4801 docs: drop obsolete link
  README.md
Labels: S-automerge

#4818 chore: move MIT/Apache from root and link to relevant folders
  chain/pool/LICENSE-APACHE
  chain/pool/LICENSE-MIT
  core/crypto/LICENSE-APACHE
  core/crypto/LICENSE-MIT
  core/metrics/LICENSE-APACHE
  core/metrics/LICENSE-MIT
  core/primitives-core/LICENSE-APACHE
  core/primitives-core/LICENSE-MIT
  core/primitives/LICENSE-APACHE
  core/primitives/LICENSE-MIT
  core/store/LICENSE-APACHE
  core/store/LICENSE-MIT
  licenses/LICENSE-APACHE
  licenses/LICENSE-MIT
  runtime/near-vm-errors/LICENSE-APACHE
  runtime/near-vm-errors/LICENSE-MIT
  runtime/near-vm-logic/LICENSE-APACHE
  runtime/near-vm-logic/LICENSE-MIT
  runtime/near-vm-runner/LICENSE-APACHE
  runtime/near-vm-runner/LICENSE-MIT
  runtime/runtime/LICENSE-APACHE
  runtime/runtime/LICENSE-MIT
  tools/rpctypegen/core/LICENSE-APACHE
  tools/rpctypegen/core/LICENSE-MIT
  tools/rpctypegen/macro/LICENSE-APACHE
  tools/rpctypegen/macro/LICENSE-MIT
Labels: S-automerge

#4840 near-test-contracts: make sure RUSTFLAGS env. variable takes effect
  runtime/near-test-contracts/build.rs
Labels: S-automerge, A-CI, T-nodeX

#4844 nayduck: use correct URL when scheduling runs
  scripts/nayduck.py
Labels: S-automerge, A-CI, T-nodeX

#4834 feat: make debugging param estimator failures in docker easier
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4843 fix(script): build sandbox when dir not exist
  Makefile
Labels: S-automerge

#4848 fix(near-primitives): `EpochReference` enum can be flattened into a struct
  chain/jsonrpc-primitives/src/types/status.rs
  core/primitives/src/types.rs
Labels: S-automerge

#4849 Move to Wasmer 2.0.1
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
Labels: S-automerge

#4850 fix: use correct (not safely-multiplied) cost in the canonical costs file
  runtime/runtime-params-estimator/costs.txt
Labels: S-automerge

#4851 fix(primitives): backwards compatible ExecutionOutcomeView
  core/primitives/src/views.rs
Labels: S-automerge

#4853 refactor: remove dead code
  core/chain-configs/src/lib.rs
Labels: S-automerge

#4847 Apply block updates to split shards
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/epoch_manager/src/lib.rs
  core/primitives/src/shard_layout.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  core/store/src/db.rs
  core/store/src/test_utils.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/split_state.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
  test-utils/state-viewer/src/main.rs
  tools/restored-receipts-verifier/src/main.rs
Labels: S-automerge

#4857 feat: use one command to run parameter estimation
  .buildkite/pipeline.yml
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4852 chore(sandbox): add more records to test sandbox
  pytest/tests/sandbox/patch_state.py
Labels: S-automerge

#4856 Remove TestEnv::new_with_runtime constructor in favour of a builder
  chain/client/src/test_utils.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/client/runtimes.rs
  integration-tests/tests/client/sandbox.rs
  nearcore/tests/economics.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/state-viewer/src/state_dump.rs
Labels: S-automerge

#4868 runtime-tester: add support for inspecting the home directory
  test-utils/runtime-tester/src/lib.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/runtime-tester/src/scenario_builder.rs
Labels: S-automerge

#4873 runtime-tester: use provided account ids when creating test environment
  test-utils/runtime-tester/src/run_test.rs
Labels: S-automerge

#4872 Remove TestEnv::new constructor in favour of a builder
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/tests/chunks_management.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/process_blocks.rs
Labels: S-automerge

#4875 Minor small improvements to TestEnv structure
  chain/client/src/test_utils.rs
Labels: S-automerge

#4112 new routing exchange prototype using IBF
  Cargo.lock
  chain/chain/Cargo.toml
  chain/client/Cargo.toml
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/types/adversarial.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/test-utils/Cargo.toml
  chain/jsonrpc/test-utils/src/lib.rs
  chain/jsonrpc/tests/test_utils/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/benches/ibf.rs
  chain/network/src/cache.rs
  chain/network/src/codec.rs
  chain/network/src/ibf.rs
  chain/network/src/ibf_peer_set.rs
  chain/network/src/ibf_set.rs
  chain/network/src/lib.rs
  chain/network/src/metrics.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/peer_store.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  chain/network/src/utils.rs
  chain/network/tests/cache_edges.rs
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/network/peer_handshake.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/Cargo.toml
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/lib/messages/network.py
  pytest/tests/sanity/routing_table_sync.py
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  utils/near-performance-metrics-macros/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-stable-hasher/Cargo.toml
  utils/near-stable-hasher/src/lib.rs
Labels: S-automerge

#4878 ibf: fix [usize; 3] not being an iterator compilation error
  chain/network/src/ibf.rs
Labels: S-automerge

#4880 nightly: remove unnecessary ‘adevrsarial’ feature
  nightly/README.md
  nightly/pytest-sanity.txt
Labels: S-automerge

#4874 feat: upgrade to wasmer2 via a protocol feature
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  neard/Cargo.toml
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/vm_kind.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  test-utils/logger/Cargo.toml
  test-utils/logger/src/lib.rs
  test-utils/logger/src/tracing_capture.rs
Labels: S-automerge

#4879 ibf: fix adversarial build
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer_manager.rs
Labels: S-automerge

#4881 Revert "ibf: fix [usize; 3] not being an iterator compilation error"
  chain/network/src/ibf.rs
Labels: S-automerge

#4884 fix(jsonrpc-primitives): fix adversarial-related compilation errors
  chain/jsonrpc-primitives/Cargo.toml
  chain/network/Cargo.toml
Labels: S-automerge

#4890 refactor: remove ActualRuntimeConfig
  core/primitives/src/runtime/config.rs
Labels: A-transaction-runtime

#4883 feat: log potentially problematic error from wasmer0
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: S-automerge

#4896 Include getting GCP permissions in the state-viewer documentation.
  test-utils/state-viewer/README.md
Labels: S-automerge

#4892 runtime-tester: fix runtime_fuzzer test
  test-utils/runtime-tester/fuzz/fuzz_targets/runtime_fuzzer.rs
Labels: S-automerge
