Repository near/nearcore, pull requests merged in 2021-12, with the labels that each got.

#5493 Move tests for `near-vm-logic` from `/tests` to `/src/tests/`
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/tests/context.rs
  runtime/near-vm-logic/src/tests/ecrecover-tests.json
  runtime/near-vm-logic/src/tests/fixtures.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
  runtime/near-vm-logic/src/tests/iterators.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-logic/src/tests/promises.rs
  runtime/near-vm-logic/src/tests/registers.rs
  runtime/near-vm-logic/src/tests/storage_read_write.rs
  runtime/near-vm-logic/src/tests/storage_usage.rs
  runtime/near-vm-logic/src/tests/view_method.rs
  runtime/near-vm-logic/src/tests/vm_logic_builder.rs
Labels: S-automerge, P-medium

#5545 fix: Fix`lib.proxy.bridge` crashing in when header is not full read
  pytest/lib/proxy.py
Labels: P-low, S-automerge

#5552 Re: Fix file not found error for `pytest/tests/sanity/restacked.py`
  pytest/tests/sanity/restaked.py
Labels: S-automerge

#5551 Fix `delete-remote-nodes.py` broke due to `sys.path.append`
  pytest/tests/delete_remote_nodes.py
Labels: P-low, S-automerge

#5467 nightly: remove no-longer-used mocknet tests from nightly set
  nightly/mocknet.txt
  nightly/nightly.txt
  scripts/check_pytests.py
Labels: S-automerge, A-CI, T-nodeX

#5540 test: test for wasmer0-vs-wasmer2 differences
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#5532 feat: Fix `nayduck.py --run-locally` to work from any directory
  scripts/nayduck.py
Labels: P-low, S-automerge

#5561 pytest: allow empty header reads in `proxy.bridge`
  pytest/lib/proxy.py
Labels: A-testing, S-automerge, A-benchmark, T-nodeX

#5536 re: Fix not measuring time correctly in `near-performance-metrics`
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: P-high, S-automerge

#5557 re: Remove unused dependencies from `near-primitives`
  Cargo.lock
  core/primitives/Cargo.toml
Labels: P-low, S-automerge

#5558 feat: Propagate `ActixMessageWrapper` between `PeerManagerActor` and `RoutingTableActor`
  chain/network/src/common/message_wrapper.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/types.rs
  utils/near-rate-limiter/src/framed_read.rs
Labels: P-high, S-automerge

#5575 re+doc(account-id): refactor and fully document near-account-id
  core/account-id/Cargo.toml
  core/account-id/README.md
  core/account-id/fuzz/Cargo.lock
  core/account-id/fuzz/README.md
  core/account-id/src/errors.rs
  core/account-id/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/config.rs
Labels: S-automerge

#5572 feat: Remove `Copy` traits from `core/crypto/src/signature.rs`.
  core/crypto/src/signature.rs
Labels: S-automerge

#5576 pytest: close stdout and stderr when local node is cleaned up
  pytest/lib/cluster.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5582 pytest: add /block Rosetta RPC tests
  nightly/pytest-rosetta.txt
  nightly/pytest-sanity.txt
  nightly/pytest.txt
  pytest/tests/rosetta/account-delete.py
  pytest/tests/sanity/rosetta.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5547 re: remove unused dependencies from `near-client`
  Cargo.lock
  chain/client/Cargo.toml
Labels: P-low, S-automerge

#5491 re: Update `RoutingTableUpdateResponse` docs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
Labels: P-low, S-automerge

#5550 re: Fix imports order in `near-network::cache_edges.rs`
  chain/network/src/tests/cache_edges.rs
Labels: P-low, S-automerge

#5524 re: Refactor `highest_height_peers`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: P-low, S-automerge

#5584 re: `near-network`: Limit visibility of `PeerStore` to `pub(crate)`
  chain/network/src/peer_manager/peer_store.rs
Labels: S-automerge

#5512 feat: use `lru` instead of `cached` in `near-network`
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/utils.rs
Labels: P-low, S-automerge

#5608 re: Use qualified imports in `jsonrpc::lib`
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#5594 Fixed location of `core/primitives/src/version.rs` file
  docs/protocol_upgrade.md
Labels: S-automerge, autorebase

#5604 re: `near-network`: Remove `clone()` from `Edge::partial_verify`
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge.rs
Labels: S-automerge

#5564 add comments for ShardLayout functions
  chain/client/src/test_utils.rs
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/validator_selection.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/shard_layout.rs
  core/store/benches/trie_bench.rs
  core/store/src/migrations.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/update.rs
  integration-tests/src/user/runtime_user.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/client/sharding_upgrade.rs
  nearcore/src/config.rs
  nearcore/src/migrations.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
Labels: S-automerge

#5259 feat: Implement `SyncLruCache`
  Cargo.lock
  Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-cache/benches/cache.rs
  utils/near-cache/src/lib.rs
Labels: S-automerge, P-medium

#5549 re: Rename `EdgeType` to `EdgeState` in `near-network`
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/tests/cache_edges.rs
Labels: P-low, S-automerge

#5489 re: Rename `SyncData` to `RoutingTableSync` and add in code documentation
  chain/client/src/test_utils.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing.rs
  chain/network/src/types.rs
  integration-tests/tests/network/infinite_loop.rs
Labels: P-low, S-automerge

#5671 pytest: fix failure with tests that use LogTracker
  pytest/lib/cluster.py
Labels: A-testing, A-CI, T-nodeX

#5670 chore: mark near-cache unpublishable
  Cargo.lock
  utils/near-cache/Cargo.toml
Labels: S-automerge

#5617 chore: update codeowners
  CODEOWNERS
Labels: S-automerge

#5619 chain: rosetta: fix make Construction and Data APIs ids match
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/models.rs
Labels: S-automerge, T-nodeX

#5664 Fix `check_formatting.sh` permissions
  scripts/check_formatting.sh
Labels: C-enhancement, C-housekeeping, A-testing, P-low, S-automerge

#5307 re: stop exporting `PeerInfo` from `near-network-primitives` in `near-network`
  Cargo.lock
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-csv-to-json/src/serde_with.rs
Labels: C-housekeeping, A-network, S-automerge, P-medium

#5620 re: Add `README.md` to `near-rate-limiter`
  utils/near-rate-limiter/README.md
Labels: C-enhancement, A-network, C-epic, S-automerge, C-docs, P-medium

#5497 feat: Add `--dry-run/-d` optional argument to `nayduck.py`
  scripts/nayduck.py
Labels: C-enhancement, A-testing, S-automerge, A-CI, P-medium

#5587 refactor: reduce sizes of the macros in imports.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#5674 re: Remove unused code from `tests/nearcore/state_nodes.rs`
  integration-tests/tests/nearcore/stake_nodes.rs
Labels: C-housekeeping, A-testing, P-low, S-automerge, A-CI, A-build

#5616 doc: add comments for chunk_cache.rs
  chain/chunks/src/chunk_cache.rs
Labels: S-automerge

#5681 chain: rosetta: introduce errors::Result type alias
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/validated_operations/mod.rs
  chain/rosetta-rpc/src/errors.rs
  chain/rosetta-rpc/src/utils.rs
Labels: S-automerge

#5637 Revert "Revert "Request chunks for multiple blocks simultaneously (#5…
  chain/chain/src/chain.rs
  chain/chain/src/missing_chunks.rs
  chain/chain/src/tests/mod.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  test-utils/runtime-tester/src/run_test.rs
Labels: S-automerge

#5591 chain: rosetta: move network identifier checking to common function
  chain/rosetta-rpc/src/lib.rs
Labels: S-automerge

#5656 re: `near-chain` Remove not needed ` -> ()`
  chain/chain/src/chain.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge

#5658 Re: Replace `or_insert_with(|| vec![])` with `or_default()`
  chain/chain/src/chain.rs
  chain/chunks/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: C-housekeeping, P-low, S-automerge, A-core

#5682 chain: rosetta: simplify TransactionIdentifier constructors
  chain/rosetta-rpc/src/models.rs
Labels: S-automerge, T-nodeX

#5679 buildkite: add Rosetta RPC tests to CI nightly test run
  .buildkite/pipeline.yml
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5566 fix: Disable 'We expected `peer_id` to belong to a component' warning
  chain/network/src/routing/routing_table_actor.rs
Labels: C-bug, P-low, A-network, S-automerge

#5643 Re: Remove unused imports from `integration-tests`
  Cargo.lock
  integration-tests/Cargo.toml
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, C-dependencies

#5633 feat: Add extra logs to debug `routing::archival_node`
  chain/network/src/peer_manager/peer_manager_actor.rs
  integration-tests/tests/network/routing.rs
  integration-tests/tests/network/runner.rs
Labels: C-enhancement, A-testing, P-low, A-network, S-automerge, A-CI

#5455 feat: Add bandwidth stats to `PeerManagerActor`
  Cargo.lock
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  utils/near-rate-limiter/Cargo.toml
  utils/near-rate-limiter/src/framed_read.rs
  utils/near-rate-limiter/src/lib.rs
Labels: C-enhancement, P-high, A-network, C-epic, S-automerge

#5580 doc: Add `near-network` reference level documentation `Overview`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5651 `near-network`: Move network protocol files to `network_protocol.rs`
  chain/network/src/lib.rs
  chain/network/src/network_protocol.rs
  chain/network/src/types.rs
Labels: C-housekeeping, A-chain, A-network, S-automerge, P-medium

#5581 chore: cleanup near-account-id API
  chain/chain/src/doomslug.rs
  chain/chain/src/test_utils.rs
  core/account-id/Cargo.toml
  core/account-id/LICENSE-APACHE
  core/account-id/LICENSE-MIT
  core/account-id/README.md
  core/account-id/src/borsh.rs
  core/account-id/src/errors.rs
  core/account-id/src/lib.rs
  core/account-id/src/serde.rs
  core/primitives/benches/serialization.rs
  core/primitives/src/receipt.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/transaction.rs
  core/primitives/src/validator_signer.rs
  core/store/src/migrations.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/standard_cases/main.rs
  nearcore/src/migrations.rs
  nearcore/src/shard_tracker.rs
  runtime/runtime/src/actions.rs
  test-utils/state-viewer/src/state_dump.rs
Labels: S-automerge

#5677 refactor: Keep IO and ops separately tracked inside GasCost
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/qemu.rs
  runtime/runtime-params-estimator/src/testbed_runners.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#5692 chain: rosetta: small refactor; add `convert_cause_to_transaction_id`
  chain/rosetta-rpc/src/adapters/mod.rs
Labels: S-automerge, T-nodeX

#5689 optimize get_random_target_tracking_shard
  chain/chunks/src/lib.rs
Labels: S-automerge

#5578 pytest: kill node process through Popen class and then wait for it
  pytest/lib/cluster.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5652 chain: remove unnecessary ShardId redefinition
  chain/epoch_manager/src/shard_assignment.rs
  chain/epoch_manager/src/validator_selection.rs
Labels: S-automerge

#5686 pytest: rosetta: add more tests checking how transactions look
  pytest/tests/sanity/rosetta.py
Labels: A-testing, S-automerge, A-CI

#5623 doc: Add `near-network` reference level documentation `Routing table computation`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5693 re: PeerManagerActor Make exceptions readable when TcpSocket::bind unwrap panics
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, C-dependencies

#5702 Temporarily disable rpc_finality until we review it
  nightly/pytest-sanity.txt
Labels: S-automerge

#5626 doc: Add `near-network` reference level documentation `Message routing`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5655 `near-chain`: Fix `clippy::redundant-clone` issues.
  chain/chain/src/chain.rs
  chain/chain/src/doomslug.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/gc.rs
Labels: C-enhancement, C-housekeeping, A-chain, P-low, S-automerge

#5419 refactor: minimize work-around
  core/crypto/src/signature.rs
Labels: S-automerge

#5691 doc: restored-receipts-verifier
  chain/chain/src/chain.rs
  core/primitives/src/version.rs
  integration-tests/tests/client/process_blocks.rs
  runtime/runtime/src/lib.rs
  tools/restored-receipts-verifier/README.md
  tools/restored-receipts-verifier/src/main.rs
Labels: S-automerge

#5706 fix: increase trie cache size
  core/store/src/trie/trie_storage.rs
Labels: A-transaction-runtime, S-automerge

#5720 Update NayDuck URLs to HTTPS
  .github/PULL_REQUEST_TEMPLATE/feature_stabilization.md
  nightly/README.md
  scripts/nayduck.py
Labels: S-automerge, A-CI, T-nodeX

#5595 feat: Fix `near_network::RoutingTableView::get_announce ` performance
  chain/network/src/routing/routing.rs
Labels: C-bug, C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5555 feat: Remove `serde` from multiple crates in `/chain`
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/types.rs
  chain/chunks/Cargo.toml
  chain/client/Cargo.toml
  chain/epoch_manager/Cargo.toml
Labels: C-housekeeping, P-low, S-automerge, A-build, C-dependencies

#5683 re: Remove `From<&str> for Config`
  nearcore/src/config.rs
Labels: C-housekeeping, P-low, S-automerge

#5583 re: `near-network`: Move `is_forward_transaction` to `utils.rs`
  chain/network/src/peer/codec.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/utils.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5661 feat: Remove redundant `clone()`
  chain/network/src/routing/routing_table_actor.rs
Labels: C-enhancement, C-housekeeping, A-chain, S-automerge, P-medium

#5638 re: Remove `Borsh` from `AccountIdOrPeerTrackingShard`
  chain/network-primitives/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5729 bug: Ignore `archival_node` test
  integration-tests/tests/network/routing.rs
Labels: C-bug, P-low, A-network

#5593 doc: Add `README.md` to `near-stable-hasher`
  utils/near-stable-hasher/README.md
Labels: C-housekeeping, A-chain, P-low, A-network, C-epic, S-automerge, C-docs

#5685 `near-rate-limiter` make sure `README.md` is included in `cargo doc`
  utils/near-rate-limiter/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, C-docs

#5627 doc: Add `near-network` reference level documentation `Database`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5663 re: Put `GetPeerIdResult` behind `test_features` flag
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5605 re: Simlify/Optimize `Decoder::decode`
  chain/network/src/peer/codec.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5676 fe: Move `ActixMessageWrapper` from `near-network` to `near-rate-limiter`
  Cargo.lock
  chain/network/src/common/mod.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  utils/near-rate-limiter/Cargo.toml
  utils/near-rate-limiter/src/framed_read.rs
  utils/near-rate-limiter/src/lib.rs
  utils/near-rate-limiter/src/message_wrapper.rs
Labels: C-enhancement, C-housekeeping, P-high, A-network, C-epic, S-automerge, T-core

#5723 re: Use `RUST_LOG=WARN` inside `pipeline.yml`
  .buildkite/pipeline.yml
Labels: S-automerge

#5636 change request_partial_encoded_chunk to filter peers that are up to date
  chain/chunks/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#5458 added build metadata badge
  README.md
Labels: S-automerge

#5597 feat: `near_network`: Improve`PeerManagerActor::send_sync`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-bug, C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5601 re: `near-network`: Rewrite `local_edge_info` in `RoutingTableView`
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5622 doc: Add `near-network` reference level documentation `Adding new edges to routing tables`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5612 re: `near-network` Limit visibility of types outside of crate
  chain/network/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/test_utils.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5639 re: Fix `routing::archival_node` test
  integration-tests/tests/network/routing.rs
Labels: C-bug, A-testing, P-low, A-network, S-automerge

#5428 re: Rename active peer to connected peer terminology in `near-network`
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-primitives/src/types/network_info.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  chain/rosetta-rpc/src/lib.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5710 feat: Reduce CI build time to 12m.
  .buildkite/pipeline.yml
Labels: C-enhancement, A-testing, P-low, S-automerge, A-CI

#5755 test: more informative failure message
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
Labels: S-automerge

#5660 feat: more descriptive `AccountId` error kinds
  core/account-id/src/errors.rs
  core/account-id/src/lib.rs
Labels: S-automerge

#5513 re: Move `SandboxResponse` from `near-network` to `near-network-primivites`
  chain/client/src/client_actor.rs
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5722 feat: trace node counter on receipt processing
  core/store/src/trie/trie_storage.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/runtime/src/ext.rs
  runtime/runtime/src/lib.rs
Labels: A-transaction-runtime, S-automerge

#5754 re: Disable yarn test
  scripts/test_nearlib.sh
Labels: C-bug, C-housekeeping, A-testing, P-low, S-automerge, A-CI

#5629 feat: Add bandwidth stats to `PeerManagerActor` pt2
  chain/network/src/peer_manager/peer_manager_actor.rs
  utils/near-rate-limiter/src/framed_read.rs
Labels: C-enhancement, P-high, A-network, C-epic, S-automerge

#5546 re: Remove usage of `serde` from `near-network-primitives`
  Cargo.lock
  chain/jsonrpc-primitives/src/types/network_info.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/types.rs
  chain/network/src/routing/routing.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5621 doc: Add `near-network` reference level documentation `Handshake`
  docs/network.md
Labels: C-enhancement, A-network, C-epic, S-automerge, C-docs, P-medium

#5744 chain: document why we’re ignoring errors in ClientActor::process_block
  chain/client/src/client_actor.rs
Labels: S-automerge

#5797 re: Improve handling errors in `scripts/test_nearlib.sh`.
  scripts/waitonserver.sh
Labels: C-enhancement, C-housekeeping, A-testing, P-low, A-CI

#5659 feat: upgrade rust `1.57.0`
  runtime/near-vm-runner-standalone/src/main.rs
  rust-toolchain.toml
Labels: C-enhancement, C-discussion, P-low, S-automerge, C-docs, A-build, C-dependencies

#5759 refactor: drop unused serializes from some errors
  runtime/near-vm-errors/src/lib.rs
Labels: S-automerge

#5762 Revert #5723
  .buildkite/pipeline.yml
  runtime/near-vm-runner/src/imports.rs
Labels: P-high, A-CI

#5815 refactor: test contract build script $PWD agnostic
  runtime/runtime-params-estimator/test-contract/build.sh
Labels: S-automerge

#5470 re: `near-network::PeerManager`: Refactor `monitor_peers_trigger`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5615 re: Remove dead code from `near-network-primitives`
  chain/network-primitives/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5792 re: Move `Edge` and `PertialEdgeInfo` to `network-protocol.rs`
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/network_protocol.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/tests/cache_edges.rs
  chain/network/src/types.rs
  integration-tests/tests/client/process_blocks.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#5625 doc: Add `near-network` reference level documentation `Message transportation layers`
  docs/network.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#5788 re: Refactor `impl TryFrom<&[u8]> for CryptoHash`
  core/primitives-core/src/hash.rs
Labels: C-enhancement, C-housekeeping, P-low, S-automerge

#5780 re: Fix Clion false errors in `core/store/src/sb.rs`
  core/store/src/db.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge

#5586 re: `Cargo.toml`: limit the number of features used by tokio
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/fuzz/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  integration-tests/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
Labels: C-enhancement, P-low, S-automerge, A-build, C-dependencies

#5810 chore: ensures all fuzz tests are part of the workspace
  Cargo.lock
  Cargo.toml
  chain/jsonrpc/fuzz/Cargo.lock
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs
  core/account-id/fuzz/Cargo.lock
  core/account-id/fuzz/Cargo.toml
Labels: S-automerge

#5789 Simplify `PeerActorManager::propose_edge`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5760 re: Fix `unnecessary 'unsafe' block` warnings
  runtime/near-test-contracts/tiny-contract-rs/src/lib.rs
  runtime/runtime-params-estimator/small-test-contract/src/lib.rs
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: C-housekeeping, P-low, S-automerge, A-contract-runtime

#5751 re: `near-network` Fix clippy warnings suggesting to use `default()` instead of `new()`
  chain/client/src/test_utils.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  nearcore/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5808 scripts: fix `neard` binary name in `nodelib.py`
  scripts/nodelib.py
Labels: S-automerge, A-CI

#5362 refactor: Rewrite `Clock` / add tests
  chain/chain/src/tests/simple_chain.rs
  core/primitives/src/time.rs
Labels: C-enhancement, C-housekeeping, A-chain, A-network, S-automerge, P-medium

#5787 re: Remove duplicated code in `PeerStore`
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5574 Remove `Copy` from `PublicKey`/`PrivateKey`
  core/crypto/src/key_conversion.rs
  core/crypto/src/vrf.rs
Labels: C-housekeeping, P-low, S-automerge, T-core

#5828 Show a help message if `neard view_state` is called withouta subcommand.
  test-utils/state-viewer/src/cli.rs
Labels: S-automerge

#5632 feat: `runtime/near-vm-runner`: Replace `cached` with `SyncLruCache`
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  utils/near-cache/Cargo.toml
Labels: C-enhancement, C-housekeeping, S-automerge, C-dependencies, A-contract-runtime, P-medium

#5825 pytest: configure nodes to track shards in upgradable.py test
  pytest/tests/sanity/upgradable.py
Labels: A-testing, P-high, S-automerge, A-CI, T-nodeX

#5802 feat: stabilize nonce range for implicit accounts
  CHANGELOG.md
  chain/chain/src/tests/simple_chain.rs
  core/primitives/src/version.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/res/genesis_config.json
  runtime/runtime/src/actions.rs
Labels: S-automerge

#5809 Inspect epochs with state-viewer
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
  test-utils/state-viewer/src/epoch_info.rs
  test-utils/state-viewer/src/lib.rs
  test-utils/state-viewer/src/main.rs
Labels: S-automerge

#5548 re: fix feature `protocol_feature_routing_exchange_algorithm`
  chain/client/Cargo.toml
  chain/jsonrpc/Cargo.toml
Labels: C-bug, A-chain, P-low, S-automerge, A-build

#5820 nightly: add account-id and jsonrpc fuzz targets
  nightly/fuzzing.txt
  pytest/tests/fuzz.py
  pytest/tests/runtime/fuzz_runtime.py
  pytest/tests/runtime/fuzz_wasm_vm.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5790 Add `debug_assert` to `Edge::build_hash`
  chain/network/src/routing/network_protocol.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5600 re: Remove utils.rs - refactor `fetch_ping_ping`
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/utils.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5783 re: Remove `From<Vec<u8>>` for `PeerId` and `KnownPeerState`
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_store.rs
  core/primitives/src/network.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge

#5798 feat: Add `scripts/requirements_check.sh`
  scripts/requirements_check.sh
  scripts/test_nearlib.sh
Labels: C-enhancement, C-housekeeping, A-testing, P-low, S-automerge, A-CI

#5805 re: Lets try removing `-j 16` from pipeline.yml
  .buildkite/pipeline.yml
Labels: C-housekeeping, A-testing, P-low, S-automerge, A-CI

#5745 re: `near-network` Remove unused `GetRoutingTable ` type
  chain/network/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5598 Fix an error, which confuses Rust plugin for Intellij
  integration-tests/tests/network/runner.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5743 re: `near-network` Split private actix types of out `types.rs`
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/lib.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/ibf_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5610 feat: increase `OLDEST_PROTOCOL_VERSION` from `34` to `LATEST - 1`
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  core/primitives/src/version.rs
Labels: C-enhancement, C-housekeeping, P-high, A-network, S-automerge

#5509 re: Make `deepsize` a qualified import
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/src/routing/network_protocol.rs
  core/account-id/src/lib.rs
  core/crypto/src/signature.rs
  core/primitives-core/src/account.rs
  core/primitives-core/src/hash.rs
  core/primitives/src/block.rs
  core/primitives/src/block_header.rs
  core/primitives/src/challenge.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/errors.rs
  core/primitives/src/merkle.rs
  core/primitives/src/network.rs
  core/primitives/src/rand.rs
  core/primitives/src/receipt.rs
  core/primitives/src/sharding.rs
  core/primitives/src/sharding/shard_chunk_header_inner.rs
  core/primitives/src/syncing.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  runtime/near-vm-errors/src/lib.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge

#5795 Fix crash in `near-network` benches
  chain/network/benches/routing_table_actor.rs
Labels: C-bug, C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#5703 feat: `near` Print an error if the number of `peers` specified in config is higher than allowed.
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#5634 re: `PeerManager`: Refactor`find_peers`
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5794 re: Rewrite `compute_result` in `near-network::Graph`
  chain/network/benches/graph.rs
  chain/network/src/routing/routing.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#5831 pytest: refactors tests to use `utils.wait_for_blocks`
  pytest/lib/cluster.py
  pytest/lib/utils.py
  pytest/tests/adversarial/fork_sync.py
  pytest/tests/adversarial/malicious_chain.py
  pytest/tests/adversarial/start_from_genesis.py
  pytest/tests/adversarial/wrong_sync_info.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/block_sync.py
  pytest/tests/sanity/block_sync_archival.py
  pytest/tests/sanity/db_migration.py
  pytest/tests/sanity/garbage_collection.py
  pytest/tests/sanity/garbage_collection1.py
  pytest/tests/sanity/garbage_collection_sharding_upgrade.py
  pytest/tests/sanity/gc_after_sync.py
  pytest/tests/sanity/gc_after_sync1.py
  pytest/tests/sanity/gc_sync_after_sync.py
  pytest/tests/sanity/handshake_tie_resolution.py
  pytest/tests/sanity/lightclnt.py
  pytest/tests/sanity/one_val.py
  pytest/tests/sanity/proxy_restart.py
  pytest/tests/sanity/repro_2916.py
  pytest/tests/sanity/restaked.py
  pytest/tests/sanity/rpc_light_client_execution_outcome_proof.py
  pytest/tests/sanity/skip_epoch.py
  pytest/tests/sanity/spin_up_cluster.py
  pytest/tests/sanity/staking1.py
  pytest/tests/sanity/state_migration.py
  pytest/tests/sanity/state_sync.py
  pytest/tests/sanity/state_sync1.py
  pytest/tests/sanity/state_sync2.py
  pytest/tests/sanity/state_sync3.py
  pytest/tests/sanity/state_sync4.py
  pytest/tests/sanity/state_sync5.py
  pytest/tests/sanity/state_sync_fail.py
  pytest/tests/sanity/state_sync_late.py
  pytest/tests/sanity/state_sync_routed.py
  pytest/tests/sanity/switch_node_key.py
  pytest/tests/sanity/sync_ban.py
  pytest/tests/sanity/sync_chunks_from_archival.py
  pytest/tests/sanity/transactions.py
  pytest/tests/sanity/upgradable.py
  pytest/tests/sanity/validator_switch.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5833 Write `poll_next` in a cleaner way
  utils/near-rate-limiter/src/framed_read.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5756 Wasmer upgrade (to fork's 2.1.2)
  Cargo.lock
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#5589 feat(dump-state): Support two modes of state dumping: InMemory and Streaming
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
  test-utils/state-viewer/src/state_dump.rs
Labels: S-automerge

#5830 fix shardtracker comments
  nearcore/src/shard_tracker.rs
Labels: S-automerge

#5774 chore(compliance): ensure crates link to repo
  chain/chain-primitives/Cargo.toml
  chain/chunks-primitives/Cargo.toml
  chain/client-primitives/Cargo.toml
  chain/jsonrpc-primitives/Cargo.toml
  chain/network-primitives/Cargo.toml
  core/account-id/Cargo.toml
  core/chain-configs/Cargo.toml
  core/crypto/Cargo.toml
  core/metrics/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  tools/rpctypegen/core/Cargo.toml
  tools/rpctypegen/macro/Cargo.toml
Labels: S-automerge

#5772 chore(compliance): ensure all crates have the NEAR author
  chain/jsonrpc/fuzz/Cargo.toml
  runtime/near-vm-runner/fuzz/Cargo.toml
  test-utils/runtime-tester/fuzz/Cargo.toml
  test-utils/testlib/Cargo.toml
  tools/restored-receipts-verifier/Cargo.toml
  tools/storage-usage-delta-calculator/Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#5758 feat: Add test to `ThrottledFramedRead`
  Cargo.lock
  utils/near-rate-limiter/Cargo.toml
  utils/near-rate-limiter/src/framed_read.rs
Labels: C-housekeeping, A-testing, A-network, S-automerge, P-medium

#5773 chore(compliance): ensure proper licensing.
  chain/chain-primitives/LICENSE-APACHE
  chain/chain-primitives/LICENSE-MIT
  chain/chunks-primitives/LICENSE-APACHE
  chain/chunks-primitives/LICENSE-MIT
  chain/client-primitives/LICENSE-APACHE
  chain/client-primitives/LICENSE-MIT
  chain/jsonrpc-primitives/LICENSE-APACHE
  chain/jsonrpc-primitives/LICENSE-MIT
  chain/network-primitives/LICENSE-APACHE
  chain/network-primitives/LICENSE-MIT
  core/account-id/Cargo.toml
  core/chain-configs/LICENSE-APACHE
  core/chain-configs/LICENSE-MIT
Labels: S-automerge
