Repository near/nearcore, pull requests merged in 2021-01, with the labels that each got.

#3762 docu: improve README.md
  README.md
Labels: docs

#3778 add all comments suggest by Evgeny and move meta parsing to separate mod
  runtime/near-evm-runner/src/lib.rs
  runtime/near-evm-runner/src/meta_parsing.rs
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/src/utils.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
Labels: EVM, housekeeping

#3775 [WIP] Evm phase2
  CODEOWNERS
  Cargo.lock
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/benches/bench.rs
  runtime/near-evm-runner/benches/benches/cryptozombies.rs
  runtime/near-evm-runner/benches/benches/mod.rs
  runtime/near-evm-runner/src/lib.rs
  runtime/near-evm-runner/src/meta_parsing.rs
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/src/utils.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  test-utils/testlib/src/standard_evm_cases.rs
  tests/test_cases_runtime.rs
Labels: EVM, housekeeping

#3785 Pin the syn dependency to avoid breaking change
  Cargo.lock
  Cargo.toml
Labels: CI, EVM, bug, build, dependencies, housekeeping

#3797 fix(EVM): Limit max EVM gas by the max burnt gas limit
  core/primitives/src/version.rs
  nightly/nightly.txt
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/tests/build/Fibonacci.abi
  runtime/near-evm-runner/tests/build/Fibonacci.bin
  runtime/near-evm-runner/tests/build/Loop.abi
  runtime/near-evm-runner/tests/build/Loop.bin
  runtime/near-evm-runner/tests/contracts/Fibonacci.sol
  runtime/near-evm-runner/tests/contracts/Loop.sol
  test-utils/testlib/src/standard_evm_cases.rs
  tests/test_cases_runtime.rs
  tests/test_cases_testnet_rpc.rs
Labels: EVM, bug, on-fire, testing

#3783 Revert "fix(network): avoid unnecessary verification of sync data (#3…
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/process_blocks.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/network/src/peer_manager.rs
  chain/network/src/types.rs
  chain/network/tests/infinite_loop.rs
  chain/network/tests/peer_handshake.rs
  chain/network/tests/runner/mod.rs
  chain/network/tests/stress_network.rs
  core/primitives/src/network.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/types.rs
  neard/src/lib.rs
  neard/src/runtime.rs
Labels: automerge

#3763 test(evm): Add Balancer test localnode, betanet on nightly
  nightly/evm.txt
  nightly/tests_for_nayduck.txt
  pytest/tests/evm/balancer_betanet.py
  pytest/tests/evm/balancer_localnode.py
  pytest/tests/evm/keys/1608318003006.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318006307.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318008973.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318012144.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318015318.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318018596.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318021260.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318024420.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318027608.balancer-core-test.betanet.json
  pytest/tests/evm/keys/1608318030277.balancer-core-test.betanet.json
  pytest/tests/evm/keys/balancer-core-test.betanet.json
Labels: CI, EVM, enhancement, nightly, testing

#3801 Fix a bug in meta call parsing
  runtime/near-evm-runner/src/meta_parsing.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/tests/failures.rs
Labels: EVM, bug, testing

#3773 feat(evm): Raw Ethereum transaction relay support
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  neard/src/config.rs
  neard/src/runtime.rs
  runtime/near-evm-runner/src/builtins.rs
  runtime/near-evm-runner/src/interpreter.rs
  runtime/near-evm-runner/src/meta_parsing.rs
  runtime/near-evm-runner/src/near_ext.rs
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/src/utils.rs
  runtime/near-evm-runner/tests/contracts/SolTests.sol
  runtime/near-evm-runner/tests/failures.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/runtime-params-estimator/src/evm_estimator.rs
  runtime/runtime-standalone/src/lib.rs
  runtime/runtime/src/adapter.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer.rs
Labels: EVM, enhancement

#3800 fix(evm): Added betanet evm chain id and renamed test_evm to testnet_evm
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/lib.rs
  neard/src/config.rs
  neard/src/runtime.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: EVM, SRE

#3772 Add a new derive 'perf_with_debug'
  Cargo.lock
  chain/client/src/client_actor.rs
  chain/client/src/view_client.rs
  chain/network/src/types.rs
  utils/near-performance-metrics-macros/src/lib.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/stats_disabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3809 Change prints inside near-performance-metrics to be warnings
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3816 feat(mac): add osx nightly builds to the github action
  .github/workflows/mac_binary.yml
Labels: SRE

#3842 Expand CryptoZombies tests
  runtime/near-evm-runner/benches/benches/cryptozombies.rs
  runtime/near-evm-runner/tests/build/ZombieOwnership.abi
  runtime/near-evm-runner/tests/build/ZombieOwnership.bin
  runtime/near-evm-runner/tests/build/zombieAttack.abi
  runtime/near-evm-runner/tests/build/zombieAttack.bin
  runtime/near-evm-runner/tests/build_zombieattack.sh
  runtime/near-evm-runner/tests/contracts/SafeMath.sol
  runtime/near-evm-runner/tests/contracts/ZombieAttack.sol
  test-utils/testlib/src/standard_evm_cases.rs
  tests/test_cases_runtime.rs
Labels: EVM, enhancement, testing

#3840 test(epoch_manager): some sanity tests
  chain/epoch_manager/src/lib.rs
Labels: chain

#3747 add feature flag to debug memory usage
  Cargo.lock
  Cargo.toml
  core/primitives/src/lib.rs
  neard/Cargo.toml
  neard/src/main.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3870 fix: Fixing a regression in two network tests
  pytest/lib/messages/block.py
  pytest/tests/sanity/network_drop_package.py
  pytest/tests/sanity/proxy_simple.py
Labels: automerge
