Repository near/nearcore, pull requests merged in 2021-03, with the labels that each got.

#4018 refactor: move code style checks to tests from CI
  .buildkite/pipeline.yml
  tests/tidy.rs
Labels: automerge

#4014 fix: Fixing an error in cross_shard_tx
  chain/chain/src/test_utils.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/tests/cross_shard_tx.rs
Labels: automerge

#4015 Add a few important logs
  chain/jsonrpc/src/lib.rs
  neard/Cargo.toml
  neard/src/config.rs
  neard/src/main.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3971 feat: Add precompiled contracts for alt_bn128 curve [rebased]
  .buildkite/pipeline.yml
  Cargo.lock
  Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  neard/Cargo.toml
  runtime/CHANGELOG.md
  runtime/near-evm-runner/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/tests/res/nightly_test_contract_rs.wasm
  runtime/near-vm-runner/tests/res/test_contract_rs.wasm
  runtime/near-vm-runner/tests/test-contract-rs/Cargo.lock
  runtime/near-vm-runner/tests/test-contract-rs/Cargo.toml
  runtime/near-vm-runner/tests/test-contract-rs/build.sh
  runtime/near-vm-runner/tests/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/tests/test_rs_contract.rs
  runtime/runtime-params-estimator/.gitignore
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/estimate.sh
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/ext_costs_generator.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime-params-estimator/test-contract/.cargo/config
  runtime/runtime-params-estimator/test-contract/Cargo.toml
  runtime/runtime-params-estimator/test-contract/build.sh
  runtime/runtime-params-estimator/test-contract/res/large_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/large_payload
  runtime/runtime-params-estimator/test-contract/res/medium_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/medium_payload
  runtime/runtime-params-estimator/test-contract/res/near_evm.wasm
  runtime/runtime-params-estimator/test-contract/res/small_contract.wasm
  runtime/runtime-params-estimator/test-contract/res/small_payload
  runtime/runtime-params-estimator/test-contract/src/lib.rs
  runtime/runtime/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: EVM

#4012 Add new FramedWrite with buffer limits and stats
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/codec.rs
  chain/network/src/metrics.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  core/primitives/src/block_header.rs
  neard/Cargo.toml
  neard/src/config.rs
  neard/src/main.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/framed_write.rs
  utils/near-performance-metrics/src/lib.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#4000 refactor: significantly reduce costs_conting blast radius
  Cargo.toml
  core/primitives-core/src/profile.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/apply_state.rs
  neard/Cargo.toml
  neard/src/runtime.rs
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/src/runner.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/tests/vm_logic_builder.rs
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/benches/bench.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#4007 refactor: typify MethodUTF8Error out of existence
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner/benches/bench.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/near-vm-runner/tests/test_error_cases.rs
  runtime/near-vm-runner/tests/test_invalid_contracts.rs
  runtime/near-vm-runner/tests/test_rs_contract.rs
  runtime/near-vm-runner/tests/test_ts_contract.rs
  runtime/near-vm-runner/tests/test_utils/mod.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
Labels: automerge

#4031 Add Bowen to the runtime codeowners
  CODEOWNERS
Labels: automerge

#4029 replace size package with bytesize
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/codec.rs
Labels: automerge

#4026 refactor: improve visibility into wasmer1 performance
  runtime/near-vm-runner/src/wasmer1_runner.rs
Labels: automerge

#3960 fix(rpc): address slowness in validator rpc
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/src/lib.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  chain/jsonrpc/src/lib.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  core/store/src/db.rs
  neard/src/lib.rs
  neard/src/runtime.rs
  neard/tests/rpc_nodes.rs
Labels: automerge

#4033 feat: enable "how long did this thing run?" logging
  neard/src/main.rs
  runtime/near-vm-runner/src/runner.rs
  test-utils/logger/src/lib.rs
Labels: automerge

#4027 refactor: improve test compilation speed and organization
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/error_cases.rs
  runtime/near-vm-runner/src/tests/invalid_contracts.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
Labels: automerge

#3983 feat: allow more sophisticated vm benchmarks
  Cargo.lock
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/error_cases.rs
Labels: automerge

#4028 feat(primitives): Add versioning to Account
  Cargo.toml
  chain/chain/src/test_utils.rs
  chain/client/Cargo.toml
  chain/client/tests/challenges.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/utils.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/account.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/mod.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-populate/src/lib.rs
  neard/src/config.rs
  neard/src/genesis_validate.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/state-viewer/src/state_dump.rs
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/node/runtime_node.rs
  test-utils/testlib/src/runtime_utils.rs
  tests/test_cases_runtime.rs
Labels: automerge

#4045 Revert "feat(primitives): Add versioning to Account"
  Cargo.toml
  chain/chain/src/test_utils.rs
  chain/client/Cargo.toml
  chain/client/tests/challenges.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/utils.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/account.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/mod.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-populate/src/lib.rs
  neard/src/config.rs
  neard/src/genesis_validate.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/state-viewer/src/state_dump.rs
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/node/runtime_node.rs
  test-utils/testlib/src/runtime_utils.rs
  tests/test_cases_runtime.rs
Labels: SRE

#4049 fix(tests): remove `Block Missing` error message from get_all_heights
  pytest/lib/cluster.py
Labels: automerge

#4041 refactor: reduce code duplication
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
Labels: automerge

#4052 fix(test): validator_switch.py
  pytest/tests/sanity/state_sync1.py
  pytest/tests/sanity/validator_switch.py
Labels: automerge

#4053 feat: use lazy_static_include
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/tests/process_blocks.rs
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/genesis-populate/src/main.rs
  neard/Cargo.toml
  neard/src/config.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/tests/test_async_calls.rs
  runtime/runtime/tests/test_evil_contracts.rs
  test-utils/loadtester/Cargo.toml
  test-utils/loadtester/src/transactions_generator.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/runtime_utils.rs
  test-utils/testlib/src/standard_evm_cases.rs
Labels: automerge

#3880 fix(delay_detector): measure both cpu time and real time
  Cargo.lock
  tools/delay_detector/Cargo.toml
  tools/delay_detector/src/lib.rs
Labels: automerge

#4060 feat: time wasmer deserialization costs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: automerge

#4069 fix: use lower-level log level for timing info
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: automerge

#4072 refactor: don't use both log and tracing in chain
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/missing_chunks.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
Labels: automerge

#4064 fix(runtime): add access key nonce range
  Cargo.toml
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/test_utils.rs
  chain/client/tests/challenges.rs
  chain/client/tests/process_blocks.rs
  core/primitives-core/src/account.rs
  core/primitives/Cargo.toml
  core/primitives/src/errors.rs
  core/primitives/src/version.rs
  neard/Cargo.toml
  neard/src/runtime/mod.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#4075 refactor: fix one last usage of include_bytes
  runtime/near-vm-runner/src/tests/contract_preload.rs
Labels: automerge

#4070 fix(jsonrpc): Fix metrics usage and signature to prevent fails
  chain/jsonrpc-primitives/src/metrics.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/validator.rs
Labels: automerge

#4083 fix(test): staking2.py false failures
  pytest/tests/sanity/staking2.py
Labels: automerge

#4078 refactor: don't use both log and tracing
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/codec.rs
  chain/network/src/peer_store.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
  neard/Cargo.toml
  neard/src/config.rs
  neard/src/lib.rs
  neard/src/main.rs
  neard/src/runtime/mod.rs
  neard/src/shard_tracker.rs
Labels: automerge

#4080 refactor: use more natural interface for contract runner
  runtime/near-vm-runner/benches/bench.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
Labels: automerge

#4086 fix(test): one_val.py
  pytest/tests/sanity/one_val.py
Labels: automerge

#4079 refactor(jsonrpc): Refactor view_client structured errors according to removal of BlockMissing for GetBlockError, GetChunkError, QueryError
  CODEOWNERS
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/query.rs
Labels: automerge

#4088 doc: using tracing for instrumentation
  runtime/near-vm-runner/README.md
Labels: automerge

#4092 Remove release scripts
  .buildkite/pipeline.yml
  .buildkite/release-nightly.yml
  .buildkite/release-perf.yml
  .buildkite/release.yml
  scripts/binary-release.sh
  scripts/docker-release.sh
  scripts/tag_release.sh
Labels: automerge

#4097 fix(release): Fix mac release
  .github/workflows/mac_binary.yml
  scripts/mac-release.sh
Labels: automerge

#4055 update_migration_17_18
  core/store/src/migrations.rs
Labels: automerge

#4100 chmod +x mac-release script
  scripts/mac-release.sh
Labels: SRE

#4104 fix(ci): mac os x typo
  scripts/mac-release.sh
Labels: automerge

#4106 fix(example): Fixed the indexer SystemRunner to run
  tools/indexer/example/src/main.rs
Labels: automerge

#4093 fix(test): rpc_tx_forwarding with nightly_protocol
  pytest/tests/sanity/rpc_tx_forwarding.py
Labels: automerge

#4110 recompute routing graph at most once a second
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
Labels: automerge

#4121 Switch all script to use /usr/bin/env bash as /bin/bash is not portable
  chain/jsonrpc/build_errors_schema.sh
  pytest/empty-contract-rs/build.sh
  runtime/near-evm-runner/tests/build.sh
  runtime/near-vm-runner/tests/test-contract-rs/build.sh
  runtime/runtime-params-estimator/compiler.sh
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/emu-cost/ci.sh
  runtime/runtime-params-estimator/emu-cost/io_cost.sh
  runtime/runtime-params-estimator/emu-cost/run.sh
  runtime/runtime-params-estimator/estimate.sh
  runtime/runtime-params-estimator/setup.sh
  runtime/runtime-params-estimator/small-test-contract/build.sh
  runtime/runtime-params-estimator/test-contract/build.sh
  runtime/runtime/tests/tiny-contract-rs/build.sh
  scripts/build_wasm.sh
  scripts/install_precommit.sh
  scripts/mac-release.sh
  scripts/run_clippy.sh
  scripts/run_docker.sh
  scripts/setup_hooks.sh
  scripts/test_nearlib.sh
  scripts/waitonserver.sh
Labels: automerge

#4120 refactor(pytest): Update sanity/transactions.py test to pass according to dropped routing in handle_query ViewClient method
  pytest/tests/sanity/transactions.py
Labels: automerge

#4116 fix(runtime): disallow deletion of account with large state
  core/primitives-core/src/account.rs
  core/primitives/src/errors.rs
  core/primitives/src/version.rs
  neard/res/genesis_config.json
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
Labels: automerge

#4102 fix(chain): increase chunk retry timeout
  chain/chunks/src/lib.rs
Labels: automerge

#4111 Validate each edge only once
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/types.rs
Labels: automerge

#4090 refactor: switch the rest of vm-runner to use ContractCode
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: automerge

#4129 Added the infra team to codeowners for buildkite and scripts
  CODEOWNERS
Labels: automerge

#4119 fix(jsonrpc): Fix some errors inconsistency with unknown blocks or untracked shards for handle_query view_client method
  chain/chain-primitives/src/error.rs
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc/src/lib.rs
Labels: automerge

#4131 Added node interfaces team as owners of client-primitives
  CODEOWNERS
Labels: automerge

#4122 fix(test): rpc_state_changes access key nonce
  pytest/tests/sanity/rpc_state_changes.py
Labels: automerge

#4124 refactor(jsonrpc): Refactor gas_price method to be typed and errors structured
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc/src/lib.rs
Labels: automerge

#4123 fix: set proper error msg in check_actor_permissions
  runtime/runtime/src/actions.rs
Labels: automerge

#4143 fix(primitives-core): ProfileData default uses feature and add tests
  core/primitives-core/src/profile.rs
Labels: automerge

#4136 feature: more runtime performance visibility into runtime
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: automerge

#4152 fix: remove warnings in neard release
  core/primitives-core/src/profile.rs
Labels: automerge

#4154 Optimize hash function for PeerId
  core/primitives/src/network.rs
Labels: automerge

#4058 (WIP) feat: check available memory in store/rocksdb
  Cargo.lock
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/db/v6_to_v7.rs
Labels: automerge

#4149 Verify edges only once in a correct way
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/types.rs
  chain/network/tests/cache_edges.rs
Labels: automerge

#4113 Reset max memory usage after loading config
  neard/src/lib.rs
Labels: automerge

#4141 (fix) Account versioning pytest fix
  Cargo.toml
  neard/res/genesis_for_test_account_versioning.json
  pytest/lib/cluster.py
  pytest/tests/sanity/block_sync.py
  pytest/tests/sanity/garbage_collection.py
  pytest/tests/sanity/garbage_collection1.py
  pytest/tests/sanity/gc_after_sync.py
  pytest/tests/sanity/gc_sync_after_sync.py
  pytest/tests/sanity/one_val.py
  pytest/tests/sanity/switch_node_key.py
  pytest/tests/sanity/sync_chunks_from_archival.py
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/node/process_node.rs
  tests/test_rejoin.rs
Labels: automerge

#4151 refactor(crypto): impl FromStr instead of TryFrom<&str> for near_crypto::Signature and CryptoHash
  chain/client/tests/process_blocks.rs
  chain/jsonrpc/tests/rpc_query.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/models.rs
  core/crypto/src/errors.rs
  core/crypto/src/lib.rs
  core/crypto/src/signature.rs
  core/primitives-core/src/hash.rs
  test-utils/loadtester/src/remote_node.rs
Labels: automerge

#3929 fix: update example contract
  runtime/near-vm-runner-standalone/README.md
  runtime/near-vm-runner-standalone/example-contract/Cargo.lock
  runtime/near-vm-runner-standalone/example-contract/Cargo.toml
  runtime/near-vm-runner-standalone/example-contract/build.js
  runtime/near-vm-runner-standalone/example-contract/run.js
  runtime/near-vm-runner-standalone/example-contract/src/lib.rs
Labels: automerge

#4156 Add @pmnoxx and @mikhailOK to codeowners
  CODEOWNERS
Labels: automerge

#4130 refactor: code cleanup
  runtime/near-vm-logic/src/gas_counter.rs
Labels: automerge

#4160 refactor: centralize&improve infrastructure for building test contracts
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/tests/process_blocks.rs
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/genesis-populate/src/main.rs
  pytest/lib/branches.py
  pytest/tests/contracts/deploy_call_smart_contract.py
  pytest/tests/contracts/gibberish.py
  pytest/tests/mocknet/sanity.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/concurrent_function_calls.py
  pytest/tests/sanity/db_migration.py
  pytest/tests/sanity/upgradable.py
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/README.md
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/res/.gitignore
  runtime/near-test-contracts/res/test_contract_ts.wasm
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/Cargo.lock
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-test-contracts/test-contract-ts/.gitignore
  runtime/near-test-contracts/test-contract-ts/README.md
  runtime/near-test-contracts/test-contract-ts/assembly/index.ts
  runtime/near-test-contracts/test-contract-ts/assembly/tsconfig.json
  runtime/near-test-contracts/test-contract-ts/package-lock.json
  runtime/near-test-contracts/test-contract-ts/package.json
  runtime/near-test-contracts/tiny-contract-rs/Cargo.lock
  runtime/near-test-contracts/tiny-contract-rs/Cargo.toml
  runtime/near-test-contracts/tiny-contract-rs/src/lib.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/README.md
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/tests/res/nightly_test_contract_rs.wasm
  runtime/near-vm-runner/tests/res/test_contract_rs.wasm
  runtime/near-vm-runner/tests/test-contract-rs/build.sh
  runtime/runtime/Cargo.toml
  runtime/runtime/tests/test_async_calls.rs
  runtime/runtime/tests/test_evil_contracts.rs
  runtime/runtime/tests/tiny-contract-rs/build.sh
  runtime/runtime/tests/tiny-contract-rs/res/tiny_contract_rs.wasm
  test-utils/loadtester/Cargo.toml
  test-utils/loadtester/src/transactions_generator.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/node/mod.rs
  test-utils/testlib/src/runtime_utils.rs
Labels: automerge

#4163 fix(test): fix nightly access key nonce tests
  Cargo.toml
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/standard_test_cases.rs
  test-utils/testlib/src/user/mod.rs
  test-utils/testlib/src/user/rpc_user.rs
  test-utils/testlib/src/user/runtime_user.rs
Labels: automerge

#4175 Fix the broken docker release due to stable toolchain change
  Dockerfile
  Dockerfile.nightly
Labels: automerge
