Repository near/nearcore, pull requests merged in 2021-08, with the labels that each got.

#4611 nightly: fix test_gc_after_state_sync test after recent test moves
  nightly/expensive.txt
Labels: S-automerge, T-nodeX

#4616 feat(build): changed target dir for near-sandbox to avoid conflict du…
  Makefile
Labels: S-automerge, T-SRE

#4610 integration-tests: fix compiler warnings
  integration-tests/tests/test_catchup.rs
  integration-tests/tests/test_rejoin.rs
  integration-tests/tests/test_simple.rs
  integration-tests/tests/test_tps_regression.rs
Labels: S-automerge, T-nodeX

#4620 feat(build): removed CARGO_PROFILE_RELEASE_DEBUG=true env var for san…
  Makefile
Labels: S-automerge, T-SRE

#4619 pytest: remove breaking assert in bridge pytests
  pytest/lib/bridge.py
Labels: S-automerge

#4606 Remove a 'dev-dependency' of 'near-client' on 'testlib' to prevent circular dependencies.
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/tests/chunks_management.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/chunks_management.rs
  integration-tests/tests/client/main.rs
Labels: S-automerge

#4634 refactor: remove some code duplication in params estimator
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/ext_costs_generator.rs
Labels: S-automerge

#4626 nit(runtime): get rid of cells inside profile data
  core/primitives-core/src/profile.rs
  runtime/near-vm-runner/src/runner.rs
Labels: S-automerge

#4638 Change `meatdata` to `metadata`
  core/primitives/src/transaction.rs
Labels: S-automerge

#4639 refactor: make it clear that regular_op_cost uses the multiplier
  core/primitives-core/src/config.rs
Labels: S-automerge

#4643 fix: update wasmer 0 to prevent miscompilation on a specific nightly rust version
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
Labels: S-automerge

#4637 pytest: remove support for preexisting cluster
  pytest/lib/cluster.py
  pytest/tests/sandbox/patch_state.py
Labels: S-automerge

#4445 Update emu-cost docs due to nearcore changes
  runtime/runtime-params-estimator/emu-cost/README.md
Labels: S-automerge

#4657 Address outstanding comments from PR #4592
  Cargo.lock
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/genesis_validate.rs
  neard/Cargo.toml
  runtime/runtime/tests/runtime_group_tools/mod.rs
Labels: S-automerge

#4658 remove unused code in shard tracker: untrack_account and untrack_shard
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
Labels: S-automerge

#4667 nayduck: fix `lib` tests
  nightly/expensive.txt
Labels: S-automerge, A-CI, T-nodeX

#4666 Update `total_supply` when dumping state for the new genesis
  test-utils/state-viewer/src/state_dump.rs
Labels: S-automerge

#4670 Remove `run_nodes.rs`
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/run_nodes.rs
Labels: S-automerge

#4672 nayduck: support reading commented ./<path> include directives
  nightly/TODO-disabled-4552.txt
  nightly/nightly.txt
  nightly/pytest-stress.txt
  scripts/nayduck.py
Labels: S-automerge, A-CI, T-nodeX

#4562 feat: one button "run estimator in docker \w qemu"
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#4675 scripts: recognise `#expensive` lines in check_nightly.py script
  scripts/check_nightly.py
Labels: S-automerge, A-CI, T-nodeX

#4673 feat: prepare for 1.21.0 release
  chain/chain/Cargo.toml
  chain/client/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/src/runtime/migration_data.rs
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/res/genesis_config.json
  nearcore/src/migrations.rs
  neard/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/runtime/Cargo.toml
  runtime/runtime/src/lib.rs
  tools/restored-receipts-verifier/Cargo.toml
  tools/restored-receipts-verifier/src/main.rs
Labels: S-automerge

#4647 Create separate `RuntimeTestbed` for each metric
  Cargo.lock
  genesis-tools/genesis-populate/src/lib.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge, A-params-estimator

#4676 nearcore: return struct from start_with_config rather than a tuple
  chain/indexer/src/lib.rs
  integration-tests/tests/nearcore/node_cluster.rs
  integration-tests/tests/nearcore/stake_nodes.rs
  integration-tests/tests/nearcore/sync_nodes.rs
  integration-tests/tests/nearcore/sync_state_nodes.rs
  nearcore/src/lib.rs
Labels: S-automerge, T-nodeX

#4674 nightly: comment out tests which are currently consistently failing
  nightly/expensive.txt
  nightly/mocknet.txt
  nightly/nightly.txt
  nightly/pytest-sanity.txt
  nightly/pytest-stress.txt
Labels: S-automerge, A-CI, T-nodeX

#4682 nightly: move disabled tests to their corresponding files
  nightly/TODO-disabled-4552.txt
  nightly/nightly.txt
  nightly/pytest-adversarial.txt
  nightly/pytest-sanity.txt
  nightly/pytest-stress.txt
Labels: S-automerge, A-CI, T-nodeX

#4679 refactor: keep bench and release profile in sync to avoid surprises
  Cargo.toml
Labels: S-automerge

#4680 nightly: add a README
  nightly/README.md
Labels: S-automerge, A-CI, T-nodeX

#4558 Describe `Trie` entities related to `Runtime`
  docs/trie.md
Labels: A-transaction-runtime

#4663 chore: Update `primitive-types` to `0.10`, and remove old EVM dependencies
  Cargo.lock
  chain/epoch_manager/Cargo.toml
  core/crypto/Cargo.toml
  core/crypto/src/signature.rs
  core/primitives/Cargo.toml
  deny.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/fuzz/Cargo.lock
Labels: S-automerge, C-dependencies

#4530 Base parallelization
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
Labels: S-automerge

#4681 feat(neard): stop RPC servers gracefully after getting a signal
  Cargo.lock
  chain/jsonrpc/src/lib.rs
  chain/rosetta-rpc/src/lib.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/src/cli.rs
Labels: S-automerge, T-nodeX

#4684 Explain differences caused by LTO in params-estimator doc
  runtime/runtime-params-estimator/emu-cost/README.md
Labels: S-automerge, A-params-estimator

#4693 fix(bug): fix the upgradable.py and backwards_compatible.py tests aft…
  pytest/lib/branches.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/db_migration.py
  pytest/tests/sanity/upgradable.py
Labels: C-bug, S-automerge

#4694 fix(account-id): subaccounts are valid one level deep only
  core/account-id/src/lib.rs
Labels: S-automerge

#4687 fix update_res
  scripts/state/update_res.py
Labels: S-automerge

#4636 refactor: restructure estimator to allow computing a subset of costs
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/costs.txt
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/cost_table.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/measures_to_costs.rs
Labels: S-automerge

#4701 pytest: verify that `genesis-populate` run succeeded
  pytest/lib/populate.py
Labels: S-automerge, T-nodeX

#4703 pytest: don’t complain if trying to kill already dead process
  pytest/lib/cluster.py
Labels: S-automerge, T-nodeX

#4699 Break the circular dependency of runtime/runtime on testlib
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/src/node/runtime_node.rs
  integration-tests/src/runtime_utils.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge

#4700 tests: make panicks in near-test-contracts more verbose
  runtime/near-test-contracts/src/lib.rs
Labels: S-automerge, T-nodeX

#4692 Rename `key_hash` from `TrieRefcountChange` to `trie_node_or_value_hash`
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  docs/trie.md
Labels: S-automerge

#4707 refactor: remove work-around for cargo features
  Cargo.lock
  chain/client/Cargo.toml
Labels: S-automerge

#4709 fix: change default behavior of neard testnet
  neard/src/cli.rs
Labels: S-automerge

#4708 refactor: remove more dead code from estimator
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge, A-params-estimator

#4705 fix: two places in the code where we should be prev_hash instead of hash
  chain/client/src/client_actor.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4651 refactor(chain): expunge `rocksdb` from `near-jsonrpc-primitives` dependency tree
  Cargo.lock
  chain/chunks-primitives/Cargo.toml
  chain/chunks-primitives/src/error.rs
  chain/chunks-primitives/src/lib.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/lib.rs
  chain/network/src/metrics.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/recorder.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#4716 refactor: introduce `ViewConfig` for storing `max_gas_burnt_view`
  core/primitives-core/src/config.rs
  core/primitives/src/runtime/config.rs
  nearcore/src/runtime/mod.rs
  runtime/near-vm-logic/src/context.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/tests/fixtures.rs
  runtime/near-vm-logic/tests/test_context.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: A-transaction-runtime

#4720 Minor fix in nayduck.py documentation
  scripts/nayduck.py
Labels: S-automerge

#4722 scripts: update nayduck.py comment documentation
  scripts/nayduck.py
Labels: S-automerge

#4721 nightly: fix test binary file name in nightly test list
  nightly/expensive.txt
Labels: S-automerge, A-CI, T-nodeX

#4697 make `account_id_to_shard_id` and `num_shards` to take shard layout from the current epoch
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/view_client.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/tests/client/challenges.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#4728 Add a metric for the average amount of Tgas burned in chunks
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#4706 refactor: prepare and dump state inside `params-estimator`
  .buildkite/pipeline.yml
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge, A-params-estimator

#4698 feat: introduce structure for storing `RuntimeConfig`s
  core/primitives/src/runtime/config.rs
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/mod.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/client/runtimes.rs
  integration-tests/tests/client/sandbox.rs
  integration-tests/tests/test_rejoin.rs
  nearcore/res/README.md
  nearcore/res/runtime_configs/29.json
  nearcore/res/runtime_configs/42.json
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  nearcore/tests/economics.rs
  nearcore/tests/load_configs.rs
  nightly/expensive.txt
  pytest/tests/mocknet/load_testing_helper.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/state_sync4.py
  runtime/runtime/src/lib.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/state-viewer/src/main.rs
  test-utils/state-viewer/src/state_dump.rs
  test-utils/store-validator/src/main.rs
  tools/restored-receipts-verifier/src/main.rs
Labels: A-transaction-runtime, S-automerge

#4747 Human-readable output of `state-viewer view_chain` command.
  test-utils/state-viewer/README.md
  test-utils/state-viewer/src/main.rs
Labels: S-automerge

#4755 pytest: fuzz: enable parallelism
  pytest/tests/runtime/fuzz.py
Labels: S-automerge, A-CI, T-nodeX

#4756 pytest: remove unnecessary companion.py script
  pytest/lib/cluster.py
  pytest/tests/companion.py
  scripts/check_pytests.py
Labels: S-automerge

#4757 pytest: cleanup requirements.txt and delete Pipfile
  pytest/Pipfile
  pytest/Pipfile.lock
  pytest/lib/cluster.py
  pytest/requirements.txt
Labels: S-automerge, A-CI, T-nodeX

#4758 pytest: add a bit more detail to README.md
  pytest/README.md
Labels: S-automerge
