Repository near/nearcore, pull requests merged in 2021-02, with the labels that each got.

#3861 refactor(jsonrpc): Structured errors for `GetChunk` ViewClient handler and backward compatible response from JSON RPC
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/tests/rpc_query.rs
  chain/jsonrpc/tests/test_utils/mod.rs
  chain/network/src/types.rs
Labels: automerge

#3888 fix memory_stats on mac
  Cargo.lock
  neard/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
Labels: automerge

#3873 doc: update dev env section
  CONTRIBUTING.md
Labels: automerge

#3891 change peer_manager not to recompute routing multiple times
  chain/network/src/peer_manager.rs
Labels: automerge

#3883 feat (jsonrpc): Add EXPERIMENTAL_receipt jsonrpc method
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/lib.rs
Labels: automerge

#3894 fix: address circular dependency in PROTOCOL_FEATURE_MAPPING
  core/primitives/src/version.rs
Labels: automerge

#3897 refactor (jsonrpc): Remove redundant impls From<..View> for Rpc..Response
  CODEOWNERS
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc/src/lib.rs
Labels: automerge

#3866 ERC-721 CryptoZombies benchmark
  Cargo.lock
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/benches/bench.rs
  runtime/near-evm-runner/benches/benches/cryptozombies.rs
  test-utils/testlib/src/standard_evm_cases.rs
Labels: EVM, benchmark, enhancement, testing

#3885 fix: `cargo t` works in the root of the repo
  runtime/near-vm-runner/benches/bench.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/stats.rs
  runtime/runtime-params-estimator/src/testbed_runners.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
Labels: automerge

#3908 Migrate nearcore buildkite configs to the repo
  .buildkite/pipeline.yml
  .buildkite/release-nightly.yml
  .buildkite/release.yml
Labels: SRE

#3882 rewrite graph struct to be 200 times faster
  chain/network/src/peer_manager.rs
  chain/network/src/recorder.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
Labels: automerge

#3911 feat(cors): fix the cors issue, as it is too restrictive breaking wallet
  chain/jsonrpc/src/lib.rs
Labels: SRE

#3915 fix crash in performance stats while logging
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3913 refactor (indexer) Update Indexer Framework and Indexer example according to changes on actix side
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/lib.rs
  tools/indexer/example/src/main.rs
Labels: automerge

#3912 tool(delay_detector): add configurable min delay
  tools/delay_detector/src/lib.rs
Labels: automerge

#3930 fix(rosetta-rpc): fixed CORS to be permissive by default
  chain/rosetta-rpc/src/lib.rs
Labels: automerge

#3931 Improve print_stats method in near-performance-metrics.
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3845 feat(evm): Add value to the meta tx
  runtime/near-evm-runner/src/meta_parsing.rs
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/src/types.rs
  runtime/near-evm-runner/tests/failures.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
Labels: EVM, enhancement, housekeeping, runtime, testing

#3940 start using near-rust-alloctor-proxy 0.2.7 from crates.io
  Cargo.lock
  neard/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
Labels: automerge

#3919 feat(rpc): add protocol config rpc endpoint
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/types.rs
  chain/client/src/lib.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/lib.rs
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/lib.rs
  neard/Cargo.toml
  neard/src/runtime.rs
  neard/tests/rpc_nodes.rs
Labels: automerge

#3939 chore: Remove near-runtime-fees
  Cargo.lock
  Cargo.toml
  core/chain-configs/Cargo.toml
  runtime/near-evm-runner/Cargo.toml
  runtime/near-evm-runner/benches/benches/mod.rs
  runtime/near-evm-runner/src/builtins.rs
  runtime/near-evm-runner/src/interpreter.rs
  runtime/near-evm-runner/src/near_ext.rs
  runtime/near-evm-runner/src/runner.rs
  runtime/near-evm-runner/tests/standard_ops.rs
  runtime/near-evm-runner/tests/utils/mod.rs
  runtime/near-runtime-fees/Cargo.toml
  runtime/near-runtime-fees/README.md
  runtime/near-runtime-fees/src/lib.rs
  runtime/near-runtime-utils/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/tests/vm_logic_builder.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/benches/bench.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/near-vm-runner/tests/test_rs_contract.rs
  runtime/near-vm-runner/tests/test_ts_contract.rs
  runtime/near-vm-runner/tests/test_utils/mod.rs
  runtime/publish.sh
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/evm_estimator.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime-standalone/contracts/cross-contract-high-level/Cargo.lock
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/fees_utils.rs
Labels: automerge

#3935 docs: update docs links
  chain/jsonrpc/README.md
  chain/rosetta-rpc/README.md
Labels: automerge

#3900 refactor: small delay_detector cleanups
  tools/delay_detector/src/lib.rs
Labels: automerge

#3943 Fix(metrics): count blocks on block production and chunks on chunk production
  chain/client/src/client.rs
  chain/client/src/metrics.rs
Labels: automerge

#3952 fix: chain ID links
  core/chain-configs/src/genesis_config.rs
Labels: EVM, automerge, docs, enhancement, housekeeping

#3959 feat(build): added a seperate build pipeline script for the performan…
  .buildkite/release-perf.yml
  Makefile
  scripts/binary-release.sh
Labels: SRE

#3961 refactor: remove roundabout way to connect to socket
  chain/network/src/peer_manager.rs
Labels: automerge

#3964 Revert "refactor: remove roundabout way to connect to socket"
  chain/network/src/peer_manager.rs
Labels: SRE, automerge

#3966 feat(buildkite): added a trigger for the perf release with performanc…
  .buildkite/pipeline.yml
Labels: SRE, automerge

#3958 fix: paper over #3925
  neard/tests/run_nodes.rs
Labels: automerge

#3965 refactor: remove roundabout way to connect to socket
  chain/network/src/peer_manager.rs
Labels: automerge

#3968 fix(buildkite) release script perf is overriding the normal binary
  scripts/binary-release.sh
Labels: SRE

#3969 feat(jsonrpc): Add warn log to jsronrpc methods where time out can happen
  Cargo.lock
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/lib.rs
Labels: automerge

#3981 feat(jsonrpc): Add timeout log for query method
  chain/jsonrpc/src/lib.rs
Labels: automerge

#3979 Print RocksDb memory usage every minute
  Cargo.lock
  Cargo.toml
  neard/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: automerge

#3987 feat(indexer): Simplify usage of init_configs from indexer perspective
  Cargo.lock
  chain/indexer/CHANGELOG.md
  chain/indexer/Cargo.toml
  chain/indexer/src/lib.rs
  tools/indexer/example/src/configs.rs
  tools/indexer/example/src/main.rs
Labels: automerge

#3990 feat(build): Added CARGO_PROFILE_RELEASE_DEBUG=true to nightly and pe…
  Makefile
Labels: SRE

#3984 fix: minor soundness issue
  core/primitives-core/src/profile.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  runtime/runtime/tests/test_async_calls.rs
Labels: automerge

#3998 refactor: shorten code with as_deref
  chain/indexer/src/lib.rs
Labels: automerge

#3973 refactor: reduce duplication in the vm running code
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer1_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: automerge

#3999 feat(ci): set set RUSTFLAGS='-D warnings for missing steps
  .buildkite/pipeline.yml
  Makefile
  core/primitives/src/block_header.rs
Labels: SRE

#4004 fix(buildkite): fix broken master build
  Makefile
Labels: SRE, automerge

#4003 fix(buildkite): reorder label to be before command in the steps
  .buildkite/pipeline.yml
  .buildkite/release-nightly.yml
  .buildkite/release-perf.yml
  .buildkite/release.yml
Labels: SRE

#4005 fix(build): macos not building due {:?} warning
  utils/near-performance-metrics-macros/src/lib.rs
Labels: SRE, automerge

#4009 refactor: cleanup sanity checks CI step
  .buildkite/pipeline.yml
Labels: automerge

#3997 Don't validate edges multiple times
  chain/network/src/peer_manager.rs
Labels: automerge

#4008 doc: make it possible to discover architectural knowledge
  CONTRIBUTING.md
Labels: automerge

#3974 feat: add `tracing` infrastructure to contract runtime
  Cargo.lock
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner-standalone/src/tracing_timings.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: automerge

#4020 feat(indexer): Add serde derive for indexer structs to be possible to make a JSON from them
  Cargo.lock
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/types.rs
Labels: automerge
