Repository near/nearcore, pull requests merged in 2021-11, with the labels that each got.

#5101 Mocknet loadtest using the skyward smartcontract
  pytest/add_and_delete_state.wasm
  pytest/lib/account.py
  pytest/lib/mocknet.py
  pytest/tests/mocknet/__init__.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#5117 nightly: enable some of the currently-passing expensive tests
  nightly/expensive.txt
Labels: A-testing, S-automerge, T-nodeX

#5118 chain: make debug panic a bit more verbose
  chain/network/src/peer.rs
Labels: A-testing, S-automerge, T-nodeX

#5114 fix: memory leak in wasmer 2
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
Labels: S-automerge

#5108 nit(runtime): drop serde Serialize and Deserialize for VMOutcome
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner-standalone/src/main.rs
Labels: S-automerge

#5076 feat(runtime): debug log host function call except gas
  runtime/near-vm-runner/src/imports.rs
Labels: S-automerge

#5106 chore: change codeowners for network
  CODEOWNERS
Labels: S-automerge

#5124 pytest: state_sync_routed: override ‘tracked_shards’ in all nodes
  pytest/tests/sanity/state_sync_routed.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5120 nightly: disable currently broken tests
  nightly/pytest-sanity.txt
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5107 nit(runtime): reinstall PartialEq on VMOutcome
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#5122 nightly: enable ignored tests::test_chunk_grieving
  nightly/expensive.txt
Labels: A-testing, S-automerge, A-CI, T-nodeX

#4978 fix: when estimating regular_op_cost, don't measure hashing contract
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#5126 refactor: drop dead code
  chain/network/src/routing.rs
Labels: S-automerge

#5125 make view client use a different runtime object to avoid contention
  nearcore/src/lib.rs
Labels: S-automerge

#5151 refactor: simplify
  test-utils/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#5137 Hotfix removing edges from `Graph` inside `RoutingTable`
  chain/network/src/routing.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5158 pytest: pin scipy to 1.7.1
  pytest/requirements.txt
Labels: S-automerge, A-CI

#5154 Fix pytest/sanity/repro_2916.py
  nightly/pytest-sanity.txt
  pytest/tests/sanity/repro_2916.py
Labels: S-automerge

#5141 Refactor PeerManager to group messages under one enum
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/bug_repros.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/consensus.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/query_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/src/lib.rs
  chain/network/src/peer.rs
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/chunks_management.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/client/runtimes.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/runner.rs
Labels: S-automerge

#5140 Refactor network code
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/edge_verifier.rs
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/routing_table_actor.rs
  chain/network/src/test_utils.rs
  chain/network/tests/cache_edges.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
Labels: S-automerge

#5163 Move code for starting new routing table sync to RoutingTableActor
  chain/network/src/peer_manager.rs
  chain/network/src/routing_table_actor.rs
Labels: C-enhancement, A-network, S-automerge, T-core

#5162 Add extra checks to `Graph` and more comments
  chain/network/src/routing.rs
  chain/network/tests/cache_edges.rs
Labels: C-enhancement, A-network, S-automerge, T-core

#5150 test: add more cases for gas overflow behavior
  runtime/near-vm-logic/tests/test_gas_counter.rs
  runtime/near-vm-logic/tests/test_promises.rs
Labels: S-automerge

#5093 ci: don’t print echo commands
  .buildkite/pipeline.yml
Labels: S-automerge, A-CI

#5091 scripts: hide authorisation code when entering it to nayduck.py
  scripts/nayduck.py
Labels: A-testing, S-automerge, T-nodeX

#5172 Prevent crash in stats_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: S-automerge

#5170 nightly: increase timeout for state_sync_massive tests
  nightly/pytest-sanity.txt
  pytest/tests/sanity/state_sync_massive.py
  pytest/tests/sanity/state_sync_massive_validator.py
Labels: A-testing, S-automerge, T-nodeX

#5159 Make RoutingTableActor use Contex instead of SyncContext.
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/network/src/lib.rs
  chain/network/src/peer_manager.rs
  chain/network/src/routing_table_actor.rs
  chain/network/src/test_utils.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
Labels: C-enhancement, A-network, S-automerge, T-core

#5160 Add new features to RoutingTableActor
  chain/network/src/peer_manager.rs
  chain/network/src/routing.rs
  chain/network/src/routing_table_actor.rs
Labels: C-enhancement, A-network, S-automerge, T-core

#5165 Restructure network code
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network/benches/graph.rs
  chain/network/benches/ibf.rs
  chain/network/src/lib.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/codec.rs
  chain/network/src/routing/edge_verifier_actor.rs
  chain/network/src/routing/ibf.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/ibf_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/stats/mod.rs
  chain/network/src/stats/rate_counter.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  chain/network/tests/cache.rs
  chain/network/tests/cache_edges.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
  test-utils/state-viewer/src/main.rs
Labels: C-enhancement, A-network, S-automerge, T-core

#5089 Move routing table exchange to another thread
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  chain/network/tests/cache.rs
  chain/network/tests/cache_edges.rs
  integration-tests/tests/network/runner.rs
  pytest/tests/sanity/routing_table_sync.py
Labels: C-enhancement, A-network, S-automerge, T-core

#5180 chore: change codeowners for chain
  CODEOWNERS
Labels: S-automerge

#5186 Hotfix routing table recalculation
  chain/network/src/routing/routing_table_actor.rs
Labels: S-automerge

#5184 runtime: simplify prepaid gas accounting in view calls
  runtime/near-vm-logic/src/gas_counter.rs
Labels: S-automerge, T-nodeX

#5190 Fix `tests/sanity/routing_table_sync.py`test
  chain/network/src/routing/routing_table_actor.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5187 runtime: prefer reporting GasLimitExceeded
  runtime/near-vm-logic/src/gas_counter.rs
Labels: S-automerge

#5185 Chunk delay monitoring
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/client/src/chunks_delay_tracker.rs
  chain/client/src/client.rs
  chain/client/src/lib.rs
  chain/client/src/metrics.rs
  core/metrics/src/lib.rs
  core/primitives/src/sharding.rs
Labels: S-automerge

#5209 We should remove cloning from Edge
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge_verifier_actor.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5207 Remove unused code
  chain/network/src/routing/routing_table_actor.rs
Labels: S-automerge

#5216 Add comments to utils.rs
  chain/network/src/utils.rs
Labels: S-automerge

#5153 Fix ViewClient::GetExecutionOutcome to work with sharding upgrade
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/src/lib.rs
  core/primitives/src/shard_layout.rs
  core/primitives/src/version.rs
  core/store/src/db.rs
  core/store/src/migrations.rs
  integration-tests/tests/client/sharding_upgrade.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#5219 Refactor code for handling time in near-performance-metrics
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/framed_write.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: S-automerge

#4927 A prototype of socket read limiter
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  utils/near-performance-metrics/src/stats_enabled.rs
  utils/near-rate-limiter/Cargo.toml
  utils/near-rate-limiter/src/framed_read.rs
  utils/near-rate-limiter/src/lib.rs
Labels: S-automerge

#5212 Increase cache for RockDB by column
  core/store/src/db.rs
Labels: S-automerge

#5215 Use bytesize for size constants in db.rs
  core/store/src/db.rs
Labels: S-automerge

#5211 Replace Edge with Arc<Edge> to improve performance
  chain/network/Cargo.toml
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5210 We shouldn't be cloning PeerId so often
  chain/network/benches/graph.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  core/primitives/src/network.rs
Labels: S-automerge

#5192 Add extra logs to investigate issues
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
Labels: S-automerge

#5247 Fix routing::ping_jump test
  integration-tests/tests/network/routing.rs
Labels: S-automerge

#5250 Fix routing_table_sync after changing internal representation
  pytest/tests/sanity/routing_table_sync.py
Labels: S-automerge

#5167 fix: require that wasm target is installed via toolchain file
  .buildkite/pipeline.yml
  Dockerfile
  Dockerfile.nightly
  pytest/tests/stress/hundred_nodes/create_gcloud_image.py
  runtime/near-test-contracts/build.rs
  rust-toolchain
  rust-toolchain.toml
Labels: S-automerge

#5204 refactor: remove default impl of `VMConfig`
  core/primitives-core/src/config.rs
  core/primitives/src/runtime/config.rs
  runtime/near-vm-logic/tests/test_gas_counter.rs
  runtime/near-vm-logic/tests/vm_logic_builder.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: A-transaction-runtime, S-automerge

#5246 Add RUST_BACKTRACE=1 to CI to debug test failures
  .buildkite/pipeline.yml
Labels: S-automerge

#5217 Add comments to `chain/network/src/test_utils.rs`
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
  chain/network/src/test_utils.rs
  integration-tests/src/node/process_node.rs
  integration-tests/tests/nearcore/rpc_error_structs.rs
  integration-tests/tests/nearcore/rpc_nodes.rs
  integration-tests/tests/nearcore/run_nodes.rs
  integration-tests/tests/nearcore/stake_nodes.rs
  integration-tests/tests/nearcore/sync_nodes.rs
  integration-tests/tests/nearcore/sync_state_nodes.rs
  integration-tests/tests/nearcore/track_shards.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
Labels: S-automerge

#5257 Add documentation to .gitignore about '.idea' folder
  .gitignore
Labels: S-automerge

#5261 Migrate `state-viewer` to `clap-derive`
  Cargo.lock
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/README.md
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
  test-utils/state-viewer/src/lib.rs
  test-utils/state-viewer/src/main.rs
Labels: S-automerge

#5229 Dont clone PublicKey
  chain/network/src/routing/routing.rs
  core/primitives/src/network.rs
Labels: S-automerge

#5234 Use saturating_duration_since
  chain/network/src/peer/peer_actor.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/stats/rate_counter.rs
  integration-tests/tests/network/infinite_loop.rs
Labels: S-automerge

#5228 Replace Arc<Edge> with a structure
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/routing.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5260 chore: drop obsolete part of gitignore
  .gitignore
Labels: S-automerge

#5239 Move RateConter to be together with PeerActor
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/rate_counter.rs
  chain/network/src/stats/mod.rs
Labels: S-automerge

#5269 Change api for schedule_printing_performance_stats to take Duration
  neard/src/main.rs
  utils/near-performance-metrics/src/process.rs
Labels: S-automerge

#5240 Stop using lazy macro
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/stats/metrics.rs
  chain/network/src/test_utils.rs
Labels: S-automerge

#5264 Make PublicKey attribute private
  chain/network-primitives/src/types.rs
  chain/network/src/routing/codec.rs
  core/primitives/src/network.rs
Labels: S-automerge

#5272 Ignore flunky tests
  chain/client/src/chunks_delay_tracker.rs
Labels: S-automerge

#5252 Optimize build_hash function by 50%
  chain/network-primitives/src/types.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing.rs
  core/primitives-core/src/hash.rs
  core/primitives/src/network.rs
Labels: S-automerge

#5218 Add comments/refactor rate_counter.rs
  chain/network/src/peer/rate_counter.rs
Labels: S-automerge

#5227 Replace PeerId with Arc<PeerId>
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  core/primitives/src/network.rs
Labels: S-automerge

#5232 Remove deprecated code std::u64::MAX
  chain/chain/src/doomslug.rs
  chain/network/src/peer/peer_actor.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/test_overflows.rs
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/tests/test_miscs.rs
  runtime/near-vm-logic/tests/test_registers.rs
  runtime/near-vm-logic/tests/test_storage_read_write.rs
  runtime/runtime/src/balance_checker.rs
Labels: S-automerge

#5233 Remove dead code from PeerActor
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#5235 Mark some of near-network crates as private
  chain/client/src/client.rs
  chain/network/src/lib.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/routing/mod.rs
Labels: S-automerge

#5256 Fix test_blocks_ahead_of_head by using same time
  chain/client/src/chunks_delay_tracker.rs
Labels: S-automerge

#5253 Make <&PeerId> to Vec<u8> conversions explicit
  chain/network/src/routing/routing_table_actor.rs
  core/primitives/src/network.rs
Labels: S-automerge

#5243 Make peer_actor.rs smaller and therefore easier to read
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tracker.rs
Labels: S-automerge

#5236 Change code owners for network primitives
  CODEOWNERS
Labels: S-automerge

#5242 Reorganize dependencies in Cargo.toml for near-network
  Cargo.lock
  chain/network/Cargo.toml
Labels: S-automerge

#5231 Replace constants with Duration
  chain/client/src/client.rs
Labels: S-automerge, autorebase

#5241 Reorganize imports in near-network
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
Labels: S-automerge

#5262 doc: start code style document
  docs/style.md
Labels: S-automerge

#5287 Refactor PeerManager to join multiple 'impl PeerManagerActor' into one
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#5284 Move out Edge to edge.rs from routing.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/codec.rs
  chain/network/src/routing/edge.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/types.rs
  chain/network/tests/cache_edges.rs
  integration-tests/tests/client/process_blocks.rs
Labels: S-automerge

#5282 Dont set/get global variables in a unit test.
  chain/client/src/chunks_delay_tracker.rs
Labels: S-automerge

#5293 pytest: add timeout to the runtime/fuzz.py test
  pytest/tests/runtime/fuzz.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5299 chore: don't include near-vm-runner-standalone in release artifacts
  Makefile
Labels: S-automerge

#5280 REFACTOR Make stats module in near-network private
  chain/network/src/lib.rs
  integration-tests/tests/network/peer_handshake.rs
Labels: S-automerge

#5277 REFACTOR Remove unused code
  chain/network/src/peer_manager/peer_store.rs
Labels: S-automerge

#5276 REFACTOR Make all attributes in `EdgeInfo` private
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge.rs
  chain/network/src/routing/edge_verifier_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/tests/cache_edges.rs
Labels: S-automerge

#5273 FEATURE: Add extra checks to ping_jump test
  integration-tests/tests/network/routing.rs
Labels: S-automerge

#5278 REFACTOR Make PeerStore package private
  chain/network/src/lib.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_store.rs
  test-utils/state-viewer/src/commands.rs
Labels: S-automerge

#5223 REFACTOR Remove unused method from Edge struct
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge.rs
  chain/network/src/routing/routing_table_actor.rs
Labels: S-automerge

#5300 Make @mm-near code owners of /core /neard /nearcore
  CODEOWNERS
Labels: S-automerge

#5286 REFACTOR Remove direct conversion from PublicKey to PeerId
  chain/client/src/test_utils.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/codec.rs
  chain/network/src/test_utils.rs
  core/primitives/src/network.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
Labels: S-automerge

#5279 REFACTOR Make peer_manager.rs pub(crate) instead of pub
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/mod.rs
Labels: S-automerge

#5289 fix test: Better interface for ChunksDelayTracker testing
  chain/client/src/chunks_delay_tracker.rs
Labels: S-automerge

#5285 REFACTOR Move blacklist_from_iter to near-network-primitives
  Cargo.lock
  chain/network-primitives/src/lib.rs
  chain/network-primitives/src/utils.rs
  chain/network/src/utils.rs
  integration-tests/Cargo.toml
  integration-tests/tests/network/runner.rs
  nearcore/Cargo.toml
  nearcore/src/config.rs
Labels: S-automerge

#5201 store multiple PartialEncodedChunks before processing them instead of only storing one
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/tests/chunks_management.rs
  integration-tests/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#5200 Implement fast gas counting using intrinsics
  Cargo.lock
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#5237 refactor: use near_network_primitives directly
  Cargo.lock
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/bug_repros.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/consensus.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/query_client.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/utils.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/codec.rs
  chain/network/src/routing/routing.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/tests/client/chunks_management.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/client/runtimes.rs
  integration-tests/tests/nearcore/sync_nodes.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/config.rs
Labels: S-automerge

#5265 refactor: Stop using near_metrics::Result<IntCounter>
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/codec.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/stats/metrics.rs
  integration-tests/tests/network/peer_handshake.rs
Labels: S-automerge

#5309 bug(release): fix broken nearcore release after deleting near-vm-runn…
  scripts/mac-release.sh
Labels: S-automerge

#5298 doc: document wrapping style for docs
  docs/style.md
Labels: S-automerge

#5305 refactor: Move utils.rs and make it private
  chain/network/src/lib.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/utils.rs
Labels: S-automerge, S-donotmerge

#5311 refactor: Reorganize imports in near-network
  chain/network/benches/routing_table_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/codec.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
  chain/network/src/types.rs
  rustfmt.toml
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
  utils/near-rate-limiter/src/lib.rs
Labels: S-automerge

#5325 bug: fix `network/routing.rs` tests
  integration-tests/tests/network/runner.rs
Labels: S-automerge

#5314 refactor: Use usize in route_back_cache.rs instead of doing casting to u64
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
Labels: S-automerge

#5313 refactor: Add Default and move constants to route_back_cache.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing.rs
Labels: S-automerge

#5306 refactor: Make chain/network/src/routing pub(crate)
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/benches/ibf.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/ibf_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/types.rs
  chain/network/tests/cache.rs
  chain/network/tests/cache_edges.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
Labels: S-automerge

#5267 refactor: Move EdgeInner methods to Edge
  chain/network/src/routing/edge.rs
Labels: S-automerge

#5324 utils: use internally-mutable validated flag in MaybeValidated
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  core/primitives/src/utils.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/runtimes.rs
Labels: S-automerge, T-nodeX

#5319 chain: avoid cloning block in save_block and save_orphan methods
  chain/chain/src/chain.rs
  chain/client/src/client_actor.rs
  integration-tests/tests/client/process_blocks.rs
Labels: S-automerge, T-nodeX

#5294 pytest: document new NayDuck features
  nightly/README.md
  pytest/README.md
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5341 Remove a superfluous BorshDeserialize derive
  core/primitives/src/network.rs
Labels: S-automerge

#5350 Add help to `tools/indexer/example`
  tools/indexer/example/src/configs.rs
Labels: S-automerge

#5352 feature: Add logging in indexer to stdout
  tools/indexer/example/src/configs.rs
Labels: S-automerge

#5308 refactor: Reduce number of ways you can import types from near-network
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/client/tests/bug_repros.rs
  chain/client/tests/catching_up.rs
  chain/client/tests/chunks_management.rs
  chain/client/tests/consensus.rs
  chain/client/tests/cross_shard_tx.rs
  chain/client/tests/query_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/test_utils.rs
  chain/rosetta-rpc/src/lib.rs
  integration-tests/tests/client/challenges.rs
  integration-tests/tests/client/chunks_management.rs
  integration-tests/tests/client/process_blocks.rs
  integration-tests/tests/nearcore/stake_nodes.rs
  integration-tests/tests/nearcore/sync_nodes.rs
  integration-tests/tests/network/infinite_loop.rs
  integration-tests/tests/network/peer_handshake.rs
  integration-tests/tests/network/runner.rs
  integration-tests/tests/network/stress_network.rs
  nearcore/src/lib.rs
Labels: S-automerge

#5356 Wording in the documentation reflects reality
  runtime/near-vm-runner/FAQ.md
  runtime/near-vm-runner/README.md
  runtime/near-vm-runner/src/vm_kind.rs
Labels: S-automerge

#5297 refactor: remove unused `max_gas_burnt_view` field
  core/primitives-core/src/config.rs
  nearcore/res/mainnet_genesis.json
Labels: S-automerge

#5355 Specify explicitly the WASM features we want to enable for WASM parsing/validation
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#5332 feat: nightly protocol feature to lower regular op cost some more
  chain/chain/tests/simple_chain.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  nearcore/res/runtime_configs/124.json
  neard/Cargo.toml
Labels: S-automerge

#5320 buildkite: enable test_features when running tests on CI
  .buildkite/pipeline.yml
Labels: A-testing, S-automerge, A-CI, T-nodeX

#5334 refactor: Move EdgeVerifierHelper from routing.rs to edge_verifier_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge_verifier_actor.rs
  chain/network/src/routing/routing.rs
Labels: S-automerge

#5323 refactor: stop using lazy_static inside chain/json*
  Cargo.lock
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/metrics.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/changes.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/light_client.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
Labels: S-automerge

#5364 chore: Reduced @frol's code ownership
  CODEOWNERS
Labels: S-automerge

#5349 refactor: simplify get_gc_stop_height to not use macro
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#5338 refactor: Move codes.rs in the same module as peer_actor.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/mod.rs
Labels: S-automerge

#5335 refactor: Move EdgeType to edges.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  t_shard_layout_upgrade_cross_contract_call
Labels: S-automerge

#5343 Adds process_block_test to be used in tests
  chain/chain/src/lib.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/mod.rs
  chain/chain/src/tests/simple_chain.rs
Labels: S-automerge

#5292 refactor: remove default impls inside VMConfig
  core/primitives-core/src/config.rs
  core/primitives/src/runtime/config_store.rs
  nearcore/res/runtime_configs/123.json
  nearcore/res/runtime_configs/124.json
  nearcore/res/runtime_configs/29.json
  nearcore/res/runtime_configs/29_testnet.json
  nearcore/res/runtime_configs/42.json
  nearcore/res/runtime_configs/48.json
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/tests/fixtures.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/state_viewer/mod.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#5359 Adjust the documentation for `External` methods
  runtime/near-vm-logic/src/dependencies.rs
Labels: S-automerge

#5365 feat: stabilize LowerRegularOpCost2
  CHANGELOG.md
  chain/chain/src/tests/simple_chain.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  nearcore/res/genesis_config.json
  nearcore/res/runtime_configs/49.json
  neard/Cargo.toml
Labels: S-automerge

#5360 Make non-validators not wait for forwarded chunks
  chain/chain/src/chain.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  integration-tests/tests/client/process_blocks.rs
Labels: S-automerge

#5384 Bump Wasmer2 VM configuration version
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#5321 refactor: Remove usage of lazy_static! not neard files
  Cargo.lock
  integration-tests/src/test_helpers.rs
  neard/Cargo.toml
  neard/src/main.rs
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/src/cli.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge

#5378 refactor: Remove slab from near-rate-limiter dependencies
  Cargo.lock
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#5393 refactor: Rename OldDuration to chrono::Duration
  chain/client/src/client_actor.rs
Labels: S-automerge

#5376 Remove unused dependencies for near-network
  Cargo.lock
  chain/network/Cargo.toml
Labels: S-automerge

#5390 refactor: Add debug logs to runner.rs
  integration-tests/tests/network/runner.rs
Labels: S-automerge

#5361 feat: stabilize limiting functions number in a contract
  CHANGELOG.md
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/res/runtime_configs/123.json
  nearcore/res/runtime_configs/49.json
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
Labels: S-automerge

#5385 bug: Fix for `fuzz` not compiling `core/primitives/src/network.rs`
  core/primitives/src/network.rs
Labels: S-automerge

#5363 fix(near-crypto): get near-crypto compilable on Windows
  core/crypto/src/key_file.rs
Labels: S-automerge

#5399 bug: ignore `routing::archival_node()` test
  integration-tests/tests/network/routing.rs
Labels: P-high, S-automerge

#5283 refactor: Split `test_utils.rs` to avoid having code with `test_features` and without in one file.
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/network/src/test_utils.rs
Labels: S-automerge

#5413 chore: mark near-rate-limiter unpublishable
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#5414 fix: near-rate-limter build
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#5403 bug: fix sync errors in `Clion`
  core/crypto/src/signature.rs
Labels: P-low, S-automerge

#5382 refactor: add a trait to abstract over a VM runtime
  docs/architecture.md
  integration-tests/tests/client/process_blocks.rs
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
  runtime/near-vm-runner/src/vm_kind.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/testbed_runners.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#5391 re: Update `README.md`
  test-utils/runtime-tester/fuzz/README.md
Labels: P-low, S-automerge

#5412 re: Fix clippy warnings
  core/account-id/src/lib.rs
  utils/near-performance-metrics-macros/src/lib.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: S-automerge

#5402 bug: Fix errors inside comments breaking `Clion` error check
  core/metrics/src/lib.rs
Labels: P-low, S-automerge

#5416 Remove unused dependencies from core
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
Labels: P-low, S-automerge
