Repository near/nearcore, pull requests merged in 2021-06, with the labels that each got.

#4339 fix(neard): fixed failed CI tests due to features mismatches
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  docs/architecture.md
  integration-tests/Cargo.toml
  integration-tests/tests/add.wasm
  integration-tests/tests/hello.wasm
  integration-tests/tests/singlepass_crash.wasm
  integration-tests/tests/test_cases_runtime.rs
  integration-tests/tests/test_cases_testnet_rpc.rs
  integration-tests/tests/test_catchup.rs
  integration-tests/tests/test_errors.rs
  integration-tests/tests/test_overflows.rs
  integration-tests/tests/test_rejoin.rs
  integration-tests/tests/test_simple.rs
  integration-tests/tests/test_tps_regression.rs
  integration-tests/tests/tidy.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  pytest/tests/sanity/state_migration.py
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  runtime/runtime-params-estimator/emu-cost/ci.sh
  scripts/state/update_res.py
Labels: automerge

#4360 Set block protocol version in a separate function in process_blocks
  chain/client/Cargo.toml
  chain/client/tests/process_blocks.rs
Labels: automerge, housekeeping

#4363 Revert "Set block protocol version in a separate function in process_…
  chain/client/Cargo.toml
  chain/client/tests/process_blocks.rs
Labels: SRE, automerge, revert

#4365 Increase JsonRpcClient payload receivable size to 100mb
  chain/jsonrpc/client/src/lib.rs
Labels: automerge

#4356 refactor(neard): switch to derive clap
  .buildkite/pipeline.yml
  Cargo.lock
  chain/chain/src/chain.rs
  chain/indexer/src/lib.rs
  genesis-tools/README.md
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/main.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/restaked.py
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/emu-cost/ci.sh
  runtime/runtime-params-estimator/emu-cost/io_cost.sh
  runtime/runtime-params-estimator/estimate.sh
  scripts/nodelib.py
  scripts/run_docker.sh
  scripts/start_localnet.py
  scripts/start_unittest.py
Labels: automerge

#4368 Cover cargo build failures in buildkite/nearcore
  .buildkite/pipeline.yml
Labels: automerge

#4366 Set block protocol version in process_blocks, fixed version
  chain/client/tests/process_blocks.rs
Labels: automerge

#4313 doc: document TestEnv
  chain/client/src/test_utils.rs
Labels: automerge

#4334 doc: update architecture.md
  CODEOWNERS
  docs/architecture.md
Labels: automerge

#4376 feat(primitive): prepare for adding profile data to execution outcome
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/client/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  chain/telemetry/Cargo.toml
  core/primitives/src/transaction.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  core/store/src/migrations.rs
  nearcore/src/lib.rs
  runtime/runtime/src/lib.rs
Labels: automerge

#4389 Introduce `TrieRefcountChange` for better readability
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
Labels: automerge, housekeeping

#4383 doc: add vm-runner to architecture.md
  docs/architecture.md
Labels: automerge

#4397 Add test to test infinite loop contracts
  nightly/complete_nayduck_set.txt
  pytest/tests/contracts/infinite_loops.py
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
Labels: automerge

#4407 Update codeowners
  CODEOWNERS
Labels: automerge

#4388 fix: remove no longer relevant EVM costs computations
  chain/client/src/client_actor.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/cases.rs
  runtime/runtime-params-estimator/src/evm_estimator.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
  test-utils/testlib/src/node/process_node.rs
  test-utils/testlib/src/node/thread_node.rs
Labels: automerge

#4382 fix(chain): change max gas price
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/client/tests/process_blocks.rs
Labels: automerge

#4415 pytest: introduce helper `load_test_contract` function
  pytest/lib/utils.py
  pytest/tests/contracts/deploy_call_smart_contract.py
  pytest/tests/contracts/gibberish.py
  pytest/tests/contracts/infinite_loops.py
  pytest/tests/mocknet/sanity.py
  pytest/tests/sandbox/patch_state.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/concurrent_function_calls.py
  pytest/tests/sanity/db_migration.py
  pytest/tests/sanity/upgradable.py
Labels: automerge

#4344 Compile contracts on writing them to state
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/Cargo.toml
  chain/client/tests/process_blocks.rs
  core/primitives/src/state_record.rs
  core/store/src/lib.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
Labels: A-runtime

#4418 pytest: migrate away from using WASM blobs
  integration-tests/tests/add.wasm
  integration-tests/tests/singlepass_crash.wasm
  pytest/testdata/hello.wasm
  pytest/tests/sanity/rpc_light_client_execution_outcome_proof.py
  pytest/tests/sanity/rpc_state_changes.py
  pytest/tests/sanity/rpc_tx_status.py
Labels: S-automerge
