Repository near/nearcore, pull requests merged in 2022-11, with the labels that each got.

#7929 feat(o11y): Tracing of work caused by network messages received by PeerActor
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7951 doc: move serialization docs over from confluence
  docs/SUMMARY.md
  docs/architecture/how/serialization.md
Labels: S-automerge

#7944 store: read BlockHeader from hot db when accessing through ColdDB
  core/store/src/columns.rs
  core/store/src/db/colddb.rs
  core/store/src/lib.rs
Labels: S-automerge

#7980 feat: estimate `ed25519` base and bytes separately
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#7975 moved is_inbound_allowed to NetworkState
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7974 moved rayon utils to concurrency module
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/concurrency/mod.rs
  chain/network/src/concurrency/rayon.rs
  chain/network/src/concurrency/tests.rs
Labels: S-automerge

#7959 docs: move proof docs over from confluence
  docs/SUMMARY.md
  docs/architecture/how/proofs.md
Labels: S-automerge

#7969 refactor: simplify get_epoch_sync_data_hash
  chain/chain/src/types.rs
Labels: S-automerge

#7967 refactor: move parts API to the epoch manager
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/epoch-manager/src/adapter.rs
  chain/epoch-manager/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7954 store: disable refcount merge operator when opening cold RocksDB
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  core/store/src/opener.rs
Labels: S-automerge

#7979 feat: design for flat storage creation
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/lib.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/store/src/flat_state.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7984 fix: use new database version for flat state
  core/store/src/metadata.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#7982 docs: clarify that `Db::Receipts` doesn't store _all_ receipts
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#7977 moved fixing local edges to a background task.
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/broadcast/mod.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/store/schema/tests.rs
  chain/network/src/time.rs
Labels: S-automerge

#7993 chore: upgrade rust-version to 1.65.0
  Cargo.toml
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/contract-for-fuzzing-rs/Cargo.toml
  runtime/near-test-contracts/estimator-contract/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#7985 debug: add assertions to flat state get_ref
  core/store/src/trie/mod.rs
Labels: S-automerge

#7998 refactor: simplify `split_method_names` in vm Logic
  runtime/near-vm-logic/src/utils.rs
Labels: S-automerge

#7987 feat: trie storage for parallel reads
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
Labels: S-automerge

#7872 Add support for dynamic config and use it for expected shutdown
  Cargo.lock
  Cargo.toml
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/indexer/Cargo.toml
  core/dyn-configs/Cargo.toml
  core/dyn-configs/LICENSE-APACHE
  core/dyn-configs/LICENSE-MIT
  core/dyn-configs/README.md
  core/dyn-configs/src/lib.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/log_config_watcher.rs
  neard/src/main.rs
  neard/src/watchers/dyn_config_watcher.rs
  neard/src/watchers/log_config_watcher.rs
  neard/src/watchers/mod.rs
  tools/mirror/Cargo.toml
Labels: S-automerge, T-node

#7973 Fixed broadcasting of AnnounceAccounts
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/routing/routing_table_view.rs
Labels: S-automerge

#8000 crypto: remove unused impl
  core/crypto/src/traits.rs
Labels: S-automerge

#7997 chore: no rust-version for unpublishable contracts
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/client/Cargo.toml
  chain/epoch-manager/Cargo.toml
  chain/indexer/Cargo.toml
  chain/jsonrpc-adversarial-primitives/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/client/Cargo.toml
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/network/Cargo.toml
  chain/pool/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  chain/telemetry/Cargo.toml
  core/account-id/fuzz/Cargo.toml
  core/store/Cargo.toml
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/keypair-generator/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/contract-for-fuzzing-rs/Cargo.toml
  runtime/near-test-contracts/estimator-contract/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/fuzz/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/estimator-warehouse/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/actix-test-utils/Cargo.toml
  test-utils/logger/Cargo.toml
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/fuzz/Cargo.toml
  test-utils/store-validator/Cargo.toml
  test-utils/testlib/Cargo.toml
  tools/amend-genesis/Cargo.toml
  tools/chainsync-loadtest/Cargo.toml
  tools/delay-detector/Cargo.toml
  tools/indexer/example/Cargo.toml
  tools/mirror/Cargo.toml
  tools/mock-node/Cargo.toml
  tools/restaked/Cargo.toml
  tools/state-viewer/Cargo.toml
  tools/storage-usage-delta-calculator/Cargo.toml
  tools/themis/Cargo.toml
  tools/themis/src/rules.rs
  utils/mainnet-res/Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-performance-metrics-macros/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-stable-hasher/Cargo.toml
Labels: S-automerge

#7994 refactor: move miscelaneous epoch APIs to epoch manager adapter
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7988 Move sync into check_triggers
  chain/client/src/client_actor.rs
Labels: S-automerge

#7970 fix: mark slow tests as such
  integration-tests/src/tests/client/chunks_management.rs
  nightly/expensive.txt
Labels: S-automerge

#8003 feat: test for flat storage background creation
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/client/mod.rs
Labels: S-automerge

#8009 replaced ResponseUpdateNonce with SyncRoutingTable
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
Labels: S-automerge

#8005 refactor: simplify synchronization for next hops table
  chain/network/src/routing/graph_with_cache.rs
Labels: S-automerge

#8013 crypto: Rust has &[T] → [T; N] conversion for arbitrary N; use it
  core/crypto/src/signature.rs
Labels: S-automerge

#8010 docs: estimator metrics
  docs/architecture/gas/estimator.md
Labels: S-automerge

#8016 nit(amend-genesis): print out path names in errors
  tools/amend-genesis/src/cli.rs
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#7887 Add `maintenance_window` RPC
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/client-primitives/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/lib.rs
  chain/client/src/tests/maintenance_windows.rs
  chain/client/src/tests/mod.rs
  chain/client/src/view_client.rs
  chain/epoch-manager/src/adapter.rs
  chain/jsonrpc-primitives/src/types/maintenance.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc/src/api/maintenance.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/lib.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/views.rs
Labels: S-automerge, T-node

#8014 Added documentation about cross shard transactions
  docs/SUMMARY.md
  docs/architecture/how/cross-shard.md
Labels: S-automerge

#8002 Refactored routing table edges verification.
  chain/network/src/config.rs
  chain/network/src/network_protocol/edge.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/mod.rs
  chain/network/src/store/schema/tests.rs
Labels: S-automerge

#8017 fix: block hash in trie for storage usage test
  chain/chain/src/types.rs
  integration-tests/src/tests/client/features/fix_storage_usage.rs
Labels: S-automerge

#8021 docs: formatting changes:
  docs/architecture/how/cross-shard.md
Labels: S-automerge

#8020 Removed the PeerActor -> PeerManagerActor dependency.
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
Labels: S-automerge

#8015 doc: some intro material for new Rust programmers!
  docs/SUMMARY.md
  docs/practices/rust.md
Labels: S-automerge

#8025 chore: remove backtrace dependency
  Cargo.lock
  Cargo.toml
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
Labels: S-automerge

#8024 removed unused PeerChainInfo
  chain/network/src/network_protocol/peer.rs
  chain/network/src/types.rs
Labels: S-automerge

#8028 fixed flaky accounts_data::broadcast
  chain/network/src/peer_manager/tests/accounts_data.rs
Labels: S-automerge

#8027 debug: observe single measurements in estimator
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge, A-params-estimator

#8031 feat: set ed25519 verification gas parameters
  core/primitives/res/runtime_configs/parameters.txt
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#8026 network: remove PeerManagerActor::config field
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#8034 nit(network): make ConnectError::IO transparent
  chain/network/src/raw/connection.rs
Labels: S-automerge

#8019 feat: switch to fetching state step on flat storage creation
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/flat_storage.rs
Labels: S-automerge

#8041 crypto: reduce boilerplate code by using derives
  core/crypto/src/signature.rs
  core/crypto/src/traits.rs
Labels: S-automerge

#7989 store: read EpochInfo from hot database in ColdDB
  core/store/src/db/colddb.rs
Labels: S-automerge, A-cold-storage

#8030 refactor: move some leftover APIs to EpochManagerAdapter
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#8037 reimplemented tokio::time::Interval for FakeClock
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/time.rs
Labels: S-automerge

#8043 Use relative paths in debug pages
  chain/jsonrpc/res/chain_n_chunk_info.html
  chain/jsonrpc/res/debug.html
  chain/jsonrpc/res/epoch_info.html
  chain/jsonrpc/res/last_blocks.js
  chain/jsonrpc/res/network_info.html
  chain/jsonrpc/res/sync.html
  chain/jsonrpc/res/validator.html
Labels: S-automerge

#8023 Ping tool exports prometheus metrics
  Cargo.lock
  tools/ping/Cargo.toml
  tools/ping/src/cli.rs
  tools/ping/src/lib.rs
  tools/ping/src/metrics.rs
Labels: S-automerge

#8046 doc: better priority in the mastery section
  docs/practices/rust.md
Labels: S-automerge

#8044 refactor: 1:1 mapping for `ActionCosts` to fees
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  core/primitives/src/views.rs
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#8048 docs: runtime config store
  docs/architecture/gas/parameter_definition.md
Labels: S-automerge

#8054 doc: add extended quick start
  docs/README.md
  docs/SUMMARY.md
  docs/practices/workflows/README.md
  docs/practices/workflows/deploy_a_contract.md
  docs/practices/workflows/run_a_node.md
Labels: S-automerge

#8035 feat: add more scenarios to FlatStorageState unit tests
  chain/chain/src/store.rs
  core/store/src/flat_state.rs
Labels: S-automerge

#8040 Add metric for dynamic config change
  Cargo.lock
  core/dyn-configs/Cargo.toml
  core/dyn-configs/src/lib.rs
Labels: S-automerge

#8047 Metric for the duration of creating state parts
  chain/chain/src/metrics.rs
  chain/chain/src/state_request_tracker.rs
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#8042 log an error if wasmer compile fails after preparation
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#8068 doc: fix wording in styleguide
  docs/practices/style.md
Labels: S-automerge

#8061 Add hash to PeerChainInfo
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc/res/network_info.html
  chain/jsonrpc/src/lib.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tracker.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/process_blocks.rs
  nightly/pytest-adversarial.txt
  pytest/tests/adversarial/wrong_sync_info.py
  tools/chainsync-loadtest/src/fetch_chain.rs
  tools/mock-node/src/lib.rs
Labels: S-automerge

#8066 crypto: move base58 decoding into a common helper function
  core/crypto/src/signature.rs
Labels: S-automerge

#8077 fix: reimplemented flaky test
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#8079 deflaked fix_local_edges test
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/tests/nonce.rs
Labels: S-automerge

#8080 Fix typo
  docs/practices/workflows/README.md
Labels: S-automerge

#8078 docs: document the process for tracking security sensitive issues
  docs/SUMMARY.md
  docs/practices/security_vulnerabilities.md
Labels: S-automerge

#8071 do not enter sync mode if peer is at an invalid hash
  chain/chain-primitives/src/error.rs
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/client/src/client_actor.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#8063 feat: honor NO_COLOR in tests
  core/o11y/src/lib.rs
  core/o11y/src/testonly.rs
Labels: S-automerge

#8049 set file descriptor limit in neard to accomodate up to 1000 connections
  Cargo.lock
  neard/Cargo.toml
  neard/src/main.rs
Labels: S-automerge

#8067 feat: rename `value_return` in gas profile
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  core/primitives/src/views.rs
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#8086 docs: Paragraphize the aside callout
  docs/practices/security_vulnerabilities.md
Labels: S-automerge

#8089 store: test RawTrieNode encoding produces expected result
  core/store/src/trie/mod.rs
Labels: S-automerge

#7986 feat: increase column block cache for flat state
  core/store/src/config.rs
Labels: S-automerge

#8050 Measure the number of hops of routed messages
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#8090 mark block as invalid in preprocess_block
  chain/chain/src/chain.rs
Labels: S-automerge

#8091 make debug page show whether the peer is at an invalid or valid block
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/jsonrpc/res/network_info.html
  chain/network/src/types.rs
  core/primitives/src/views.rs
Labels: S-automerge

#8088 feat: configure num threads for flat storage creation
  CHANGELOG.md
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/client/src/info.rs
  chain/client/src/test_utils.rs
  core/chain-configs/src/client_config.rs
  core/store/src/config.rs
  integration-tests/src/genesis_helpers.rs
  nearcore/src/config.rs
  tools/speedy_sync/src/main.rs
Labels: S-automerge

#8087 Introduce ‘stdx’ crate with split array polyfills
  Cargo.lock
  Cargo.toml
  core/crypto/Cargo.toml
  core/crypto/src/util.rs
  core/store/Cargo.toml
  core/store/src/db/refcount.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/array_utils.rs
  utils/stdx/Cargo.toml
  utils/stdx/LICENSE-APACHE
  utils/stdx/LICENSE-MIT
  utils/stdx/src/lib.rs
Labels: S-automerge

#8096 store: detect spurious bytes at the end of RawTrieNode encoding
  core/store/src/trie/mod.rs
  docs/architecture/how/serialization.md
Labels: S-automerge

#8085 revamped TIER1 discovery protocol
  chain/client/src/client.rs
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/account_key.rs
  chain/network/src/network_protocol/proto_conv/crypto.rs
  chain/network/src/network_protocol/proto_conv/handshake.rs
  chain/network/src/network_protocol/proto_conv/net.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/types.rs
  nearcore/src/config.rs
Labels: S-automerge

#8094 docs: formatting and sentence structure
  docs/architecture/README.md
  docs/architecture/how/README.md
  docs/architecture/how/cross-shard.md
  docs/architecture/how/epoch.md
  docs/architecture/how/gc.md
  docs/architecture/how/serialization.md
  docs/architecture/how/sync.md
  docs/architecture/how/tx_receipts.md
  docs/architecture/how/tx_routing.md
Labels: S-automerge

#8103 doc: move estimator guide to workflows
  docs/SUMMARY.md
  docs/architecture/gas/estimator.md
  docs/practices/workflows/gas_estimations.md
Labels: S-automerge

#8108 made imports of "tracing" and "actix" across near-network uniform
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#8076 Remove routing actor.
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/broadcast/mod.rs
  chain/network/src/concurrency/mod.rs
  chain/network/src/concurrency/runtime.rs
  chain/network/src/config.rs
  chain/network/src/network_protocol/edge.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/bfs.rs
  chain/network/src/routing/graph/mod.rs
  chain/network/src/routing/graph/tests.rs
  chain/network/src/routing/graph_with_cache.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_view/mod.rs
  chain/network/src/routing/routing_table_view/tests.rs
  chain/network/src/routing/tests/cache_edges.rs
  chain/network/src/routing/tests/mod.rs
  chain/network/src/routing/tests/routing_table_view.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/testonly/stream.rs
Labels: S-automerge

#8104 fix(mirror): fix bug in handling of access keys that have been deleted
  pytest/tools/mirror/test.py
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/lib.rs
Labels: S-automerge

#8059 Add update_cold_head
  core/store/src/cold_storage.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  integration-tests/src/tests/client/cold_storage.rs
Labels: A-cold-storage

#8100 refactor: cleaning up RuntimeConfig
  Cargo.lock
  chain/indexer/src/streamer/utils.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/utils.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives-core/src/runtime/fees.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config.rs
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/mod.rs
  core/primitives/src/runtime/parameter_table.rs
  core/primitives/src/views.rs
  integration-tests/src/node/runtime_node.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/runtime/deployment.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  integration-tests/src/tests/test_errors.rs
  nearcore/tests/economics.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/genesis.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
  test-utils/testlib/src/fees_utils.rs
Labels: S-automerge

#8112 Added an early exit to add_edges.
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/routing/graph/mod.rs
Labels: S-automerge

#8111 feat(mirror): don't start a full node for the source chain by default
  Cargo.lock
  pytest/tools/mirror/mirror_utils.py
  pytest/tools/mirror/offline_test.py
  pytest/tools/mirror/online_test.py
  tools/mirror/Cargo.toml
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/cli.rs
  tools/mirror/src/lib.rs
  tools/mirror/src/offline.rs
  tools/mirror/src/online.rs
Labels: S-automerge

#8118 Separated Tier1Handshake message from Tier2Handshake message
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/raw/connection.rs
Labels: S-automerge

#8102 Easy epoch selection for dumping state parts and log the number of nodes visited
  core/store/src/trie/state_parts.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/dump_state_parts.rs
  tools/state-viewer/src/epoch_info.rs
Labels: S-automerge

#8073 Migrate RoutingTable tests to network crate
  chain/network/src/peer_manager/tests/routing.rs
  integration-tests/src/tests/network/routing.rs
Labels: S-automerge

#8110 Migrate ping and ttl tests to network crate
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/routing.rs
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/multiset.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#8120 remove unused spawn_with_nonce
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#8116 fix: revert accidental protocol change in #8044
  Cargo.lock
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
Labels: S-automerge

#8121 fixed edge updates
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
Labels: S-automerge

#8126 Made type of ArcMutex::update more strict.
  chain/network/src/accounts_data/mod.rs
  chain/network/src/concurrency/arc_mutex.rs
  chain/network/src/concurrency/tests.rs
  chain/network/src/peer_manager/connection/mod.rs
Labels: S-automerge

#8129 fix(mirror): initialize global logging
  tools/mirror/src/cli.rs
Labels: S-automerge

#8109 Migrate boot node and blacklisting tests to network crate
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/tests/routing.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#8097 fuzzing: simplify Function::arbitrary
  Cargo.lock
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/src/fuzzing.rs
Labels: S-automerge

#8106 Added AccountKey to Handshake message.
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/account_key.rs
  chain/network/src/network_protocol/proto_conv/handshake.rs
  chain/network/src/network_protocol/proto_conv/util.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/private_actix.rs
  chain/network/src/raw/connection.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#8130 feat(mirror): send extra AddKey txs for function calls that add keys
  Cargo.lock
  pytest/tools/mirror/contract/Cargo.lock
  pytest/tools/mirror/contract/Cargo.toml
  pytest/tools/mirror/contract/src/lib.rs
  pytest/tools/mirror/mirror_utils.py
  pytest/tools/mirror/online_test.py
  tools/mirror/Cargo.toml
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/lib.rs
  tools/mirror/src/offline.rs
  tools/mirror/src/online.rs
Labels: S-automerge

#8134 Adding documentation to State Sync code
  chain/client/src/sync/state.rs
Labels: S-automerge

#8127 fix(migrations): make sure to call finish() on batched updates
  core/store/src/migrations.rs
Labels: S-automerge

#8135 [StateSync] Moving StateResponse handling logic into state.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/state.rs
Labels: S-automerge
