Repository near/nearcore, pull requests merged in 2022-01, with the labels that each got.

#5837 refactor: make sure there's only one code path an InconsistentStateError can take through runtime
  core/primitives/src/errors.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/ext.rs
Labels: S-automerge

#5881 Add a text describing runtimes and their requirements
  runtime/near-vm-runner/RUNTIMES.md
Labels: S-automerge

#5990 chore: add Longarithm to test-contract owners
  CODEOWNERS
Labels: S-automerge

#5986 feat: tool for measuring store stats
  Cargo.lock
  Cargo.toml
  tools/rocksdb-stats/Cargo.toml
  tools/rocksdb-stats/README.md
  tools/rocksdb-stats/src/main.rs
Labels: S-automerge

#5856 fix: do not cache io errors
  genesis-tools/genesis-populate/src/main.rs
  integration-tests/src/tests/client/process_blocks.rs
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/tiny-contract-rs/Cargo.lock
  runtime/near-test-contracts/tiny-contract-rs/Cargo.toml
  runtime/near-test-contracts/tiny-contract-rs/src/lib.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  utils/near-cache/src/lib.rs
Labels: S-automerge

#5997 Manually set the target for wasmer Singlepass
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#5941 chain: refactor `shard_assignments` module testing code
  chain/epoch_manager/src/shard_assignment.rs
Labels: P-high, S-automerge

#5554 feat: Use `AcqRel` instead of `SeqCst` in `ThrottleController`
  utils/near-rate-limiter/src/framed_read.rs
Labels: C-enhancement, C-housekeeping, A-chain, P-low, A-network, S-automerge

#5940 re: `near-network` Move test types to `test_utils.rs`
  chain/client/src/test_utils.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, T-core

#5867 refactor(indexer): avoid fetching protocol config multiple times
  chain/indexer/src/streamer/mod.rs
Labels: S-automerge

#6014 chain: simplify `.mut_store().store_update().store().store_update()`
  chain/chain/src/store.rs
Labels: S-automerge

#6013 fix(chain): fix `test_clear_old_data_too_many_heights` test
  chain/chain/src/store.rs
Labels: P-high, S-automerge

#5778 chore: rename neard testnet subcommand to localnet
  neard/src/cli.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/upgradable.py
Labels: S-automerge

#5929 Chunks and blocks statistics: produced/expected by validators
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
  core/metrics/src/lib.rs
Labels: S-automerge

#6005 refactor: move rocksdb stats to state viewer
  Cargo.lock
  Cargo.toml
  test-utils/state-viewer/Cargo.toml
  test-utils/state-viewer/README.md
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/lib.rs
  test-utils/state-viewer/src/main.rs
  test-utils/state-viewer/src/rocksdb_stats.rs
  tools/rocksdb-stats/Cargo.toml
  tools/rocksdb-stats/README.md
Labels: S-automerge

#6023 feat: Print cargo test output only on error.
  test-utils/logger/src/lib.rs
Labels: C-enhancement, P-low, S-automerge

#5746 doc: Fix broken link to validator's instructions
  README.md
Labels: S-automerge

#6019 re: Cleanup imports in `testlib`
  Cargo.lock
  test-utils/testlib/Cargo.toml
Labels: C-housekeeping, P-low, S-automerge

#6012 nightly: remove duplicate expensive tests
  nightly/expensive.txt
Labels: S-automerge

#6022 nighthly: disable broken `routing_table_sync.py` test
  nightly/pytest-sanity.txt
Labels: A-testing, S-automerge, A-CI

#5871 feat: `near-chain` Replace `cached` with `lru`
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/store.rs
  core/store/Cargo.toml
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
Labels: C-enhancement, P-low, S-automerge

#6002 chain: document that `assign_shards` expects producers to be sorted
  chain/epoch_manager/src/shard_assignment.rs
Labels: S-automerge

#5887 chain: rosetta: extract transaction-related code to new module
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/transactions.rs
Labels: S-automerge, T-nodeX

#6034 test: run fuzzer with VM we actually use
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
Labels: S-automerge

#6031 integration-tests: fix some expensive tests marking
  integration-tests/Cargo.toml
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/test_catchup.rs
  integration-tests/src/tests/test_tps_regression.rs
  nightly/expensive.txt
Labels: A-testing, S-automerge, A-CI

#5960 refactor: use the lower level wasmer APIs
  Cargo.lock
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#5987 refactor: Runtime structure now contains VMConfig
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#6041 Revert the changes to use low level wasmer2 implementation
  Cargo.lock
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#5704 scripts: replace `check_formatting.sh` with `formatting` script
  .buildkite/pipeline.yml
  scripts/check_formatting.sh
  scripts/formatting
Labels: S-automerge

#6006 feat: Reintroduce single_thread_rocksdb
  core/store/Cargo.toml
Labels: S-automerge

#6039 nodelib: better support ‘--chain-id’ flag
  scripts/nodelib.py
Labels: S-automerge

#6048 state-viewer: Get a receipt from the DB
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
Labels: S-automerge

#6049 state-viewer: Get chunks and partial chunks from the DB
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
Labels: S-automerge

#6036 cli: better respect RUST_LOG
  neard/src/cli.rs
Labels: S-automerge

#6038 neard: state explicitly that unsafe_reset_all deletes directory
  neard/src/cli.rs
Labels: S-automerge

#5982 pytest: fix str formatting of BlockId
  pytest/lib/cluster.py
Labels: S-automerge

#6047 Mocknet: Robust error handling
  pytest/lib/account.py
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#5981 Use make targets when building docker images
  Dockerfile
  Makefile
Labels: S-automerge

#6043 re: restore the low level wasmer2 refactor
  Cargo.lock
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#6052 Add a script for requesting block and chunk info through rpc
  debug_scripts/request_chain_info.py
Labels: S-automerge

#5970 Makefile: add `neard-sandbox` executable name
  Makefile
  pytest/tests/sandbox/patch_state.py
Labels: S-automerge

#6004 Add metrics related to the epoch, sync state and node version
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
  chain/epoch_manager/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6017 re: Remove unused `nix` dependency from `near-performance-metrics`
  Cargo.lock
  utils/near-performance-metrics/Cargo.toml
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6032 Use `cfg_attr` to ignore expensive tests
  chain/chain/src/store.rs
  chain/chain/src/tests/doomslug.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/tests/mod.rs
  chain/chunks/src/lib.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/consensus.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/mod.rs
  chain/client/src/tests/query_client.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/standard_cases/rpc.rs
  integration-tests/src/tests/test_catchup.rs
  integration-tests/src/tests/test_simple.rs
  integration-tests/src/tests/test_tps_regression.rs
  nightly/README.md
  scripts/check_nightly.py
Labels: A-testing, S-automerge, A-CI, T-nodeX

#6060 docs: document testing recommendations
  docs/architecture.md
Labels: A-testing, S-automerge, A-CI

#5956 re: Fix last two clippy warnings in `near-network`
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/graph.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/tests/cache_edges.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6051 fix: use pwasm-utils 0.18 for more correct stack accounting
  Cargo.lock
  core/primitives-core/src/config.rs
  core/primitives/res/runtime_configs/50.json
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/version.rs
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#5613 Add `README.md` to `near-network-primitives`
  chain/network-primitives/README.md
Labels: A-network, C-epic, S-automerge, C-docs, P-medium

#6056 Move tests taking over 60 s to nightly
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/rpc_error_structs.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/nearcore/run_nodes.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/nearcore/track_shards.rs
  nightly/expensive.txt
Labels: A-testing, S-automerge, A-CI

#5954 re: `PeerActor` Simplify logic for receiving messages
  chain/network/src/peer/peer_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5958 re: Refactor `ThrottledFramedRead`
  chain/network/src/peer_manager/peer_manager_actor.rs
  utils/near-rate-limiter/README.md
  utils/near-rate-limiter/src/framed_read.rs
  utils/near-rate-limiter/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, T-core

#5944 re: Move `Edge` related types to `near-network-primitives`
  Cargo.lock
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/Cargo.toml
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/network_protocol/edge.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/test_utils.rs
  chain/network/src/tests/cache_edges.rs
  chain/network/src/types.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5963 re: Make `near-rust-allocator-proxy` package optional
  chain/network/Cargo.toml
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  nearcore/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, T-core

#6028 re: Remove unused dependencies for `near-network`
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  tools/rpctypegen/core/Cargo.toml
  tools/rpctypegen/macro/Cargo.toml
  utils/near-rate-limiter/Cargo.toml
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#5618 re: Document buggy behavior of `fetch_edges_for_peer_from_disk`
  chain/network/src/routing/routing_table_actor.rs
Labels: C-bug, P-low, A-network, S-automerge, C-docs

#6065 refactor: remove dead code
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#6071 re: Remove unused dependencies from `runtime-params-estimator`
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#6050 Fix comments and some implementation style in chunks
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
Labels: S-automerge

#6057 Metric for the transaction pool size
  Cargo.lock
  chain/pool/Cargo.toml
  chain/pool/src/lib.rs
  chain/pool/src/metrics.rs
Labels: S-automerge

#6054 neard: deprecate unsafe_reset_{all,data} commands
  Cargo.lock
  nearcore/src/config.rs
  neard/Cargo.toml
  neard/src/cli.rs
  pytest/lib/mocknet.py
Labels: P-low, S-automerge

#5721 chain: rosetta: add `related_transactions` to transactions
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator1_receipt_processing_transaction.snap
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__nfvalidator2_action_receipt_gas_reward_transaction.snap
  chain/rosetta-rpc/src/adapters/snapshots/near_rosetta_rpc__adapters__tests__validators_update_transaction.snap
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/models.rs
  pytest/tests/sanity/rosetta.py
Labels: S-automerge

#6094 make near-vm-runner build /w --no-default-features
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/preload.rs
Labels: S-automerge

#6018 feat: Implement download file progress bar
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/src/config.rs
Labels: S-automerge

#6068 Adding comments to all the database columns
  core/store/src/db.rs
Labels: S-automerge

#6001 re: Simplify code in `near-performance-metrics-macros`
  utils/near-performance-metrics-macros/src/lib.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6087 re: chore: Fix doc string in `edge_validator_actor`
  chain/network/src/routing/edge_validator_actor.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6088 re: chore: Change `comments` to doc strings for `RoutingTableMessages`
  chain/network/src/routing/routing_table_actor.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6082 re: chore: Rewrite `find_peers` in `peer_store.rs`
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6084 re: chore: Refactor code in `PeerManager` related to removing local edges
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/tests/cache.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6077 re: Cleanup usage of `actix::Message` in `near-network::test_utils`
  chain/network/src/test_utils.rs
Labels: P-low, S-automerge

#6076 re: Fix Clion false error in `near_network.rs`
  chain/network/src/network_protocol.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5966 re: Reformat `Cargo.toml` for `near-network` related packages
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-performance-metrics-macros/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-rate-limiter/Cargo.toml
  utils/near-stable-hasher/Cargo.toml
Labels: C-housekeeping, P-low, A-network, S-automerge, T-core

#6103 pytest: fix Rosetta test after genesis records started being loaded
  pytest/tests/sanity/rosetta.py
Labels: P-high, S-automerge

#5705 feat: Don't hide errors with parsing `network config`.
  Cargo.lock
  chain/indexer/src/lib.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/config.rs
  integration-tests/src/node/thread_node.rs
  integration-tests/src/tests/nearcore/node_cluster.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/src/cli.rs
  tools/indexer/example/src/main.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6000 re: Refactor `PeerManagerActor` pt 1
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#5906 re: Replace `Arc<Store>` with `Store`
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/epoch_manager/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/routing.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/test_utils.rs
  chain/network/src/tests/cache_edges.rs
  core/store/benches/store_bench.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  core/store/src/test_utils.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  genesis-tools/genesis-populate/src/lib.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  test-utils/state-viewer/src/apply_chain_range.rs
  test-utils/state-viewer/src/cli.rs
  test-utils/state-viewer/src/commands.rs
  test-utils/state-viewer/src/epoch_info.rs
  test-utils/state-viewer/src/state_dump.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge

#6003 re: `PeerManagerActor` Simplify `send_message`
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#5775 pytest: restaked: wait for at least one block to be generated
  pytest/tests/sanity/restaked.py
Labels: A-testing, P-high, S-automerge, A-CI, T-nodeX

#6059 integration-tests: fix test assuming block heights don’t skip numbers
  integration-tests/src/tests/client/chunks_management.rs
Labels: A-testing, P-high, S-automerge, A-CI

#6080 re: chore: Fix unused `msg` paramater warnings in `near-network`
  chain/client/src/client_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  utils/near-performance-metrics-macros/src/lib.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6112 pytest: improve getting current branch name
  pytest/lib/branches.py
Labels: S-automerge

#6102 Makefile: fix sandbox target not building in sandbox directory
  Makefile
Labels: P-high, S-automerge

#6109 re: Remove unused dependencies from runtime
  Cargo.lock
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  test-utils/runtime-tester/Cargo.toml
Labels: S-automerge

#6111 pytest: print more information about nodes
  pytest/lib/cluster.py
Labels: S-automerge

#6097 tests: fix flaky integration test
  integration-tests/src/tests/test_download_file.rs
  nearcore/src/config.rs
Labels: S-automerge

#6107 re: chore: Reduce visibility of HandshakeAutoDes in `near-network-primitives`
  chain/network/src/network_protocol.rs
Labels: P-low, A-network, S-automerge

#6121 pytest: ensure branch is always reset
  pytest/lib/branches.py
Labels: S-automerge

#6118 re: `near-network` Inline one line methods to improve readability.
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#6086 re: chore: Refactor `PeerManagerActor` before big changes
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/test_utils.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6026 re: Remove dependency on `near-network` from genesis tools
  Cargo.lock
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-populate/Cargo.toml
Labels: C-housekeeping, P-low, S-automerge

#6027 re: Cleanup imports in `integration-tests`
  Cargo.lock
  integration-tests/Cargo.toml
Labels: C-housekeeping, A-chain, P-low, S-automerge

#5999 re: `near-network` Remove `chain/network/src/routing/routing.rs`
  chain/network/src/routing/routing.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6114 re: Rename `active_peer` to `connected_peer`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6081 re: chore: Refactor `client-actor` code
  chain/client/src/client_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge, T-core

#6106 Betanet loadtest using mocknet scripts
  pytest/betanet_state.wasm
  pytest/lib/account.py
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/helpers/state_contract.rs
  pytest/tests/mocknet/load_test_betanet.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#6141 pytest: skip_epoch.py: don't refetch status when printing error msg
  pytest/tests/sanity/skip_epoch.py
Labels: S-automerge

#6144 debt: upgrade wasmtime to latest version
  Cargo.lock
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#6128 docs: link Zulip&Discourse
  README.md
Labels: S-automerge

#6159 Update architecture.md
  docs/architecture.md
Labels: S-automerge

#5712 Fix small discrepancy in validator threshold
  chain/chain/src/tests/simple_chain.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/proposals.rs
  chain/epoch_manager/src/validator_selection.rs
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  neard/Cargo.toml
Labels: S-automerge

#6133 doc: Add comments to storage estimations
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#6138 Mocknet: Read genesis records from a separate file
  pytest/lib/mocknet.py
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/bounce.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#6110 Fix NixOS patching implementation in pytest
  pytest/lib/branches.py
Labels: S-automerge

#6166 debt: handle review comments on #6144
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#6147 re: chore: Rewrite `index_to_bytes` to not do hidden memory allocations
  chain/chain/src/store.rs
  core/primitives/src/utils.rs
Labels: S-automerge

#6029 feat: Finish replacing `cached` with `lru`
  Cargo.lock
  chain/chunks/Cargo.toml
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/sync.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/test_helpers.rs
  integration-tests/src/tests/client/runtimes.rs
Labels: C-housekeeping, A-chain, P-low, S-automerge, T-core

#6113 re: `near-network` Remove usage of `actix::spawn` when it's not necessary
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: P-low, A-network, S-automerge

#6163 chore: remove chefsale from codeowners and replace rtsai123
  CODEOWNERS
Labels: S-automerge

#6155 fix a bug in chunk requesting
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
Labels: S-automerge

#5644 re: Simplify `PeerActorManager` by removing `IncomingCrutch`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#6171 Fix near-test-contracts build script to work if CARGO_TARGET_DIR is set.
  runtime/near-test-contracts/build.rs
Labels: S-automerge

#6152 pytest: fix `git symbolic-ref` not understanding `@`
  pytest/lib/branches.py
Labels: A-testing, P-high, S-automerge, A-CI

#6172 chain: rosetta: refactor convert_block_changes_to_transactions function
  chain/rosetta-rpc/src/adapters/transactions.rs
Labels: S-automerge

#6182 Update to wasmer-near 2.2.0
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#6179 feat: Make jsonrpc-primitives types derive `Debug`
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/sandbox.rs
Labels: S-automerge

#6167 refactor: remove dead code
  neard/tests/rpc_nodes.rs
Labels: S-automerge

#6178 re: Remove unused types from `near-primitives`
  chain/network-primitives/src/types.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6161 re: Fix qualified imports inside `client_actor.rs`
  chain/client/src/client_actor.rs
Labels: P-low, A-network, S-automerge

#6131 re: chore: Refactor `monitor_peer_stats_trigger`
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6145 re: chore: Rewrite `prune_unreachable_edges_and_save_to_db` to a functional style
  chain/network/src/routing/routing_table_actor.rs
Labels: S-automerge

#6130 re: `near-network::routing` Remove not needed `mut self`
  chain/network/src/routing/ibf.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/tests/cache.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#6083 feat: Optimize `find_route_from_peer_id` in `near-network`
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/routing/routing_table_view.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5945 re: Derive `MessageResponse` instead of implementing it
  chain/network-primitives/src/types.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/types.rs
  utils/near-rate-limiter/src/message_wrapper.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5902 fix: Fix memory leak in `near-network` affecting `indexer` and probably all nodes
  chain/network/src/peer/codec.rs
  utils/near-performance-metrics/src/framed_write.rs
Labels: C-bug, P-low, A-network, S-automerge, T-core

#6020 feat: `RateCounter` rewrite
  chain/network-primitives/src/types.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/rate_counter.rs
  chain/network/src/peer/tracker.rs
  chain/network/src/peer/transfer_stats.rs
Labels: C-bug, C-housekeeping, A-chain, P-low, A-network, S-automerge

#6189 pytest: add frol as owner of rosetta.py test
  CODEOWNERS
Labels: S-automerge

#5596 feat: Optimize `RoutingTableView` iterators
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/tests/cache.rs
Labels: C-enhancement, C-housekeeping, P-low, A-network, S-automerge

#6098 re: chore: `routing_table_view` Change visibility to pub(crate) / remove dead code
  chain/network/src/routing/routing_table_view.rs
Labels: C-housekeeping, P-low, S-automerge

#6168 chain: rosetta: guarantee order of operations in genesis block
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/utils.rs
  pytest/tests/sanity/rosetta.py
Labels: P-high, S-automerge

#6089 re: chore: Refactor decode in `near-network::Codec`
  chain/network/src/peer/codec.rs
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, A-chain, P-low, A-network, S-automerge, T-core

#6044 pytest: add test for computing block hash from JSON RPC response
  nightly/pytest-sanity.txt
  pytest/lib/messages/block.py
  pytest/lib/messages/crypto.py
  pytest/tests/sanity/rpc_hash.py
Labels: S-automerge

#6174 bug: Fix `routing_table_sync.py` test
  chain/network/src/peer_manager/peer_manager_actor.rs
  nightly/pytest-sanity.txt
Labels: C-bug, A-testing, P-low, A-network, S-automerge

#6196 chore: update crates to use single hashbrown version
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/client/Cargo.toml
  chain/epoch_manager/Cargo.toml
  chain/network/Cargo.toml
  core/store/Cargo.toml
  deny.toml
  runtime/near-vm-logic/Cargo.toml
  utils/near-cache/Cargo.toml
Labels: S-automerge

#6142 feat: Upgrade rust to 1.58.1
  chain/client/src/tests/catching_up.rs
  integration-tests/src/tests/test_tps_regression.rs
  rust-toolchain.toml
Labels: C-housekeeping, P-low, A-network, S-automerge

#5834 feat: Move `RoutedMessage` inside `Box` to reduce `PeerMessage` enum size
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/utils.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#6192 Use `derive(actix::Message)` instead of implementing it manually
  chain/network/src/private_actix.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/types.rs
Labels: C-housekeeping, P-low, S-automerge

#6191 Fix: Avoid counting metrics for unsupported RPC metrics
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#6146 re: rewrite `prune_unreachable_edges_and_save_to_db` to functional style pt2
  chain/network/src/routing/routing_table_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#5791 feat: Use `criterion` instead of `bencher`
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/benches/routing_table_actor.rs
Labels: C-housekeeping, P-low, A-network, S-automerge, A-benchmark

#6148 fix: reduce number of chunk requesting messages
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6190 Add more unit test for ShardsManager
  Cargo.lock
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  integration-tests/src/tests/client/runtimes.rs
Labels: S-automerge

#6134 Update `near-rust-allocator-proxy ` to 0.4.0
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/Cargo.toml
  neard/src/main.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6210 Disable fetching chunks for multiple blocks
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6205 gitignore: allow target to be a symlink
  .gitignore
Labels: S-automerge

#6151 Measure time of successful block processing
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
Labels: S-automerge

#6045 Increase test_inflation testing time Closes #5327
  integration-tests/src/tests/nearcore/stake_nodes.rs
Labels: S-automerge
