Repository near/nearcore, pull requests merged in 2022-02, with the labels that each got.

#6219 pytest: fix a failure in skip_epoch.py
  pytest/lib/utils.py
  pytest/tests/sanity/skip_epoch.py
Labels: S-automerge

#6202 feat(themis): whitelist `neard` from unversioned checks
  neard/Cargo.toml
  tools/themis/src/rules.rs
Labels: S-automerge

#5793 feat: `near-primitives` Improve `combine_hash` performance by `40%`.
  chain/chain/src/chain.rs
  chain/network-primitives/src/network_protocol/mod.rs
  core/primitives/benches/serialization.rs
  core/primitives/src/block_header.rs
  core/primitives/src/merkle.rs
  core/primitives/src/sharding.rs
Labels: C-enhancement, C-housekeeping, A-chain, P-low, S-automerge, A-benchmark

#6206 refactor: simplify callback handling in chain
  chain/chain/src/chain.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/mod.rs
  chain/chain/src/tests/sync_chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6181 fix: support relative TARGET_DIR in near-test-contracts
  runtime/near-test-contracts/build.rs
Labels: S-automerge

#6037 neard: don’t overwrite validator and node keys when initialising chain
  core/crypto/src/signer.rs
  nearcore/Cargo.toml
  nearcore/src/config.rs
Labels: S-automerge

#6198 pytest: remove restaked.py test
  nightly/README.md
  nightly/pytest-sanity.txt
  pytest/tests/sanity/restaked.py
Labels: A-testing, S-automerge

#5732 nearcore: support dling compressed `genesis.json` and `config.json`
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/src/config.rs
Labels: S-automerge, T-nodeX

#5814 re: Remove dead code from `scripts/test_nearlib.sh`
  .buildkite/pipeline.yml
Labels: C-housekeeping, P-low, A-CI

#6231 rosetta: add `--download-config` to starting node instructions
  chain/rosetta-rpc/README.md
Labels: S-automerge

#6239 chore: bump version to 0.12.0
  Cargo.toml
Labels: S-automerge

#6240 fix(CI): exclude neard from being versioned by cargo-workspaces
  Cargo.toml
Labels: S-automerge

#6237 aarch64: fix compilation issue
  chain/network/src/network_protocol.rs
Labels: S-automerge

#6248 refactor: move group_receipts_by_shard and build_receipts_hashes to c…
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  integration-tests/src/tests/client/challenges.rs
Labels: S-automerge

#6099 chain: fix and refactor assign_shards function
  chain/epoch_manager/src/shard_assignment.rs
Labels: S-automerge

#6258 chain: refactor status line formatting
  chain/client/src/info.rs
Labels: S-automerge

#6256 cleanup: remove ToEnvelope trait bound on create_sync_job_scheduler()
  chain/client/src/client_actor.rs
Labels: S-automerge

#6246 fix(network-primitives): pin actix-derive to fix isolated compilation issues
  Cargo.lock
  chain/network-primitives/Cargo.toml
Labels: S-automerge

#6160 change block sync to request 5 blocks at a time
  chain/chain-primitives/src/error.rs
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/sync.rs
Labels: S-automerge

#6238 client: add GetBlockHash request and use it in Rosetta RPC
  chain/chain/src/chain.rs
  chain/client-primitives/src/types.rs
  chain/client/src/lib.rs
  chain/client/src/view_client.rs
  chain/rosetta-rpc/src/lib.rs
Labels: S-automerge

#6268 feat: add metrics about chunk fullness
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#6271 chain: client: avoid unnecessary String allocations
  chain/client/src/info.rs
Labels: P-low, S-automerge

#6259 Fix copy path in Dockerfile
  Dockerfile
Labels: S-automerge

#6260 chain: make status line more descriptive
  chain/client/src/info.rs
Labels: S-automerge

#6273 chore: reformat Cargo.toml lists with many elements in one line
  chain/chain/Cargo.toml
  chain/client/Cargo.toml
  chain/epoch_manager/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  core/crypto/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/state-viewer/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: P-low, S-automerge

#6251 Remove references to the state-viewer tool
  Makefile
  pytest/lib/branches.py
  pytest/tests/sanity/state_migration.py
  scripts/mac-release.sh
  test-utils/state-viewer/README.md
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6275 Metric for missing chunks
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#6232 fuzz: introduce fuzzer configuration
  nightly/fuzz.toml
Labels: S-automerge

#6278 feat: Differentiate code and data bytes
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#6267 Convert state-viewer into a library
  Cargo.toml
  neard/Cargo.toml
  test-utils/state-viewer/src/main.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/README.md
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
  tools/state-viewer/src/lib.rs
  tools/state-viewer/src/rocksdb_stats.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#6209 re: chore: Elide `mut self` in `near-network`
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6289 chore: Upgrade rust-rocksdb 0.16 to 0.18
  Cargo.lock
  chain/indexer/Cargo.toml
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/db/refcount.rs
  core/store/src/db/v6_to_v7.rs
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#6287 Adding more debug information (like avg gas) to apply_chain)
  tools/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#6253 chain: refactor assign_with_possible_repeats in shard_assignment.rs
  chain/epoch_manager/src/shard_assignment.rs
  core/primitives/src/utils/min_heap.rs
Labels: P-low, S-automerge

#6297 chain: include information whether node is a validator in status line
  chain/client/src/info.rs
Labels: S-automerge

#6252 pytest: fix sync_chunks_from_archival.py test
  pytest/tests/sanity/sync_chunks_from_archival.py
Labels: P-high, S-automerge

#6188 neard: generate NEARD_VERSION et al via `build.rs` script
  Cargo.lock
  neard/Cargo.toml
  neard/build.rs
  neard/src/cli.rs
  neard/src/main.rs
Labels: P-low, S-automerge

#6304 chain: add space between block hash and validator status
  chain/client/src/info.rs
Labels: S-automerge

#6312 Dockerfile: change back from ENTRYPOINT to CMD
  Dockerfile
  scripts/run_docker.sh
Labels: P-high, S-automerge

#6314 fuzz: adjust branches with the latest release
  nightly/fuzz.toml
Labels: S-automerge

#6310 fuzz: introduce fuzzing configuration
  nightly/fuzz.toml
Labels: S-automerge

#6303 feat: replace `Vec<u8>` with `Arc<[u8]>` in trie cache
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
Labels: S-automerge

#6298 pytest: fuzz: fix test not killing fuzz processes correctly
  pytest/requirements.txt
  pytest/tests/fuzz.py
Labels: S-automerge

#6318 Log to WARN information about invalid chunk state and invalid challenges
  chain/chain/src/chain.rs
Labels: S-automerge

#6307 End-to-end test for canaries
  pytest/endtoend/__init__.py
  pytest/endtoend/endtoend.py
  pytest/lib/account.py
  pytest/lib/mocknet_helpers.py
Labels: S-automerge

#6305 client: add rustc_version to --version page and /status response
  Cargo.lock
  core/primitives/src/version.rs
  deny.toml
  neard/Cargo.toml
  neard/build.rs
  neard/src/main.rs
Labels: S-automerge

#6330 neard: make build.rs work with git worktree
  neard/build.rs
Labels: P-low, S-automerge

#6325 Added chunk info to state viewer's print chain
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6269 buildkite: set common environment variables in `env` section
  .buildkite/pipeline.yml
Labels: S-automerge

#6329 Replace log with tracing
  Cargo.lock
  chain/chain-primitives/Cargo.toml
  chain/chain-primitives/src/error.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/types.rs
  core/metrics/Cargo.toml
  core/metrics/src/lib.rs
  core/store/Cargo.toml
  integration-tests/Cargo.toml
  integration-tests/src/node/process_node.rs
  integration-tests/src/tests/client/chunks_management.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/ext.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer/mod.rs
  test-utils/logger/Cargo.toml
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/src/run_test.rs
  tools/delay_detector/Cargo.toml
  tools/delay_detector/src/lib.rs
  tools/restaked/Cargo.toml
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/Cargo.toml
  tools/storage-usage-delta-calculator/src/main.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/process.rs
  utils/near-performance-metrics/src/stats_enabled.rs
  utils/near-rate-limiter/Cargo.toml
Labels: P-low, S-automerge

#6327 scripts: accept NEAR_HOME from environment and other minor improvements
  scripts/run_docker.sh
Labels: P-low, S-automerge

#6341 chore: drop stale tests
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
Labels: S-automerge

#6064 mocknet: Instructions improvements
  pytest/lib/mocknet.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#6282 Safe DB migrations using RocksDB Checkpoints
  core/store/src/db.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
Labels: S-automerge

#6334 chore: Upgrade tokio to 1.16
  Cargo.lock
  neard/Cargo.toml
Labels: S-automerge

#6345 refactor: Align gas metering estimation
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge
