Repository near/nearcore, pull requests merged in 2022-07, with the labels that each got.

#7154 chore: drop gratitious dependency
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/estimator_params.rs
Labels: S-automerge

#7149 network: bypass near_store::Store abstraction in network’s Store
  chain/network/src/store/mod.rs
  chain/network/src/store/schema/mod.rs
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#7155 chore: remove a bunch of unused dependencies
  Cargo.lock
  chain/epoch_manager/Cargo.toml
  core/crypto/Cargo.toml
  core/primitives/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
Labels: S-automerge

#7156 chore: upgrade sysinfo
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/info.rs
Labels: S-automerge

#7153 test: add convenience helper to upgrade protocol in tests
  chain/client/src/test_utils.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7123 feat: limit the total size of a chunk
  Cargo.toml
  chain/chain/src/test_utils.rs
  integration-tests/src/tests/client/benchmarks.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7157 store: change static ShardTries methods into regular ones
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7151 cleanup(shardnet): remove unused var from restake.py
  pytest/tests/shardnet/README.md
  pytest/tests/shardnet/restake.py
Labels: S-automerge

#7159 store: remove unused ShardTries::apply_genesis method
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7166 chore: Disable the stale bot
  .github/stale.yml
Labels: S-automerge

#7147 refactor: use serde_repr to cut some boilerplate
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
Labels: S-automerge

#7168 chore: update openssl
  Cargo.lock
Labels: S-automerge

#7170 fix: CpuBenchmarkSha256 encoding in assertion
  runtime/runtime-params-estimator/src/estimator_params.rs
Labels: S-automerge

#7160 fix/refactor(mocknet): don't alter forked genesis shard config by default
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#7169 test: Integration test for fixed loading cost
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7174 simplified the round robin in RoutingTableView
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/graph_with_cache.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/routing/tests/cache.rs
  chain/network/src/routing/tests/mod.rs
  chain/network/src/routing/tests/routing_table_view.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#7176 removed unused broadcast metric
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/test_utils.rs
Labels: S-automerge

#7161 Fix chunk forwarding for chunk only producers
  chain/chain/src/test_utils.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/test_utils.rs
Labels: S-automerge

#7180 pytest: remove Docker container once sanity/docker.py test finishes
  pytest/tests/sanity/docker.py
Labels: A-testing, S-automerge

#6968 Make apply_chunks async
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/chain.rs
  chain/chain/src/crypto_hash_timer.rs
  chain/chain/src/lib.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/mod.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7185 refactor: simplify PROTOCOL_VERSION declaration
  core/primitives/src/version.rs
Labels: S-automerge

#6996 feat: estimate fn call action without loading cost
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#7173 chore: Enable M1 builds on master
  .github/workflows/mac_m1_binary.yml
  scripts/mac-release.sh
Labels: S-automerge

#7189 test: unignore wasmer2 upgrade test
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7190 test: simplify code a bit
  chain/chain/src/test_utils.rs
Labels: S-automerge

#7191 test: tiny simplification in setup_mock_all_validators
  chain/client/src/test_utils.rs
Labels: S-automerge

#7192 test: simplify setup_mock_validators a bit
  chain/client/src/test_utils.rs
Labels: S-automerge

#7143 fuzz: copy all cargo-fuzz targets to cargo-bolero integration tests
  Cargo.lock
  core/account-id/Cargo.toml
  core/account-id/src/borsh.rs
  core/account-id/src/serde.rs
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: S-automerge

#7195 Disable the secondary stack limit for fuzzing
  runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: S-automerge

#7158 store: remove unused map_col_from_key function
  core/store/src/migrations.rs
Labels: P-low, S-automerge

#7201 Remove duplicated serialisation formats implementations
  core/primitives-core/src/serialize.rs
  core/primitives/src/lib.rs
  core/primitives/src/serialize.rs
  runtime/near-vm-logic/src/context.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-logic/src/serde_with.rs
  runtime/near-vm-logic/src/types.rs
Labels: P-low, S-automerge

#7206 renamed Validator to AccountData
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/account_key.rs
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/tests.rs
Labels: S-automerge

#7211 test: more useful assert
  chain/client/src/test_utils.rs
Labels: S-automerge

#7200 trie_key: don’t store single bytes as slices
  core/primitives/src/state_record.rs
  core/primitives/src/trie_key.rs
Labels: P-low, S-automerge

#7213 test: simplify cops support in KeyValue runtime
  chain/chain/src/test_utils.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/test_utils.rs
Labels: S-automerge

#7216 Refactor: remove some dead code
  core/primitives-core/src/serialize.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-logic/src/types.rs
Labels: S-automerge

#7218 store: move RocskDB and TestDB structs to their separate modules
  chain/client/src/rocksdb_metrics.rs
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/testdb.rs
  core/store/src/lib.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  neard/src/cli.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#7214 also respect storage config when checking rocksdb version
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
Labels: S-automerge

#7212 Modify state dumper and replay to select / replace the right accounts
  pytest/tests/replay/replay.py
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7221 show output file path after dumping tx
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#7222 Display block and chunk producers of an epoch
  tools/state-viewer/src/epoch_info.rs
Labels: S-automerge

#7234 store: handle Insert operation in ShardTries::update_cache
  core/store/src/trie/shard_tries.rs
Labels: P-low, S-automerge

#7229 Shardnet improvements to debug page
  chain/jsonrpc/res/last_blocks.html
  chain/jsonrpc/res/network_info.html
Labels: S-automerge

#6939 fix(sync): fix a syncing stall when a shard split is happening soon
  chain/client-primitives/src/types.rs
  chain/client/src/sync.rs
Labels: S-automerge

#7230 fix: graceful zero least-squares estimations
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime-params-estimator/src/qemu.rs
Labels: S-automerge

#7243 add metrics for block ordinal for current chain head
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
Labels: S-automerge

#7240 store: Trie: empty_root() → EMPTY_ROOT and use it more consistently
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/types.rs
  chain/network/src/network_protocol/testonly.rs
  core/primitives-core/src/hash.rs
  core/primitives/benches/serialization.rs
  core/store/benches/trie_bench.rs
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
  integration-tests/src/tests/client/challenges.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7231 debug: forward debug flag to loading estimation
  runtime/runtime-params-estimator/src/function_call.rs
Labels: S-automerge

#7239 Expose node_key in the status response
  chain/client/src/client_actor.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7144 fix(shardnet): Create the correct account
  pytest/tests/shardnet/scripts/create_account.sh
Labels: S-automerge

#7241 Revert "feat: stabilize precharged contract loading gas (#7177)"
  CHANGELOG.md
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#7236 refactor: Use std API to avoid throwing errors that should not be possible
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/mod.rs
Labels: S-automerge

#7237 store: prefer Trie::iter to TrieIterator::new
  chain/chain/src/store_validator/validate.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/state_parts.rs
  nearcore/benches/store.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7248 core: harmonise dec_format serialisation formats
  core/chain-configs/src/genesis_config.rs
  core/primitives-core/src/account.rs
  core/primitives-core/src/runtime/fees.rs
  core/primitives-core/src/serialize.rs
  core/primitives/src/errors.rs
  core/primitives/src/receipt.rs
  core/primitives/src/runtime/config.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  runtime/near-vm-logic/src/context.rs
Labels: P-low, S-automerge

#7252 Scraper for collecting IP addresses of validators
  pytest/tests/shardnet/collect_ips.py
Labels: S-automerge

#7208 implemented accounts data cache
  Cargo.lock
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/lib.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/testonly/mod.rs
  core/primitives/src/types.rs
Labels: S-automerge

#7259 refactor: avoid double hash-map lookup
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7244 add more detailed metrics for block processing times
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/chain/src/types.rs
Labels: S-automerge

#7257 store: make TrieRefcountChange::rc non-zero
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_tests.rs
Labels: P-low, S-automerge

#7262 Update README.md
  README.md
Labels: S-automerge

#7258 refactor: simplify send message
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7261 refactor: remove unwrap
  Cargo.lock
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7269 refactored NetworkRecipient interface
  chain/client/src/test_utils.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#7264 Add more detailed validator information in debug page
  chain/client-primitives/src/debug.rs
  chain/client/src/debug.rs
  chain/jsonrpc/res/epoch_info.html
Labels: S-automerge

#7274 Update README.md
  chain/epoch_manager/README.md
  core/account-id/README.md
  tools/state-viewer/README.md
Labels: S-automerge

#7266 Refactor: remove unnecessary `pub` from a field
  core/store/src/trie/mod.rs
Labels: S-automerge

#7246 runtime: refactor try_fold to avoid unnecessary collect in check_balance
  runtime/runtime/src/balance_checker.rs
Labels: S-automerge

#7268 refactor: replace some `allow(dead_code)` with `cfg(test)`s
  core/store/src/trie/mod.rs
Labels: S-automerge

#7276 runtime: Arc<CompiledContractCache> → Box<_>
  core/primitives/src/runtime/apply_state.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7270 Extend TelemetryInfo with an additional freeform field
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  core/primitives/src/telemetry.rs
Labels: S-automerge

#7275 store: use Database directly in StoreCompiledContractCache
  core/primitives/src/types.rs
  core/store/src/lib.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7273 refactor: don't compute the genesis json hash if it's already stored
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7283 Fix some bug in validator info debug page
  chain/jsonrpc/res/epoch_info.html
Labels: S-automerge

#7279 fix(collect-ips): Use non-debug endpoints
  pytest/tests/shardnet/collect_ips.py
Labels: S-automerge

#7289 [SHRD-134] Exporting more detailed info about peers
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/runner.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock_node/src/lib.rs
Labels: S-automerge

#7282 network: get rid of RoutedMessageBody::Query{Request,Response}
  chain/client/src/test_utils.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7292 doc: document why we may need to store more than one outcome per tx
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#7256 test: introduce ValidatorSchedule to specify COPs for KeyValue runtime conveniently
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/test_utils/validator_schedule.rs
  chain/chain/src/tests/gc.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/query_client.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#7171 Implemented broadcasting per-account data
  Cargo.lock
  chain/chain/src/chain.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/network-primitives/src/config.rs
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/accounts_data/mod.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/connected_peers.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/test_utils.rs
  chain/network/src/testonly/fake_client.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock_node/src/lib.rs
Labels: S-automerge

#7233 store: deduplicate code retrieving of a raw trie node
  core/store/src/trie/mod.rs
Labels: S-automerge

#7272 added signing of AccountData to ValidatorSigner
  chain/network/src/accounts_data/tests.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  core/primitives/src/validator_signer.rs
Labels: S-automerge

#7280 test: use ValidatorSchedule in setup_mock_all_validators
  chain/chain/src/test_utils/validator_schedule.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/bug_repros.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/consensus.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/query_client.rs
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7288 docs: add links to NEP and implementation PR to feature-stabilization checklist
  .github/PULL_REQUEST_TEMPLATE/feature_stabilization.md
Labels: S-automerge

#7302 jsonrpc: fuzz: fix Base58String type; should read 64
  Cargo.lock
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs
Labels: P-low, S-automerge
