Repository near/nearcore, pull requests merged in 2022-08, with the labels that each got.

#7300 nearcore: deprecate network configurations’s external_address field
  CHANGELOG.md
  chain/network-primitives/src/config_json.rs
  nearcore/res/example-config-gc.json
  nearcore/res/example-config-no-gc.json
  nearcore/src/config.rs
Labels: P-low, S-automerge

#7305 neard: use release tags when determining build string
  neard/build.rs
Labels: P-low, S-automerge

#7309 fix a bug in send_network_chain_info
  chain/client/src/client.rs
Labels: S-automerge

#7311 pytest: update tests to no longer used deleted ‘testnet’ command
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/upgradable.py
Labels: P-high, S-automerge

#7308 core: views: prefer base64_format to manual base64 conversions
  chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/sandbox.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/runtime/deployment.rs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  integration-tests/src/tests/runtime/test_evil_contracts.rs
  integration-tests/src/tests/standard_cases/mod.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#7255 doc: prefer for loops to for_each and try_for_each methods
  chain/chain/src/chain.rs
  chain/chunks/src/lib.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/network/src/store/mod.rs
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/trie_tests.rs
  docs/style.md
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/runtime/test_evil_contracts.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7291 Add uptime to prometheus metrics and telemetry info
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/info.rs
  core/primitives/src/telemetry.rs
Labels: S-automerge

#7290 Configurable telemetry reporting interval
  Cargo.lock
  chain/telemetry/Cargo.toml
  chain/telemetry/src/lib.rs
Labels: S-automerge

#7316 deny: remove outdated deny skips
  deny.toml
Labels: P-low, S-automerge

#7320 refactor: drop needless mut
  chain/epoch_manager/src/lib.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#7321 Display node uptime on the /status and /debug pages
  chain/client/src/client_actor.rs
  chain/jsonrpc/res/debug.html
  core/primitives/src/views.rs
Labels: S-automerge

#7297 Refactor BlockInProgress to print more information of processed blocks and chunks
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/blocks_delay_tracker.rs
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  chain/chain/src/missing_chunks.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/jsonrpc/res/chain_n_chunk_info.html
  core/primitives/src/views.rs
Labels: S-automerge

#7322 [SHRD-135] Don't route the messages through peers that are too far behind
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/graph.rs
  chain/network/src/routing/graph_with_cache.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7287 refactor: Splitting out process_block tests
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/features/fix_contract_loading_cost.rs
  integration-tests/src/tests/client/mod.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7328 fix(uptime): duration formatting
  chain/jsonrpc/res/debug.html
Labels: S-automerge

#7299 Implemented sending signed AccountData by validators
  Cargo.lock
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/test_utils.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/lib.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/lib.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/net.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/src/node/mod.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock_node/src/lib.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7307 refactor: remove needless indirection
  core/primitives/src/network.rs
Labels: S-automerge

#7334 fix chunk forwarding so parts can be forwarded even if the previous b…
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  core/primitives/src/version.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7317 refactor: replace WaitOrTimeoutActor with wait_or_timeout function
  integration-tests/src/node/process_node.rs
Labels: S-automerge

#7260 refactor: minor cleanups to handle_msg_register_peer
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7314 refactor: replace WaitOrTimeoutActor with wait_or_timeout function
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
Labels: S-automerge

#7329 Export `extra_telemetry_info` also in a structured form
  chain/client/src/info.rs
  core/primitives/src/telemetry.rs
Labels: S-automerge

#7312 reorganize validator info page
  chain/client-primitives/src/debug.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/jsonrpc/res/validator.html
Labels: S-automerge

#7333 chain: avoid unnecessary Arc::clone
  chain/chain/src/chain.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
Labels: P-low, S-automerge

#7325 refactor: split out more tests from `process_blocks.rs`
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/fix_storage_usage.rs
  integration-tests/src/tests/client/features/restore_receipts_after_fix_apply_chunks.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7339 minor: fix a compiler warning on mac
  runtime/near-vm-runner/src/tests.rs
Labels: S-automerge

#7331 send partial encoded chunk message three times
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7340 chore: remove buildkite codeowners
  CODEOWNERS
Labels: S-automerge

#7342 fix validator debug page so that approvals are shown even if the thre…
  chain/chain/src/doomslug.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
Labels: S-automerge

#7296 Update CONTRIBUTING.md to reflect the new code review process
  CONTRIBUTING.md
Labels: S-automerge

#7344 add missing blocks and chunks stats at last_blocks page
  chain/jsonrpc/res/last_blocks.html
Labels: S-automerge

#7343 refactor: replace wait actor with function
  integration-tests/src/tests/nearcore/run_nodes.rs
  integration-tests/src/tests/nearcore/track_shards.rs
Labels: S-automerge

#7349 moved edge loading before filtering
  chain/network/src/routing/actor.rs
Labels: S-automerge

#7350 deflaked network tests
  chain/network/src/accounts_data/mod.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/testonly/actix.rs
Labels: S-automerge

#7346 Add more detailed chunk info in the chain and chunk debug page
  chain/chain/src/blocks_delay_tracker.rs
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/jsonrpc/res/chain_n_chunk_info.html
  core/primitives/src/views.rs
Labels: S-automerge

#7341 fixed unchecked subtractions Instant - Duration
  chain/network-primitives/src/types.rs
  chain/network/src/config.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/route_back_cache.rs
  integration-tests/src/tests/network/ban_peers.rs
  integration-tests/src/tests/network/full_network.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#7336 chore: remove some noise from CI logs
  .buildkite/pipeline.yml
Labels: S-automerge

#7358 Revert "Fix/rosetta rpc predecessor"
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/adapters/validated_operations/transfer.rs
  chain/rosetta-rpc/src/models.rs
Labels: S-automerge

#7353 test of edge broadcast after restart
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
Labels: S-automerge

#7352 removed duplicate delay in routing table sync after handshake
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7354 removed unnecessary caching of TIER1 account keys in the near_client
  chain/client/src/client.rs
  chain/network/src/accounts_data/mod.rs
Labels: S-automerge

#7335 feat(o11y): Trace AnnounceAccount callback
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7351 Send approvals multiple times
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7361 pytest: remove requirement of specific scipy version
  pytest/requirements.txt
Labels: S-automerge

#7079 chore(primitives): drop `BaseDecode` trait
  core/primitives-core/src/hash.rs
  core/primitives-core/src/serialize.rs
  integration-tests/src/tests/client/challenges.rs
Labels: S-automerge

#7263 runtime: move closures out of check_balance to refactor it slightly
  runtime/runtime/src/balance_checker.rs
Labels: S-automerge

#7357 Update rocksdb to 0.19
  Cargo.lock
  chain/indexer/Cargo.toml
  core/store/Cargo.toml
  core/store/src/db/rocksdb.rs
  deny.toml
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#7345 feat: simple flat storage
  chain/chain/Cargo.toml
  chain/chain/src/store.rs
  core/primitives/src/lib.rs
  core/primitives/src/state.rs
  core/primitives/src/state_record.rs
  core/store/Cargo.toml
  core/store/src/columns.rs
  core/store/src/flat_state.rs
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  neard/Cargo.toml
  runtime/runtime/Cargo.toml
  runtime/runtime/src/genesis.rs
Labels: S-automerge

#7365 Add traces to PeerManagerActor `handle()` functions
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7373 chain: maybe_block_id_to_block_hash → maybe_block_id_to_block_header
  chain/client/src/view_client.rs
Labels: S-automerge

#7277 store: remove unnecessary TrieNodeWithSize::from_raw calls
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
Labels: P-low, S-automerge

#7376 store: accept IntoIterator by Trie::update
  core/store/benches/trie_bench.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
Labels: S-automerge

#7374 rosetta: refactor BlockIdentifier construction
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/models.rs
Labels: S-automerge

#7372 sandbox: refactor SandboxStatePatch making it unit on non-sandbox builds
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  core/primitives/src/lib.rs
  core/primitives/src/sandbox.rs
  core/primitives/src/sandbox_state_patch.rs
  integration-tests/src/tests/client/sandbox.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
Labels: P-low

#7377 core: get rid of BaseEncode trait
  chain/jsonrpc/src/lib.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/serialize.rs
Labels: P-low, S-automerge

#7366 refactor: Made ConnectedPeer a shared state of PeerActor.
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tracker.rs
  chain/network/src/peer/transfer_stats.rs
  chain/network/src/peer_manager/connected_peers.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
  chain/network/src/types.rs
Labels: S-automerge

#7363 Add feature max_kickout_stake_ratio
  chain/chain/src/tests/simple_chain.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/epoch_manager/src/validator_selection.rs
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/primitives/Cargo.toml
  core/primitives/src/epoch_manager.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  nearcore/src/shard_tracker.rs
Labels: S-automerge

#7370 Start accepting timestamp-based network edge nonces
  chain/network-primitives/src/network_protocol/edge.rs
  chain/network-primitives/src/types.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/graph_with_cache.rs
  chain/network/src/routing/tests/cache_edges.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7380 Add protocol config changes for chunk only producers
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/epoch_manager.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#7381 StabIlize feature chunk_only_producers and max_kickout_stake
  chain/chain/Cargo.toml
  chain/chain/src/test_utils.rs
  chain/chain/src/test_utils/validator_schedule.rs
  chain/chain/src/tests/simple_chain.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/Cargo.toml
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/reward_calculator.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/epoch_manager/src/validator_selection.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  chain/rosetta-rpc/Cargo.toml
  core/chain-configs/Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/primitives/Cargo.toml
  core/primitives/src/epoch_manager.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  core/store/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  neard/Cargo.toml
  runtime/runtime/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: S-automerge

#7382 rosetta: avoid unnecessary clones by taking Genesis and Addr by ref
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/lib.rs
Labels: S-automerge

#7356 Log type and length of sent messages
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#7386 fix: a quickfix to make demux tolerant to stopping tokio::Runtime
  chain/network/src/concurrency/demux.rs
  chain/network/src/concurrency/tests.rs
  chain/network/src/peer_manager/connected_peers.rs
Labels: S-automerge

#7355 Adding experimental config options to connect only to boot nodes
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/peer_store_test.rs
Labels: S-automerge

#7384 chain: pass genesis hash to Rosetta and get rid of GetBlockHash request
  chain/client-primitives/src/types.rs
  chain/client/src/lib.rs
  chain/client/src/view_client.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/lib.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7330 refactor: cleanup network config a bit
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/config.rs
Labels: S-automerge

#7390 test of demux behavior when the runtime is dropped
  chain/network/src/concurrency/demux.rs
  chain/network/src/concurrency/tests.rs
Labels: S-automerge

#7395 fix: remove mistaken write-once assert from CompiledContractCache
  core/store/src/lib.rs
Labels: S-automerge

#7396 refactor: add some assertions about column types to DBTransaction
  core/store/src/db.rs
Labels: S-automerge

#7394 chain: normalise ‘_by_hash’ and ‘_by_height’ naming
  chain/client/src/client_actor.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/utils.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/test_tps_regression.rs
  integration-tests/src/user/mod.rs
  integration-tests/src/user/rpc_user.rs
  integration-tests/src/user/runtime_user.rs
Labels: P-low, S-automerge

#7401 Revert "Update rocksdb to 0.19 (#7357)"
  Cargo.lock
  chain/indexer/Cargo.toml
  core/store/Cargo.toml
  core/store/src/db/rocksdb.rs
  deny.toml
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#7397 chain: avoid fetching header in ViewClientActor::get_block_hash_by_finality
  chain/client/src/view_client.rs
Labels: S-automerge

#7393 chain: standardise on ‘get_block_header’ naming
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/client/src/debug.rs
  chain/client/src/sync.rs
  chain/client/src/view_client.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: P-low, S-automerge

#7399 Simplify DBCol’s Display implementation and prefer it over Debug
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  core/store/src/columns.rs
  core/store/src/lib.rs
  nearcore/src/lib.rs
Labels: P-low, S-automerge

#7379 core: avoid allocations when formatting crypto hash as base58
  core/primitives-core/src/hash.rs
Labels: P-low, S-automerge

#7404 fix log_sumary to use header_head instead of head for get_valiator_info
  chain/client/src/client_actor.rs
Labels: S-automerge

#7383 add config check that validators track all shards
  nearcore/src/config.rs
  pytest/lib/cluster.py
Labels: S-automerge

#7414 core: remove unused pretty_results
  core/primitives-core/src/logging.rs
Labels: P-low, S-automerge

#7409 core: get rid of unused from_base_buf function
  core/primitives-core/src/serialize.rs
Labels: P-low, S-automerge

#7324 Skip sending some of the tombstones in shardnet
  chain/client/Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#7318 fix: fix logical deadlock in the network
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
Labels: P-critical, S-automerge

#7415 Move routing table actor to its own arbiter
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7417 chain: rename RoutedMessageBody::Unused to _UnusedReceiptOutcomeResponse
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
Labels: P-low, S-automerge

#7378 store: introduce TrieAccess and make getter functions use it
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/update.rs
  integration-tests/src/tests/client/process_blocks.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/lib.rs
  tools/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#7419 refactor: minor sync cleanups
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
Labels: S-automerge

#7423 chain: get rid of Query’s query_id
  chain/client-primitives/src/types.rs
Labels: S-automerge

#7422 Add some debug metrics for PeerManager performance
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7413 fix: subtract estimator block overhead per block
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#7411 chain: cleanup ReceiptOutcomeRequest et al.
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  tools/chainsync-loadtest/src/network.rs
Labels: S-automerge

#7431 test: fix wrong_sync_info.py
  chain/client/src/adversarial.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/view_client.rs
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#7426 core: make Genesis::records and records_file private
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/genesis_validate.rs
  integration-tests/src/node/mod.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
  test-utils/testlib/src/runtime_utils.rs
  tools/state-viewer/src/state_dump.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#7430 Add metrics for view client
  chain/client/src/metrics.rs
  chain/client/src/view_client.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7427 refactor: introduce EpochManagerHandle
  chain/epoch_manager/src/lib.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
Labels: S-automerge

#7437 crypto: create key file as world-unreadable
  core/crypto/src/key_file.rs
Labels: S-automerge

#7433 nearcore: make sure validators track all shards
  nearcore/src/config.rs
Labels: S-automerge

#7432 core: avoid temporary memory allocation when parsing base58 CryptoHash
  core/primitives-core/src/hash.rs
Labels: P-low, S-automerge

#7446 store: remove DBCol::variant_name
  chain/chain/src/store_validator.rs
  core/store/src/columns.rs
  core/store/src/db/rocksdb.rs
Labels: S-automerge

#7421 fix: consider blocks being processed as known
  Cargo.lock
  chain/chain/src/chain.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  core/o11y/src/lib.rs
  core/o11y/src/tracing_capture.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
  test-utils/logger/src/lib.rs
Labels: S-automerge

#7442 store: fetch node in TrieIterator::descend_into_node
  core/store/src/trie/iterator.rs
Labels: S-automerge

#7463 chore: upgrade anyhow and thiserror
  Cargo.lock
Labels: S-automerge

#7461 store: make StoreOpener::open return Result rather than panicking
  chain/indexer/src/streamer/mod.rs
  chain/network/src/peer_manager/peer_store_test.rs
  core/store/benches/store_bench.rs
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/main.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/store-validator/src/main.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#7464 docs: add a few more points to naming style
  docs/style.md
Labels: S-automerge

#7453 Introducing ArcMutex
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/concurrency/arc_mutex.rs
  chain/network/src/concurrency/mod.rs
  chain/network/src/concurrency/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7454 renamed ConnectedPeer to Connection
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
Labels: S-automerge

#7469 made PeerManagerActor::new accept a clock
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/test_utils.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#7458 store: track max_open_files together with instances count
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/instance_tracker.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7460 store: add Mode::ReadWriteExisting
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
Labels: S-automerge

#7467 store: move database migration snapshot handling to near-store
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7465 store: propagate errors from migration functions
  Cargo.lock
  core/store/Cargo.toml
  core/store/src/migrations.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#7475 fix: default genesis minimum gas price
  chain/chain/src/types.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  nearcore/src/config.rs
Labels: S-automerge

#7479 fix(o11y): Add a missing `target` to a log message
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7480 feat: early prunning of tombstones of sharnet
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7444 test: Fix chunks_recovered_from_full_timeout_too_short.
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#7481 Remove the warning of receiving forwarded parts multiple times
  chain/chunks/src/lib.rs
Labels: S-automerge

#7457 moved some fields from PeerManagerActor to NetworkState
  chain/network/src/config.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/routing/tests/cache.rs
  chain/network/src/routing/tests/routing_table_view.rs
  chain/network/src/sink.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#7441 store: remove integer values from DBCol variants
  chain/client/src/rocksdb_metrics.rs
  core/store/src/columns.rs
  core/store/src/db/rocksdb.rs
Labels: S-automerge

#7483 store: introduce Database::get_with_rc_stripped method
  core/store/src/db.rs
  core/store/src/db/refcount.rs
  core/store/src/lib.rs
Labels: S-automerge

#7438 refactor: use EpochError::NotAValidaotor
  chain/chain-primitives/src/error.rs
  chain/epoch-manager/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7429 feat: improved shard cache
  CHANGELOG.md
  chain/chain/src/store.rs
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/metrics.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: T-storage

#7489 network: update to rand 0.7 and switch from PCG to xorshift
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/testonly/mod.rs
  deny.toml
Labels: S-automerge

#7492 pytest: fix sanity/rosetta.py test
  pytest/tests/sanity/rosetta.py
Labels: P-high, S-automerge

#7471 Overhaul CONTRIBUTING.md
  CONTRIBUTING.md
  docs/README.md
Labels: S-automerge

#7470 moved outgoing_peers inside connection::Pool
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7487 crypto: remove direct dependency on rand_core
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/randomness.rs
  core/crypto/src/signature.rs
  core/crypto/src/vrf.rs
Labels: S-automerge

#7491 core: avoid Vec↔Arc conversions when reading trie nodes
  core/primitives/src/challenge.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
Labels: S-automerge

#7490 primitives: keep data as Arc<[u8]> in StateRootNode
  chain/chain/src/test_utils.rs
  core/primitives/src/types.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7485 fix: estimator rust version
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#7486 store: add StoreConfig::migration_snapshot option; deprecated options in Config
  core/store/src/config.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7500 integration-tests: fix test_tx_not_enough_balance_must_return_error
  integration-tests/src/tests/nearcore/rpc_nodes.rs
Labels: P-high, S-automerge

#7435 chore: remove epoch_manager -> chain dep
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/view_client.rs
  chain/epoch-manager/Cargo.toml
  chain/epoch-manager/src/lib.rs
  core/primitives/src/types.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7472 migrated connection_spam_security_test to near_network
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/test_utils.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/types.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/peer_handshake.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock-node/src/lib.rs
Labels: S-automerge

#7504 removed UpdateEdge from PeerManagerActor
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
Labels: S-automerge

#7502 feat(estimator): compact RocksDB in testbed setup
  core/store/src/db.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/testdb.rs
  core/store/src/lib.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#7482 store: add ColdDatabase Database interface
  Cargo.lock
  core/primitives-core/src/hash.rs
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/db/colddb.rs
Labels: S-automerge

#7510 refactor: cleanup contract runtime entry point
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7513 store: refactor flat_state.rs to reduce amount of annotations
  core/store/src/flat_state.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7459 chain: pass the raw Database when creating PeerManagerActor
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/peer_store_test.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/routing/tests/cache.rs
  chain/network/src/routing/tests/cache_edges.rs
  chain/network/src/routing/tests/routing_table_view.rs
  chain/network/src/store/mod.rs
  chain/network/src/store/schema/mod.rs
  chain/network/src/test_utils.rs
  core/store/src/db/colddb.rs
  core/store/src/db/testdb.rs
  core/store/src/test_utils.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#7501 Improve the logic of handling old protocol versions
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/client/src/test_utils.rs
  core/primitives/Cargo.toml
  core/primitives/src/test_utils.rs
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7499 Simplify simple_nightshade shard layout config
  chain/epoch-manager/src/test_utils.rs
  chain/epoch-manager/src/tests/mod.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/shard_layout.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  nearcore/src/shard_tracker.rs
  pytest/tests/sanity/upgradable.py
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge
