Repository near/nearcore, pull requests merged in 2022-05, with the labels that each got.

#6730 nearcore: add IS_ARCHIVE key to the database
  core/store/src/db.rs
  nearcore/src/lib.rs
Labels: S-automerge

#6672 Implemented protobuf equivalent of network_protocol.rs
  Cargo.lock
  chain/client/src/test_utils.rs
  chain/network/Cargo.toml
  chain/network/build.rs
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/utils.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/routing/ibf_peer_set.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/tests/actix.rs
  chain/network/src/tests/cache.rs
  chain/network/src/tests/data.rs
  chain/network/src/tests/mod.rs
  chain/network/src/tests/network_protocol.rs
  chain/network/src/tests/peer_actor.rs
  chain/network/src/tests/peer_communication.rs
  chain/network/src/tests/util.rs
  chain/network/src/types.rs
  deny.toml
Labels: S-automerge

#6733 Export structured traces data via OpenTelemetry to Jaeger
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#6739 test: check sanity of nondeterministic costs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nondeterministic.snap
Labels: S-automerge

#6735 refactor how incoming_receipts are handled in process_block
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
Labels: S-automerge

#6741 network: replace strum::AsStrRef derives with strum::IntoStaticStr
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#6743 network: prefer strum::IntoStatiStr than strum::AsStaticStr
  chain/network/src/tests/peer_actor.rs
  chain/network/src/types.rs
Labels: S-automerge

#6750 Separate collecting rocksdb statistics and re-exporting them to prometheus
  chain/client/src/client_actor.rs
  core/chain-configs/src/client_config.rs
  core/store/src/lib.rs
  nearcore/src/config.rs
Labels: S-automerge

#6744 move the saving of block_extra to after apply_chunks
  chain/chain/src/chain.rs
Labels: S-automerge

#6753 added a metric monitoring Proto/Borsh encoding for peer connections
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/types.rs
Labels: S-automerge

#6754 Add function preprocess_block
  chain/chain/src/chain.rs
Labels: S-automerge

#6762 client: don’t update validators produced counters when syncing
  chain/client/src/client_actor.rs
Labels: S-automerge

#6732 Adding more debug information to the pages
  chain/client/src/client_actor.rs
  chain/jsonrpc/res/epoch_info.html
  chain/jsonrpc/res/last_blocks.html
  chain/jsonrpc/res/sync_info.html
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/types.rs
  core/primitives/src/views.rs
Labels: S-automerge

#6766 Reduce verbosity of transaction receiving/forwarding.
  chain/client/src/client.rs
Labels: S-automerge

#6544 bugfix: fix m1 sandbox
  runtime/near-vm-runner/src/cache.rs
Labels: S-automerge

#6760 fix: verify that challenges root is empty
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/challenges.rs
Labels: S-automerge

#6767 fixing a typo in debug HTML
  chain/jsonrpc/res/sync_info.html
Labels: S-automerge

#6758 added ignoring unparseable messages
  pytest/lib/peer.py
  pytest/lib/proxy.py
Labels: S-automerge

#6769 store: improve error message when setting NOFILE limit
  core/store/src/db.rs
Labels: S-automerge

#6759 move self.chain_store_update.remove_state_changes_for_split_states out of apply_chunks_preprocessing
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: S-automerge

#6740 fix(params-warehouse): Use specified metric
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/db.rs
Labels: S-automerge

#6776 create Chain::preprocess_block
  chain/chain/src/chain.rs
Labels: S-automerge

#6770 CHANGELOG: borsh -> protobuf PR
  CHANGELOG.md
Labels: S-automerge

#6779 Option to disable colored log output.
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  neard/src/cli.rs
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6775 move mark_block_as_challenged outside of preprocess_block
  chain/chain/src/chain.rs
Labels: S-automerge

#6693 feat: Flat and differential runtime config files
  Cargo.lock
  core/primitives-core/src/lib.rs
  core/primitives-core/src/parameter.rs
  core/primitives/Cargo.toml
  core/primitives/res/README.md
  core/primitives/res/runtime_configs/42.txt
  core/primitives/res/runtime_configs/48.txt
  core/primitives/res/runtime_configs/49.txt
  core/primitives/res/runtime_configs/50.txt
  core/primitives/res/runtime_configs/52.txt
  core/primitives/res/runtime_configs/53.txt
  core/primitives/res/runtime_configs/legacy_configs/29.json
  core/primitives/res/runtime_configs/legacy_configs/29_testnet.json
  core/primitives/res/runtime_configs/legacy_configs/42.json
  core/primitives/res/runtime_configs/legacy_configs/48.json
  core/primitives/res/runtime_configs/legacy_configs/49.json
  core/primitives/res/runtime_configs/legacy_configs/50.json
  core/primitives/res/runtime_configs/legacy_configs/52.json
  core/primitives/res/runtime_configs/legacy_configs/53.json
  core/primitives/res/runtime_configs/parameters.txt
  core/primitives/res/runtime_configs/parameters_testnet.txt
  core/primitives/src/runtime/config.rs
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/mod.rs
  core/primitives/src/runtime/parameter_table.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6725 test: work-around flaky tests
  integration-tests/src/tests/standard_cases/mod.rs
Labels: S-automerge

#6774 refactor: vendor pwasm_utils
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/instrument.rs
  runtime/near-vm-runner/src/instrument/gas/mod.rs
  runtime/near-vm-runner/src/instrument/gas/validation.rs
  runtime/near-vm-runner/src/instrument/rules.rs
  runtime/near-vm-runner/src/instrument/stack_height/max_height.rs
  runtime/near-vm-runner/src/instrument/stack_height/mod.rs
  runtime/near-vm-runner/src/instrument/stack_height/thunk.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/prepare.rs
Labels: S-automerge

#6783 chain: update build_chain test to use insta
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/tests/simple_chain.rs
Labels: S-automerge

#6780 test: Snapshot tests for estimator warehouse
  Cargo.lock
  runtime/runtime-params-estimator/estimator-warehouse/Cargo.toml
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/db.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/import.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-2.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-3.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-4.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__tests__stats.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/zulip.rs
Labels: S-automerge

#6784 test: Remove old runtime config tests
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/res/README.md
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
Labels: S-automerge

#6786 chore: Delete obsolete estimator scripts
  runtime/runtime-params-estimator/emu-cost/README.md
  runtime/runtime-params-estimator/emu-cost/ci.sh
  runtime/runtime-params-estimator/emu-cost/compare_costs.py
  runtime/runtime-params-estimator/emu-cost/safety_mutiplier.py
Labels: S-automerge

#6777 Consistently use spans to instrument important node functions
  chain/chain/src/chain.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/network/src/peer/peer_actor.rs
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  docs/style.md
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
  tools/mock_node/src/setup.rs
  tools/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#6415 added panic=abort to the whole workspace
  Cargo.toml
Labels: S-automerge

#6755 bumped protocol version (protobuf support)
  chain/chain/src/tests/simple_chain.rs
  core/primitives/src/version.rs
  nearcore/res/genesis_config.json
Labels: S-automerge

#6773 chain-primitives: use StorageError kind and avoid string allocation
  chain/chain-primitives/src/error.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  nearcore/src/runtime/mod.rs
Labels: P-low, S-automerge

#6795 fix(network): PeerStore's cache gets out of sync
  chain/network/src/peer_manager/peer_store.rs
Labels: S-automerge

#6799 Update strum dependency to 0.24
  Cargo.lock
  chain/chain/Cargo.toml
  chain/client-primitives/Cargo.toml
  chain/client/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/store/Cargo.toml
  deny.toml
  nearcore/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
Labels: S-automerge

#6800 Observability: Instrument syncing
  chain/chain/src/chain.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
Labels: S-automerge

#6794 feat: Improve add fn key estimation
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#6803 fix: make sure that `cargo test` can be killed with ctrl+c
  test-utils/actix-test-utils/src/lib.rs
Labels: S-automerge

#6804 refactor: simplify chain::Error
  Cargo.lock
  chain/chain-primitives/Cargo.toml
  chain/chain-primitives/src/error.rs
  chain/chain-primitives/src/lib.rs
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/simple_chain.rs
  chain/chain/src/validate.rs
  chain/chunks/src/lib.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/view_client.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6806 refactor: don't type-erase IO errors
  Cargo.lock
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/view_client.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6807 chain: refactor AdversarialControls to reduce conditional compilation
  chain/client/src/adversarial.rs
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
  tools/mock_node/src/setup.rs
Labels: P-low, S-automerge

#6809 chain: normalise number formatting in status line
  chain/client/src/info.rs
Labels: P-low, S-automerge

#6812 fix: don't show 0 -> 0 changes in continuous estimation
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-4.snap
Labels: S-automerge

#6796 Send batches of spans asynchronously for better performance when opentelemetry feature is enabled.
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  neard/Cargo.toml
  neard/src/cli.rs
  tools/chainsync-loadtest/Cargo.toml
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/Cargo.toml
  tools/indexer/example/src/main.rs
  tools/restaked/Cargo.toml
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/Cargo.toml
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6817 store: remove ‘pub’ from StoreConfig constants
  core/store/src/config.rs
Labels: P-low, S-automerge

#6814 test: add imports to runtime fuzzing setup
  Cargo.lock
  runtime/near-vm-runner/fuzz/Cargo.toml
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
Labels: S-automerge

#6821 refactor: use built-in option to strip compiled WASM
  runtime/runtime-params-estimator/test-contract/Cargo.toml
  runtime/runtime-params-estimator/test-contract/build.sh
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: S-automerge

#6694 chore: upgrade `actix-web` to `v4.0.1`
  Cargo.lock
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/client/Cargo.toml
  chain/jsonrpc/src/lib.rs
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/models.rs
  chain/telemetry/Cargo.toml
  core/chain-configs/Cargo.toml
  core/crypto/Cargo.toml
  core/crypto/src/signature.rs
  core/crypto/src/test_utils.rs
  core/primitives-core/Cargo.toml
  deny.toml
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  tools/mock_node/Cargo.toml
  tools/mock_node/benches/sync.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#6832 doc: describe the required toolchain version
  CONTRIBUTING.md
Labels: S-automerge

#6833 feat: expose logs and receipt metadata from VMLogic
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#6830 chore: bump version to 0.13.0
  Cargo.toml
Labels: S-automerge

#6836 chore: update `awc` to stable
  Cargo.lock
  chain/jsonrpc/client/Cargo.toml
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  chain/telemetry/Cargo.toml
  nearcore/Cargo.toml
Labels: S-automerge

#6831 store: introduce RocksDB::cf_handle method
  core/store/src/db.rs
Labels: S-automerge

#6835 test: use new alt_bn costs in test config
  core/primitives-core/src/config.rs
Labels: S-automerge

#6810 neard: support no-value --verbose flag
  core/o11y/src/lib.rs
  neard/src/cli.rs
Labels: P-low, S-automerge

#6829 store: prefer enum_map::EnumMap to strum’s count and iterator
  Cargo.lock
  core/store/Cargo.toml
  core/store/src/columns.rs
  core/store/src/db.rs
Labels: S-automerge

#6827 Rollback #6713 due to possibility of dropping transactions received right before an epoch boundary.
  chain/client/src/client.rs
Labels: S-automerge

#6802 refactor: mark ShardsManager columns as insert-only
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#6846 rosetta: fix after actix update
  chain/rosetta-rpc/src/lib.rs
Labels: A-testing, P-high, S-automerge

#6847 test: fix non-determinisit tests
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
Labels: S-automerge

#6851 chore(jsonrpc): cleanup adversarial-primitives
  chain/jsonrpc-adversarial-primitives/Cargo.toml
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc/Cargo.toml
Labels: S-automerge

#6852 refactor: use modern way to strip symbols from WASM
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/contract-for-fuzzing-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
Labels: S-automerge

#6853 chore(jsonrpc): move request parsing logic to server
  Cargo.lock
  chain/jsonrpc-adversarial-primitives/Cargo.toml
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc-primitives/src/lib.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/changes.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/light_client.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/sandbox.rs
  chain/jsonrpc-primitives/src/types/transactions.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  chain/jsonrpc-primitives/src/utils.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/parser.rs
Labels: S-automerge

#6864 fix: don't type convert errors to strings unnecessary
  chain/chain/src/chain.rs
Labels: S-automerge

#6863 test: more helpful assertion messages
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
Labels: S-automerge

#6866 refactor: make blocks and headers cheaply clonable
  core/primitives/src/block.rs
  core/primitives/src/block_header.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  test-utils/testlib/src/process_blocks.rs
Labels: S-automerge

#6867 fix: remove test that fails locally
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#6844 hack: restore JSON API compatibility
  core/primitives-core/src/config.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
Labels: S-automerge

#6808 neard: improve localnet command arguments
  neard/src/cli.rs
Labels: P-low, S-automerge

#6840 Only save partial chunk if chunk is completed
  chain/chunks/src/lib.rs
Labels: S-automerge

#6861 Prometheus metrics for on-chain values
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
  core/metrics/src/lib.rs
Labels: S-automerge

#6858 store: introduce StoreOpener; get rid of StoreConfig::read_only
  Cargo.lock
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/mod.rs
  chain/network/src/peer_manager/peer_store.rs
  core/store/benches/store_bench.rs
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  genesis-tools/genesis-populate/src/lib.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/benches/store.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  neard/src/cli.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/store-validator/src/main.rs
  tools/mock_node/src/setup.rs
  tools/restored-receipts-verifier/src/main.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/rocksdb_stats.rs
Labels: S-automerge

#6862 feat: log information when hitting a deserialization error
  runtime/near-vm-runner/src/prepare.rs
Labels: S-automerge

#6880 fix: reduce spammy logging
  chain/client/src/client_actor.rs
Labels: S-automerge

#6854 Revert "fix shard tracking issue for localnet"
  nearcore/src/config.rs
Labels: A-testing, S-automerge, A-python-test

#6856 core: get rid of SharedChunkHeader::prev_block_hash_ref
  chain/chain/src/chain.rs
  chain/chain/src/validate.rs
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/catching_up.rs
  chain/network-primitives/src/network_protocol/mod.rs
  core/primitives/src/sharding.rs
Labels: P-low, S-automerge

#6877 refactor: use ?
  chain/chain/src/chain.rs
Labels: S-automerge

#6883 Run mocknet nodes on port 3030
  pytest/lib/mocknet.py
Labels: S-automerge

#6885 Fix local build on mac
  core/crypto/src/key_file.rs
Labels: S-automerge

#6828 fix: race in NetworkRecepient
  Cargo.lock
  chain/network/Cargo.toml
  chain/network/src/test_utils.rs
Labels: S-automerge

#6841 mark DbCol::PartialChunk as insert only
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#6870 increased the timeout of the network integration tests
  Cargo.lock
  chain/client/src/test_utils.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/graph.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/multiset.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#6886 fix: platform-compatibility bug in key_file
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/key_file.rs
Labels: S-automerge

#6842 store: use enum_map::EnumMap in StoreValidator
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  core/store/src/columns.rs
  core/store/src/db.rs
Labels: S-automerge

#6845 integration-tests: use single temp directory in NodeCluster
  integration-tests/src/tests/nearcore/node_cluster.rs
  integration-tests/src/tests/nearcore/rpc_error_structs.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/nearcore/run_nodes.rs
  integration-tests/src/tests/nearcore/track_shards.rs
Labels: A-testing, S-automerge

#6890 move some of preprocess_block from ChainUpdate to Chain
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/challenges.rs
Labels: S-automerge

#6893 refactor: remove redundant clones
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/tests/simple_chain.rs
  chain/chain/src/tests/sync_chain.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/chunks_management.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/view_client.rs
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/epoch_manager/src/tests/random_epochs.rs
  chain/jsonrpc-primitives/src/errors.rs
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/tests/network_protocol.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  core/o11y/src/lib.rs
  core/store/src/trie/trie_tests.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/runtime/deployment.rs
  nearcore/benches/store.rs
  nearcore/src/config.rs
  nearcore/src/runtime/mod.rs
  nearcore/tests/economics.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/state_viewer/mod.rs
  test-utils/runtime-tester/src/fuzzing.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/runtime-tester/src/scenario_builder.rs
  tools/chainsync-loadtest/src/main.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock_node/src/lib.rs
  tools/mock_node/src/setup.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#6876 modify NetworkMetrics to use a hashmap to store metrics
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/test_utils.rs
  integration-tests/src/tests/network/peer_manager.rs
Labels: S-automerge

#6901 fix(pytests): fix gc_after_sync.py failure
  pytest/lib/cluster.py
  pytest/tests/sanity/gc_after_sync.py
Labels: S-automerge

#6889 refactor: make some of ChainStore methods &
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  integration-tests/src/genesis_helpers.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6874 Configure opentelemetry data export as a command-line flag
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/log_config_watcher.rs
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6909 Update to wasmer 2.4.0
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#6457 feat(rosetta): only return info about final blocks and transactions
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/utils.rs
Labels: T-integrations

#6892 test: verify operation of host function `used_gas`
  integration-tests/src/tests/runtime/sanity_checks.rs
Labels: S-automerge

#6859 state viewer changes: show full hashes, print number of state changes
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6916 Debug pages changes: separate endpoints, new page with sync
  Cargo.lock
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc/res/debug.html
  chain/jsonrpc/res/epoch_info.html
  chain/jsonrpc/res/last_blocks.html
  chain/jsonrpc/res/sync.html
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/types.rs
  core/primitives/src/views.rs
Labels: S-automerge

#6902 chore(jsonrpc): move `nearcore` type conversions to server
  Cargo.lock
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/errors.rs
  chain/jsonrpc-primitives/src/lib.rs
  chain/jsonrpc-primitives/src/metrics.rs
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/changes.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/config.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/light_client.rs
  chain/jsonrpc-primitives/src/types/network_info.rs
  chain/jsonrpc-primitives/src/types/query.rs
  chain/jsonrpc-primitives/src/types/receipts.rs
  chain/jsonrpc-primitives/src/types/sandbox.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc-primitives/src/types/transactions.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/errors.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
  integration-tests/src/tests/test_errors.rs
Labels: S-automerge

#6913 Move `--color` into `o11y::Options`
  core/o11y/src/lib.rs
  neard/src/cli.rs
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6919 refactor: simplify gas_and_error_match
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#6897 feat: more idiomatic CLI interface for mock network
  Cargo.lock
  tools/mock_node/Cargo.toml
  tools/mock_node/README.md
  tools/mock_node/benches/README.md
  tools/mock_node/benches/sync.rs
  tools/mock_node/src/lib.rs
  tools/mock_node/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#6917 chore(jsonrpc): split the `parser` and `errors` module
  chain/jsonrpc/src/api/adversarial.rs
  chain/jsonrpc/src/api/blocks.rs
  chain/jsonrpc/src/api/changes.rs
  chain/jsonrpc/src/api/chunks.rs
  chain/jsonrpc/src/api/config.rs
  chain/jsonrpc/src/api/gas_price.rs
  chain/jsonrpc/src/api/light_client.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/api/network_info.rs
  chain/jsonrpc/src/api/query.rs
  chain/jsonrpc/src/api/receipts.rs
  chain/jsonrpc/src/api/sandbox.rs
  chain/jsonrpc/src/api/status.rs
  chain/jsonrpc/src/api/transactions.rs
  chain/jsonrpc/src/api/validator.rs
  chain/jsonrpc/src/errors.rs
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/parser.rs
Labels: S-automerge

#6926 feat: reduce spammy gc logs
  chain/client/src/client.rs
Labels: S-automerge

#6928 use anyhow rather than unwrap
  tools/mock_node/src/main.rs
Labels: S-automerge

#6891 state_dump: convert StateDump::from_dir to use use StoreOpener::home
  genesis-tools/genesis-populate/src/state_dump.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#6923 test: fix non-hermetic test
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic_nightly.snap
  runtime/near-test-contracts/src/lib.rs
Labels: S-automerge

#6905 nearcore: use StoreOpener in database migration functions
  core/store/src/config.rs
  core/store/src/migrations.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
Labels: S-automerge
