Repository near/nearcore, pull requests merged in 2022-04, with the labels that each got.

#6211 feat(sandbox): fast forward timestamp and epoch height
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/query_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/types.rs
  core/primitives/benches/serialization.rs
  core/primitives/src/block.rs
  core/primitives/src/test_utils.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/sandbox.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  nightly/sandbox.txt
  pytest/tests/sandbox/fast_forward.py
  pytest/tests/sandbox/fast_forward_epoch_boundary.py
Labels: S-automerge

#6519 blacklist: use derive instead of impl
  chain/network-primitives/src/blacklist.rs
Labels: P-low, S-automerge

#6139 Alt-bn128 audit fixes and tests
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge, X-mm-near-skip

#6518 core: small KeyForStateChanges refactor
  chain/chain/src/store.rs
  core/primitives/src/trie_key.rs
  core/store/src/trie/shard_tries.rs
Labels: P-low, S-automerge

#6468 refactor: Receipt handling to be done in VM logic
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-logic/src/receipt_manager.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/promises.rs
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/ext.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#6526 Switch __count field in Enum to strum
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
Labels: S-automerge

#6528 feat: more compact output for the estimator
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#6532 jsonrpc: drop flatten specification for `RpcGasPriceRequest`
  chain/jsonrpc-primitives/src/types/gas_price.rs
Labels: S-automerge

#6534 fix: protocol_feature handling for FunctionCallWeight
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/runtime/Cargo.toml
Labels: S-automerge

#6533 refactor: remove needless closure
  runtime/near-vm-logic/src/tests/gas_counter.rs
Labels: S-automerge

#6439 chain: gc partial chunks on archival nodes
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chunks/src/chunk_cache.rs
  chain/client/src/client.rs
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/tests/sanity/block_sync_archival.py
Labels: S-automerge

#6536 fix!: adjust gas distribution formula for NEP264
  runtime/near-vm-logic/src/receipt_manager.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
Labels: S-automerge

#6523 add metrics for how long a block stay in the orphan pool and the miss…
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/blocks_delay_tracker.rs
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/metrics.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/chunks_delay_tracker.rs
  chain/client/src/client.rs
  chain/client/src/lib.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#6540 nightly: disable broken ‘start_from_genesis.py overtake doomslug_off’ test
  nightly/pytest-adversarial.txt
Labels: P-critical, S-automerge

#6477 neard: recompress_storage: clean out unnecessary columns
  nearcore/src/lib.rs
  neard/src/cli.rs
Labels: S-automerge

#6545 debug_scripts: enforce Python style
  debug_scripts/request_chain_info.py
  scripts/formatting
Labels: S-automerge

#6546 refactor: minor cleanups to EpochManager
  chain/epoch_manager/src/lib.rs
Labels: S-automerge

#6527 Update tail bug fix
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/gc.rs
  core/store/src/test_utils.rs
Labels: S-automerge

#6496 fix(chain): don't store to ColTrieChanges in archival nodes
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/gc.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  core/store/src/trie/shard_tries.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/mock_network/mod.rs
  integration-tests/src/mock_network/setup.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/benches/store.rs
  nearcore/src/migrations.rs
  tools/restored-receipts-verifier/src/main.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6543 Add gc tail metrics
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
Labels: S-automerge

#6554 refactor: compress locking of EpochManager
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6550 fix: remove unnecessary clones in receipt generation
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#6514 create epoch info debug page to show validators
  chain/client/src/client_actor.rs
  chain/jsonrpc/res/debug.html
  chain/jsonrpc/res/epoch_info.html
  chain/jsonrpc/src/lib.rs
  core/primitives/src/views.rs
Labels: S-automerge

#6565 recompress_storage: fix handling of rc columns
  nearcore/src/lib.rs
Labels: S-automerge

#6568 feat(shardConfig): remove `impl From<EpochConfig> for ShardConfig`
  chain/epoch_manager/src/lib.rs
  core/primitives/src/epoch_manager.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6570 chain: remove failing debug asserts
  chain/chain/src/blocks_delay_tracker.rs
Labels: P-high, S-automerge

#6549 perf: avoid locks in epoch manager
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/tests/random_epochs.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
  utils/near-cache/src/lib.rs
Labels: S-automerge

#6559 refactor: use existing Result alias in receipt_manager
  runtime/near-vm-logic/src/receipt_manager.rs
Labels: S-automerge

#6557 neard: enable target:"recompress" info logs by default
  core/o11y/src/lib.rs
Labels: S-automerge

#6573 chore: bump `actix` to `v0.12.0` stable
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/client-primitives/Cargo.toml
  chain/client/Cargo.toml
  chain/indexer/Cargo.toml
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/rosetta-rpc/Cargo.toml
  chain/telemetry/Cargo.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
  tools/chainsync-loadtest/Cargo.toml
  tools/indexer/example/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/framed_write.rs
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#6576 chain: improve EpochInfoAggregator documentation
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/types.rs
Labels: S-automerge

#6582 feat: separate counter for chunk nodes cache
  core/primitives/src/types.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/runtime/src/ext.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#6585 Increase the secondary stack cleck limit
  core/primitives-core/src/config.rs
  core/primitives/res/runtime_configs/53.json
  core/primitives/src/runtime/config_store.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#6581 refactor: DBTransaction
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/src/mock_network/setup.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#6574 refactor: simplify test module structure
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/tests/mod.rs
Labels: S-automerge

#6578 add blocks with missing chunks on chain page
  chain/chain/src/missing_chunks.rs
  chain/client/src/client_actor.rs
  chain/jsonrpc/res/chain_info.html
  core/primitives/src/views.rs
Labels: S-automerge

#6473 Make state-viewer optionally open the RocksDB in readwrite mode instead of readonly only
  neard/src/cli.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#6591 pytest: don’t set rpc.metrics_addr
  pytest/lib/cluster.py
Labels: P-low, S-automerge

#6588 feat: add read_cached_trie_node cost
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  core/primitives/Cargo.toml
  nearcore/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#6597 nightly: increase timeout for contracts/gibberish.py test
  nightly/pytest-contracts.txt
Labels: S-automerge

#6592 chain: make GC_FORK_CLEAN_STEP into configuration option
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/tests/gc.rs
  chain/client/src/client.rs
  core/chain-configs/src/client_config.rs
  core/chain-configs/src/lib.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/config.rs
  testdata/example-config-gc.json
  testdata/example-config-no-gc.json
Labels: S-automerge

#6587 feat: rename `contract_compile` gas parameter
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  core/primitives/res/runtime_configs/29.json
  core/primitives/res/runtime_configs/29_testnet.json
  core/primitives/res/runtime_configs/42.json
  core/primitives/res/runtime_configs/48.json
  core/primitives/res/runtime_configs/49.json
  core/primitives/res/runtime_configs/50.json
  core/primitives/res/runtime_configs/52.json
  core/primitives/res/runtime_configs/53.json
  core/primitives/src/runtime/config_store.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/res/mainnet_genesis.json
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
Labels: S-automerge

#6602 chore: upgrade actix to 0.13.0
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chunks/Cargo.toml
  chain/client-primitives/Cargo.toml
  chain/client/Cargo.toml
  chain/indexer/Cargo.toml
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/rosetta-rpc/Cargo.toml
  chain/telemetry/Cargo.toml
  deny.toml
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
  tools/chainsync-loadtest/Cargo.toml
  tools/indexer/example/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
  utils/near-rate-limiter/Cargo.toml
Labels: S-automerge

#6603 chain: initialise block and header head height metrics at startup
  chain/chain/src/chain.rs
Labels: S-automerge

#6593 Log RocksDB instance counter to `info`
  core/store/src/db.rs
Labels: S-automerge

#6598 Changelog: NEP205
  CHANGELOG.md
Labels: S-automerge

#6566 possible fix for the 'SyncRoutingTable' overload
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#6612 nearcore: take max_open_files into consideration in recompress_storage
  nearcore/src/lib.rs
Labels: S-automerge

#6608 Fixed network integration tests which were succeeding even though nodes were crashing in the middle.
  Cargo.lock
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  chain/network/src/test_utils.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/network/ban_peers.rs
  integration-tests/src/tests/network/churn_attack.rs
  integration-tests/src/tests/network/full_network.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#6610 db: store error message directly in DBError
  core/store/src/db.rs
Labels: S-automerge

#6450 feat: activate chunk nodes cache on nightly
  chain/chain/src/tests/simple_chain.rs
  core/primitives/res/runtime_configs/128.json
  core/primitives/src/test_utils.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  core/store/src/trie/trie_storage.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  integration-tests/src/user/mod.rs
  integration-tests/src/user/rpc_user.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
Labels: S-automerge

#6505 refactor: cleanup nightly alt_bn128 API
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/array_utils.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/alt_bn128.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#6609 chore: drop needless nesting in test modules
  integration-tests/src/tests/standard_cases/rpc.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  integration-tests/src/tests/test_simple.rs
  integration-tests/src/tests/test_tps_regression.rs
  nightly/expensive.txt
Labels: S-automerge

#6619 neard: prefer kebab-case for subcommand names
  CHANGELOG.md
  neard/src/cli.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#6564 runtime: Stabilise NEP264
  CHANGELOG.md
  core/primitives-core/Cargo.toml
  core/primitives-core/src/types.rs
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/receipt_manager.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
Labels: S-automerge

#6579 implemented node whitelist
  Cargo.lock
  chain/network-primitives/src/blacklist.rs
  chain/network-primitives/src/config.rs
  chain/network/Cargo.toml
  chain/network/src/peer_manager/peer_manager_actor.rs
  integration-tests/src/tests/network/full_network.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/config.rs
Labels: S-automerge

#6620 refactor: cleanup feature handling in test contract
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  pytest/lib/utils.py
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
Labels: S-automerge

#6601 pytest: add end-to-end recompress-storage sanity test
  nightly/pytest-sanity.txt
  pytest/tests/sanity/__init__.py
  pytest/tests/sanity/recompress_storage.py
  pytest/tests/sanity/rpc_tx_status.py
Labels: A-testing, S-automerge

#6615 db: don’t populate ColPartialChunks during 9→10 database version migration
  core/store/src/migrations.rs
  nearcore/src/lib.rs
Labels: P-low, S-automerge

#6589 CHANGELOG: add 1.24 and 1.25 changelog; update date formatting
  CHANGELOG.md
Labels: S-automerge

#6529 feat: update cost model for alt_bn128
  core/primitives-core/src/config.rs
  core/primitives/res/runtime_configs/128.json
  core/primitives/res/runtime_configs/29.json
  core/primitives/res/runtime_configs/29_testnet.json
  core/primitives/res/runtime_configs/42.json
  core/primitives/res/runtime_configs/48.json
  core/primitives/res/runtime_configs/49.json
  core/primitives/res/runtime_configs/50.json
  core/primitives/res/runtime_configs/52.json
  core/primitives/res/runtime_configs/53.json
  core/primitives/src/runtime/config_store.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: S-automerge

#6567 add info print for GC and block production at epoch starts
  chain/chain/src/doomslug.rs
  chain/chain/src/tests/doomslug.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
Labels: S-automerge

#6625 refactor: drop unneded lifetimes
  core/store/src/trie/split_state.rs
Labels: S-automerge

#6626 start-mock-network: limit the number of worker threads
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/src/mock_network/setup.rs
Labels: S-automerge

#6624 perf: avoid needless clone
  core/store/src/lib.rs
Labels: S-automerge

#6629 refactor: Simplify estimator debug flags
  runtime/runtime-params-estimator/src/config.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6613 store: change max_open_files to u32
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: P-low, S-automerge

#6606 Changelog: Safe DB migrations
  CHANGELOG.md
Labels: S-automerge

#6633 Upgrade wasmer-near to 2.2.2
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
Labels: S-automerge

#6611 Complex test for PeerManager, and adding broadcasting metrics
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/test_utils.rs
  core/metrics/src/lib.rs
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/peer_manager.rs
Labels: S-automerge

#6637 fix: update changelog
  CHANGELOG.md
Labels: S-automerge

#6644 Fix a flaky test by adding a retry for requesting blocks
  integration-tests/src/tests/nearcore/rpc_nodes.rs
Labels: S-automerge

#6641 Change gc test to not depend on the default value.
  chain/chain/src/tests/gc.rs
Labels: S-automerge

#6643 Add debug information to gc_sync_after_sync.py
  pytest/tests/sanity/gc_sync_after_sync.py
Labels: S-automerge

#6627 test: don't spam to console when testing download file
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/src/tests/mod.rs
  integration-tests/src/tests/test_download_file.rs
  nearcore/src/config.rs
  nearcore/src/download_file.rs
  nearcore/src/lib.rs
Labels: C-housekeeping, P-low, S-automerge

#6651 integration-tests: fix lower_storage_key_limit_test protocol upgrading
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6650 integration-tests: fix verify_contract_limits_upgrade() protocol upgrading
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6655 metrics: refactor NetworkMetrics and remove bunch of dead functions
  Cargo.lock
  chain/network/src/stats/metrics.rs
  core/metrics/Cargo.toml
  core/metrics/src/lib.rs
Labels: P-low, S-automerge

#6652 nearcore: propagate errors when applying migrations
  nearcore/src/lib.rs
Labels: S-automerge

#6630 Enable `info` logs of `db` target by default
  core/o11y/src/lib.rs
Labels: S-automerge

#6648 store: propagate error from ensure_max_open_files_limit i/o panicking
  core/store/src/db.rs
Labels: S-automerge

#6660 pytest: move logging from wait_for_blocks to poll_blocks
  pytest/lib/utils.py
Labels: S-automerge

#6662 fuzz: bump near-vm-runner fuzzer to 3G max RAM
  nightly/fuzz.toml
Labels: S-automerge

#6661 network: remove near_<msg-type>_{total,bytes} metrics
  CHANGELOG.md
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#6654 Prefer lazy_static_include_bytes in tests
  Cargo.lock
  nearcore/res/example-config-gc.json
  nearcore/res/example-config-no-gc.json
  nearcore/src/config.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/script.rs
Labels: P-low, S-automerge

#6664 store: propagate errors when reading db version rather than panicking
  core/store/src/db.rs
  core/store/src/migrations.rs
  nearcore/src/lib.rs
Labels: P-low, S-automerge

#6663 fuzz: adjust branches to fuzz 1.26 and 1.25
  nightly/fuzz.toml
Labels: S-automerge

#6638 rocksdb_metrics: prefer char pattern when replacing characters
  chain/client/src/rocksdb_metrics.rs
Labels: P-low, S-automerge

#6658 Allow localnet init to create accounts for fixed shards
  integration-tests/src/node/mod.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  pytest/tests/loadtest/loadtest.py
  pytest/tests/loadtest/setup.py
Labels: S-automerge

#6586 refactor: introduce log_assert to be used instead of missused debug_asserts
  Cargo.lock
  core/o11y/src/lib.rs
  core/store/Cargo.toml
  core/store/src/lib.rs
Labels: S-automerge

#6671 feat: add print_backtrace function for easier debugging
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
Labels: S-automerge

#6337 Redirect to the 0-copy wasmer branch
  Cargo.lock
  deny.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#6164 test artifact stability with more contracts
  Cargo.lock
  deny.toml
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/src/lib.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/fuzz/Cargo.toml
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#6673 refactor: Clean up VMResult::NotRun
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/near-vm-runner-standalone/src/script.rs
  runtime/near-vm-runner/src/preload.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#6667 store: remove old migration code
  chain/epoch_manager/src/lib.rs
  core/store/src/db.rs
  core/store/src/db/v6_to_v7.rs
  core/store/src/migrations.rs
  core/store/src/migrations/v6_to_v7.rs
  core/store/src/migrations/v8_to_v9.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/trie_tests.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#6674 feat: introduce StoreUpdate::set_raw escape hatch
  chain/chain/src/store_validator.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  nearcore/src/lib.rs
Labels: S-automerge

#6675 refactor: simplify StoreUpdate::merge implementation
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#6676 test_gc_fork_tail: make test not depend on config values
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6680 client: introduce `near_build_info` metric with node’s release info
  CHANGELOG.md
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#6558 chore: Update estimator docker image to Rust 1.60
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6687 client: fix docstring of metrics::export_version
  chain/client/src/metrics.rs
Labels: P-low, S-automerge

#6688 Fix a flaky test `test_query_rpc_account_view_account_doesnt_exist_must_return_error`
  integration-tests/src/tests/nearcore/rpc_nodes.rs
Labels: S-automerge

#6685 fix(contiunous estimation): Icount comparison
  runtime/runtime-params-estimator/estimator-warehouse/src/db.rs
Labels: S-automerge

#6683 fix: 'chunk_id' is not defined in request_chain_info.py
  debug_scripts/request_chain_info.py
Labels: S-automerge

#6666 Allow changing logging at runtime
  CHANGELOG.md
  Cargo.lock
  chain/jsonrpc/Cargo.toml
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/log_config_watcher.rs
  neard/src/main.rs
  tools/chainsync-loadtest/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6690 refactor: cleanup alt_bn128 estimates
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: S-automerge

#6689 integration-tests: remove assertion that fork_tail <= tail
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6647 chain: set the gc_fork_clean_step default to 100
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge

#6679 runtime: add `near_action_called_count` metric with an action label
  CHANGELOG.md
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/transaction.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/metrics.rs
Labels: S-automerge

#6700 fix(chain): revert the gc_blocks_limit default to 2
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge

#6701 store: get rid of RocksDBOptions
  core/store/src/db.rs
  core/store/src/lib.rs
  nearcore/src/lib.rs
Labels: S-automerge

#6697 Improve logging when the neard client stops
  neard/src/cli.rs
Labels: S-automerge

#6668 Added some documentation about how rc works
  core/store/src/columns.rs
Labels: S-automerge

#6678 network: add `near_dropped_message_by_type_and_reason_count` metric
  CHANGELOG.md
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#6605 test: add check that costs don't change by accident
  Cargo.lock
  integration-tests/Cargo.toml
  integration-tests/src/tests/runtime/mod.rs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/src/tests/cache.rs
Labels: S-automerge

#6703 strum: reduce usage of deprecated strum::AsStaticStr
  chain/client-primitives/src/types.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  utils/near-performance-metrics-macros/src/lib.rs
  utils/near-performance-metrics/src/stats_disabled.rs
Labels: S-automerge

#6709 added Send + Sync to std::error::Error in core/
  chain/chain/src/store_validator/validate.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/serialize.rs
  core/primitives/src/shard_layout.rs
  core/primitives/src/utils.rs
  core/primitives/src/views.rs
Labels: S-automerge

#6561 Add asserts for fn that should not be used with rc columns
  core/store/src/lib.rs
Labels: S-automerge

#6595 neard: set up rayon thread pool stack size
  Cargo.lock
  nearcore/src/runtime/mod.rs
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/main.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
Labels: S-automerge

#6670 feat: add runtime checks for "immutable" columns
  chain/epoch_manager/src/lib.rs
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#6711 CP-48 Improving loadtest - add option of initite loop
  integration-tests/src/bin/start_mock_network.rs
  pytest/tests/loadtest/contract/src/lib.rs
  pytest/tests/loadtest/loadtest.py
Labels: S-automerge

#6722 runtime: make test_cost_sanity independent of receipt hash
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap
Labels: A-testing, S-automerge

#6406 fix shard tracking issue for localnet
  nearcore/src/config.rs
Labels: S-automerge

#6714 move mock_network and rename it to mock_node
  Cargo.lock
  Cargo.toml
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/lib.rs
  tools/mock_node/Cargo.toml
  tools/mock_node/README.md
  tools/mock_node/src/lib.rs
  tools/mock_node/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#6723 test: fix regressed nightly test
  chain/chain/src/store.rs
  core/store/src/lib.rs
Labels: S-automerge

#6728 doc: update some urls in readme
  README.md
Labels: S-automerge
