Repository near/nearcore, pull requests merged in 2022-06, with the labels that each got.

#6899 move more of preprocess_block from ChainUpdate to Chain
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/challenges.rs
Labels: S-automerge

#6915 feat: show block sync percentage based on sync start height
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
Labels: S-automerge

#6929 feat: check responsiveness in mock-node
  Cargo.lock
  chain/network/src/test_utils.rs
  tools/mock_node/Cargo.toml
  tools/mock_node/src/main.rs
Labels: S-automerge

#6932 refactor: use simpler wait_or_timeout
  integration-tests/src/tests/network/peer_handshake.rs
Labels: S-automerge

#6930 update mock node README
  tools/mock_node/README.md
Labels: S-automerge

#6936 move the rest of preprocess_block from ChainUpdate to Chain
  chain/chain/src/chain.rs
Labels: S-automerge

#6791 Add BlockProcessingPool
  Cargo.lock
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
Labels: S-automerge

#6907 refactor: cleanup NightshadeRuntime creation
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/store-validator/src/main.rs
  tools/mock_node/src/setup.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6911 Added a presubmit testing proto backward compatibility
  .buildkite/pipeline.yml
  buf.yaml
Labels: S-automerge

#6824 feat: stabilize alt_bn128 familiy of host functions
  CHANGELOG.md
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives-core/src/profile.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  nearcore/Cargo.toml
  nearcore/res/genesis_config.json
  neard/Cargo.toml
  runtime/near-test-contracts/contract-for-fuzzing-rs/src/lib.rs
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/alt_bn128.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/test-contract/Cargo.toml
  runtime/runtime-params-estimator/test-contract/build.sh
  runtime/runtime-params-estimator/test-contract/src/lib.rs
  runtime/runtime/Cargo.toml
  test-utils/testlib/Cargo.toml
Labels: S-automerge

#6934 refactor: cleanup network runner
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#6943 refactor: vm runner test for preloaded execution
  runtime/near-vm-runner/src/tests/contract_preload.rs
Labels: S-automerge

#6772 feat: Precharge fn loading gas cost
  chain/chain/src/tests/simple_chain.rs
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  nearcore/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/contract_preload.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#6940 fix(adversarial): make sure sync_height() starts as None
  chain/client/src/adversarial.rs
Labels: S-automerge

#6789 state dump with account selection
  Cargo.lock
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#6951 store: use match instead of col_set for DBCol::if_foo methods
  core/store/src/columns.rs
Labels: S-automerge

#6953 refactor: use entry API more efficiently
  chain/chain/src/store.rs
Labels: S-automerge

#6944 refactor: mark block columns as insert-only
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#6946 refactor: remove some now needless mut_store accesses
  chain/chain/src/chain.rs
  chain/chain/src/lightclient.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
Labels: S-automerge

#6945 refactor: drop unused fields
  chain/chain/src/store.rs
Labels: S-automerge

#6956 feat: tracing logs in estimator
  Cargo.lock
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6938 store: add `path` field to StoreConfig
  CHANGELOG.md
  core/store/src/config.rs
  nearcore/src/lib.rs
  pytest/tests/sanity/spin_up_cluster.py
Labels: S-automerge

#6961 feat: record burnt_gas in tracing spans
  integration-tests/src/tests/client/process_blocks.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#6950 refactor callbacks in process_block to not use callbacks
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/mod.rs
  chain/chain/src/tests/sync_chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6973 store: make home directory required when constructing StoreOpener
  chain/network/src/peer_manager/peer_store.rs
  core/store/benches/store_bench.rs
  core/store/src/config.rs
  core/store/src/db.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/store-validator/src/main.rs
  tools/mock_node/src/setup.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#5994 style: discourage as_ref()
  docs/style.md
Labels: S-automerge

#6958 fix: data sections in test wat codes
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/runtime/deployment.rs
  runtime/near-test-contracts/src/lib.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#6887 proto and config for the Validator IP announcement
  chain/network-primitives/src/blacklist.rs
  chain/network-primitives/src/config.rs
  chain/network-primitives/src/config_json.rs
  chain/network-primitives/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/peer_store_test.rs
  chain/network/src/test_utils.rs
  integration-tests/src/tests/network/infinite_loop.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/peer_manager.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  neard/src/cli.rs
  tools/chainsync-loadtest/src/main.rs
  tools/mock_node/benches/sync.rs
  tools/mock_node/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#6977 indexer: take StoreConfig into account when opening storage
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/mod.rs
Labels: S-automerge

#6960 Last blocks page to mark which chunks were skipped
  chain/jsonrpc/res/last_blocks.html
Labels: S-automerge

#6983 chore: don't depend on sim in loadtest contract
  pytest/tests/loadtest/contract/Cargo.lock
  pytest/tests/loadtest/contract/Cargo.toml
Labels: S-automerge

#6986 Fix broken backtrace having panic=abort
  .cargo/config.toml
Labels: S-automerge

#6820 chore: remove estimator from CI
  .buildkite/pipeline.yml
Labels: S-automerge

#6976 doc: style tie-breaker for `&pat` vs `*val`
  docs/style.md
Labels: S-automerge

#6991 Update estimator to rustc 1.61.0
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6988 store: replace Store::get_rocksdb with Store::flush
  core/store/src/db.rs
  core/store/src/lib.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#6980 feat(mock-node): send unrequested blocks and chunk requests
  Cargo.lock
  tools/mock_node/Cargo.toml
  tools/mock_node/README.md
  tools/mock_node/benches/sync.rs
  tools/mock_node/src/lib.rs
  tools/mock_node/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#6966 rosetta: fix return message when block not final and improve tests
  chain/rosetta-rpc/src/utils.rs
  pytest/tests/sanity/rosetta.py
Labels: A-testing, S-automerge

#6964 test: make sure that calls to gas don't overflow
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#6987 nearcore: use StoreConfig read from config in benchmarks
  nearcore/benches/store.rs
Labels: S-automerge

#6997 runtime-params-estimator: use in-memory store
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#6989 Fix wrong command in README of pytest
  pytest/tests/loadtest/README.md
Labels: S-automerge

#7001 Update README.md
  genesis-tools/README.md
Labels: S-automerge

#6922 RFC: introduce unified testing infrastructure for contract runtime
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
  runtime/near-vm-runner/src/vm_kind.rs
Labels: S-automerge

#6967 refactor: handle state patching in a more principled way
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  core/primitives/Cargo.toml
  core/primitives/src/lib.rs
  core/primitives/src/sandbox_state_patch.rs
  integration-tests/src/tests/client/sandbox.rs
  nearcore/src/runtime/mod.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7007 remove unnecessary log
  chain/client/src/client_actor.rs
Labels: S-automerge

#7009 Impemented a clock in terms of time crate.
  Cargo.lock
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/lib.rs
  chain/network-primitives/src/time.rs
  core/primitives/src/time.rs
Labels: S-automerge

#7013 chore: remove impossible-to-trigger panic
  core/primitives-core/src/account.rs
Labels: S-automerge

#7008 refactor(mock-node): remove GetChainTargetBlockHeight
  tools/mock_node/benches/sync.rs
  tools/mock_node/src/lib.rs
  tools/mock_node/src/main.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#7010 Implemented store module for near-network
  chain/network-primitives/src/network_protocol/edge.rs
  chain/network/src/lib.rs
  chain/network/src/store/mod.rs
  chain/network/src/store/schema/mod.rs
  chain/network/src/store/schema/tests.rs
  chain/network/src/store/testonly.rs
  chain/network/src/tests/mod.rs
Labels: S-automerge

#7006 fix: state-viewer starting timestamp
  tools/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#7002 fix: estimator check block overhead everywhere
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/trie.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#7017 Stop using `lazy_static_include` crate because it doesn't work with debug assertions
  Cargo.lock
  Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/lib.rs
  nearcore/Cargo.toml
  nearcore/src/config.rs
  nearcore/src/migrations.rs
  scripts/state/update_res.py
  utils/mainnet-res/Cargo.toml
  utils/mainnet-res/README.md
  utils/mainnet-res/res/mainnet_genesis.json
  utils/mainnet-res/res/mainnet_restored_receipts.json
  utils/mainnet-res/res/storage_usage_delta.json
  utils/mainnet-res/src/lib.rs
  utils/mainnet-res/tests/load_genesis.rs
Labels: S-automerge

#7016 view-state: fix rocksdb-stats command
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/rocksdb_stats.rs
Labels: S-automerge

#7005 Trace code execution across actix queues for PeerManagerActor->PeerActor messages
  Cargo.lock
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
  chain/network/src/tests/peer_actor.rs
  chain/network/src/types.rs
  core/o11y/src/lib.rs
Labels: S-automerge

#6999 chore: remove obsolete todo
  chain/chain/src/chain.rs
Labels: S-automerge

#7031 Add missing ‘chain/telemetry’ to workspace
  Cargo.toml
Labels: S-automerge

#7029 fix: make TestDB iterator deterministic
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#7027 store: introduce StoreConfig::test_config constructor
  chain/network/src/peer_manager/peer_store_test.rs
  core/store/benches/store_bench.rs
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/src/runtime/mod.rs
  test-utils/runtime-tester/src/run_test.rs
Labels: S-automerge

#7035 crypto: add ‘private_key’ alias for ‘secret_key’ field
  CHANGELOG.md
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/key_file.rs
Labels: S-automerge

#7022 feat: trie cache factory to allow variable cache sizes
  chain/chain/src/test_utils.rs
  core/primitives/src/shard_layout.rs
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  genesis-tools/genesis-populate/src/lib.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge, T-core

#7037 Removed the IBF python test
  nightly/pytest-sanity.txt
  pytest/tests/sanity/routing_table_sync.py
Labels: S-automerge

#7034 refactor: privatise NightshadeRuntime::new
  genesis-tools/genesis-populate/src/lib.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6982 dump block transactions into a file
  core/primitives/src/transaction.rs
  tools/state-viewer/README.md
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/lib.rs
  tools/state-viewer/src/tx_dump.rs
Labels: S-automerge

#7054 Add a make target for shardnet
  Makefile
Labels: S-automerge

#6963 Refactor of the RoutingTable
  Cargo.lock
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/benches/graph.rs
  chain/network/benches/routing_table_actor.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tracker.rs
  chain/network/src/peer/transfer_stats.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/peer_store_test.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/graph.rs
  chain/network/src/routing/graph_with_cache.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/route_back_cache.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/store/mod.rs
  chain/network/src/store/schema/mod.rs
  chain/network/src/test_utils.rs
  chain/network/src/tests/cache.rs
  chain/network/src/tests/cache_edges.rs
  chain/network/src/tests/data.rs
  chain/network/src/tests/mod.rs
  chain/network/src/tests/network_protocol.rs
  chain/network/src/tests/peer_actor.rs
  chain/network/src/tests/peer_communication.rs
  chain/network/src/tests/util.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/infinite_loop.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/peer_manager.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#7023 Implemented proto translation for IP announcement messages
  chain/network-primitives/src/time.rs
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/account_key.rs
  chain/network/src/network_protocol/proto_conv/crypto.rs
  chain/network/src/network_protocol/proto_conv/handshake.rs
  chain/network/src/network_protocol/proto_conv/mod.rs
  chain/network/src/network_protocol/proto_conv/net.rs
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/proto_conv/time.rs
  chain/network/src/network_protocol/proto_conv/util.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/store/schema/tests.rs
  chain/network/src/tests/cache_edges.rs
  chain/network/src/tests/mod.rs
  chain/network/src/tests/peer_communication.rs
  chain/network/src/types.rs
Labels: S-automerge

#7028 update pytest readme file with path tips & typos
  pytest/tests/loadtest/README.md
Labels: S-automerge

#7044 refactor: remove misplaced sandbox requests from network
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/Cargo.toml
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/types.rs
  integration-tests/Cargo.toml
  tools/state-viewer/Cargo.toml
Labels: S-automerge

#7049 Metircs for the duration of producing chunks and distributing chunks
  chain/chunks/src/lib.rs
  chain/chunks/src/metrics.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/metrics.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7067 chore: Remove estimator contract size padding
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/test-contract/Cargo.toml
  runtime/runtime-params-estimator/test-contract/build.sh
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: S-automerge

#7050 Measure latency of network messages assuming all nodes have synchronized clocks
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/tests/peer_communication.rs
Labels: S-automerge

#7068 Cleanup 2 compilation flags that are no longer used (routing_algo and key_nonce)
  chain/chain/Cargo.toml
  chain/client/Cargo.toml
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/Cargo.toml
  chain/jsonrpc/src/lib.rs
  chain/network/Cargo.toml
  core/primitives-core/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
  runtime/runtime/Cargo.toml
Labels: S-automerge

#7069 Shardnet compilation flag
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  neard/Cargo.toml
Labels: S-automerge

#7072 Adding chunk-only-producers support in epoch debug page (and epoch manager)
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  chain/epoch_manager/src/lib.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/jsonrpc/res/epoch_info.html
  core/primitives/src/views.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7074 refactor: remove the unused StakeChunkOnlyAction
  chain/rosetta-rpc/src/adapters/mod.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#7071 Use an enum instead of bool to aid readability
  core/store/src/config.rs
  core/store/src/db.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  neard/src/cli.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#7080 CHANGELOG 1.27.0
  CHANGELOG.md
Labels: S-automerge

#7082 Use shardnet compilation flag in shardnet make target
  Makefile
Labels: S-automerge

#7083 refactor: remove no-op into
  core/chain-configs/src/genesis_config.rs
Labels: S-automerge

#7086 feat: add support for aarch64-linux
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#7084 refactor: remove needless generics form GenesisConfig API
  chain/chain/src/types.rs
  core/chain-configs/src/genesis_config.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  nearcore/src/lib.rs
  nearcore/tests/economics.rs
  test-utils/runtime-tester/src/run_test.rs
  tools/mock_node/src/lib.rs
  tools/mock_node/src/setup.rs
Labels: S-automerge

#7046 Fixed proto compatibility presubmit
  .buildkite/pipeline.yml
Labels: S-automerge

#7078 fix chunk cache so that get_chunk_headers_for_block do not remove the…
  chain/chunks/src/chunk_cache.rs
Labels: S-automerge

#7087 perf: avoid unnecessary allocations when merklizing stuff
  core/primitives/src/merkle.rs
  core/primitives/src/sharding.rs
Labels: S-automerge

#7085 refactor: remove `is_chunk_only` field from ValidatorStake
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/simple_chain.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/validator_selection.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7090 Add shardnet to the list of networks that need to download config and genesis instead of generating it
  nearcore/src/config.rs
Labels: S-automerge

#7081 Refactor: moving debug-related objects to separate debug.rs files
  chain/client-primitives/src/debug.rs
  chain/client-primitives/src/lib.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/lib.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc/src/api/status.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7088 refactor: make leftover Chain getters non-mut
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7093 [fix] protobuf backward compatibility test
  .buildkite/pipeline.yml
Labels: S-automerge

#7076 store: refactor RocksDB::open by harmonising rw and ro paths
  core/store/src/config.rs
  core/store/src/db.rs
Labels: S-automerge

#7095 store: get rid of DBError type
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#7096 store: add unit tests for near_store::db::refcount functions
  core/store/src/db.rs
  core/store/src/db/refcount.rs
Labels: S-automerge

#7097 store: separate StoreUpdate::update_refcount into increase and decrease
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/db/refcount.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7101 fix: revert default value for trie cache capacity
  core/store/src/config.rs
Labels: S-automerge

#7103 store: add documentation to Database trait and refactor it a little
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#7102 store: various small near_store::db::refcount changes
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/db/refcount.rs
Labels: S-automerge

#7098 Changing remove_witness to get_witness in Doomslug
  chain/chain/src/doomslug.rs
  chain/client/src/client.rs
Labels: S-automerge

#7109 shardnet compilation feature for near-indexer-for-explorer
  chain/client/Cargo.toml
Labels: S-automerge

#7113 refactor: don't hard-code NightshadeRuntime in state-viewer
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge

#7110 feat: add benchmark for chunk production time
  integration-tests/src/tests/client/benchmarks.rs
  integration-tests/src/tests/client/mod.rs
Labels: S-automerge

#7111 store: use RocksDB’s iterate upper bound in prefix iterator
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: S-automerge

#7114 Use Rational32 instead of Rational
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/simple_chain.rs
  chain/chain/src/types.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/query_client.rs
  chain/epoch_manager/src/reward_calculator.rs
  chain/epoch_manager/src/test_utils.rs
  chain/epoch_manager/src/tests/mod.rs
  chain/epoch_manager/src/validator_selection.rs
  chain/network/src/network_protocol/testonly.rs
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/genesis_validate.rs
  core/primitives/benches/serialization.rs
  core/primitives/src/block.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/test_utils.rs
  integration-tests/src/node/mod.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  nearcore/src/config.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/shard_tracker.rs
  nearcore/tests/economics.rs
Labels: S-automerge

#7127 store: check ShardTries isn’t changed when setting it on StoreUpdate
  Cargo.lock
  core/store/Cargo.toml
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7130 fix: don't set rustflags for WASM
  .cargo/config.toml
Labels: S-automerge

#7099 narrowed down the public API of PeerManagerActor.
  chain/chunks/src/lib.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc-adversarial-primitives/src/lib.rs
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/api/adversarial.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/lib.rs
  chain/network-primitives/src/network_protocol/edge.rs
  chain/network-primitives/src/types.rs
  chain/network/Cargo.toml
  chain/network/src/broadcast/mod.rs
  chain/network/src/broadcast/tests.rs
  chain/network/src/lib.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer/tests/mod.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/routing/mod.rs
  chain/network/src/routing/routing_table_view.rs
  chain/network/src/routing/tests/cache.rs
  chain/network/src/routing/tests/cache_edges.rs
  chain/network/src/routing/tests/mod.rs
  chain/network/src/sink.rs
  chain/network/src/store/schema/tests.rs
  chain/network/src/test_utils.rs
  chain/network/src/testonly/actix.rs
  chain/network/src/testonly/fake_client.rs
  chain/network/src/testonly/mod.rs
  chain/network/src/testonly/stream.rs
  chain/network/src/tests/mod.rs
  chain/network/src/types.rs
  core/primitives/src/network.rs
  integration-tests/src/tests/network/infinite_loop.rs
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/peer_manager.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/network.rs
Labels: S-automerge

#7133 fix: minor typo
  core/primitives/src/errors.rs
Labels: S-automerge

#7131 network: replace store::Store::new with From implementations
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  chain/network/src/peer_manager/peer_store_test.rs
  chain/network/src/routing/tests/cache.rs
  chain/network/src/routing/tests/cache_edges.rs
  chain/network/src/store/mod.rs
Labels: S-automerge

#7100 Orchestrate shardnet restaking
  pytest/tests/shardnet/README.md
  pytest/tests/shardnet/__init__.py
  pytest/tests/shardnet/restake.py
  pytest/tests/shardnet/scripts/create_account.sh
  pytest/tests/shardnet/scripts/restaked.sh
  scripts/check_pytests.py
Labels: S-automerge

#7138 Pass protocol_feature_chunk_only_producers correctly when enabled by the indexer
  chain/indexer/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#7139 feat: enforce that account_ids are valid in FunctionCallPermission
  chain/chain/src/tests/simple_chain.rs
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/130.txt
  core/primitives/res/runtime_configs/parameters.txt
  core/primitives/src/errors.rs
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/process_blocks.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#7145 nit(shardnet): print date in restaked.sh
  pytest/tests/shardnet/scripts/restaked.sh
Labels: S-automerge

#7150 fix(shardnet): don't ignore errors in restake.py
  pytest/tests/shardnet/restake.py
Labels: S-automerge
