Repository near/nearcore, pull requests merged in 2022-12, with the labels that each got.

#8144 typo
  runtime/near-test-contracts/src/lib.rs
Labels: S-automerge

#8142 Rearranged code for the coming TIER1 implementation
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#8147 refactor: various changes to address clippy warnings
  runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/import.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/zulip.rs
  tools/rpctypegen/core/src/lib.rs
  tools/themis/src/utils.rs
  utils/near-cache/src/cell.rs
Labels: S-automerge

#8131 fix(migrations): dedup TransactionResult keys by id and block hash
  core/store/src/migrations.rs
Labels: S-automerge

#8143 documentation about future plans
  docs/SUMMARY.md
  docs/architecture/next/README.md
  docs/architecture/next/catchup_and_state_sync.md
  docs/architecture/next/malicious_chunk_producer_and_phase2.md
Labels: S-automerge

#8152 Added document describing different testing libraries
  docs/SUMMARY.md
  docs/practices/testing/test_utils.md
Labels: S-automerge

#8136 stdx: add as_chunks function
  Cargo.lock
  core/store/src/trie/mod.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/runtime/sanity_checks.rs
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/array_utils.rs
  runtime/near-vm-logic/src/lib.rs
  utils/stdx/src/lib.rs
Labels: S-automerge

#8158 refactor: fix clippy deprecated since warning
  core/account-id/src/lib.rs
Labels: S-automerge

#8141 TIER1 implementation
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer/tests/stream.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/connection/tests.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/mod.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/private_actix.rs
  chain/network/src/tcp.rs
  chain/network/src/testonly/fake_client.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge, T-SRE

#8161 fix for the protobuf check
  .buildkite/pipeline.yml
Labels: S-automerge

#8167 [Refactor] Moving KeyValueRuntime to a separate file
  chain/chain/src/test_utils.rs
  chain/chain/src/test_utils/kv_runtime.rs
Labels: S-automerge

#8163 [Test utils] Added TestBlockBuilder
  chain/chain/src/tests/gc.rs
  chain/chain/src/tests/simple_chain.rs
  chain/chain/src/tests/sync_chain.rs
  chain/chain/src/types.rs
  core/primitives/src/test_utils.rs
Labels: S-automerge

#8162 feat(mocknet): add a script for running mocknet tests based on `tools/mirror`
  pytest/lib/mocknet.py
  pytest/tests/mocknet/mirror.py
Labels: S-automerge

#8164 Adding test to state sync
  chain/chain/src/chain.rs
  chain/client-primitives/src/types.rs
  chain/client/src/sync/state.rs
  chain/network/src/test_utils.rs
Labels: S-automerge

#8169 refactor: Fix near-stdx clippy warnings
  runtime/near-vm-logic/src/alt_bn128.rs
  runtime/near-vm-logic/src/tests/alt_bn128.rs
  utils/stdx/src/lib.rs
Labels: S-automerge

#8168 Migrate remaining routing tests to network crate
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/routing.rs
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#8176 Added create_test_signer function that simplifies tests
  chain/chain/src/doomslug.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/doomslug.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/sync/header.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/process_blocks.rs
  chain/client/src/tests/query_client.rs
  chain/network/src/config.rs
  core/primitives/src/test_utils.rs
  docs/practices/testing/test_utils.md
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/config.rs
  nearcore/src/runtime/mod.rs
  test-utils/testlib/src/process_blocks.rs
Labels: S-automerge

#8165 Fix a bug in processing skips approvals when there are forks
  chain/client/src/client.rs
  chain/client/src/tests/doomslug.rs
  chain/client/src/tests/mod.rs
Labels: S-automerge

#8160 removed edge field from Connection
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/tier1.rs
Labels: S-automerge

#8155 runtime: simplify MemoryLike trait
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_memory.rs
  runtime/near-vm-runner/src/memory.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#8179 gas: fix the computation of `self.promises_gas`
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
Labels: S-automerge

#8175 runtime: don’t unnecessarily copy promise indices
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#8183 Update SECURITY.md
  SECURITY.md
Labels: S-automerge

#8181 Add TIER1 network debug page
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/info.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc/res/debug.html
  chain/jsonrpc/res/network_info.css
  chain/jsonrpc/res/network_info.html
  chain/jsonrpc/res/network_info.js
  chain/jsonrpc/res/tier1_network_info.html
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/process_blocks.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock-node/src/lib.rs
Labels: S-automerge

#8182 deprecating AnnounceAccount
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#8208 doc: add text about re-request reviews
  CONTRIBUTING.md
Labels: S-automerge

#8204 attempt to deflake test_dropping_duplicate_messages
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#8209 added info about TIER1 to the CHANGELOG
  CHANGELOG.md
  docs/SUMMARY.md
  docs/advanced_configuration/networking.md
Labels: S-automerge

#8213 refactor: disable clippy for near-test-contracts
  runtime/near-test-contracts/contract-for-fuzzing-rs/src/lib.rs
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
Labels: C-housekeeping, S-automerge

#8216 document findings on database format
  docs/SUMMARY.md
  docs/misc/database.md
Labels: S-automerge

#8220 TIER1 debug: fix usage of AccountKey vs PeerId
  chain/jsonrpc/res/tier1_network_info.html
Labels: S-automerge

#8194 primitives: get rid of Cursor
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/shard_layout.rs
  core/primitives/src/state.rs
  core/store/src/flat_state.rs
Labels: S-automerge

#8226 runtime: create common unit tests for MemoryLike implementations
  runtime/near-vm-runner/src/memory.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#8222 refactor: Remove unnecessary `#[allow(dead_code)]` macros
  runtime/near-vm-logic/src/logic.rs
Labels: S-automerge

#8223 refactor: improve documentation and variable naming
  runtime/near-vm-logic/src/gas_counter.rs
Labels: S-automerge

#8224 runtime: avoid copying register values unnecessarily
  core/primitives-core/src/config.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/vmstate.rs
Labels: S-automerge

#8207 use nextest for better test isolation
  .buildkite/pipeline.yml
  .config/nextest.toml
  docs/practices/testing/README.md
Labels: S-automerge

#8233 doc: Fix typo in parameter_definition.md
  docs/architecture/gas/parameter_definition.md
Labels: S-automerge

#8231 runtime: add vmstate::Registers unit tests
  runtime/near-vm-logic/src/vmstate.rs
Labels: S-automerge

#8229 removed redundant test and unused code
  chain/network/src/test_utils.rs
  integration-tests/src/tests/network/ban_peers.rs
  integration-tests/src/tests/network/churn_attack.rs
  integration-tests/src/tests/network/mod.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#8173 Migrate tests to use the new TestBlockBuilder
  chain/chain/src/store.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/sync/header.rs
  chain/client/src/sync/state.rs
  core/primitives/src/test_utils.rs
  docs/practices/testing/test_utils.md
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#8248 doc: Fix typo in parameter estimator docs
  docs/architecture/gas/estimator.md
Labels: S-automerge

#8237 runtime: track registers memory usage rather than recomputing each time
  runtime/near-vm-logic/src/vmstate.rs
Labels: S-automerge

#8253 docs: more details about catchup
  docs/architecture/how/sync.md
Labels: S-automerge

#8241 refactor: fix clippy issues in near-crypto
  core/crypto/src/hash.rs
  core/crypto/src/key_file.rs
  core/crypto/src/signature.rs
  core/crypto/src/signer.rs
  core/crypto/src/traits.rs
Labels: S-automerge

#8247 refactor: fix clippy warnings in near-account-id
  core/account-id/src/borsh.rs
  core/account-id/src/lib.rs
  core/account-id/src/serde.rs
Labels: S-automerge

#8193 feat: support block catchups for flat storage
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/sync/state.rs
  core/store/Cargo.toml
  core/store/src/flat_state.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#8255 fix: flaky prefetcher tests
  runtime/runtime/src/prefetch.rs
Labels: S-automerge

#8249 set the in-flight limit on the demuxed calls to 1 for now
  chain/network/src/concurrency/demux.rs
Labels: S-automerge

#8259 runtime: move get_vec_from_memory_or_register into separate function
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/vmstate.rs
Labels: S-automerge

#8256 Improve adversenet script
  pytest/lib/mocknet.py
  pytest/tests/mocknet/run_adversenet.py
Labels: S-automerge

#8215 refactor: clean up busy waiting in prefetcher blocking get
  core/store/src/lib.rs
  core/store/src/sync_utils.rs
  core/store/src/trie/prefetching_trie_storage.rs
Labels: S-automerge

#8251 feat(estimator): Send/exec action costs
  runtime/runtime-params-estimator/src/action_costs.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/transaction_builder.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#8007 wasmer2: do not re-validate wasm code after instrumentation
  Cargo.lock
  Cargo.toml
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#8268 features: remove the memory_stats feature and near-rust-allocator-proxy
  Cargo.lock
  Cargo.toml
  Makefile
  chain/network/Cargo.toml
  core/o11y/src/lib.rs
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/Cargo.toml
  neard/src/main.rs
  utils/near-performance-metrics/Cargo.toml
  utils/near-performance-metrics/src/actix_enabled.rs
  utils/near-performance-metrics/src/stats_enabled.rs
Labels: S-automerge

#8267 logging: print out the part ords in chunk request/response debug logs
  chain/chunks/src/lib.rs
Labels: S-automerge

#8274 test-utils: remove kind of pointless encode_int function
  Cargo.lock
  integration-tests/src/tests/runtime/state_viewer.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge
