Repository near/nearcore, pull requests merged in 2022-03, with the labels that each got.

#6335 localnet with many shards
  nearcore/src/config.rs
Labels: S-automerge

#6204 re: chore: Cleanup `pub` modifiers in `near-network::peer`
  chain/network/src/peer/codec.rs
  chain/network/src/peer/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tracker.rs
  chain/network/src/peer/transfer_stats.rs
  chain/network/src/peer/utils.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6203 re: chore: Remove unused dependencies from utils
  Cargo.lock
  chain/network-primitives/Cargo.toml
  utils/near-performance-metrics/Cargo.toml
Labels: C-housekeeping, P-low, A-network, S-automerge

#6194 re: chore: Rewrite `Codec::decode` in a way to avoid unwraps
  chain/network/src/peer/codec.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6176 Make `delay-detector` required, and make it's functionality flag dependent.
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/routing_table_actor.rs
  nearcore/Cargo.toml
  tools/delay_detector/Cargo.toml
  tools/delay_detector/src/lib.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6129 re: Use std::mem::take instead of std::mem::swap
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: P-low, A-network, S-automerge

#5877 fix: Fix `PeerManager::monitor_peers_trigger` stopping on error
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: C-bug, P-high, A-network, S-automerge, T-core

#6355 core: preallocate known vector capacity in encode_transaction_receipts
  core/primitives/src/sharding.rs
Labels: P-low, S-automerge

#6356 chain: refactor `process_partial_encoded_chunk_request` method
  chain/chunks/src/lib.rs
Labels: S-automerge

#6286 chain: add epoch info to StatusSyncInfo
  chain/client/src/client_actor.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
  core/primitives/src/views.rs
Labels: S-automerge

#6350 refactor: migrate from failure crate to thiserror & anyhow
  Cargo.lock
  chain/chain-primitives/Cargo.toml
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
Labels: S-automerge

#6366 refactor: simplify if statements in persist_partial_chunk_for_data_av…
  chain/chunks/src/lib.rs
Labels: S-automerge

#6368 pytest: remove unused variable
  pytest/tests/sanity/rpc_hash.py
Labels: P-low, S-automerge

#6370 pytest: explicitly check synced blocks in block_sync_archival.py test
  pytest/lib/cluster.py
  pytest/tests/sanity/block_sync_archival.py
Labels: P-low, S-automerge

#6324 feat(sandbox): add debug log host function to sandbox
  Cargo.lock
  neard/src/cli.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/runtime/Cargo.toml
Labels: S-automerge

#6379 change NUM_ORPHAN_ANCESTORS_CHECK to 3
  chain/chain/src/chain.rs
Labels: S-automerge

#6309 NEP205: Delay voting for new version until a certain date and time
  Cargo.lock
  core/primitives/Cargo.toml
  core/primitives/src/block_header.rs
  core/primitives/src/lib.rs
  core/primitives/src/upgrade_schedule.rs
  core/primitives/src/version.rs
Labels: S-automerge

#6375 Moving log_summary into check_triggers
  chain/client/src/client_actor.rs
Labels: S-automerge

#6388 fix: fix account deserialization on arm64 while keeping the behavior of panicking if deserializing too big a slice
  core/primitives-core/src/account.rs
Labels: S-automerge

#6326 Graceful shutdown on panic
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  core/store/Cargo.toml
  core/store/src/db.rs
  integration-tests/src/mock_network/setup.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/lib.rs
  neard/Cargo.toml
  neard/src/cli.rs
Labels: S-automerge

#6342 chain: add RpcQueryError::GarbageCollectedBlock
  chain/client-primitives/src/types.rs
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/query.rs
Labels: S-automerge

#6391 fuzz: fight fuzzer false positives by attempting to reduce the allowed memory
  nightly/fuzz.toml
Labels: S-automerge

#5786 re: Rewrite `PeerStore::new` in a functional way
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_store.rs
Labels: C-housekeeping, P-low, A-network, S-automerge

#6359 doc(params-estimator): Memory related costs docs
  runtime/runtime-params-estimator/src/cost.rs
Labels: S-automerge

#6398 Makefile: classify perf-release as release build
  Makefile
Labels: P-low, S-automerge

#6393 Update issue tracker links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-automerge

#6389 feat: state_viewer: add an apply_chunk command
  Cargo.lock
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/lib.rs
Labels: S-automerge

#6315 refactor: move nodes counter to the caching storage
  core/store/src/test_utils.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  runtime/runtime/src/ext.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#6336 feat(params-estimator): Touching trie node est.
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/transaction_builder.rs
  runtime/runtime-params-estimator/test-contract/src/lib.rs
Labels: S-automerge

#6382 fix(rosetta): separate transfers from gas fees in Rosetta operations
  chain/rosetta-rpc/src/adapters/transactions.rs
  pytest/tests/sanity/rosetta.py
Labels: S-automerge, X-mm-near-skip

#6285 feat: implement NEP264, function call gas weight
  chain/chain/src/tests/simple_chain.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/types.rs
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/ext.rs
Labels: S-automerge

#6410 add some debug lines for debugging why blocks catchup for archival nodes takes too long
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  chain/client/src/sync.rs
Labels: S-automerge

#6411 endtoend: make more resilient to exceptions and other minor improvements
  pytest/endtoend/endtoend.py
Labels: S-automerge

#6417 fuzz: go back to the default 2G of ram for each fuzzer
  nightly/fuzz.toml
Labels: S-automerge

#6418 Revert "start client actor in a separate thread"
  Cargo.lock
  chain/client/src/client_actor.rs
  test-utils/actix-test-utils/Cargo.toml
  test-utils/actix-test-utils/src/lib.rs
Labels: S-automerge

#6430 db: prefer cfg!() expression to cfg attribute
  core/store/src/db.rs
Labels: P-low, S-automerge

#6420 pytest: add default timeout to utils.wait_for_blocks
  pytest/lib/utils.py
  pytest/tests/adversarial/malicious_chain.py
  pytest/tests/adversarial/start_from_genesis.py
  pytest/tests/sanity/backward_compatible.py
  pytest/tests/sanity/block_sync.py
  pytest/tests/sanity/block_sync_archival.py
  pytest/tests/sanity/garbage_collection.py
  pytest/tests/sanity/garbage_collection1.py
  pytest/tests/sanity/gc_after_sync1.py
  pytest/tests/sanity/gc_sync_after_sync.py
  pytest/tests/sanity/handshake_tie_resolution.py
  pytest/tests/sanity/proxy_restart.py
  pytest/tests/sanity/repro_2916.py
  pytest/tests/sanity/spin_up_cluster.py
  pytest/tests/sanity/state_sync2.py
  pytest/tests/sanity/state_sync3.py
  pytest/tests/sanity/state_sync_fail.py
  pytest/tests/sanity/switch_node_key.py
  pytest/tests/sanity/sync_ban.py
  pytest/tests/sanity/sync_chunks_from_archival.py
  pytest/tests/sanity/transactions.py
Labels: P-low, S-automerge

#6431 chain: ShardManager: add metrics for partial encoded chunk response
  Cargo.lock
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/metrics.rs
Labels: S-automerge

#6419 Metrics for execution time per Petagas
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6434 fuzz: disable runtime-tester for now as it's got lots of intermittent failures anyway
  nightly/fuzz.toml
Labels: S-automerge

#6437 Proper rocksdb shutdown if many run_actix threads are running
  Cargo.lock
  test-utils/actix-test-utils/Cargo.toml
  test-utils/actix-test-utils/src/lib.rs
Labels: S-automerge

#6440 pytest: reduce block production delay in block_sync_archival.py
  pytest/tests/sanity/block_sync_archival.py
Labels: P-low, S-automerge

#6449 pytest: fix block_sync_archival.py
  pytest/tests/sanity/block_sync_archival.py
Labels: P-high, S-automerge

#6452 pytest: observe metrics in block_sync_archival.py test
  pytest/tests/sanity/block_sync_archival.py
Labels: S-automerge

#6451 chain: avoid duplicate hash map lookup in EncodedChunksCache
  chain/chunks/src/chunk_cache.rs
Labels: P-low, S-automerge

#6425 scripts: actually look at ‘scripts’ directory when ‘formatting’
  scripts/formatting
Labels: P-low, S-automerge

#6455 fix(script): Estimator CI
  runtime/runtime-params-estimator/emu-cost/ci.sh
Labels: S-automerge

#6424 nightly: remove fuzz tests from NayDuck
  nightly/README.md
  nightly/fuzz.toml
  nightly/fuzzing.txt
  nightly/nightly.txt
  pytest/requirements.txt
  pytest/tests/fuzz.py
  scripts/check_fuzzing.py
Labels: P-low, S-automerge

#6453 Update genesis_time when dumping state
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#6454 Reintroduce the PR that starts client in the separate thread
  chain/client/src/client_actor.rs
Labels: S-automerge

#6465 db: use EnumCount instead of NUM_COLS
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  core/store/src/db.rs
  core/store/src/lib.rs
Labels: P-low, S-automerge

#6447 neard: add recompress-storage command
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/src/lib.rs
  neard/src/cli.rs
Labels: S-automerge

#6448 feature(params-estimator): JSON output
  runtime/runtime-params-estimator/src/config.rs
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#6464 fix(params-estimator): TouchingTrieNodeWrite
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#6469 neard: document ‘recompress-storage’ command more
  neard/src/cli.rs
Labels: P-low, S-automerge

#6193 chain: rosetta: guarantee order of operations in transactions
  chain/rosetta-rpc/src/adapters/mod.rs
  pytest/tests/sanity/rosetta.py
Labels: S-automerge

#6467 Add metrics for delay between client actor and network
  chain/chunks/src/lib.rs
  chain/client/src/client_actor.rs
  chain/client/src/metrics.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/catching_up.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/types.rs
  integration-tests/src/mock_network/mod.rs
  integration-tests/src/tests/client/chunks_management.rs
  tools/chainsync-loadtest/src/network.rs
Labels: S-automerge

#6441 chore: migrate clap to v3
  Cargo.lock
  deny.toml
  genesis-tools/genesis-csv-to-json/Cargo.toml
  genesis-tools/genesis-csv-to-json/src/main.rs
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/keypair-generator/Cargo.toml
  genesis-tools/keypair-generator/src/main.rs
  integration-tests/Cargo.toml
  integration-tests/src/bin/start_mock_network.rs
  neard/Cargo.toml
  neard/src/cli.rs
  runtime/near-vm-runner-standalone/Cargo.toml
  runtime/near-vm-runner-standalone/src/main.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/rocksdb.rs
  test-utils/store-validator/Cargo.toml
  test-utils/store-validator/src/main.rs
  tools/chainsync-loadtest/Cargo.toml
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/Cargo.toml
  tools/indexer/example/src/configs.rs
  tools/indexer/example/src/main.rs
  tools/restaked/Cargo.toml
  tools/restaked/src/main.rs
  tools/restored-receipts-verifier/Cargo.toml
  tools/restored-receipts-verifier/src/main.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/epoch_info.rs
Labels: S-automerge

#6478 neard: use u64 counters in recompress-storage to avoid overflows
  nearcore/src/lib.rs
Labels: S-automerge

#6482 nearcore: download compressed betanet and testnet genesis.json file
  nearcore/src/config.rs
Labels: S-automerge

#6396 add support for start_height in start_mock_network
  Cargo.lock
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/epoch_manager/Cargo.toml
  chain/epoch_manager/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/bin/start_mock_network.rs
  integration-tests/src/mock_network/README.md
  integration-tests/src/mock_network/mod.rs
  integration-tests/src/mock_network/setup.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6471 avoid catch up when no new shards are needed
  chain/chain/src/chain.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#6446 RocksDB stats re-exported as Prometheus metrics
  chain/chain/src/store.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/lib.rs
  chain/client/src/rocksdb_metrics.rs
  core/metrics/src/lib.rs
  core/store/src/db.rs
  core/store/src/lib.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#6487 Adding metrics for counting and timing client messages
  chain/client/src/client_actor.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#6470 Use non-blocking log writer
  Cargo.lock
  Cargo.toml
  core/o11y/Cargo.toml
  core/o11y/README.md
  core/o11y/src/lib.rs
  deny.toml
  neard/Cargo.toml
  neard/src/cli.rs
  test-utils/logger/Cargo.toml
  test-utils/logger/src/lib.rs
  tools/chainsync-loadtest/Cargo.toml
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/Cargo.toml
  tools/indexer/example/src/configs.rs
  tools/indexer/example/src/main.rs
  tools/restaked/Cargo.toml
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/Cargo.toml
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6492 peer_store: avoid unnecessary Vector allocation
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
Labels: P-low, S-automerge

#6105 feat: benchmark for iterating trie
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/benches/store.rs
Labels: S-automerge

#6497 chore: update wasm-smith
  Cargo.lock
  runtime/near-vm-runner/fuzz/Cargo.toml
Labels: S-automerge

#6493 style: Add guidance on `tracing`
  docs/architecture.md
  docs/style.md
Labels: S-automerge

#6476 refactor: combine part_id+num_parts into PartId struct #5731
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client/src/client_actor.rs
  core/primitives/src/lib.rs
  core/primitives/src/state_part.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/mock_network/setup.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#6490 feat(serde): show missed de fields in debug mode #6436
  Cargo.lock
  nearcore/Cargo.toml
  nearcore/src/config.rs
Labels: S-automerge

#6426 feat: trigger binary release on tagged releases
  .github/workflows/mac_binary.yml
Labels: S-automerge

#6502 make start_mock_network print epoch start height information
  integration-tests/src/mock_network/setup.rs
Labels: S-automerge

#6506 Register the subscriber globally
  core/o11y/src/lib.rs
  neard/src/cli.rs
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#6503 peer_store: apply IP blacklist to peer store
  chain/network-primitives/src/blacklist.rs
  chain/network-primitives/src/config.rs
  chain/network-primitives/src/types.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/config.rs
Labels: S-automerge

#6501 Add more debug metrics
  chain/client/src/client_actor.rs
  chain/client/src/metrics.rs
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#6515 fix(buildkite) Fix docker conflicts with previous runs
  .buildkite/pipeline.yml
Labels: T-SRE

#6466 Print more detailed information about upcoming blocks
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/Cargo.toml
  chain/client/src/chunks_delay_tracker.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
Labels: S-automerge

#6488 nit(state-viewer): print out current gas limit in apply command
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#6509 doc: Describe fee estimations
  runtime/runtime-params-estimator/src/cost.rs
Labels: S-automerge

#6508 enable rpc endpoint for mock_network
  integration-tests/src/bin/start_mock_network.rs
  integration-tests/src/mock_network/setup.rs
Labels: S-automerge
