Repository near/nearcore, pull requests merged in 2022-10, with the labels that each got.

#7748 fix: typo
  core/store/src/lib.rs
Labels: S-automerge

#7747 pytest: fix Rosetta test after addition of transfer_fee_type
  pytest/tests/sanity/rosetta.py
Labels: P-high, S-automerge

#7738 integration-tests: enable test_tps_regression::test_highload expensive tests
  integration-tests/src/tests/test_tps_regression.rs
Labels: A-testing, P-low, S-automerge

#7743 store: stop TrieUpdateIterator after error is encountered
  core/store/src/trie/update.rs
Labels: P-low, S-automerge

#7711 feat(o11y): Export basic node config values as static opentelemetry attributes
  Cargo.lock
  Cargo.toml
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  neard/src/cli.rs
  pytest/lib/cluster.py
  tools/chainsync-loadtest/src/main.rs
  tools/indexer/example/src/main.rs
  tools/restaked/src/main.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#7742 store: introduce StoreUpdateStorage to StoreUpdate
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: P-low, S-automerge

#7753 docs: refresh CONTRIBUTING.md
  CONTRIBUTING.md
  docs/architecture/README.md
Labels: S-automerge

#7724 fix: compare head heights before updating flat storage
  chain/chain/src/chain.rs
  core/store/src/flat_state.rs
Labels: S-automerge, T-storage

#7750 chore: ensure that rust-toolcahin and Cargo.toml rust-versions are co…
  tools/themis/src/main.rs
  tools/themis/src/rules.rs
  tools/themis/src/types.rs
  tools/themis/src/utils.rs
Labels: S-automerge

#7416 view_client: remove confusing comment about ‘legacy support’ around TxStatus
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7754 changelog: add 1.29.0 changes
  CHANGELOG.md
Labels: S-automerge

#7755 doc: move build optimization content from wiki into internal docs
  CONTRIBUTING.md
  docs/SUMMARY.md
  docs/practices/fast_builds.md
Labels: S-automerge

#7737 Add information about chunk producer and block timestamp to state-viewer
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#7763 fix: race condition in rpctypegen macro
  Cargo.lock
  tools/rpctypegen/macro/Cargo.toml
  tools/rpctypegen/macro/src/lib.rs
Labels: S-automerge

#7764 nearcore: don’t serialise `archive` if false
  nearcore/src/config.rs
Labels: P-low, S-automerge

#7765 fix: broken pytest
  Cargo.toml
  pytest/tests/loadtest/contract/Cargo.toml
Labels: S-automerge

#7759 enabled TIER1 peer discovery in all envs
  CHANGELOG.md
  nearcore/src/config.rs
Labels: S-automerge

#7719 fix: disallowed loop connections
  chain/network/src/lib.rs
  chain/network/src/network_protocol/edge.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/stream.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer/tests/stream.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/connection/tests.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/private_actix.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/tcp.rs
  chain/network/src/testonly/stream.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#7760 core: add simple unit test for CryptoHash::hash_borsh and hash_borsh_slice
  core/primitives-core/src/hash.rs
Labels: P-low, S-automerge

#7779 store: introduce CompiledContractCache::has to avoid data cloning
  core/primitives/src/types.rs
  core/store/src/lib.rs
  runtime/near-vm-runner/src/cache.rs
Labels: P-low, S-automerge

#7772 store: move TrieIterator to separate module
  core/store/src/trie/update.rs
  core/store/src/trie/update/iterator.rs
Labels: P-low, S-automerge

#7768 feat: gc deltas and block infos from flat storage
  core/store/src/flat_state.rs
Labels: S-automerge

#7786 runtime-params-estimator: remove unused walrus dependency
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: P-low, S-automerge

#7762 feat(o11y): Disable span events in logs by default
  core/o11y/src/lib.rs
Labels: S-automerge

#7746 feat: discard non-finalizable blocks
  chain/chain-primitives/src/error.rs
  chain/chain/src/chain.rs
  chain/chain/src/tests/challenges.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7776 doc: fix typo in chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/mod.rs
Labels: S-automerge

#7728 doc: remove obsolete metrics docs
  METRICS.md
Labels: S-automerge

#7790 runtime: prefer block_height field name and remove obsolete TODOs
  core/primitives/src/runtime/apply_state.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/src/runtime/mod.rs
  runtime/near-test-contracts/contract-for-fuzzing-rs/src/lib.rs
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-logic/src/context.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/context.rs
  runtime/near-vm-logic/src/tests/fixtures.rs
  runtime/near-vm-logic/src/tests/view_method.rs
  runtime/near-vm-runner/fuzz/src/lib.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer/mod.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
Labels: P-low, S-automerge

#7794 doc: fix typo sing -> sign
  core/primitives/src/transaction.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7773 feat(o11y): Attach tracing context to ClientActor work items
  Cargo.lock
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/bug_repros.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/consensus.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/query_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/private_actix.rs
  chain/network/src/testonly/fake_client.rs
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/src/lib.rs
  core/o11y/Cargo.toml
  core/o11y/src/context.rs
  core/o11y/src/lib.rs
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock-node/src/lib.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7793 pytest: fix tests after archive flag changes
  pytest/lib/cluster.py
Labels: A-testing, P-high, S-automerge, A-python-test

#7771 core: introduce CryptoHash::hash_borsh_iter method
  chain/chain/src/chain.rs
  core/primitives-core/src/hash.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
Labels: P-low, S-automerge

#7796 Remove deepsize dependency
  Cargo.lock
  Cargo.toml
  chain/client-primitives/src/debug.rs
  chain/jsonrpc-adversarial-primitives/Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/network_protocol/edge.rs
  chain/network/src/network_protocol/peer.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  core/account-id/Cargo.toml
  core/account-id/src/lib.rs
  core/crypto/Cargo.toml
  core/crypto/src/signature.rs
  core/crypto/src/vrf.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/account.rs
  core/primitives-core/src/hash.rs
  core/primitives/Cargo.toml
  core/primitives/src/block.rs
  core/primitives/src/block_header.rs
  core/primitives/src/challenge.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/errors.rs
  core/primitives/src/merkle.rs
  core/primitives/src/network.rs
  core/primitives/src/rand.rs
  core/primitives/src/receipt.rs
  core/primitives/src/sharding.rs
  core/primitives/src/sharding/shard_chunk_header_inner.rs
  core/primitives/src/syncing.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
Labels: P-low, S-automerge

#7797 Revert "json: remove deprecated old style path+data request format"
  CHANGELOG.md
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
  chain/jsonrpc/src/api/query.rs
  core/primitives-core/src/serialize.rs
Labels: P-high, S-automerge

#7798 fix: adjust behaviour of chunk nodes cache test
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
Labels: S-automerge

#7801 fix: failing mock node test for flat state
  tools/mock-node/src/lib.rs
Labels: S-automerge

#7803 store: simplify RocksDB::iter, iter_prefix and iter_raw_bytes
  core/store/src/db/rocksdb.rs
Labels: P-low, S-automerge

#7781 o11y: introduce Bytes to format binary data in a smart way
  core/o11y/src/lib.rs
  core/o11y/src/pretty.rs
  core/primitives-core/src/serialize.rs
  core/store/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
Labels: P-low

#7766 doc: freshen architecture overview
  docs/architecture/README.md
Labels: S-automerge

#7789 Flat storage: fix two tests around state sync and block catchup
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  integration-tests/src/tests/client/features/fix_storage_usage.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/benches/store.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7800 core: accept passing arguments by value in CryptoHash::hash_bytes
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/network/src/network_protocol/edge.rs
  chain/network/src/network_protocol/mod.rs
  core/primitives-core/src/hash.rs
  core/primitives/src/merkle.rs
  core/primitives/src/network.rs
  core/primitives/src/transaction.rs
  core/primitives/src/validator_signer.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  runtime/near-vm-runner/src/cache.rs
Labels: P-low, S-automerge

#7729 chore: remove obsolete license
  LICENSE
Labels: S-automerge

#7823 doc: fix typo treasure -> treasury
  runtime/runtime/src/lib.rs
Labels: S-automerge

#7778 moved connection::Connection to PeerStatus
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/connection/tests.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/private_actix.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/routing_table_view.rs
Labels: S-automerge

#7815 refactor: split guest aborts / runtime errors
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
  runtime/near-vm-runner/fuzz/fuzz_targets/runner.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/errors.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/memory.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#7826 doc: move GC docs over from confluence
  docs/architecture/how/gc.md
Labels: S-automerge

#7814 refactor: remove dead code
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/types.rs
Labels: S-automerge

#7833 Fuzz the running releases
  nightly/fuzz.toml
Labels: S-automerge

#7835 [TransactionResult] Avoid panicing if original column had duplicate entries
  core/store/src/migrations.rs
Labels: S-automerge

#7838 docs: move epoch docs from confluence
  docs/SUMMARY.md
  docs/architecture/how/epoch.md
Labels: S-automerge

#7837 docs: move sync docs from confluence
  docs/SUMMARY.md
  docs/architecture/how/sync.md
Labels: S-automerge

#7752 nearcore: run node in archival mode if database is an archive
  nearcore/src/lib.rs
  neard/src/cli.rs
Labels: S-automerge

#7828 client: add {node,validator}_public_key field to /status response; deprecated node_key
  CHANGELOG.md
  chain/client/src/client_actor.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7834 fix(o11y): Write all logs to stderr
  core/o11y/src/lib.rs
  pytest/lib/cluster.py
Labels: S-automerge

#7727 refactor: move get_validator_info to EpochManagerAdapter
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7841 chain: don’t clone Store in RuntimeAdapter::get_store
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client_actor.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7850 docs: move transaction routing from confluence
  docs/SUMMARY.md
  docs/architecture/how/tx_routing.md
Labels: S-automerge

#7849 refactor: move `UnsupportedCompiler` to errors
  chain/jsonrpc/res/rpc_errors_schema.json
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7756 Introduce database kind
  chain/client/src/metrics.rs
  core/store/src/config.rs
  core/store/src/db.rs
  core/store/src/db/rocksdb.rs
  core/store/src/lib.rs
  core/store/src/metadata.rs
  core/store/src/migrations.rs
  core/store/src/opener.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  neard/src/main.rs
Labels: S-automerge

#7853 nit: fix mixed up info log on chain init
  chain/chain/src/chain.rs
Labels: S-automerge

#7852 refactor: don't lose underlying io::Error in CacheError
  Cargo.lock
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7816 fix: make non-integration tests work with flat storage
  nearcore/src/runtime/mod.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7782 chain: reuse more types in JSON RPC fuzzer
  Cargo.lock
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/types/blocks.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc-primitives/src/types/gas_price.rs
  chain/jsonrpc-primitives/src/types/validator.rs
  chain/jsonrpc/fuzz/Cargo.toml
  chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs
  core/account-id/Cargo.toml
  core/account-id/src/lib.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/hash.rs
  core/primitives/Cargo.toml
  core/primitives/src/types.rs
Labels: P-low, S-automerge

#7819 Trace context for the following actors:
  chain/chunks/src/client.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/bug_repros.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  chain/indexer/src/streamer/fetchers.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/testonly/fake_client.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/lib.rs
  chain/rosetta-rpc/src/utils.rs
  chain/telemetry/src/lib.rs
  core/o11y/src/lib.rs
  core/o11y/src/macros.rs
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/rpc_error_structs.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/nearcore/run_nodes.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/nearcore/track_shards.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock-node/benches/sync.rs
  tools/mock-node/src/main.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7862 doc: fix typo 'orphan'
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
Labels: S-automerge

#7777 doc: fix typo in chain/rosetta-rpc/src/lib.rs
  chain/chunks/src/lib.rs
  chain/epoch-manager/src/lib.rs
  chain/epoch-manager/src/tests/mod.rs
  chain/rosetta-rpc/src/lib.rs
Labels: S-automerge

#7851 refactor: streamline contract caching code
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7863 jsonrpc: check base58 length limit before the whole buffer is decoded
  Cargo.lock
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/api/query.rs
  core/primitives-core/src/serialize.rs
Labels: P-low, S-automerge

#7873 chore: remove FunctionCallError::_EVMError
  runtime/near-vm-errors/src/lib.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7867 store: remove unused version.rs file
  core/store/src/version.rs
Labels: P-low, S-automerge

#7866 feat(o11y): Attach tracing context to messages received by PeerManagerActor
  Cargo.lock
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/routing/actor.rs
  chain/network/src/routing/edge_validator_actor.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  chain/telemetry/src/lib.rs
  core/o11y/src/macros.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  tools/chainsync-loadtest/src/network.rs
  tools/mock-node/src/lib.rs
Labels: S-automerge

#7874 fix: remove second memory in smallest_rs_contract
  runtime/near-test-contracts/src/lib.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: S-automerge

#7880 core: represent no voting schedule as timestamp in the past
  chain/client/src/metrics.rs
  core/primitives/src/upgrade_schedule.rs
  core/primitives/src/version.rs
Labels: P-low, S-automerge

#7870 store: pass StoreUpdate as argument to ShardTries::apply_all
  chain/chain/src/tests/gc.rs
  core/store/benches/trie_bench.rs
  core/store/src/test_utils.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/testbed.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/genesis.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
Labels: P-low, S-automerge

#7840 Add option to verify proofs to neard
  CHANGELOG.md
  Cargo.lock
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  neard/Cargo.toml
  neard/res/invalid_proof.json
  neard/res/proof_example.json
  neard/src/cli.rs
Labels: S-automerge

#7881 refactor: remove `ContractCallError`
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives/src/errors.rs
  integration-tests/src/tests/runtime/test_evil_contracts.rs
  integration-tests/src/tests/standard_cases/mod.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/runtime/src/actions.rs
Labels: S-automerge

#7886 o11y: introduce pretty::AbbrBytes formatter
  Cargo.lock
  chain/network/src/peer/peer_actor.rs
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  core/o11y/src/pretty.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/logging.rs
  core/primitives/Cargo.toml
  core/primitives/src/receipt.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
Labels: P-low, S-automerge

#7891 docs: document documentation process
  docs/README.md
  docs/SUMMARY.md
  docs/architecture/how/README.md
  docs/practices/docs.md
Labels: S-automerge

#7855 move the check for is_height_processed forward
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7761 Added peer store information to network page
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/res/network_info.html
  chain/jsonrpc/src/api/status.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/debug.rs
  chain/network/src/lib.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  core/primitives/src/views.rs
  nearcore/src/lib.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7885 Do not use flat storage for storage_write
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/update.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/near-vm-logic/src/tests/storage_read_write.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/ext.rs
Labels: S-automerge

#7749 feat: limit trie cache by memory consumption
  CHANGELOG.md
  core/store/src/trie/config.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
Labels: S-automerge

#7183 feat: add a transaction mirror binary
  Cargo.lock
  Cargo.toml
  core/chain-configs/src/genesis_config.rs
  core/chain-configs/src/lib.rs
  neard/Cargo.toml
  neard/src/cli.rs
  pytest/lib/key.py
  pytest/tools/mirror/test.py
  tools/mirror/Cargo.toml
  tools/mirror/README.md
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/cli.rs
  tools/mirror/src/genesis.rs
  tools/mirror/src/key_mapping.rs
  tools/mirror/src/lib.rs
  tools/mirror/src/metrics.rs
  tools/mirror/src/secret.rs
Labels: S-automerge

#7897 refactor: simplify error handling in main
  neard/src/cli.rs
  neard/src/main.rs
Labels: S-automerge

#7904 doc: fix typos
  core/primitives/src/errors.rs
  pytest/lib/mocknet.py
  tools/delay-detector/README.md
Labels: S-automerge

#7907 crypto: Remove unused randomness module
  core/crypto/src/lib.rs
  core/crypto/src/randomness.rs
  core/crypto/src/vrf.rs
Labels: P-low, S-automerge

#7905 doc: update logo
  docs/images/logo.svg
Labels: S-automerge

#7906 [Debug UI] Fixed bug in network html when syncing
  chain/jsonrpc/res/network_info.html
Labels: S-automerge

#7914 Prefer implementing `Display` to `From<T>` for `String`
  chain/client-primitives/src/types.rs
  core/crypto/src/signature.rs
Labels: P-low, S-automerge

#7913 replaced Client struct with async_trait
  Cargo.lock
  Cargo.toml
  chain/client/Cargo.toml
  chain/client/src/adapter.rs
  chain/client/src/lib.rs
  chain/network/Cargo.toml
  chain/network/src/client.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/test_utils.rs
  chain/network/src/testonly/fake_client.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/Cargo.toml
  tools/chainsync-loadtest/src/main.rs
  tools/chainsync-loadtest/src/network.rs
Labels: S-automerge

#7900 mirror: make it easier to see what happened in debug logs
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/lib.rs
Labels: S-automerge

#7915 chain: remove TxStatusError::InvalidTx variant
  chain/client-primitives/src/types.rs
  chain/jsonrpc/src/api/transactions.rs
  chain/rosetta-rpc/src/errors.rs
Labels: S-automerge

#7912 core: add chain Error → TxStatusError conversion
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
Labels: S-automerge

#7864 fix(sync): Prevent state sync from being terminally verbose
  chain/client/src/sync.rs
Labels: S-automerge

#7918 doc: gas cost parameter chapter
  docs/SUMMARY.md
  docs/architecture/gas_params/README.md
  docs/architecture/gas_params/estimator.md
  docs/architecture/gas_params/gas_profile.md
  docs/architecture/gas_params/parameter_definition.md
Labels: S-automerge

#7889 Changelog: include o11y changes
  CHANGELOG.md
Labels: S-automerge

#7871 store: introduce cold storage
  chain/indexer/src/streamer/mod.rs
  core/store/Cargo.toml
  core/store/benches/store_bench.rs
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  core/store/src/metadata.rs
  core/store/src/opener.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/Cargo.toml
  nearcore/benches/store.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  neard/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
  test-utils/store-validator/src/main.rs
  tools/mirror/src/lib.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#7908 moved Network(View)Client(Messages/Responses) to near_client
  chain/client/src/adapter.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/bug_repros.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/consensus.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/types.rs
  chain/rosetta-rpc/src/lib.rs
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  tools/mirror/src/lib.rs
  tools/mock-node/src/lib.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge

#7922 doc: Minor grammar fixes
  docs/architecture/gas_params/README.md
  docs/architecture/gas_params/estimator.md
  docs/architecture/gas_params/gas_profile.md
Labels: S-automerge

#7920 core: remove unused to_base58 function
  core/primitives-core/src/serialize.rs
Labels: P-low, S-automerge

#7924 chain: remove unnecessary `mut` from self reference
  chain/chain/src/chain.rs
Labels: P-low, S-automerge

#7898 [refactor] Refactor client and client actor to move the code for block processing to client
  chain/chain/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/tests/mod.rs
  chain/client/src/tests/process_blocks.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7890 moved PeerStore from PeerManagerActor to NetworkState.
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store/mod.rs
  chain/network/src/peer_manager/peer_store/testonly.rs
  chain/network/src/peer_manager/peer_store/tests.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/private_actix.rs
  chain/network/src/test_utils.rs
  chain/network/src/types.rs
  integration-tests/src/tests/nearcore/node_cluster.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/routing.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/res/example-config-gc.json
  nearcore/res/example-config-no-gc.json
  neard/src/cli.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#7934 doc: parameter overview
  docs/architecture/gas/README.md
Labels: S-automerge

#7935 o11y: introduce pretty::Slice for formatting slices of arbitrary types
  core/o11y/src/pretty.rs
  core/primitives-core/src/lib.rs
  core/primitives-core/src/logging.rs
  core/primitives/src/lib.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
Labels: P-low, S-automerge

#7895 split Network(View)ClientMessage enum into separate actix messages.
  chain/client/src/adapter.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/bug_repros.rs
  chain/client/src/tests/catching_up.rs
  chain/client/src/tests/consensus.rs
  chain/client/src/tests/cross_shard_tx.rs
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  chain/jsonrpc/src/lib.rs
  chain/rosetta-rpc/src/lib.rs
  integration-tests/src/tests/client/chunks_management.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  tools/mirror/src/lib.rs
  tools/mock-node/src/lib.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge

#7930 Change debug page to display error messages in block processing
  chain/chain/src/blocks_delay_tracker.rs
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/client.rs
  chain/jsonrpc/res/chain_n_chunk_info.html
  core/primitives/src/views.rs
Labels: S-automerge

#7910 Changing peer selection process & show connection errors in debug page
  chain/jsonrpc/res/network_info.html
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store/mod.rs
  chain/network/src/peer_manager/peer_store/tests.rs
  chain/network/src/store/schema/mod.rs
  chain/network/src/types.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7941 Split peer_manager tests into multiple files.
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/connection_pool.rs
  chain/network/src/peer_manager/tests/mod.rs
  chain/network/src/peer_manager/tests/nonce.rs
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#7940 Removed the delay before the initial SyncRoutingTable.
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#7909 Added test for genesis hash
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7939 feat: add a neard amend-genesis command
  Cargo.lock
  neard/Cargo.toml
  neard/src/cli.rs
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tools/mirror/test.py
  tools/amend-genesis/Cargo.toml
  tools/amend-genesis/src/cli.rs
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#7945 chain: flatten match pattern to reduce indentation depth
  chain/client/src/view_client.rs
Labels: P-low, S-automerge

#7947 docs: move docs about receipts from confluence
  docs/SUMMARY.md
  docs/architecture/how/tx_receipts.md
Labels: S-automerge

#7923 chore: introduce `--profile prod`
  Cargo.toml
  Makefile
  docs/practices/fast_builds.md
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#7953 crypto: move base58 formatting into single struct reducing duplication
  core/crypto/src/signature.rs
Labels: P-low, S-automerge

#7957 docs: review docs/practices/docs.md
  docs/practices/docs.md
Labels: S-automerge

#7956 docs: proof-read fast-builds nearcore book page
  docs/practices/fast_builds.md
Labels: S-automerge

#7952 doc: how to add a new parameter
  docs/architecture/gas/parameter_definition.md
Labels: S-automerge

#7578 feat: trie cache configuration
  CHANGELOG.md
  core/primitives/src/shard_layout.rs
  core/store/src/config.rs
  core/store/src/trie/config.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7955 refactor: cleanup ed25519_verify
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/ed25519_verify.rs
Labels: S-automerge

#6914 Speedy-sync - experimental tool for faster syncing
  Cargo.lock
  Cargo.toml
  chain/epoch-manager/src/lib.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/merkle.rs
  tools/speedy_sync/Cargo.toml
  tools/speedy_sync/README.md
  tools/speedy_sync/src/main.rs
Labels: S-automerge

#7963 fixed compilation error in store_bench
  core/store/benches/store_bench.rs
Labels: S-automerge

#7962 [DEBUG] move chain processing status to a separate API endpoint
  chain/client-primitives/src/debug.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc/res/chain_n_chunk_info.html
  chain/jsonrpc/src/api/status.rs
  chain/jsonrpc/src/lib.rs
  core/primitives/src/views.rs
Labels: S-automerge

#7946 Download records.json when initializing configs
  chain/indexer/src/lib.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  runtime/runtime-params-estimator/src/main.rs
  tools/indexer/example/src/configs.rs
Labels: S-automerge

#7948 fix(amend-genesis): remove unwanted changes to the output genesis
  pytest/lib/mocknet.py
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#7541 feat: add a ping tool
  Cargo.lock
  Cargo.toml
  chain/network/src/lib.rs
  chain/network/src/raw/connection.rs
  chain/network/src/raw/mod.rs
  chain/network/src/raw/tests.rs
  neard/Cargo.toml
  neard/src/cli.rs
  tools/ping/Cargo.toml
  tools/ping/src/cli.rs
  tools/ping/src/csv.rs
  tools/ping/src/lib.rs
Labels: S-automerge

#7968 fix(mocknet): Fix config.json
  pytest/lib/mocknet.py
Labels: S-automerge
