Repository near/nearcore, pull requests merged in 2022-09, with the labels that each got.

#7523 network: introduce near_peer_message_sent_by_type_{bytes,total} metrics
  CHANGELOG.md
  chain/network/src/peer/peer_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7494 store: avoid Vec conversion when getting data from RocksDB
  chain/chain/src/chain.rs
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/db/slice.rs
  core/store/src/db/testdb.rs
  core/store/src/flat_state.rs
  core/store/src/lib.rs
Labels: S-automerge

#7517 pytest: fix one_val.py test
  pytest/tests/sanity/one_val.py
Labels: P-high, S-automerge, A-python-test

#7443 Fix compilation determinism issue
  nightly/fuzz.toml
  runtime/near-vm-runner/src/instrument/stack_height/thunk.rs
  runtime/near-vm-runner/src/tests/__fuzz__/tests__fuzzers__wasmer2_is_reproducible/crashes/crash-7efd70f50949e0fdff8f4c8d6cc66709faf6d3cf
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: S-automerge

#7529 Shardnet release schedule
  core/primitives/src/version.rs
Labels: S-automerge

#7522 Upgrade shardnet shard layout
  chain/epoch-manager/src/validator_selection.rs
  core/primitives/src/epoch_manager.rs
  core/primitives/src/shard_layout.rs
  core/primitives/src/version.rs
Labels: S-automerge

#7527 feat(estimator): remove IO costs in icount/qemu
  runtime/runtime-params-estimator/src/estimator_params.rs
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#7533 core: avoid double Vec::last call in TrieItorator::iter_step
  core/store/src/trie/iterator.rs
Labels: P-low, S-automerge

#7536 refactor: split out some more tests from `process_blocks.rs`
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/cap_max_gas_price.rs
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/wasmer2.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7537 refactor: split out some more tests from `process_blocks.rs`
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/features/limit_contract_functions_number.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#7503 refactored PeerActor::new
  chain/network/src/actix.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/private_actix.rs
  chain/network/src/test_utils.rs
  chain/network/src/testonly/mod.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  nearcore/src/lib.rs
  tools/chainsync-loadtest/src/main.rs
Labels: S-automerge

#7532 feat(estimator): option to select metric
  runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
Labels: S-automerge

#7530 feat: track current sizes of network buffers
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#7534 Add catchup info to debug page
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/debug.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/info.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/jsonrpc/res/sync.html
  chain/jsonrpc/src/lib.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7538 Add RejectBlocksWithOutdatedProtocolVersions to the next shardnet release
  chain/chain/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
Labels: S-automerge

#7548 network: deprecate near_peer_message_received_total
  CHANGELOG.md
  chain/network/src/stats/metrics.rs
Labels: P-low, S-automerge

#7539 chore: remove dead code
  core/metrics/src/lib.rs
Labels: S-automerge

#7547 Prefer `&[T]` to `&Vec<T>`
  chain/chain/src/chain.rs
  chain/chain/src/doomslug.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/sync.rs
  chain/client/src/test_utils.rs
  chain/epoch-manager/src/tests/random_epochs.rs
  core/primitives/src/block.rs
  core/primitives/src/sharding.rs
  core/primitives/src/syncing.rs
  core/store/benches/store_bench.rs
  core/store/src/lib.rs
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/update.rs
  genesis-tools/genesis-csv-to-json/src/serde_with.rs
  nearcore/src/runtime/mod.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/tx_dump.rs
Labels: S-automerge

#7544 store: allow configuring RocksDB with support for subset of columns
  core/store/src/db/rocksdb.rs
Labels: S-automerge

#7546 store: make pre-write check thresholds into constants
  core/store/src/db/rocksdb.rs
Labels: P-low

#7555 store: extend test_iterator_seek test
  core/store/src/trie/mod.rs
Labels: S-automerge

#7540 refactor: merge metrics crate into o11y
  Cargo.lock
  Cargo.toml
  chain/chain/Cargo.toml
  chain/chain/src/metrics.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/metrics.rs
  chain/client/Cargo.toml
  chain/client/src/metrics.rs
  chain/client/src/rocksdb_metrics.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/src/lib.rs
  chain/jsonrpc/src/metrics.rs
  chain/network/Cargo.toml
  chain/network/src/peer/codec.rs
  chain/network/src/stats/metrics.rs
  chain/pool/Cargo.toml
  chain/pool/src/metrics.rs
  chain/telemetry/Cargo.toml
  chain/telemetry/src/metrics.rs
  core/metrics/Cargo.toml
  core/metrics/LICENSE-APACHE
  core/metrics/LICENSE-MIT
  core/o11y/Cargo.toml
  core/o11y/README.md
  core/o11y/src/lib.rs
  core/o11y/src/metrics.rs
  core/store/Cargo.toml
  core/store/src/metrics.rs
  core/store/src/trie/trie_storage.rs
  nearcore/Cargo.toml
  nearcore/src/metrics.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/metrics.rs
Labels: S-automerge

#7552 store: move DbVersion and DB_VERSION to near-store
  chain/client/src/metrics.rs
  core/primitives/src/version.rs
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  core/store/src/version.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  neard/src/main.rs
Labels: S-automerge

#7556 refactor: use a simple `if` instead of `match` + `if`
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#7560 store: document migration snapshot options deprecation in change log
  CHANGELOG.md
Labels: P-low, S-automerge

#7550 moved NetworkState to a separate module
  chain/network-primitives/src/types.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests.rs
Labels: S-automerge

#7558 runtime: remove serde implementation from VMContext
  core/primitives-core/src/serialize.rs
  runtime/near-vm-logic/src/context.rs
Labels: P-low, S-automerge

#7561 json: remove dependency on uuid crate
  Cargo.lock
  chain/jsonrpc-primitives/Cargo.toml
  chain/jsonrpc-primitives/src/message.rs
  chain/jsonrpc/client/Cargo.toml
Labels: P-low, S-automerge

#7559 store: move StoreOpener to its own module
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/opener.rs
Labels: S-automerge

#7557 store: make TrieNode’s debug formatting more concise
  core/store/src/trie/mod.rs
Labels: P-low, S-automerge

#7535 store: return raw bytes from Trie::retrieve_node
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
Labels: S-automerge

#7165 NEP-364
  Cargo.lock
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives-core/src/profile.rs
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/parameters.txt
  core/primitives/res/runtime_configs/parameters_testnet.txt
  core/primitives/src/version.rs
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/costs.txt
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#7565 store: extract DBSlice::Rocks into RocksSlice type
  core/store/src/db/slice.rs
Labels: P-low, S-automerge

#7525 Indexer streamer metrics
  Cargo.lock
  chain/indexer/Cargo.toml
  chain/indexer/src/streamer/metrics.rs
  chain/indexer/src/streamer/mod.rs
Labels: S-automerge

#7566 refactor: trie cache configuration
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  core/store/src/trie/config.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: S-automerge

#7000 Replace unmaintained parity-secp256k1 to secp256k1
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/signature.rs
  core/crypto/src/test_utils.rs
Labels: S-automerge

#7410 chain: slight refactor in finality and ‘on chain’ check methods
  chain/chain/src/chain.rs
  chain/client/src/view_client.rs
Labels: S-automerge

#7545 store: rip out pre-write checks
  core/store/src/db/rocksdb.rs
Labels: P-low, S-automerge

#7574 store: introduce StoreOpener::create; deal with version in StoreOpener
  core/store/src/opener.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7562 feat: enable backtraces by default
  CHANGELOG.md
  neard/src/main.rs
Labels: S-automerge

#7577 refactor: remove unused lifetimes
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: S-automerge

#7549 Replaced FrameReader with plain event loop
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/peer/codec.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/actor.rs
  chain/network/src/stats/metrics.rs
  core/o11y/src/metrics.rs
  utils/near-rate-limiter/Cargo.toml
  utils/near-rate-limiter/README.md
  utils/near-rate-limiter/src/framed_read.rs
  utils/near-rate-limiter/src/lib.rs
  utils/near-rate-limiter/src/message_wrapper.rs
Labels: S-automerge

#7551 added tests for the connection pool
  chain/network/src/broadcast/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer_manager/connection/mod.rs
  chain/network/src/peer_manager/connection/tests.rs
  chain/network/src/peer_manager/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/peer_store/mod.rs
  chain/network/src/peer_manager/peer_store/tests.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/sink.rs
Labels: S-automerge

#7572 nightly: enable couple tests which are passing
  nightly/pytest-sanity.txt
Labels: P-low, S-automerge

#7575 Fix failed state_sync_fail.py test on nayduck
  nightly/pytest-sanity.txt
  pytest/tests/sanity/state_sync_fail.py
Labels: S-automerge

#7569 feat: stabilize account_id_in_function_call_permission protocol feature
  CHANGELOG.md
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/57.txt
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__57.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_57.json.snap
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
Labels: S-automerge

#7581 Prefer `to_string` to `format!("{}")`
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/client/src/client.rs
  chain/client/src/info.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/message.rs
  chain/network/src/network_protocol/tests.rs
  core/crypto/src/signature.rs
  core/o11y/benches/metrics.rs
  core/o11y/src/io_tracer.rs
  core/primitives/src/validator_signer.rs
  core/store/src/db/colddb.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  docs/style.md
  genesis-tools/keypair-generator/src/main.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  runtime/runtime/tests/test_async_calls.rs
  test-utils/runtime-tester/fuzz/fuzz_targets/runtime_fuzzer.rs
Labels: S-automerge

#7563 Replace opentelemetry-jaeger with opentelemetry-otlp as a more flexible alternative.
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  deny.toml
Labels: S-automerge

#7583 fix: don't enable mocknode feature unconditionally
  chain/chain/src/store.rs
  chain/epoch-manager/src/lib.rs
  tools/mock-node/Cargo.toml
  tools/mock-node/README.md
  tools/mock-node/benches/README.md
Labels: S-automerge

#7473 adding view_trie to state-viewer
  core/store/src/trie/mod.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#7587 near-vm-runner: fix m1 build
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: S-automerge

#7585 store: replace TrieIterator::seek by seek_prefix
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/update.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#7588 state-viewer: avoid unnecessary Arc
  tools/state-viewer/src/apply_chain_range.rs
Labels: P-low, S-automerge

#7591 store: replace StoreOpener::create with Mode::Create
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/opener.rs
  nearcore/benches/store.rs
  nearcore/src/lib.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#7594 store: propagate error when deleting the snapshot
  core/store/src/db/rocksdb/snapshot.rs
  nearcore/src/lib.rs
Labels: S-automerge

#7589 minor network API cleanup
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/testonly.rs
  chain/network/src/peer/tests/communication.rs
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests.rs
  chain/network/src/types.rs
Labels: S-automerge

#7593 store: add proof to ViewState response
  core/primitives/src/views.rs
  core/store/src/lib.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#7600 Fix failing tests by removing an assert that was actually possible
  chain/chunks/src/lib.rs
Labels: S-automerge

#7597 buildkite: don’t start Redis when running tests
  .buildkite/pipeline.yml
Labels: P-low, S-automerge, A-CI

#7601 json: remove deprecated old style path+data request format
  CHANGELOG.md
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
  chain/jsonrpc/src/api/query.rs
  core/primitives-core/src/serialize.rs
  integration-tests/src/user/rpc_user.rs
Labels: S-automerge

#7607 pytest: fix db_migration.py after changes to migration config options
  pytest/tests/sanity/db_migration.py
Labels: P-high, S-automerge

#7592 Structural implementation of flat storage
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/store/src/flat_state.rs
  core/store/src/trie/shard_tries.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7611 VersionedPartialEncodedChunk is important
  chain/network-primitives/src/network_protocol/mod.rs
Labels: S-automerge

#7610 removed deprecated RoutedMessageBody::PartialEncodedChunk
  chain/network-primitives/src/network_protocol/mod.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7590 feat: prefetch accounts and access keys
  Cargo.lock
  core/store/Cargo.toml
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/trie/config.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/lib.rs
  runtime/runtime/src/prefetch.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#7609 Mark BlockHeader as insert only
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#7604 feat: add flat state deltas for each shard
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  core/primitives/src/state.rs
  core/store/src/columns.rs
  core/store/src/flat_state.rs
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/Cargo.toml
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/genesis.rs
Labels: S-automerge, T-storage

#7613 Function call success and error metrics
  Cargo.lock
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/metrics.rs
Labels: S-automerge

#7620 feat: argument based prefetcher
  Cargo.lock
  core/store/src/config.rs
  core/store/src/metrics.rs
  core/store/src/trie/config.rs
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/metrics.rs
  runtime/runtime/src/prefetch.rs
Labels: S-automerge

#7619 fix: Fix a compiler warning on mac
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: S-automerge

#7615 Prefer CryptoHash::hash_borsh to try_to_vec+hash combo
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  core/primitives/src/challenge.rs
  core/primitives/src/merkle.rs
  core/primitives/src/validator_signer.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/standard_cases/mod.rs
  runtime/near-vm-runner/src/cache.rs
Labels: P-low, S-automerge

#7626 network: avoid double Arc::clone in NetworkState
  chain/network/src/peer_manager/network_state.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: P-low, S-automerge

#7632 store: deprecate GCCount column
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/store_validator/validate.rs
  core/primitives-core/src/types.rs
  core/store/src/columns.rs
  core/store/src/db/rocksdb.rs
  test-utils/store-validator/src/main.rs
Labels: P-low, S-automerge

#7456 Use jemalloc in rocksdb
  Cargo.lock
  chain/indexer/Cargo.toml
  core/store/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#7629 Minor fixes to documentation
  chain/chunks/src/lib.rs
  chain/client/src/client_actor.rs
  chain/network/src/concurrency/demux.rs
  chain/network/src/config_json.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/models.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/version.rs
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/db/slice.rs
  core/store/src/opener.rs
  core/store/src/trie/state_parts.rs
  core/store/src/version.rs
  nearcore/src/download_file.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/receipt_manager.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_params.rs
  runtime/runtime/src/prefetch.rs
  tools/themis/src/style.rs
Labels: P-low, S-automerge

#7630 core: replace ShardChunkHeader::version_range by valid_for
  chain/chunks/src/lib.rs
  core/primitives/src/sharding.rs
  core/primitives/src/version.rs
Labels: P-low, S-automerge

#7612 primitives: optimise ExecutionOutcomeWithId::to_hashes
  core/primitives/src/transaction.rs
Labels: P-low, S-automerge

#7633 chore: remove deprecated crate
  runtime/near-test-contracts/test-contract-rs/Cargo.lock
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
Labels: S-automerge

#7608 store: remove TrieUpdate::range
  core/store/src/trie/update.rs
Labels: S-automerge

#7640 feat: Remove feature of disabling jemalloc
  neard/Cargo.toml
  neard/src/main.rs
Labels: S-automerge

#7603 view_state: add include_proof argument to view state request
  CHANGELOG.md
  chain/client/src/test_utils.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_query.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  integration-tests/src/user/rpc_user.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/adapter.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: P-high, S-automerge

#7644 fix: estimator contract and feature_ed25519_verify
  runtime/near-test-contracts/estimator-contract/Cargo.toml
  runtime/near-test-contracts/estimator-contract/src/lib.rs
Labels: S-automerge

#7651 feat: icount estimations without RocksDB
  core/store/src/db/testdb.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  runtime/runtime-params-estimator/src/config.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#7614 Implement flat storage factory
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/store/src/flat_state.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7281 add cops to chunk management tests
  chain/chain/src/test_utils/validator_schedule.rs
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#7617 feat: tests and stubs for flat storage deltas
  core/primitives/src/state.rs
  core/store/src/flat_state.rs
Labels: S-automerge, T-storage

#7643 fix: flaky test
  .buildkite/pipeline.yml
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7624 Add 'near_' prefix to metrics exported from nearcore for consistency
  chain/client/src/metrics.rs
  chain/network/src/stats/metrics.rs
  docs/style.md
Labels: S-automerge

#7658 integration-tests: fix hashing of a list of elements
  core/primitives-core/src/hash.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
Labels: P-high, S-automerge

#7652 refactor: add EpochManagerAdapter infra
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  chain/epoch-manager/src/lib.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7655 refactor: move validator accessor to EpochManagerHandle
  Cargo.lock
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test_utils.rs
  chain/epoch-manager/Cargo.toml
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#7656 refactor: move signature verification functions to EpochManagerAdapter
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7667 fix: disable life support for nearlib test
  .buildkite/pipeline.yml
  scripts/nodelib.py
  scripts/start_unittest.py
  scripts/test_nearlib.sh
Labels: S-automerge

#7646 Optimize prometheus metrics which are incremented most often
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/benches/metrics.rs
  core/store/Cargo.toml
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  docs/style.md
Labels: S-automerge

#7659 refactor: prettify chunk management test
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#7657 refactor: move verify_approvals_and_threshold_orphan to EMA
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7660 refactor: move shard layout API to EpochManagerAdapter
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7665 move block->epoch APIs to EpochManagerHandle
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#7666 refactor: expose get_epoch_id as a method of EpochManagerAdapter
  chain/chain/src/test_utils.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7647 Allowing configure more peer-related things in config
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#7664 fix: actually test dropping chunk forwarding
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#7661 feat: enable receipt prefetching by default
  CHANGELOG.md
  core/store/src/config.rs
  runtime/runtime-params-estimator/src/testbed.rs
Labels: S-automerge

#7668 feat: scaffold for dev guide
  .github/workflows/book.yml
  book/book.toml
  book/src/README.md
  book/src/SUMMARY.md
Labels: S-automerge

#7675 doc: book skeloton
  book/src/README.md
  book/src/SUMMARY.md
  book/src/architecture/README.md
  book/src/misc/README.md
  book/src/practices/README.md
Labels: S-automerge

#7678 doc: improve wording
  book/src/README.md
Labels: S-automerge

#7677 doc: move the content from docs to book
  README.md
  book/src/SUMMARY.md
  book/src/architecture/README.md
  book/src/architecture/network.md
  book/src/architecture/trie.md
  book/src/images/architecture.svg
  book/src/images/logo.svg
  book/src/misc/README.md
  book/src/practices/protocol_upgrade.md
  book/src/practices/style.md
  docs/README.md
  docs/architecture.md
  docs/network.md
  docs/protocol_upgrade.md
  docs/trie.md
Labels: S-automerge

#7684 refactor: more useful error message
  chain/chain-primitives/src/error.rs
Labels: S-automerge

#7688 chore: Update a couple of more crates to 1.64
  chain/chain/Cargo.toml
  core/account-id/Cargo.toml
Labels: S-automerge

#7690 feat: always display uncertain estimation warnings
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-2.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-3.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command-4.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/snapshots/estimator_warehouse__check__tests__check_command.snap
  runtime/runtime-params-estimator/estimator-warehouse/src/zulip.rs
Labels: S-automerge, A-params-estimator

#7663 Implement FlatStorageState
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/primitives/src/errors.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
  tools/mock-node/Cargo.toml
Labels: S-automerge

#7691 Upgrade tracing and opentelemetry crates
  Cargo.lock
  chain/jsonrpc/Cargo.toml
  chain/network-primitives/Cargo.toml
  chain/network/Cargo.toml
  core/o11y/Cargo.toml
  neard/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#7699 chore: remove unused dependency
  Cargo.lock
  core/o11y/Cargo.toml
Labels: S-automerge

#7700 fix: do not block on prefetcher
  core/store/src/trie/prefetching_trie_storage.rs
Labels: S-automerge

#7702 fix(mocknet): Don't report mocknet telemetry to the mainnet explorer
  pytest/lib/mocknet.py
Labels: S-automerge

#7707 themis: publishable crates shouldn't depend on non-publishable ones
  core/o11y/Cargo.toml
  core/o11y/LICENSE-APACHE
  core/o11y/LICENSE-MIT
  tools/themis/src/main.rs
  tools/themis/src/rules.rs
  tools/themis/src/types.rs
  tools/themis/src/utils.rs
Labels: S-automerge

#7673 refactor: move shard_layout_from_prev_block to EMA
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge

#7701 feat(o11y): Configure opentelemetry filter at runtime
  Cargo.lock
  core/o11y/Cargo.toml
  core/o11y/src/lib.rs
  neard/src/log_config_watcher.rs
Labels: S-automerge

#7710 fix: create FlatStorageState inside RuntimeAdapter
  chain/chain/src/chain.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  core/store/src/flat_state.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge, T-storage

#7712 fix: properly stop prefetching background threads
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#7704 feat(rosetta-rpc): Add Metadata tagging fee-related Operations
  chain/rosetta-rpc/src/adapters/transactions.rs
  chain/rosetta-rpc/src/models.rs
  chain/rosetta-rpc/src/types.rs
Labels: S-automerge

#7726 refactor: simplify get_epoch_sync_data_hash
  chain/chain/src/test_utils.rs
  chain/chain/src/types.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#7734 Fix: typos
  README.md
  docs/src/README.md
Labels: S-automerge

#7584 store: refactor handling of database migration
  core/store/src/config.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  core/store/src/opener.rs
  core/store/src/version.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#7736 doc: get rid of useless src folder
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/architecture/README.md
  docs/architecture/network.md
  docs/architecture/trie.md
  docs/book.toml
  docs/images/architecture.svg
  docs/images/logo.svg
  docs/misc/README.md
  docs/practices/README.md
  docs/practices/protocol_upgrade.md
  docs/practices/style.md
  docs/practices/testing/README.md
  docs/practices/testing/python_tests.md
Labels: S-automerge

#7731 Update rocksdb to 0.19 (#7357)
  Cargo.lock
  Cargo.toml
  core/store/src/db/rocksdb.rs
  deny.toml
Labels: S-automerge

#7730 fix: correct #7667
  scripts/nodelib.py
  scripts/waitonserver.sh
Labels: S-automerge

#7713 doc: Document the tracking issue process
  docs/SUMMARY.md
  docs/practices/tracking_issues.md
Labels: S-automerge

#7740 Avoid Vec allocations where slice suffices
  chain/chain/src/chain.rs
  chain/chain/src/store_validator.rs
  chain/chunks/src/chunk_cache.rs
  chain/chunks/src/lib.rs
  chain/client/src/sync.rs
  chain/epoch-manager/src/tests/mod.rs
  chain/network/src/routing/graph.rs
  chain/network/src/routing/graph_with_cache.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_tests.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  integration-tests/src/tests/standard_cases/mod.rs
  nearcore/src/runtime/mod.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-logic/src/tests/registers.rs
  runtime/near-vm-runner/src/instrument/gas/mod.rs
  runtime/runtime/src/verifier.rs
  runtime/runtime/tests/test_async_calls.rs
  tools/state-viewer/src/state_dump.rs
Labels: P-low, S-automerge
