Repository near/nearcore, pull requests merged in 2023-08, with the labels that each got.

#9362 fix: during resharding, reassign outgoing receipts to lowest index child
  Cargo.lock
  chain/chain-primitives/src/error.rs
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  core/primitives/src/test_utils.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: S-automerge

#9384 fix(loadtest): submit tx on top of final chain
  pytest/lib/cluster.py
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9341 feat: Add compact database tool
  core/store/src/db/rocksdb.rs
  tools/database/README.md
  tools/database/src/analyse_data_size_distribution.rs
  tools/database/src/commands.rs
  tools/database/src/compact.rs
  tools/database/src/lib.rs
  tools/database/src/state_perf.rs
  tools/database/src/utils.rs
Labels: A-storage, S-automerge

#9385 feat(loadtest): Sweat record large batches
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/sweat.py
  pytest/tests/loadtest/locust/locustfiles/sweat.py
Labels: S-automerge

#9391 fix(flat-storage): Handle chain forks gracefully
  chain/chain/src/chain.rs
  core/store/src/flat/storage.rs
Labels: S-automerge

#9376 fix: Verbose handler spans
  chain/chain/src/chain.rs
  chain/chain/src/resharding.rs
  chain/chain/src/types.rs
  chain/client-primitives/src/debug.rs
  chain/client-primitives/src/types.rs
  chain/client/src/adapter.rs
  chain/client/src/client_actor.rs
  chain/network/src/test_utils.rs
  core/o11y/src/macros.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#9380 fix(state-sync): Remove `state_fetch_horizon` because it causes nodes to crash
  Cargo.lock
  chain/client-primitives/src/types.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/block.rs
  chain/client/src/sync/state.rs
  chain/client/src/sync/state_sync_actor.rs
  core/chain-configs/src/client_config.rs
  core/o11y/src/lib.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  nearcore/res/example-config-gc.json
  nearcore/res/example-config-no-gc.json
  nearcore/src/config.rs
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/tests/sanity/gc_after_sync1.py
  pytest/tests/sanity/state_sync_epoch_boundary.py
  pytest/tests/stress/stress.py
  tools/flat-storage/Cargo.toml
Labels: S-automerge

#9397 fix(logging): Add "near_vm" target to near-vm logging
  runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/compiler-singlepass/src/compiler.rs
  runtime/near-vm/compiler/src/translator/environ.rs
  runtime/near-vm/compiler/src/translator/module.rs
  runtime/near-vm/compiler/src/translator/state.rs
  runtime/near-vm/engine/src/universal/code_memory.rs
  runtime/near-vm/engine/src/universal/engine.rs
  runtime/near-vm/engine/src/universal/link.rs
  runtime/near-vm/test-api/src/sys/instance.rs
  runtime/near-vm/test-api/src/sys/module.rs
  runtime/near-vm/vm/src/instance/mod.rs
  runtime/near-vm/vm/src/vmoffsets.rs
Labels: S-automerge

#9398 fix(state-sync): Enable State Sync from GCS by default
  CHANGELOG.md
  chain/client/src/info.rs
Labels: S-automerge

#9403 Delete tier1_network_info RPC endpoint
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#9404 RoutingTableView: fix handling of 0 distances
  tools/debug-ui/src/RoutingTableView.tsx
Labels: S-automerge

#9332 runtime: move actions back to near_primitives
  Cargo.lock
  chain/client/src/test_utils.rs
  chain/rosetta-rpc/src/adapters/mod.rs
  chain/rosetta-rpc/src/adapters/validated_operations/delegate_action.rs
  core/primitives-core/src/types.rs
  core/primitives/Cargo.toml
  core/primitives/src/action/delegate.rs
  core/primitives/src/action/mod.rs
  core/primitives/src/lib.rs
  core/primitives/src/signable_message.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  integration-tests/src/user/mod.rs
  runtime/near-vm-runner/src/logic/dependencies.rs
  runtime/near-vm-runner/src/logic/logic.rs
  runtime/near-vm-runner/src/logic/mocks/mock_external.rs
  runtime/near-vm-runner/src/logic/mod.rs
  runtime/near-vm-runner/src/logic/tests/gas_counter.rs
  runtime/near-vm-runner/src/logic/tests/logs.rs
  runtime/near-vm-runner/src/logic/tests/promises.rs
  runtime/near-vm-runner/src/logic/tests/vm_logic_builder.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/runtime-params-estimator/src/action_costs.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/ext.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/receipt_manager.rs
  runtime/runtime/src/state_viewer/mod.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#9396 fix(logging): Reduce logging verbosity of high-frequency messages
  chain/client/src/client_actor.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#9400 Docs: Update state sync documentation
  docs/architecture/how/sync.md
  docs/misc/state_sync_dump.md
  docs/misc/state_sync_from_external_storage.md
  docs/misc/state_sync_from_s3.md
Labels: S-automerge

#9410 docs: Update loadtest readme
  pytest/tests/loadtest/locust/README.md
Labels: S-automerge

#9407 feat(mocknet): move initialization logic to neard_runner.py
  pytest/tests/mocknet/README.md
  pytest/tests/mocknet/helpers/neard_runner.py
  pytest/tests/mocknet/mirror.py
Labels: S-automerge

#9409 Fix flaky test routing::max_num_peers_limit
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#9390 feat(state-sync) convert state sync messages to peer messages
  chain/client/src/test_utils.rs
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/raw/connection.rs
  chain/network/src/raw/tests.rs
  chain/network/src/types.rs
  tools/state-parts/src/lib.rs
Labels: S-automerge

#9406 [refactor] Refactor update_flat_storage_for_block and save_flat_state_changes to flat_storage_manager
  chain/chain/src/chain.rs
  core/store/src/flat/manager.rs
Labels: S-automerge

#9411 fix: SweatUser has no attribute 'sweat'
  pytest/tests/loadtest/locust/locustfiles/sweat.py
Labels: S-automerge

#9416 [cleanup] Remove unused, unused_mut, and dead_code references
  chain/chain/src/store.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/epoch-manager/src/lib.rs
  chain/epoch-manager/src/shard_tracker.rs
  chain/epoch-manager/src/tests/mod.rs
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/network/src/network_protocol/borsh.rs
  core/primitives/src/trie_key.rs
  core/store/src/cold_storage.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/storage.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  pytest/tests/mocknet/helpers/state_contract.rs
  runtime/near-vm-runner/src/logic/tests/helpers.rs
  runtime/near-vm-runner/src/logic/tests/view_method.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm/compiler-singlepass/src/emitter_x64.rs
  runtime/near-vm/test-api/src/sys/store.rs
  runtime/near-vm/types/src/entity/mod.rs
  runtime/runtime/src/verifier.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#9426 test_builder: more flexibility and control
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
Labels: S-automerge

#9419 [resharding] Include state_changes in ApplySplitStateResult for split_state
  chain/chain/src/resharding.rs
  core/primitives/src/types.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/split_state.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#9421 [resharding] Write flat state and update head during resharding and handling split_state
  chain/chain/src/chain.rs
  core/store/src/flat/delta.rs
  core/store/src/trie/split_state.rs
Labels: S-automerge

#9428 test: parallel account creation in loadtest
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/sweat.py
Labels: S-automerge

#9429 feat: allow updating config.json in mirror script
  pytest/tests/mocknet/helpers/neard_runner.py
  pytest/tests/mocknet/mirror.py
Labels: S-automerge

#9425 config_store: add a test to verify all config files are included
  core/primitives/src/runtime/config_store.rs
Labels: S-automerge

#9335 [resharding] Use flat storage to iterate over keys for resharding
  Cargo.lock
  chain/chain/Cargo.toml
  chain/chain/src/resharding.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
Labels: S-automerge

#9431 fix(logging): Change near_vm log level to debug
  runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/compiler-singlepass/src/compiler.rs
  runtime/near-vm/compiler/src/translator/environ.rs
  runtime/near-vm/compiler/src/translator/module.rs
  runtime/near-vm/compiler/src/translator/state.rs
  runtime/near-vm/engine/src/universal/engine.rs
  runtime/near-vm/engine/src/universal/link.rs
  runtime/near-vm/test-api/src/sys/instance.rs
  runtime/near-vm/test-api/src/sys/module.rs
  runtime/near-vm/vm/src/instance/mod.rs
  runtime/near-vm/vm/src/vmoffsets.rs
Labels: S-automerge

#9427 fix(state-sync): Make partial chunks message deterministic
  chain/chunks/src/lib.rs
  chain/chunks/src/logic.rs
  core/primitives/src/sharding.rs
  docs/misc/state_sync_from_external_storage.md
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/tests/sanity/state_sync_epoch_boundary.py
  pytest/tests/sanity/state_sync_then_catchup.py
Labels: S-automerge

#9402 feat: adding cross_contract_calls integration test for the V1->V2 resharding
  .gitignore
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/logic.rs
  chain/client/src/test_utils.rs
  chain/epoch-manager/Cargo.toml
  chain/epoch-manager/src/lib.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: S-automerge

#9448 test: faster init for sweat storage stress-test
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/locustfiles/sweat.py
Labels: S-automerge

#9452 refactor: refactoring code around incoming receipts handling
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/client.rs
Labels: S-automerge

#9439 runtime: pass around the RuntimeConfig rather than just fees
  chain/indexer/src/streamer/utils.rs
  core/primitives/src/views.rs
  integration-tests/src/node/runtime_node.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/test_errors.rs
  nearcore/tests/economics.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  test-utils/testlib/src/fees_utils.rs
Labels: S-automerge

#9445 fix(mirror): add an extra key to accounts with no keys created by con…
  pytest/tools/mirror/contract/src/lib.rs
  pytest/tools/mirror/mirror_utils.py
  pytest/tools/mirror/offline_test.py
  pytest/tools/mirror/online_test.py
  tools/mirror/src/lib.rs
Labels: S-automerge

#9454 fix(logging): Undo #9376 because it's too verbose
  chain/chain/src/resharding.rs
  chain/chain/src/state_snapshot_actor.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync_jobs_actor.rs
  chain/client/src/view_client.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/telemetry/src/lib.rs
  core/o11y/src/macros.rs
Labels: S-automerge

#9463 doc: fix gas price limits
  docs/architecture/how/gas.md
Labels: S-automerge

#9458 chore: Add metrics that shows the current height of approvals
  CHANGELOG.md
  chain/chain/src/doomslug.rs
  chain/chain/src/metrics.rs
Labels: S-automerge

#9460 toolchain: update to 1.72.0
  Cargo.toml
  chain/client/src/test_utils.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  runtime/near-vm/test-api/src/sys/externals/function.rs
  runtime/near-vm/test-api/src/sys/module.rs
  runtime/near-vm/test-api/src/sys/ptr.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  runtime/runtime-params-estimator/src/gas_cost.rs
  runtime/runtime/src/receipt_manager.rs
  rust-toolchain.toml
Labels: S-automerge

#9453 feat: add single column compaction for database tool compact command
  core/store/src/db/rocksdb.rs
  tools/database/src/analyse_data_size_distribution.rs
  tools/database/src/compact.rs
  tools/database/src/utils.rs
Labels: A-storage, S-automerge

#9469 remove trailing spaces
  chain/chunks/README.md
Labels: C-housekeeping

#9471 fix contributing process for merge queues
  CONTRIBUTING.md
Labels: C-housekeeping
