Repository near/nearcore, pull requests merged in 2023-05, with the labels that each got.

#8990 add test for #8977
  chain/chain/src/test_utils/validator_schedule.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/process_blocks.rs
Labels: S-automerge

#8993 Fuzz branch 1.34.0
  nightly/fuzz.toml
Labels: S-automerge

#8985 core: make StoreKey, StoreValue and FunctionArgs serde serialisable
  core/primitives-core/src/serialize.rs
  core/primitives/src/state_record.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/sandbox.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  runtime/runtime/src/genesis.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/state_viewer/mod.rs
  tools/state-viewer/src/commands.rs
Labels: C-housekeeping, S-automerge

#8986 fix: remove unused validator stake view type
  core/primitives/src/views.rs
  pytest/lib/lightclient.py
  pytest/lib/messages/block.py
Labels: S-automerge

#9000 refactor: Fix clippy's len_zero errors
  chain/chain/src/doomslug.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/validate.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/header.rs
  chain/client/src/tests/catching_up.rs
  chain/network/src/config.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  runtime/near-vm/lib/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/lib/compiler-singlepass/src/machine.rs
  runtime/runtime-params-estimator/src/action_costs.rs
  scripts/run_clippy.sh
  tools/ping/src/cli.rs
Labels: C-housekeeping, S-automerge

#8988 feat: implement inlining for small values in flat storage
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/flat_storage.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: A-storage, S-automerge

#9003 refactor: no logic duplication in `TrieRecordingStorage`
  chain/chain/src/flat_storage_creator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  tools/state-viewer/src/commands.rs
Labels: A-storage

#9005 Revert "feat: implement inlining for small values in flat storage"
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/flat_storage.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: A-storage, S-automerge

#9009 revert: near-vm and finite-wasm changes
  CHANGELOG.md
  core/primitives-core/src/config.rs
  core/primitives/res/runtime_configs/61.yaml
  core/primitives/res/runtime_configs/parameters.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__61.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_61.json.snap
  core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
  core/primitives/src/version.rs
  integration-tests/src/tests/client/features/wasmer2.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
  runtime/near-test-contracts/src/lib.rs
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/vm_kind.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#9002 fix: Sample different accounts in sharding test
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: C-housekeeping, S-automerge

#9023 chore: update `tokio` to `1.28`
  Cargo.lock
  Cargo.toml
Labels: S-automerge

#9029 feat: implement inlining for small values in flat storage
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/metadata.rs
  core/store/src/migrations.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/migrations.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: A-storage, S-automerge

#9030 fix(metrics): Current protocol version
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#9031 fix(loadtest2): gas amount
  pytest/tests/loadtest/loadtest2.py
Labels: S-automerge

#9033 cleanup(migrations): Remove old migration code
  core/store/src/migrations.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#9036 feature: Introduce transaction pool size accounting
  chain/pool/src/lib.rs
Labels: S-automerge

#9034 fix(mocknet): bump up the stakes for validators in the mocknet test
  pytest/tests/mocknet/mirror.py
Labels: S-automerge

#9035 fix: Make sure we generate enough accounts for sharding test
  core/store/src/test_utils.rs
  core/store/src/trie/split_state.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: S-automerge

#9043 fix: visit_nodes_interval should exclude path_end
  core/store/src/trie/iterator.rs
Labels: A-storage, S-automerge

#8970 feature: Introduce a limit to transaction pool size
  chain/chunks/src/client.rs
  chain/client/src/client.rs
  chain/pool/src/lib.rs
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge, A-congestion

#9006 refactor: remove majority of `as_caching_storage` calls
  core/store/src/test_utils.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
Labels: S-automerge

#9050 Fix: flaky split storage tests
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8995 feat: state boundaries on KV pairs
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  core/primitives/src/challenge.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_tests.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: A-storage, S-automerge

#9059 param-estimator: use value_enum for vm_kind
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/vm_kind.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
Labels: C-housekeeping, S-automerge

#9055 core: avoid memory allocations when dealing with Serde data
  chain/jsonrpc/client/src/lib.rs
  core/primitives-core/src/serialize.rs
  utils/fmt/src/lib.rs
Labels: S-automerge

#9053 near-vm: add to diffrunner
  runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
Labels: S-automerge

#9052 feature: Add metric measuring size of transaction pool
  chain/pool/src/lib.rs
  chain/pool/src/metrics.rs
Labels: S-automerge

#9064 fix(metrics): Enforce 'near_' prefix for new metrics
  core/o11y/src/metrics.rs
Labels: S-automerge

#9071 feat(state-viewer): Display kickouts information
  Cargo.lock
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
Labels: S-automerge

#9068 chore: add support for workspace inheritance to themis
  tools/themis/src/rules.rs
  tools/themis/src/types.rs
  tools/themis/src/utils.rs
Labels: S-automerge

#9067 Switch to using serde_with
  Cargo.lock
  Cargo.toml
  chain/chain/src/tests/simple_chain.rs
  chain/client/src/debug.rs
  chain/jsonrpc/Cargo.toml
  chain/jsonrpc/fuzz/fuzz_targets_disabled/fuzz_target_1.rs
  chain/jsonrpc/src/api/transactions.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/serialize.rs
  core/primitives/Cargo.toml
  core/primitives/src/receipt.rs
  core/primitives/src/state_record.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/upgrade_schedule.rs
  core/primitives/src/utils.rs
  core/primitives/src/views.rs
  deny.toml
  genesis-tools/genesis-csv-to-json/src/csv_parser.rs
  runtime/near-test-contracts/test-contract-rs/Cargo.lock
  runtime/near-test-contracts/test-contract-rs/Cargo.toml
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/db.rs
Labels: S-automerge

#9062 [neard] Add `view-state clear-cache` command to neard
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#9037 feat: flat state value inlining migration
  core/store/src/flat/inlining_migration.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/metrics.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#9079 refactor: convenient iteration over flat state entries
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/splitdb.rs
  core/store/src/db/testdb.rs
  core/store/src/flat/store_helper.rs
  core/store/src/lib.rs
  integration-tests/src/tests/client/flat_storage.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#9070 fix: don't panic on SIGTERM during flat storage creation
  chain/chain/src/flat_storage_creator.rs
Labels: A-storage, S-automerge

#9076 refactor: put `sync_prev_prev_hash` to `obtain_state_part`
  chain/chain/src/chain.rs
  chain/chain/src/types.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/state_sync.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/state_parts.rs
Labels: A-storage, S-automerge

#9078 refactor: minor: prefer borrowing instead of using `ref`
  core/primitives/src/views.rs
Labels: S-automerge

#9072 refactor: Extract `update_cache` in store
  chain/chain/src/store.rs
  core/store/src/config.rs
  core/store/src/lib.rs
  core/store/src/trie/config.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/trie_storage.rs
Labels: C-housekeeping, S-automerge

#9075 test: locust based loadtest PoC
  pytest/lib/mocknet_helpers.py
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/locustfile.py
Labels: S-automerge

#9103 make sure diffrunner fuzzer actually runs with contract prepare version v2
  integration-tests/src/tests/runtime/deployment.rs
  runtime/near-vm-runner/fuzz/fuzz_targets/diffrunner.rs
  runtime/near-vm-runner/src/prepare.rs
Labels: S-automerge

#9066 finite-wasm: add a nightly feature
  core/primitives-core/src/config.rs
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/133.yaml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic_nightly.snap
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/regression_tests.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm/compiler-test-derive/build.rs
Labels: S-automerge

#9104 fix: flat-storage verify cmd
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#9091 jsonrpc: encode state proofs using base64 and remove deprecated field
  core/primitives/src/views.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  runtime/runtime/src/state_viewer/mod.rs
Labels: S-automerge

#8927 feat: construct state sync parts using flat storage
  chain/chain/src/flat_storage_creator.rs
  core/primitives/src/state.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/inlining_migration.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/lib.rs
  core/store/src/migrations.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/nibble_slice.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  tools/flat-storage/src/commands.rs
  tools/state-viewer/src/state_dump.rs
Labels: A-storage, S-automerge

#9088 test: Add test for `iter_flat_state_entries`
  core/store/src/flat/store_helper.rs
Labels: A-testing, A-storage, S-automerge

#9109 refactor: Clean flat state via range
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  tools/flat-storage/src/commands.rs
Labels: C-housekeeping, A-storage, S-automerge

#9113 do not spend time tracing finite_wasm_gas
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/tests/regression_tests.rs
Labels: S-automerge

#9069 feature: Add transaction pool size to Config
  nearcore/src/config.rs
Labels: S-automerge, A-congestion

#9112 fix(state-viewer): View actually latest state in `view-trie`, `dump-state` and other commands
  Cargo.lock
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#9106 chore: revert near-account-id's MSRV
  core/account-id/Cargo.toml
Labels: S-automerge

#9107 fix: implement valid AccountId generation from arbitrary data
  core/account-id/src/lib.rs
Labels: S-automerge

#9108 chore: bump crates version to 0.17.0
  Cargo.toml
Labels: S-automerge

#9117 refactor: remove redundant flat storage methods from RuntimeAdapter
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/storage.rs
  docs/architecture/storage/flat_storage.md
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  tools/flat-storage/src/commands.rs
Labels: C-housekeeping, A-storage, S-automerge

#9119 near-vm: add a nightly feature
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/nearvm.rs
  nearcore/Cargo.toml
  runtime/near-vm-runner/src/vm_kind.rs
Labels: S-automerge

#9123 fix: clear previous epoch block/chunk production metrics
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#9120 refactor: use proper type for FlatState iterator values
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/store_helper.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/flat_storage.rs
  tools/flat-storage/src/commands.rs
Labels: C-housekeeping, A-storage, S-automerge

#9126 fix(test): import correct retry library
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9115 feat: report validator stake
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#9124 chore: fix panic on arbitrary `AccountId` generation
  core/account-id/src/lib.rs
Labels: S-automerge
