Repository near/nearcore, pull requests merged in 2023-06, with the labels that each got.

#9131 fix: improve error message in get_gc_stop_height after the gc_num_epochs_to_keep is increased
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#9086 refactor: RoutingTableView
  chain/network/src/announce_accounts/mod.rs
  chain/network/src/announce_accounts/tests.rs
  chain/network/src/lib.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/routing/graph/mod.rs
  chain/network/src/routing/routing_table_view/mod.rs
  chain/network/src/routing/routing_table_view/tests.rs
Labels: S-automerge

#8831 doc: io_trace feature to debug IO perf
  docs/SUMMARY.md
  docs/practices/workflows/io_trace.md
Labels: S-automerge, C-docs

#9132 finite-wasm: upgrade to 0.5.0
  Cargo.lock
  Cargo.toml
Labels: S-automerge

#9139 core: minor KeyForStateChanges refactoring
  core/primitives-core/src/hash.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge

#9142 feat: extra validation for beneficiary id
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#9133 feat(loadtest): SocialDB load
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
  pytest/tests/loadtest/locust/locustfile.py
Labels: S-automerge

#9130 refactor: improve flat storage error handling
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/flat_storage.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#9083 [documentation] Minor changes
  docs/architecture/how/resharding.md
  docs/architecture/how/serialization.md
  docs/architecture/how/tx_receipts.md
Labels: S-automerge

#9144 stabilize finite-wasm and near-vm
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/62.yaml
  core/primitives/res/runtime_configs/parameters.snap
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__62.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_62.json.snap
  core/primitives/src/version.rs
  integration-tests/src/tests/client/features/nearvm.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/regression_tests.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/vm_kind.rs
Labels: S-automerge

#9145 fix: Remove near-o11y dependency from near-chain-configs to reduce the dependency graph for near-jsonrpc-client
  core/chain-configs/Cargo.toml
  core/chain-configs/src/lib.rs
  core/chain-configs/src/updateable_config.rs
  nearcore/Cargo.toml
Labels: S-automerge

#9148 fix(state-parts): Instrument creation of state parts
  core/store/src/flat/chunk_view.rs
  core/store/src/metrics.rs
  core/store/src/trie/state_parts.rs
Labels: S-automerge

#9156 prepare_v2: replace pwasm with wasmparser/encoder
  Cargo.lock
  Cargo.toml
  runtime/near-test-contracts/src/lib.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/prepare/prepare_v2.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
Labels: S-automerge

#9008 fix(SplitStorage): More verbose script explaining what it does
  core/store/src/cold_storage.rs
  nearcore/src/cold_storage.rs
  scripts/split_storage_migration.sh
Labels: S-automerge

#9162 fix(state-parts): Adjust state part size
  core/primitives/src/syncing.rs
  integration-tests/src/tests/client/state_dump.rs
Labels: S-automerge

#9085 fix(jsonrpc): don't unwrap socket listeners
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#9168 move ProtocolFeature and checked_feature to near-primitives-core
  core/primitives-core/Cargo.toml
  core/primitives-core/src/lib.rs
  core/primitives-core/src/version.rs
  core/primitives/Cargo.toml
  core/primitives/src/epoch_manager.rs
  core/primitives/src/lib.rs
  core/primitives/src/version.rs
Labels: S-automerge

#9173 test: use WASM for backwards-compatibility tests
  runtime/near-test-contracts/build.rs
  runtime/near-test-contracts/res/base_test_contract_rs.wasm
  runtime/near-test-contracts/src/lib.rs
Labels: S-automerge

#9174 Fix blips in the transaction pool size metric
  chain/pool/src/lib.rs
  chain/pool/src/types.rs
Labels: S-automerge, A-congestion

#9175 test: use `backwards_compatible_rs_contract` where appropriate
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/features/flat_storage.rs
  integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/nearvm.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  pytest/lib/utils.py
  runtime/near-test-contracts/res/backwards_compatible_rs_contract.wasm
  runtime/near-test-contracts/src/lib.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#9172 Set default transaction pool size limit to 100MB.
  CHANGELOG.md
  nearcore/src/config.rs
Labels: S-automerge, A-congestion

#9176 Move CompiledContract and CompiledContractCache to near-vm-errors
  Cargo.lock
  core/primitives/src/runtime/apply_state.rs
  core/primitives/src/types.rs
  core/primitives/src/utils.rs
  core/primitives/src/views.rs
  core/store/Cargo.toml
  core/store/src/lib.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/src/runtime/mod.rs
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/function_call.rs
  runtime/runtime-params-estimator/src/gas_metering.rs
  runtime/runtime-params-estimator/src/vm_estimator.rs
Labels: C-housekeeping, S-automerge

#9166 feat(state-viewer): Human-readable DB scan
  Cargo.lock
  core/primitives/src/shard_layout.rs
  core/primitives/src/state_record.rs
  core/primitives/src/transaction.rs
  core/store/src/columns.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/store_helper.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
  tools/state-viewer/src/lib.rs
  tools/state-viewer/src/scan_db.rs
Labels: S-automerge

#9178 fix(metrics): near_client_tracked_shards metric tracks all tracked shards
  chain/client/src/info.rs
  pytest/tests/sanity/recompress_storage.py
Labels: S-automerge

#9157 Locust Congestion Workload
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/locustfile.py
Labels: S-automerge, A-congestion

#9183 make near-vm-runner not depend on all of near-primitives
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/runner.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
  runtime/near-vm-runner/src/tests/regression_tests.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/runtime_errors.rs
  runtime/near-vm-runner/src/tests/test_builder.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/vm_kind.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: C-housekeeping, S-automerge

#8725 wasmtime: upgrade to 9.0.3
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#9188 feat: add detailed chunk application cost metrics
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/metrics.rs
Labels: S-automerge

#9192 remove old function checking for protocol version
  core/primitives-core/src/version.rs
  core/primitives/src/version.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
Labels: C-housekeeping, S-automerge

#9195 refactor: Separate locust workloads into different files
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
  pytest/tests/loadtest/locust/locustfiles/congestion.py
  pytest/tests/loadtest/locust/locustfiles/ft.py
  pytest/tests/loadtest/locust/locustfiles/social.py
Labels: C-housekeeping, S-automerge

#9197 refactor: Store contract deps alongside the code
  pytest/tests/loadtest/locust/README.md
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
  pytest/tests/loadtest/locust/download_contracts.sh
  pytest/tests/loadtest/locust/res/congestion.wasm
  pytest/tests/loadtest/locust/res/fungible_token.wasm
  pytest/tests/loadtest/locust/res/social_db.wasm
Labels: S-automerge

#9196 runtime: upgrade dynasm to 2 and integrate near/wasmer#146
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/near-vm/compiler-singlepass/Cargo.toml
  runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/compiler-singlepass/src/compiler.rs
Labels: S-automerge

#9190 feat: Reset block head to tail
  tools/undo-block/src/cli.rs
  tools/undo-block/src/lib.rs
Labels: S-automerge

#9208 move TrieNodesCount to near-vm-errors
  core/primitives/src/types.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
Labels: C-housekeeping, S-automerge

#9161 [resharding] Offline tool to construct trie from flat storage
  core/store/src/lib.rs
  core/store/src/trie/from_flat.rs
  core/store/src/trie/mod.rs
  tools/flat-storage/src/commands.rs
Labels: S-automerge

#9210 [genesis] Refactor genesis state and state applier into store
  Cargo.lock
  chain/chain/src/chain.rs
  core/store/Cargo.toml
  core/store/src/genesis.rs
  core/store/src/genesis_state_applier.rs
  core/store/src/lib.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/runtime_utils.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  tools/storage-usage-delta-calculator/Cargo.toml
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#9209 feat(loadtest): use `broadcast_tx_async` on rpc
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
Labels: S-automerge

#9212 near-vm: remove the unwind registry
  runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/compiler/src/function.rs
  runtime/near-vm/compiler/src/lib.rs
  runtime/near-vm/compiler/src/unwind.rs
  runtime/near-vm/engine-universal/src/code_memory.rs
  runtime/near-vm/engine-universal/src/engine.rs
  runtime/near-vm/engine-universal/src/lib.rs
  runtime/near-vm/engine-universal/src/unwind/dummy.rs
  runtime/near-vm/engine-universal/src/unwind/mod.rs
  runtime/near-vm/engine-universal/src/unwind/systemv.rs
  runtime/near-vm/engine-universal/src/unwind/windows_x64.rs
Labels: S-automerge

#9211 move DataReceiver to near-vm-errors
  core/primitives/src/receipt.rs
  runtime/near-vm-errors/src/lib.rs
Labels: C-housekeeping, S-automerge

#9218 fix: Change `post_json` type annotation
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9217 move action to near-vm-errors
  Cargo.lock
  core/primitives/src/lib.rs
  core/primitives/src/transaction.rs
  runtime/near-vm-errors/Cargo.toml
  runtime/near-vm-errors/src/action.rs
  runtime/near-vm-errors/src/delegate_action.rs
  runtime/near-vm-errors/src/lib.rs
  runtime/near-vm-errors/src/signable_message.rs
Labels: C-housekeeping, S-automerge

#9090 feat(state-sync): DB Snapshots
  CHANGELOG.md
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/lib.rs
  chain/chain/src/state_snapshot_actor.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/tests/gc.rs
  chain/chain/src/types.rs
  chain/client/src/adapter.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/sync/state.rs
  chain/client/src/test_utils.rs
  chain/client/src/tests/query_client.rs
  chain/client/src/view_client.rs
  core/chain-configs/src/client_config.rs
  core/store/src/config.rs
  core/store/src/db/rocksdb.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/inlining_migration.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/storage.rs
  core/store/src/lib.rs
  core/store/src/metrics.rs
  core/store/src/opener.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/state_dump.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
  nightly/pytest-stress.txt
  pytest/lib/cluster.py
  pytest/tests/contracts/infinite_loops.py
  pytest/tests/sanity/block_sync_archival.py
  pytest/tests/sanity/epoch_switches.py
  pytest/tests/sanity/garbage_collection.py
  pytest/tests/sanity/garbage_collection1.py
  pytest/tests/sanity/gc_after_sync.py
  pytest/tests/sanity/gc_after_sync1.py
  pytest/tests/sanity/gc_sync_after_sync.py
  pytest/tests/sanity/lightclnt.py
  pytest/tests/sanity/state_sync_fail.py
  pytest/tests/stress/stress.py
  tools/flat-storage/src/commands.rs
  tools/mock-node/src/setup.rs
  tools/speedy_sync/src/main.rs
Labels: S-automerge

#9223 feat(loadtest): retry on timeout
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9230 refactor(loadtest): remove `send_transaction`
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
Labels: S-automerge

#9231 feat(loadtest): allow rerunning on the same state
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
Labels: S-automerge

#9234 refactor: default seed in `key.from_seed_testonly`
  pytest/lib/key.py
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/social.py
Labels: S-automerge

#9232 [refactor] Refactor function `add_validator_proposals` from runtime to epoch_manager
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  chain/epoch-manager/src/lib.rs
  chain/epoch-manager/src/types.rs
  genesis-tools/genesis-populate/src/lib.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#9240 re-introduce tests lost when splitting up near-vm and finite-wasm into separate features
  runtime/near-test-contracts/test-contract-rs/src/lib.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: C-housekeeping, S-automerge

#9194 feat: spread account IDs across shards in the locust test
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/sharding.py
Labels: S-automerge

#9245 refactor(loadtest): remove dead code
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
Labels: C-housekeeping, S-automerge

#9249 refactor: move get_block_execution_outcomes to ChainStore
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/src/view_client.rs
  core/store/src/columns.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge, T-core

#9189 ChangeDbKind tool
  Cargo.lock
  Cargo.toml
  neard/Cargo.toml
  neard/src/cli.rs
  tools/adjust-db/Cargo.toml
  tools/adjust-db/README.md
  tools/adjust-db/src/cli.rs
  tools/adjust-db/src/lib.rs
Labels: S-automerge

#9253 fix(state-sync): s3 credentials file
  Cargo.lock
  chain/client/Cargo.toml
  chain/client/src/sync/external.rs
  chain/client/src/sync/mod.rs
  chain/client/src/sync/state.rs
  integration-tests/src/tests/client/state_dump.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/state_sync.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#9259 fix(state-snapshots): Flat Storage Inlining doesn't crash if state snapshotting is in process
  core/store/src/flat/inlining_migration.rs
Labels: S-automerge

#9256 near-vm: reduce the scope of the test-api
  runtime/near-vm/test-api/src/sys/cell.rs
  runtime/near-vm/test-api/src/sys/env.rs
  runtime/near-vm/test-api/src/sys/exports.rs
  runtime/near-vm/test-api/src/sys/externals/function.rs
  runtime/near-vm/test-api/src/sys/externals/global.rs
  runtime/near-vm/test-api/src/sys/externals/memory.rs
  runtime/near-vm/test-api/src/sys/externals/mod.rs
  runtime/near-vm/test-api/src/sys/externals/table.rs
  runtime/near-vm/test-api/src/sys/import_object.rs
  runtime/near-vm/test-api/src/sys/instance.rs
  runtime/near-vm/test-api/src/sys/mod.rs
  runtime/near-vm/test-api/src/sys/module.rs
  runtime/near-vm/test-api/src/sys/native.rs
  runtime/near-vm/test-api/src/sys/ptr.rs
  runtime/near-vm/test-api/src/sys/tunables.rs
  runtime/near-vm/test-api/src/sys/types.rs
  runtime/near-vm/tests/compilers/compilation.rs
  runtime/near-vm/tests/compilers/config.rs
  runtime/near-vm/tests/compilers/imports.rs
  runtime/near-vm/tests/compilers/native_functions.rs
  runtime/near-vm/tests/compilers/traps.rs
  runtime/near-vm/tests/compilers/wast.rs
Labels: S-automerge

#9260 fix(logging): Orphaned blocks take a lot of logs. Add an option for more compact logging
  chain/client/src/info.rs
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge

#9016 feat: limit state sync downloading threads
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/state.rs
  chain/client/src/test_utils.rs
Labels: S-automerge

#9261 remove near-o11y dep from near-vm-runner
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/logic/logic.rs
Labels: C-housekeeping, S-automerge

#9171 feat: Script to analyse RocksDB data distribution
  Cargo.lock
  Cargo.toml
  neard/Cargo.toml
  neard/src/cli.rs
  tools/database/Cargo.toml
  tools/database/README.md
  tools/database/src/analyse_data_size_distribution.rs
  tools/database/src/commands.rs
  tools/database/src/lib.rs
Labels: A-storage, S-automerge, A-benchmark

#9244 near-vm: use a recycling pool of shared code memories instead of a in-memory cache of loaded artifacts
  Cargo.lock
  Cargo.toml
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm/compiler/src/error.rs
  runtime/near-vm/engine/Cargo.toml
  runtime/near-vm/engine/src/universal/artifact.rs
  runtime/near-vm/engine/src/universal/builder.rs
  runtime/near-vm/engine/src/universal/code_memory.rs
  runtime/near-vm/engine/src/universal/engine.rs
  runtime/near-vm/engine/src/universal/mod.rs
  runtime/near-vm/test-api/src/sys/instance.rs
  runtime/near-vm/test-api/src/sys/store.rs
  runtime/near-vm/tests/compilers/compilation.rs
  runtime/near-vm/tests/compilers/config.rs
  runtime/near-vm/tests/compilers/deterministic.rs
  runtime/near-vm/tests/compilers/stack_limiter.rs
  runtime/near-vm/vm/src/artifact.rs
Labels: S-automerge

#9269 refactor: add FlatStateValue constructor for on-disk values
  core/primitives/src/state.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/inlining_migration.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/types.rs
  core/store/src/trie/state_parts.rs
Labels: A-storage, S-automerge

#9264 refactor: Move adjust-db tool to database tool
  Cargo.lock
  Cargo.toml
  neard/Cargo.toml
  neard/src/cli.rs
  tools/adjust-db/Cargo.toml
  tools/adjust-db/README.md
  tools/adjust-db/src/lib.rs
  tools/database/Cargo.toml
  tools/database/README.md
  tools/database/src/adjust_database.rs
  tools/database/src/analyse_data_size_distribution.rs
  tools/database/src/commands.rs
  tools/database/src/lib.rs
Labels: C-housekeeping, A-storage, S-automerge

#9219 feat: remove fixed shards
  CHANGELOG.md
  core/primitives/src/shard_layout.rs
  integration-tests/src/node/mod.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  pytest/tests/sanity/garbage_collection_sharding_upgrade.py
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#9273 remove near-cache dep from near-vm-runner
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
Labels: C-housekeeping, S-automerge

#9268 fix(state-sync): Clear flat storage outside of ClientActor
  chain/chain/src/chain.rs
  chain/client/src/client_actor.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge
