Repository near/nearcore, pull requests merged in 2023-04, with the labels that each got.

#8861 fix(params-estimator): inner iterations mistake
  runtime/runtime-params-estimator/src/action_costs.rs
Labels: S-automerge

#8870 docs: mention intrinsification of `gas` host fn
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm/lib/types/src/types.rs
Labels: S-automerge

#8858 publish near-vm crates
  runtime/near-vm/lib/README.md
  runtime/near-vm/lib/api/Cargo.toml
  runtime/near-vm/lib/api/LICENSE
  runtime/near-vm/lib/api/README.md
  runtime/near-vm/lib/compiler-singlepass/Cargo.toml
  runtime/near-vm/lib/compiler-singlepass/LICENSE
  runtime/near-vm/lib/compiler-singlepass/README.md
  runtime/near-vm/lib/compiler-universal
  runtime/near-vm/lib/compiler/Cargo.toml
  runtime/near-vm/lib/compiler/LICENSE
  runtime/near-vm/lib/compiler/README.md
  runtime/near-vm/lib/engine-universal/Cargo.toml
  runtime/near-vm/lib/engine-universal/LICENSE
  runtime/near-vm/lib/engine-universal/README.md
  runtime/near-vm/lib/engine/Cargo.toml
  runtime/near-vm/lib/engine/LICENSE
  runtime/near-vm/lib/engine/README.md
  runtime/near-vm/lib/types/Cargo.toml
  runtime/near-vm/lib/types/LICENSE
  runtime/near-vm/lib/types/README.md
  runtime/near-vm/lib/vm/Cargo.toml
  runtime/near-vm/lib/vm/LICENSE
  runtime/near-vm/lib/vm/README.md
  tools/themis/src/rules.rs
Labels: S-automerge

#8873 introduce VMKind::NearVm
  runtime/near-vm-runner/src/cache.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/vm_kind.rs
Labels: S-automerge

#8875 misc cleanups from doing #8323
  chain/client/src/test_utils.rs
  core/primitives-core/src/config.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/prepare/prepare_v0.rs
  runtime/near-vm-runner/src/runner.rs
Labels: C-housekeeping, S-automerge

#8876 feat: create NodeStorage from checkpoint
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/splitdb.rs
  core/store/src/db/testdb.rs
  core/store/src/lib.rs
  core/store/src/opener.rs
Labels: S-automerge

#8833 Fix: rosetta zero balance accounts tests
  Cargo.lock
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/src/utils.rs
  pytest/tests/sanity/rosetta.py
Labels: S-automerge

#8848 feat(network::raw): add a Listener type that allows accepting incoming connections
  chain/network/src/raw/connection.rs
  chain/network/src/raw/mod.rs
  chain/network/src/raw/tests.rs
  tools/ping/src/lib.rs
  tools/state-parts/src/lib.rs
Labels: S-automerge

#8871 feat: override NetworkConfig from JSON config
  CHANGELOG.md
  chain/network/src/config.rs
  chain/network/src/config_json.rs
Labels: S-automerge

#8850 feat: Option to track different shards every epoch
  chain/epoch-manager/src/shard_tracker.rs
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge

#8874 adjust imports for near-vm
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
Labels: S-automerge

#8883 introduce contract preparation code v2
  Cargo.lock
  core/primitives-core/src/config.rs
  deny.toml
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  integration-tests/src/tests/runtime/deployment.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/prepare/prepare_v0.rs
  runtime/near-vm-runner/src/prepare/prepare_v1.rs
  runtime/near-vm-runner/src/prepare/prepare_v2.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#8885 Remove deprecated db migration options
  nearcore/src/config.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#8889 Fix docs typos
  docs/practices/style.md
Labels: S-automerge

#8882 feat: cold storage - explicitly check each column if it should be in the cold storage
  chain/chain/src/store.rs
  core/store/src/columns.rs
Labels: S-automerge

#8887 adding TestSplitStorage.test_archival_node_sync
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8891 chore: minor updates to crypto dependencies
  Cargo.lock
Labels: C-housekeeping, C-dependencies

#8894 refactor: pull o11y/pretty into its own crate
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/peer/peer_actor.rs
  core/o11y/src/lib.rs
  core/primitives/Cargo.toml
  core/primitives/src/receipt.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/cold_storage.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/replay.rs
  utils/fmt/Cargo.toml
  utils/fmt/LICENSE-APACHE
  utils/fmt/LICENSE-MIT
  utils/fmt/README.md
  utils/fmt/src/lib.rs
Labels: S-automerge

#8900 chore: remove duplicate dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: C-housekeeping, S-automerge

#8886 actually call near-vm when using VMKind::NearVm
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/runner.rs
Labels: S-automerge

#8856 disable tests with intermittent failures
  chain/network/src/peer_manager/tests/nonce.rs
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#8778 [Runtime Epoch Split] (5/n) Migrate ShardsManager to use only EpochManager and ShardTracker.
  Cargo.lock
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chunks/Cargo.toml
  chain/chunks/src/lib.rs
  chain/chunks/src/logic.rs
  chain/chunks/src/shards_manager_actor.rs
  chain/chunks/src/test/basic.rs
  chain/chunks/src/test/multi.rs
  chain/chunks/src/test_loop.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  chain/epoch-manager/src/adapter.rs
  chain/epoch-manager/src/test_utils.rs
  core/async/src/examples/async_component_test.rs
  core/async/src/examples/multi_instance_test.rs
  core/async/src/examples/sum_numbers_test.rs
  core/async/src/examples/timed_component_test.rs
  core/async/src/test_loop.rs
  core/async/src/test_loop/adhoc.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#8906 Revert "feature: Implement compute usage aggregation and limiting (#8…
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/primitives/src/runtime/parameter_table.rs
  core/primitives/src/transaction.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  tools/state-viewer/src/contract_accounts.rs
Labels: S-automerge

#8901 also test near-vm as soon as protocol upgrade is done
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/tests/test_builder.rs
Labels: S-automerge

#8905 run near-vm in with_vm_variants
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/rs_contract.rs
  runtime/near-vm-runner/src/tests/ts_contract.rs
  runtime/near-vm-runner/src/tests/wasm_validation.rs
Labels: S-automerge

#8789 feat: State Sync from External Storage
  CHANGELOG.md
  Cargo.lock
  chain/chain/src/chain.rs
  chain/client-primitives/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/metrics.rs
  chain/client/src/sync/state.rs
  core/chain-configs/src/client_config.rs
  docs/misc/state_sync_from_s3.md
  nearcore/src/config.rs
  nearcore/src/config_validate.rs
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  nearcore/src/state_sync.rs
Labels: S-automerge

#8782 chore: Publish `near-vm-runner` and it's dependencies
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/LICENSE-APACHE
  runtime/near-test-contracts/LICENSE-MIT
  runtime/near-vm-runner/Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-cache/LICENSE-APACHE
  utils/near-cache/LICENSE-MIT
  utils/near-stable-hasher/Cargo.toml
  utils/near-stable-hasher/LICENSE-APACHE
  utils/near-stable-hasher/LICENSE-MIT
Labels: S-automerge

#8744 store: make RawTrieNode borsh serialisable
  Cargo.lock
  Cargo.toml
  core/store/Cargo.toml
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/raw_node.rs
  core/store/src/trie/state_parts.rs
  docs/architecture/how/serialization.md
  integration-tests/src/tests/runtime/state_viewer.rs
  nearcore/Cargo.toml
  runtime/near-vm/lib/compiler-singlepass/Cargo.toml
  tools/cold-store/Cargo.toml
  tools/cold-store/src/cli.rs
Labels: S-automerge

#8916 tests: Disable precompilation test on aarch64-apple
  runtime/runtime/src/lib.rs
Labels: C-housekeeping, S-automerge

#8923 Add flat_storage_creation_enabled config flag
  chain/client/src/client_actor.rs
  core/chain-configs/src/client_config.rs
  core/store/src/config.rs
  nearcore/src/config.rs
Labels: A-storage, S-automerge

#8925 cleanup: Clippy in state-viewer, neard, nearcore, near-o11y
  chain/client/src/debug.rs
  chain/client/src/info.rs
  chain/client/src/sync/state.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/chunks.rs
  chain/jsonrpc/src/lib.rs
  core/o11y/src/lib.rs
  nearcore/src/cold_storage.rs
  nearcore/src/config.rs
  nearcore/src/config_validate.rs
  nearcore/src/download_file.rs
  nearcore/src/dyn_config.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/state_sync.rs
  neard/src/cli.rs
  neard/src/main.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/contract_accounts.rs
  tools/state-viewer/src/epoch_info.rs
  tools/state-viewer/src/state_changes.rs
  tools/state-viewer/src/state_dump.rs
  tools/state-viewer/src/state_parts.rs
  tools/state-viewer/src/tx_dump.rs
  utils/fmt/src/lib.rs
Labels: S-automerge

#8560 store: use borsh for state file
  core/store/src/lib.rs
Labels: S-automerge

#8933 fix: fix a formatting issue
  pytest/tools/prober/prober_split.py
Labels: S-automerge

#8930 cleanup: Fix clippy::derivable_impls
  chain/network/src/store/testonly.rs
  core/primitives-core/src/account.rs
  core/primitives/src/transaction.rs
  core/primitives/src/types.rs
  core/primitives/src/views.rs
  runtime/near-vm-runner/src/instrument/gas/validation.rs
  runtime/runtime-params-estimator/src/qemu.rs
  scripts/run_clippy.sh
Labels: S-automerge

#8928 Add Compute Costs to CHANGELOG
  CHANGELOG.md
Labels: S-automerge, C-docs

#8884 feat: delegate action gas params estimation
  runtime/runtime-params-estimator/src/action_costs.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/transaction_builder.rs
Labels: S-automerge

#8917 [Runtime Epoch Split] (6/n) Refactor state-viewer away from RuntimeWithEpochManagerAdapter.
  chain/chain/src/chain.rs
  chain/chain/src/migrations.rs
  chain/chain/src/store.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/epoch_info.rs
Labels: S-automerge

#8921 runtime: test that signext and saturating ops are disabled
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/prepare.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/tests/compile_errors.rs
Labels: S-automerge, A-contract-runtime, T-contract-runtime

#8419 [doc] How resharding works and how we could improve it
  docs/SUMMARY.md
  docs/architecture/how/resharding.md
Labels: S-automerge

#8056 doc: fixed typos in near-vm-runner Readme
  runtime/near-vm-runner/README.md
Labels: S-automerge

#8931 cleanup: Enable clippy for tests, benches, examples, etc
  chain/client/src/tests/bug_repros.rs
  chain/network/src/peer_manager/tests/routing.rs
  core/async/src/examples/async_component.rs
  core/async/src/examples/sum_numbers_test.rs
  core/o11y/src/io_tracer.rs
  core/primitives/src/trie_key.rs
  core/store/benches/store_bench.rs
  core/store/src/db/rocksdb.rs
  core/store/src/flat/storage.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  integration-tests/src/tests/client/features/fix_contract_loading_cost.rs
  integration-tests/src/tests/client/features/zero_balance_account.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/undo_block.rs
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm/lib/api/src/sys/externals/function.rs
  runtime/near-vm/lib/api/src/sys/import_object.rs
  runtime/near-vm/lib/types/src/entity/boxed_slice.rs
  runtime/near-vm/lib/types/src/entity/packed_option.rs
  runtime/near-vm/lib/types/src/entity/primary_map.rs
  runtime/near-vm/lib/types/src/entity/secondary_map.rs
  runtime/near-vm/lib/types/src/values.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
  scripts/run_clippy.sh
  tools/mock-node/src/setup.rs
Labels: S-automerge

#8924 feat: set storage compute cost > gas cost
  CHANGELOG.md
  core/primitives/res/runtime_configs/61.yaml
  core/primitives/res/runtime_configs/parameters.snap
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
Labels: S-automerge

#8847 test: a pytest script to generate significant load on a FT contract
  pytest/lib/account.py
  pytest/lib/configured_logger.py
  pytest/tests/loadtest/README.md
  pytest/tests/loadtest/loadtest2.py
Labels: S-automerge

#8761 feat: stabilize flat storage for reads
  CHANGELOG.md
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  chain/client/Cargo.toml
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/Cargo.toml
  core/primitives/src/version.rs
  core/store/Cargo.toml
  core/store/src/columns.rs
  core/store/src/config.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/lib.rs
  core/store/src/metadata.rs
  core/store/src/trie/split_state.rs
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/user/runtime_user.rs
  nearcore/Cargo.toml
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  neard/Cargo.toml
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/utils.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/genesis.rs
  tools/flat-storage/Cargo.toml
  tools/mock-node/Cargo.toml
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/state_dump.rs
Labels: A-storage, S-automerge

#8943 fix: remove cfg from undo block tool
  chain/chain/src/store.rs
Labels: S-automerge

#8944 Improve docstrings and code of `TransactionPool`
  chain/pool/src/lib.rs
Labels: C-housekeeping, S-automerge

#8759 feat: Export number of expected chunks/blocks in epoch to prometheus
  CHANGELOG.md
  chain/client/src/info.rs
  chain/client/src/metrics.rs
Labels: S-automerge

#8965 Only store transactions on validator nodes
  chain/client/src/client.rs
Labels: A-congestion

#8763 cleanup: Removing RuntimeConfigView -> RuntimeConfig
  chain/indexer/src/streamer/mod.rs
  chain/indexer/src/streamer/utils.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/nearcore/rpc_nodes.rs
Labels: C-housekeeping, S-automerge

#8968 fix: correct read mode for storage_has_key
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_external.rs
  runtime/runtime/src/ext.rs
Labels: S-automerge

#8913 feat: State sync from local filesystem
  CHANGELOG.md
  Cargo.lock
  chain/client-primitives/src/types.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  chain/client/src/metrics.rs
  chain/client/src/sync/state.rs
  core/chain-configs/src/client_config.rs
  core/chain-configs/src/lib.rs
  core/dyn-configs/src/lib.rs
  docs/misc/state_sync_dump.md
  docs/misc/state_sync_from_s3.md
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  nearcore/src/config.rs
  nearcore/src/config_validate.rs
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  nearcore/src/state_sync.rs
  nightly/expensive.txt
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8919 fix(state-viewer): print hash and memory usage of tree nodes
  core/store/src/trie/mod.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8907 build fuzzers on each commit
  .github/workflows/master_fuzzer_binaries.yml
Labels: C-housekeeping, S-automerge

#8976 tests: Verify that transaction is valid and accepted
  chain/client/src/client.rs
  integration-tests/src/tests/client/benchmarks.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/cold_storage.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/features/flat_storage.rs
  integration-tests/src/tests/client/features/increase_storage_compute_cost.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/wasmer2.rs
  integration-tests/src/tests/client/features/zero_balance_account.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/sandbox.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  nearcore/tests/economics.rs
  test-utils/runtime-tester/src/run_test.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/state_dump.rs
Labels: C-housekeeping, S-automerge, A-congestion

#8974 Update clap to 4-series (and async-recursion, async-stream, serde, openssl-macros, syn)
  Cargo.lock
  Cargo.toml
  core/o11y/src/lib.rs
  deny.toml
  genesis-tools/genesis-csv-to-json/src/main.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/keypair-generator/src/main.rs
  neard/src/cli.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/check.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/estimate.rs
  runtime/runtime-params-estimator/estimator-warehouse/src/main.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/main.rs
  test-utils/store-validator/src/main.rs
  tools/restaked/src/main.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/state_changes.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8979 1.34 Changelog
  CHANGELOG.md
Labels: S-automerge

#8937 rust: 1.68.2 -> 1.69.0
  Cargo.toml
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm/tests/lib/compiler-test-derive/src/lib.rs
  runtime/near-vm/tests/lib/compiler-test-derive/src/tests.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#8982 fix(mirror): migrate the source storage before opening it
  nearcore/src/lib.rs
  tools/mirror/src/offline.rs
Labels: S-automerge
