Repository near/nearcore, pull requests merged in 2023-10, with the labels that each got.

#9606 optimize curve25519 for tests
  Cargo.toml
Labels: C-housekeeping

#9537 feat: implement post-state-root chunk production
  chain/chain/src/chain.rs
  chain/client/src/client.rs
  core/primitives/src/sharding.rs
  core/primitives/src/sharding/shard_chunk_header_inner.rs
Labels: A-chain

#9638 fix: always take gas price from previous block
  chain/chain/src/chain.rs
  core/primitives-core/src/version.rs
Labels: A-chain

#9602 Migrate all our fuzzers to cargo-bolero ones
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/near-vm-runner/src/tests/fuzzers.rs
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/src/fuzzing.rs
  test-utils/runtime-tester/src/lib.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/runtime-tester/src/scenario_builder.rs
Labels: C-housekeeping, A-security

#9980 optimize all dependencies for tests
  Cargo.toml
Labels: C-housekeeping

#9669 feat(state-sync) State sync actors
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/client/src/sync/adapter.rs
  chain/client/src/sync/mod.rs
  chain/client/src/sync/sync_actor.rs
  chain/network/src/lib.rs
  chain/network/src/state_sync.rs
  chain/network/src/types.rs
  nearcore/src/lib.rs
Labels: Node

#10000 Remove old migrations, and afferent test
  nightly/pytest-sanity.txt
  pytest/tests/sanity/state_migration.py
  scripts/migrations/10-gas-price-fix.py
  scripts/migrations/107-2-revert-add-account-versioning.py
  scripts/migrations/107-add-account-versioning.py
  scripts/migrations/11-runtime-cost-adjustment.py
  scripts/migrations/12-fix-inflation.py
  scripts/migrations/13-block-merkle-root.py
  scripts/migrations/14-update-wasmer.py
  scripts/migrations/15-col-trie-changes.py
  scripts/migrations/16-expose-validator-method.py
  scripts/migrations/17-lightclient.py
  scripts/migrations/18-exclude-debug-info-from-outcome-proof.py
  scripts/migrations/19-col-chunks-height.py
  scripts/migrations/20-refund-allowance.py
  scripts/migrations/21-minimum-attached-gas.py
  scripts/migrations/22-protocol-upgrade.py
  scripts/migrations/23-delete_action_last.py
  scripts/migrations/24-max-gas-price.py
  scripts/migrations/25-minimum-stake-divisor.py
  scripts/migrations/26-introduce-pessimistic-gas.py
  scripts/migrations/27-add-amount-burnt-to-execution-outcome.py
  scripts/migrations/28-add-executor-id-to-execution-outcome.py
  scripts/migrations/29-add-compile-time-fees.py
  scripts/migrations/5-preserve-height.py
  scripts/migrations/6-state-stake.py
  scripts/migrations/7-account-registrar.py
  scripts/migrations/8-fraction.py
  scripts/migrations/9-state-record-data.py
Labels: C-housekeeping
