Repository near/nearcore, pull requests merged in 2023-03, with the labels that each got.

#8658 add allow comments and config validation to CHANGELOG.md
  CHANGELOG.md
Labels: S-automerge

#8653 1.32 CHANGELOG update
  CHANGELOG.md
Labels: S-automerge

#8659 fix(mocknet): adjust args passed to load test scripts
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8609 cleaned up some deadcode
  chain/client/src/client_actor.rs
  chain/client/src/lib.rs
  chain/client/src/view_client.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/types.rs
  integration-tests/src/tests/network/runner.rs
Labels: S-automerge

#8656 feat: use split store in the view client
  core/store/benches/store_bench.rs
  core/store/src/cold_storage.rs
  core/store/src/db/database_tests.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  integration-tests/src/tests/client/cold_storage.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/benches/store.rs
  nearcore/src/cold_storage.rs
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/split_storage.py
  runtime/runtime-params-estimator/src/main.rs
  test-utils/runtime-tester/src/run_test.rs
  test-utils/store-validator/src/main.rs
  tools/cold-store/src/cli.rs
  tools/mirror/src/offline.rs
  tools/mock-node/src/setup.rs
  tools/speedy_sync/src/main.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#8634 feat: meta-tx in betanet loadtest
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_betanet.py
  pytest/tests/sanity/meta_tx.py
Labels: S-automerge

#8652 [TestLoop] (9/n) Add two basic TestLoop-based unit tests for ShardsManager.
  Cargo.lock
  chain/chunks/Cargo.toml
  chain/chunks/src/adapter.rs
  chain/chunks/src/client.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/test/basic.rs
  chain/chunks/src/test/multi.rs
  chain/chunks/src/test_loop.rs
  chain/network/src/lib.rs
  chain/network/src/shards_manager.rs
  chain/network/src/test_loop.rs
Labels: S-automerge

#8664 refactor: split flat storage into multiple files and rename some structs
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/flat_state.rs
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/shard_tries.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_tests.rs
  docs/architecture/storage/flat_storage.md
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime/src/genesis.rs
  runtime/runtime/src/prefetch.rs
  tools/flat-storage/src/commands.rs
  tools/state-viewer/src/commands.rs
Labels: A-storage, S-automerge

#8662 feat: introduce cached flat storage deltas
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
Labels: T-storage

#8641 feat: Add meta-tx to mocknet
  pytest/lib/mocknet.py
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_test_utils.py
  pytest/tests/mocknet/helpers/load_testing_add_and_delete_helper.py
  pytest/tests/mocknet/load_test_betanet.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8668 refactor: reduce `#[cfg(feature = "protocol_feature_flat_state")]` usage
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/chunk_view.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/trie/mod.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  neard/src/cli.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/utils.rs
  runtime/runtime/src/genesis.rs
  tools/flat-storage/src/commands.rs
  tools/flat-storage/src/lib.rs
  tools/state-viewer/src/state_dump.rs
Labels: A-storage, S-automerge, T-storage

#8682 fix(state-viewer): compare V1 and V2 ChunkExtras correctly in apply cmd
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#8669 ColdDB state_root test
  Cargo.lock
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/opener.rs
  tools/cold-store/Cargo.toml
  tools/cold-store/src/cli.rs
Labels: S-automerge

#8687 core: use ValueRef in trie nodes structs
  core/primitives/src/state.rs
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/runtime/state_viewer.rs
Labels: S-automerge

#8692 Fix unwanted UnknownChunk warning log messages.
  chain/chunks/src/lib.rs
  chain/chunks/src/metrics.rs
Labels: S-automerge

#8693 [TestLoop] (9.1/n) Forgot to include the tests into the source tree.
  chain/chunks/src/lib.rs
Labels: S-automerge

#8685 refactor: use shard uid in flat state keys
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/columns.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime/src/genesis.rs
  tools/flat-storage/src/commands.rs
Labels: S-automerge

#8672 fix: order of guarded and non-guarded db migration
  core/store/src/metadata.rs
  core/store/src/migrations.rs
  nearcore/src/migrations.rs
Labels: S-automerge

#8690 Ban nodes sending excessively large PeersResponse
  chain/network/src/config.rs
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer/tests/communication.rs
Labels: S-automerge

#8702 feat: implemented prober for comparing legacy and split archival nodes
  pytest/tools/prober/prober.py
  pytest/tools/prober/prober_split.py
  pytest/tools/prober/prober_util.py
Labels: S-automerge

#8628 feat: Dump and apply state changes for a range of blocks.
  core/primitives/src/trie_key.rs
  core/primitives/src/types.rs
  core/store/Cargo.toml
  core/store/src/trie/shard_tries.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/lib.rs
  tools/state-viewer/src/state_changes.rs
Labels: S-automerge

#8683 feat: remove ChainAccessForFlatStorage
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/columns.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/metrics.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime/src/genesis.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#8661 feat: Dump state of every epoch to S3
  CHANGELOG.md
  Cargo.lock
  chain/chain/src/store.rs
  core/chain-configs/src/client_config.rs
  core/primitives/src/syncing.rs
  docs/misc/state_sync_dump.md
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/Cargo.toml
  nearcore/src/config.rs
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  nearcore/src/state_sync.rs
  neard/src/cli.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8710 feat: use shard uids in deltas
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  integration-tests/src/tests/client/flat_storage.rs
  tools/flat-storage/src/commands.rs
Labels: S-automerge

#8701 cleanup: Remove `SECONDS_PER_PETAGAS` metric
  chain/client/src/info.rs
  chain/client/src/metrics.rs
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
Labels: C-housekeeping, S-automerge

#8709 chore: mocknet improvements
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/helpers/load_test_utils.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8689 feat: introduce flat storage status
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/store.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/columns.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#8721 toolchain: update to Rust 1.68.0
  Cargo.toml
  core/crypto/src/signature.rs
  core/primitives-core/src/hash.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#8720 feat: make prober_split pick a random reference legacy node
  pytest/tools/prober/prober_split.py
Labels: S-automerge

#8716 core: add Children type representing trie branch’s childrenas
  core/store/src/trie/insert_delete.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/state_parts.rs
  integration-tests/src/tests/runtime/state_viewer.rs
  tools/cold-store/src/cli.rs
Labels: S-automerge

#8717 mocknet improvements
  pytest/lib/mocknet.py
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8726 feat(flat-state): don't increase column caches
  core/store/src/config.rs
Labels: S-automerge

#8727 feat: remove flat state cache
  core/store/src/config.rs
  core/store/src/flat/storage.rs
  core/store/src/metrics.rs
  core/store/src/trie/config.rs
  core/store/src/trie/shard_tries.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
Labels: A-storage, S-automerge

#8715 fix(pytest): set boot nodes in recompress_storage.py
  pytest/tests/sanity/recompress_storage.py
Labels: S-automerge

#8729 feat: make FlatState value future proof for value inlining support
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
Labels: A-storage, S-automerge

#8736 refactor: State Sync - split long functions into many small functions
  chain/client/src/sync/state.rs
Labels: S-automerge

#8740 fix: more precise flat storage errors
  core/primitives/src/errors.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/types.rs
  core/store/src/trie/mod.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
Labels: A-storage, S-automerge

#8745 refactor: use shard_uid as a key in FlatStorageManager
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/store/src/flat/manager.rs
  core/store/src/flat/storage.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  tools/flat-storage/src/commands.rs
Labels: A-storage, S-automerge

#8749 feat(params-estimator): flat state deltas overhead
  core/store/src/flat/delta.rs
  runtime/runtime-params-estimator/src/config.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/transaction_builder.rs
  runtime/runtime-params-estimator/src/trie.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#8718 fix: proper flat storage deltas removal
  chain/chain/src/flat_storage_creator.rs
  core/primitives/src/shard_layout.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  integration-tests/src/tests/client/flat_storage.rs
Labels: S-automerge

#8743 feat: don't exclude delayed receipts from flat storage
  chain/chain/src/flat_storage_creator.rs
  core/primitives/src/state_record.rs
  core/store/src/flat/delta.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/split_state.rs
Labels: A-storage, S-automerge

#8739 Fix: Add --dry-run to the tool for applying state-parts
  CHANGELOG.md
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8752 refactor: move flat storage metrics to a separate module
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat/metrics.rs
  core/store/src/flat/mod.rs
  core/store/src/flat/storage.rs
  core/store/src/lib.rs
  core/store/src/metrics.rs
Labels: A-storage, S-automerge

#8755 Fix links to version.rs file
  docs/practices/protocol_upgrade.md
Labels: S-automerge, C-docs

#8754 fix: mocknet fixed helper crashing
  pytest/lib/mocknet_helpers.py
  pytest/tests/mocknet/helpers/load_test_spoon_helper.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8757 doc: flat state high-level overview
  docs/architecture/storage/flat_storage.md
Labels: S-automerge

#8735 fix: apply `log_summary_style` to state sync phase message
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/state.rs
Labels: S-automerge

#8751 fix/refactor(network::raw): rename raw::ReceivedMessage and accept message types as an arg to send_*()
  chain/network/src/raw/connection.rs
  chain/network/src/raw/mod.rs
  chain/network/src/raw/tests.rs
  tools/ping/src/lib.rs
  tools/state-parts/src/lib.rs
Labels: S-automerge

#8770 chore: Bump crates version to 0.16.1
  Cargo.toml
  utils/near-cache/README.md
Labels: S-automerge

#8767 [Runtime Epoch Split] (2/n) Narrow EpochManagerAdapter error type to EpochError wherever possible.
  chain/chain-primitives/src/error.rs
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chunks-primitives/src/error.rs
  chain/client-primitives/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/view_client.rs
  chain/epoch-manager/src/adapter.rs
  tools/mirror/src/offline.rs
Labels: S-automerge

#8766 feat: cold db overhaul
  Cargo.lock
  chain/client-primitives/src/types.rs
  core/o11y/src/lib.rs
  core/o11y/src/pretty.rs
  core/store/Cargo.toml
  core/store/src/cold_storage.rs
  core/store/src/columns.rs
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/refcount.rs
  core/store/src/db/splitdb.rs
  core/store/src/lib.rs
  integration-tests/src/tests/client/cold_storage.rs
Labels: S-automerge

#8769 [Runtime Epoch Split] (4/n) Make ShardTracker accessible from RuntimeWithEpochManagerAdapter.
  Cargo.lock
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/epoch-manager/src/adapter.rs
  chain/epoch-manager/src/lib.rs
  chain/epoch-manager/src/shard_tracker.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/features/adversarial_behaviors.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  integration-tests/src/tests/client/features/limit_contract_functions_number.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/zero_balance_account.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  test-utils/runtime-tester/Cargo.toml
  test-utils/runtime-tester/src/run_test.rs
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge

#8765 fix: Avoid `unwrap()` in code updating metrics
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
Labels: S-automerge

#8730 feat: Disable state sync by default because it's unreliable
  CHANGELOG.md
  chain/client/src/client.rs
  chain/client/src/info.rs
  chain/client/src/sync/block.rs
  core/chain-configs/src/client_config.rs
  nearcore/src/config.rs
Labels: S-automerge

#8780 Revert "chore: Enable publishing the crate near-vm-runner(and it's de…
  runtime/near-test-contracts/Cargo.toml
  runtime/near-test-contracts/LICENSE-APACHE
  runtime/near-test-contracts/LICENSE-MIT
  runtime/near-vm-runner/Cargo.toml
  utils/near-cache/Cargo.toml
  utils/near-cache/LICENSE-APACHE
  utils/near-cache/LICENSE-MIT
  utils/near-stable-hasher/Cargo.toml
  utils/near-stable-hasher/LICENSE-APACHE
  utils/near-stable-hasher/LICENSE-MIT
Labels: S-automerge

#8785 themis: skip dep publish requirement for dev-deps
  tools/themis/src/rules.rs
Labels: S-automerge

#8784 docs: describe protocol version vote and upgrade
  docs/practices/protocol_upgrade.md
Labels: S-automerge

#8786 themis: fix ENOENT when rust-toolchain.toml doesn't exist
  tools/themis/src/rules.rs
  tools/themis/src/utils.rs
Labels: S-automerge

#8783 feature: Get compute usage from profile
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  runtime/near-vm-logic/src/gas_counter.rs
Labels: S-automerge, A-contract-runtime

#8777 [TestLoop] Add AdhocEvent to allow executing arbitrary logic as part of a TestLoop event.
  core/async/src/examples/sum_numbers_test.rs
  core/async/src/test_loop.rs
  core/async/src/test_loop/adhoc.rs
  core/async/src/test_loop/event_handler.rs
  core/async/src/test_loop/multi_instance.rs
Labels: S-automerge

#8794 fix: State dump creates dumps at the correct point
  chain/chain/src/chain.rs
  core/primitives/src/syncing.rs
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
  nearcore/src/state_sync.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8803 bump protocol version for 1.33.0
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/src/version.rs
Labels: S-automerge

#8801 Fuzz 1.33.0
  nightly/fuzz.toml
Labels: S-automerge

#8800 fix(logging): clean up sync related log spam
  chain/client/src/client_actor.rs
Labels: S-automerge

#8807 fix: Epoch Sync implementation is delayed
  docs/architecture/how/sync.md
Labels: S-automerge

#8810 fix: Make the logging layer dynamically configure-able, as it used to be
  core/dyn-configs/src/lib.rs
  core/o11y/src/lib.rs
Labels: S-automerge

#8820 Upgrade to rust 1.68.2
  Cargo.toml
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#8815 fix: Update integration and pytests to enable state sync
  integration-tests/src/tests/nearcore/sync_nodes.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/state_sync.py
  pytest/tests/sanity/state_sync1.py
  pytest/tests/sanity/state_sync2.py
  pytest/tests/sanity/state_sync3.py
  pytest/tests/sanity/state_sync4.py
  pytest/tests/sanity/state_sync5.py
  pytest/tests/sanity/state_sync_fail.py
  pytest/tests/sanity/state_sync_late.py
  pytest/tests/sanity/state_sync_massive.py
  pytest/tests/sanity/state_sync_massive_validator.py
  pytest/tests/sanity/state_sync_routed.py
Labels: S-automerge

#8818 fix: Safely accumulate burnt gas for transaction to receipt conversion
  runtime/runtime/src/lib.rs
Labels: S-automerge

#8808 fix: Remove unused config fields
  chain/chain/src/test_utils/kv_runtime.rs
  chain/epoch-manager/src/shard_tracker.rs
  chain/epoch-manager/src/test_utils.rs
  chain/epoch-manager/src/tests/mod.rs
  chain/epoch-manager/src/validator_selection.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/chain-configs/src/client_config.rs
  core/chain-configs/src/genesis_config.rs
  core/primitives/src/epoch_manager.rs
  genesis-tools/genesis-csv-to-json/src/csv_to_json_configs.rs
  nearcore/res/example-config-gc.json
  nearcore/res/example-config-no-gc.json
  nearcore/src/config.rs
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#8802 Cut 1.33.0 in CHANGELOG
  CHANGELOG.md
Labels: S-automerge

#8830 Fix: rosetta zero balance accounts
  chain/rosetta-rpc/src/utils.rs
Labels: S-automerge

#8828 fix: Export as metric the current tracked shards
  chain/client/src/info.rs
Labels: S-automerge

#8824 make the near-vm stack limit an unsigned integer
  runtime/near-vm/benches/limits.rs
  runtime/near-vm/benches/static_and_dynamic_functions.rs
  runtime/near-vm/examples/README.md
  runtime/near-vm/examples/compiler_singlepass.rs
  runtime/near-vm/examples/coremark.rs
  runtime/near-vm/examples/early_exit.rs
  runtime/near-vm/examples/engine_universal.rs
  runtime/near-vm/examples/errors.rs
  runtime/near-vm/examples/exports_function.rs
  runtime/near-vm/examples/exports_global.rs
  runtime/near-vm/examples/exports_memory.rs
  runtime/near-vm/examples/features.rs
  runtime/near-vm/examples/hello_world.rs
  runtime/near-vm/examples/imports_exports.rs
  runtime/near-vm/examples/imports_function.rs
  runtime/near-vm/examples/imports_function_env.rs
  runtime/near-vm/examples/imports_global.rs
  runtime/near-vm/examples/instance.rs
  runtime/near-vm/examples/memory.rs
  runtime/near-vm/examples/table.rs
  runtime/near-vm/examples/tracy_exec.rs
  runtime/near-vm/lib/api/README.md
  runtime/near-vm/lib/api/src/lib.rs
  runtime/near-vm/lib/api/src/sys/env.rs
  runtime/near-vm/lib/api/src/sys/exports.rs
  runtime/near-vm/lib/api/src/sys/externals/function.rs
  runtime/near-vm/lib/api/src/sys/instance.rs
  runtime/near-vm/lib/api/src/sys/mod.rs
  runtime/near-vm/lib/types/src/types.rs
  runtime/near-vm/lib/vm/src/instance/mod.rs
  runtime/near-vm/tests/compilers/fast_gas_metering.rs
  runtime/near-vm/tests/compilers/imports.rs
  runtime/near-vm/tests/compilers/issues.rs
  runtime/near-vm/tests/compilers/multi_value_imports.rs
  runtime/near-vm/tests/compilers/native_functions.rs
  runtime/near-vm/tests/compilers/serialize.rs
  runtime/near-vm/tests/compilers/stack_limiter.rs
  runtime/near-vm/tests/compilers/traps.rs
  runtime/near-vm/tests/lib/wast/src/wast.rs
Labels: C-housekeeping, S-automerge

#8813 feat: update trie config values for 1.34
  core/store/src/config.rs
  core/store/src/trie/config.rs
Labels: S-automerge

#8835 store: add more cases to RawTrieNode encoding and decoding tests
  core/store/src/trie/mod.rs
Labels: S-automerge

#8837 Update networking.md with sample config
  docs/advanced_configuration/networking.md
Labels: S-automerge

#8843 chore: adjusted RocksDB logs from create/drop to open/close
  core/store/src/db/rocksdb.rs
  core/store/src/db/rocksdb/instance_tracker.rs
  nearcore/src/lib.rs
Labels: S-automerge

#8798 fix: Print `StateRecord`s corresponding to the range of a state part generated
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8838 implement finite-wasm intrinsics
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-runner/src/imports.rs
Labels: S-automerge

#8846 rename StackLimiterVersion into ContractPrepareVersion
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives/res/runtime_configs/50.yaml
  core/primitives/res/runtime_configs/parameters.snap
  core/primitives/res/runtime_configs/parameters.yaml
  core/primitives/res/runtime_configs/parameters_testnet.yaml
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__57.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__59.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_57.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_59.json.snap
  core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
  runtime/near-vm-runner/src/prepare.rs
Labels: S-automerge

#8737 feat: prober checks contract function call on split store node
  pytest/tools/prober/prober.py
  pytest/tools/prober/prober_split.py
  pytest/tools/prober/prober_util.py
Labels: S-automerge

#8849 fix: fix the buildkite tests when running on release branches
  core/primitives/src/upgrade_schedule.rs
  core/primitives/src/version.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/features/flat_storage.rs
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/zero_balance_account.rs
  pytest/lib/branches.py
  pytest/lib/cluster.py
  pytest/tests/sanity/upgradable.py
Labels: S-automerge

#8624 RocksDB metrics for cold storage
  Cargo.lock
  chain/client/src/info.rs
  chain/client/src/lib.rs
  chain/network/src/store/mod.rs
  core/store/Cargo.toml
  core/store/src/db.rs
  core/store/src/db/testdb.rs
  core/store/src/lib.rs
  core/store/src/metrics.rs
  core/store/src/rocksdb_metrics.rs
  core/store/src/test_utils.rs
  integration-tests/src/tests/client/cold_storage.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/lib.rs
Labels: S-automerge
