Repository near/nearcore, pull requests merged in 2023-02, with the labels that each got.

#8439 abort_on_panic in tests
  chain/network/src/peer_manager/tests/routing.rs
Labels: S-automerge

#8471 docs: Add documentation about `parameters.snap`
  core/primitives/res/README.md
  docs/architecture/gas/parameter_definition.md
Labels: S-automerge

#8420 refactor: Implement TryFrom for ParameterValue
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8477 feat: reject delegate actions on older protocol
  chain/client/Cargo.toml
  chain/client/src/test_utils.rs
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives/src/errors.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#8457 chore: avoid unchecked Instant - Duration
  chain/client/src/view_client.rs
  tools/mirror/src/lib.rs
Labels: S-automerge

#8459 refactor: better DB format for flat storage creation statuses
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/flat_storage.rs
Labels: S-automerge

#8472 added STUN-based TIER1 self-discovery
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/config.rs
  chain/network/src/config_json.rs
  chain/network/src/lib.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/stun/mod.rs
  chain/network/src/stun/testonly.rs
  chain/network/src/stun/tests.rs
  deny.toml
Labels: S-automerge

#8495 docs: Update Cross shard transactions deep dive
  docs/architecture/how/cross-shard.md
Labels: S-automerge, C-docs

#8496 adding cold_head_height metric
  core/store/src/cold_storage.rs
  core/store/src/metrics.rs
Labels: S-automerge

#8493 fix(mirror): dont assume receipts are always executed
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/lib.rs
Labels: S-automerge

#8483 feat(state-viewer): list actions invoked by each contract
  Cargo.lock
  core/store/src/test_utils.rs
  neard/Cargo.toml
  tools/state-viewer/Cargo.toml
  tools/state-viewer/README.md
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/contract_accounts.rs
Labels: S-automerge

#8498 refactor: Use `Gas` instead of `u64` in ProfileDataV3
  core/primitives-core/src/profile.rs
Labels: C-housekeeping, S-automerge

#8473 feat: enable flat state for runtime-params-estimator
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: A-storage, S-automerge, A-params-estimator, T-storage

#8507 docs: Update command to retrieve transaction gas profile
  docs/architecture/gas/gas_profile.md
Labels: S-automerge, C-docs

#8504 fix: re-enable nayduck nightly state_sync_massive tests
  nightly/pytest-sanity.txt
Labels: S-automerge

#8470 Handle height skips in update_cold_db
  core/store/src/cold_storage.rs
  integration-tests/src/tests/client/cold_storage.rs
  nearcore/src/cold_storage.rs
Labels: A-cold-storage

#8484 trivial: use question mark operator some more
  chain/chain/src/chain.rs
  chain/client/src/view_client.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  core/store/src/trie/prefetching_trie_storage.rs
Labels: S-automerge

#8509 fix: Allow non-validator nodes to track a subset of shards
  nearcore/src/config.rs
Labels: S-automerge

#8510 feat: allow creating cold store when hot store exists
  chain/client-primitives/src/types.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/split_storage.rs
  core/primitives/src/views.rs
  core/store/src/lib.rs
  core/store/src/metadata.rs
  core/store/src/migrations.rs
  core/store/src/opener.rs
  nearcore/src/lib.rs
  nearcore/src/migrations.rs
  pytest/lib/branches.py
  pytest/lib/cluster.py
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8530 fix(mirror): don't convert SignedTransactions to SignedTransactionViews
  tools/mirror/src/lib.rs
  tools/mirror/src/offline.rs
  tools/mirror/src/online.rs
Labels: S-automerge

#8538 feat: type guarantees for NonDelegateAction
  chain/client/src/test_utils.rs
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives/src/delegate_action.rs
  core/primitives/src/errors.rs
  core/primitives/src/lib.rs
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  runtime/runtime/src/actions.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#8546 feat: adding metrics for the cold store loop
  core/store/src/cold_storage.rs
  core/store/src/metrics.rs
  nearcore/src/cold_storage.rs
  nearcore/src/metrics.rs
Labels: S-automerge

#8536 refactor: Simplify gas price calculation logic
  core/primitives/src/block.rs
Labels: C-housekeeping, S-automerge

#8544 fix(mirror): unstake after staking pool contracts add more validators
  pytest/tools/mirror/contract/src/lib.rs
  pytest/tools/mirror/mirror_utils.py
  pytest/tools/mirror/offline_test.py
  tools/mirror/README.md
  tools/mirror/src/chain_tracker.rs
  tools/mirror/src/genesis.rs
  tools/mirror/src/key_mapping.rs
  tools/mirror/src/lib.rs
  tools/mirror/src/offline.rs
  tools/mirror/src/online.rs
Labels: S-automerge

#8446 fix: bump protocol version for ed25519 verify
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/src/version.rs
Labels: S-automerge

#8497 fix: Challenges fix from `1.30.1`
  chain/chain/src/chain.rs
Labels: S-automerge

#8552 fix: fixed the mac binary release tag pattern
  .github/workflows/mac_binary.yml
  .github/workflows/mac_m1_binary.yml
Labels: S-automerge

#8551 test: first rust meta tx integration tests
  core/primitives/src/test_utils.rs
  integration-tests/Cargo.toml
  integration-tests/src/node/runtime_node.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/user/mod.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/fees_utils.rs
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge

#8554 adding script to diff file on two google cloud machines
  scripts/remote_diff/diff_remote_files.sh
Labels: S-automerge

#8541 Update borsh dependency
  Cargo.lock
  Cargo.toml
  chain/network/src/network_protocol/borsh.rs
  core/account-id/src/borsh.rs
  core/crypto/src/signature.rs
  core/crypto/src/traits.rs
  core/primitives-core/src/account.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/profile.rs
  core/primitives-core/src/profile/profile_v2.rs
  core/primitives/src/delegate_action.rs
  core/primitives/src/time.rs
  deny.toml
  tools/speedy_sync/Cargo.toml
Labels: S-automerge

#8405 Cold db initial migration
  Cargo.lock
  core/store/src/cold_storage.rs
  core/store/src/db.rs
  core/store/src/metrics.rs
  integration-tests/src/tests/client/cold_storage.rs
  tools/cold-store/Cargo.toml
  tools/cold-store/src/cli.rs
Labels: S-automerge, A-cold-storage

#8458 Info tools for gcloud node setup
  scripts/remote_diff/show_config_hash.py
  scripts/remote_diff/show_neard_version.py
  scripts/remote_diff/utils.py
Labels: S-automerge

#8456 toolchain: update to 1.67.1
  Cargo.toml
  nearcore/src/download_file.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#8557 Canonicalize NaNs in the fuzzed modules, to avoid finding differing results between wasmtime and near-vm
  runtime/near-vm-runner/src/tests/fuzzers.rs
Labels: C-housekeeping, S-automerge

#8562 Revert borsh update
  Cargo.lock
  Cargo.toml
  chain/network/src/network_protocol/borsh.rs
  core/account-id/src/borsh.rs
  core/crypto/src/signature.rs
  core/crypto/src/traits.rs
  core/primitives-core/src/account.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/profile.rs
  core/primitives-core/src/profile/profile_v2.rs
  core/primitives/src/delegate_action.rs
  core/primitives/src/time.rs
  deny.toml
  tools/speedy_sync/Cargo.toml
Labels: C-bug, A-security, S-automerge

#8559 test: every action in a meta transaction
  integration-tests/src/tests/client/features/delegate_action.rs
Labels: S-automerge

#8564 test: meta transaction FT transfer
  core/primitives/src/test_utils.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  runtime/near-test-contracts/res/fungible_token.wasm
  runtime/near-test-contracts/src/lib.rs
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge

#8563 [fix] avoiding verifying edges twice
  chain/network/src/concurrency/rayon.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/routing/graph/mod.rs
  chain/network/src/routing/graph/tests.rs
Labels: S-automerge

#8548 feat: implemented prepare-hot subcommand for cold storage
  Cargo.lock
  chain/indexer/src/lib.rs
  chain/indexer/src/streamer/mod.rs
  core/store/benches/store_bench.rs
  core/store/src/db/rocksdb/snapshot.rs
  core/store/src/lib.rs
  core/store/src/opener.rs
  genesis-tools/genesis-populate/src/main.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/benches/store.rs
  nearcore/src/cold_storage.rs
  nearcore/src/lib.rs
  neard/src/cli.rs
  pytest/lib/cluster.py
  pytest/tests/sanity/split_storage.py
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/main.rs
  test-utils/store-validator/src/main.rs
  tools/cold-store/Cargo.toml
  tools/cold-store/src/cli.rs
  tools/mirror/src/lib.rs
  tools/mirror/src/offline.rs
  tools/mock-node/src/setup.rs
  tools/speedy_sync/src/main.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#8573 chore: cleanup irrelevant todo
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8575 fix: nayduck cli script
  scripts/nayduck.py
Labels: S-automerge

#8586 [Debug UI] Migrate TIER1 debug page
  tools/debug-ui/src/CurrentPeersView.tsx
  tools/debug-ui/src/NetworkInfoView.tsx
  tools/debug-ui/src/Tier1View.scss
  tools/debug-ui/src/Tier1View.tsx
  tools/debug-ui/src/api.tsx
  tools/debug-ui/src/utils.js
Labels: S-automerge

#8576 Add a flag to neard configuring reconnection to reliable peers on startup
  chain/network/src/config.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/tests/tier2.rs
  neard/src/cli.rs
Labels: S-automerge

#8341 [Debug UI] Migrate Epoch Info page to new UI
  tools/debug-ui/package-lock.json
  tools/debug-ui/package.json
  tools/debug-ui/src/App.tsx
  tools/debug-ui/src/EpochInfoView.scss
  tools/debug-ui/src/EpochInfoView.tsx
  tools/debug-ui/src/EpochShardsView.scss
  tools/debug-ui/src/EpochShardsView.tsx
  tools/debug-ui/src/EpochValidatorsView.scss
  tools/debug-ui/src/EpochValidatorsView.tsx
  tools/debug-ui/src/RecentEpochsView.scss
  tools/debug-ui/src/RecentEpochsView.tsx
  tools/debug-ui/src/api.tsx
  tools/debug-ui/src/index.tsx
  tools/debug-ui/src/utils.tsx
Labels: S-automerge

#8571 fix(tests): update set_no_chunk_in_block() logic
  test-utils/testlib/src/process_blocks.rs
Labels: S-automerge

#8591 fix: fix the split storage test
  chain/client/src/client_actor.rs
  nearcore/src/cold_storage.rs
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8568 test: meta transaction account creation scenarios
  Cargo.lock
  core/crypto/Cargo.toml
  core/crypto/src/test_utils.rs
  core/primitives/src/errors.rs
  core/primitives/src/test_utils.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  test-utils/testlib/Cargo.toml
  test-utils/testlib/src/fees_utils.rs
Labels: S-automerge

#8578 feat: signable message prefix for meta tx
  chain/client/src/test_utils.rs
  core/primitives/src/delegate_action.rs
  core/primitives/src/lib.rs
  core/primitives/src/signable_message.rs
  integration-tests/src/user/mod.rs
  pytest/lib/transaction.py
  runtime/runtime/src/actions.rs
Labels: S-automerge

#8597 feat: update delegate action gas cost
  core/primitives/res/runtime_configs/parameters.snap
  core/primitives/res/runtime_configs/parameters.yaml
Labels: S-automerge

#8602 chore: bump crates version to 0.16.0
  Cargo.toml
Labels: S-automerge

#8605 fix: crates.io compatible stdx dependency
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: S-automerge

#8603 docs: protocol changelog for meta transactions
  CHANGELOG.md
Labels: S-automerge

#8425 chain: avoid allocating throwaway vectors when recursing
  chain/chain/src/chain.rs
Labels: S-automerge

#8606 fix: JSON RPC Primitives with default features
  chain/jsonrpc-primitives/src/types/status.rs
Labels: S-automerge

#8612 jsonrpc: optimise parsing of legacy params format
  chain/jsonrpc/src/api/blocks.rs
  chain/jsonrpc/src/api/changes.rs
  chain/jsonrpc/src/api/chunks.rs
  chain/jsonrpc/src/api/config.rs
  chain/jsonrpc/src/api/gas_price.rs
  chain/jsonrpc/src/api/light_client.rs
  chain/jsonrpc/src/api/maintenance.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/api/query.rs
  chain/jsonrpc/src/api/receipts.rs
  chain/jsonrpc/src/api/sandbox.rs
  chain/jsonrpc/src/api/split_storage.rs
  chain/jsonrpc/src/api/transactions.rs
  chain/jsonrpc/src/api/validator.rs
  chain/jsonrpc/src/lib.rs
  core/primitives-core/src/serialize.rs
Labels: S-automerge

#8608 Update borsh dependency; again
  Cargo.lock
  Cargo.toml
  chain/network/src/network_protocol/borsh.rs
  core/account-id/src/borsh.rs
  core/crypto/src/signature.rs
  core/crypto/src/traits.rs
  core/primitives-core/src/account.rs
  core/primitives-core/src/hash.rs
  core/primitives-core/src/profile.rs
  core/primitives-core/src/profile/profile_v2.rs
  core/primitives/src/delegate_action.rs
  core/primitives/src/time.rs
  deny.toml
  tools/speedy_sync/Cargo.toml
Labels: S-automerge

#8585 [TestLoop] (3.4/n) Remove MsgRecipient and NetworkRecipient which are no longer used.
  chain/network/src/types.rs
Labels: S-automerge

#8594 [Debug UI] ESLint and Prettier for the debug UI code.
  tools/debug-ui/.eslintrc.yml
  tools/debug-ui/.prettierrc.json
  tools/debug-ui/README.md
  tools/debug-ui/package-lock.json
  tools/debug-ui/package.json
  tools/debug-ui/src/App.scss
  tools/debug-ui/src/App.tsx
  tools/debug-ui/src/ClusterNodeView.scss
  tools/debug-ui/src/ClusterNodeView.tsx
  tools/debug-ui/src/ClusterView.scss
  tools/debug-ui/src/ClusterView.tsx
  tools/debug-ui/src/ConnectionStorageView.tsx
  tools/debug-ui/src/CurrentPeersView.scss
  tools/debug-ui/src/CurrentPeersView.tsx
  tools/debug-ui/src/EpochInfoView.scss
  tools/debug-ui/src/EpochInfoView.tsx
  tools/debug-ui/src/EpochShardsView.scss
  tools/debug-ui/src/EpochShardsView.tsx
  tools/debug-ui/src/EpochValidatorsView.scss
  tools/debug-ui/src/EpochValidatorsView.tsx
  tools/debug-ui/src/HeaderBar.scss
  tools/debug-ui/src/HeaderBar.tsx
  tools/debug-ui/src/LatestBlocksView.scss
  tools/debug-ui/src/LatestBlocksView.tsx
  tools/debug-ui/src/NetworkInfoView.scss
  tools/debug-ui/src/NetworkInfoView.tsx
  tools/debug-ui/src/PeerStorageView.scss
  tools/debug-ui/src/PeerStorageView.tsx
  tools/debug-ui/src/RecentEpochsView.scss
  tools/debug-ui/src/RecentEpochsView.tsx
  tools/debug-ui/src/Tier1View.tsx
  tools/debug-ui/src/api.tsx
  tools/debug-ui/src/index.css
  tools/debug-ui/src/index.tsx
  tools/debug-ui/src/utils.tsx
  tools/debug-ui/tsconfig.json
Labels: S-automerge

#8587 [TestLoop] (4/n) Add multi-instance testing support to TestLoop framework.
  core/async/Cargo.toml
  core/async/src/examples/mod.rs
  core/async/src/examples/multi_instance_test.rs
  core/async/src/examples/sum_numbers_test.rs
  core/async/src/examples/timed_component.rs
  core/async/src/examples/timed_component_test.rs
  core/async/src/test_loop.rs
  core/async/src/test_loop/delay_sender.rs
  core/async/src/test_loop/event_handler.rs
  core/async/src/test_loop/multi_instance.rs
Labels: S-automerge

#8615 fix: enable io trace in state viewer
  core/o11y/src/lib.rs
Labels: S-automerge

#8611 feature: Add shard_id to SECONDS_PER_PETAGAS metric
  nearcore/src/metrics.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#8570 test: access keys scenarios in meta transactions
  integration-tests/src/tests/client/features/delegate_action.rs
  test-utils/testlib/src/runtime_utils.rs
Labels: S-automerge

#8531 [Flat storage] adding debug tool for flat storage
  Cargo.lock
  neard/Cargo.toml
  neard/src/cli.rs
  tools/flat-storage/Cargo.toml
  tools/flat-storage/README.md
  tools/flat-storage/src/commands.rs
  tools/flat-storage/src/lib.rs
Labels: S-automerge

#8549 Added support to iterate over a range in Database
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/database_tests.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/testdb.rs
  core/store/src/flat_state.rs
  core/store/src/lib.rs
Labels: S-automerge

#7919 fix: update IO replayer to understand new format
  core/o11y/src/pretty.rs
  runtime/runtime-params-estimator/res/75220100-75220101.s0.io_trace
  runtime/runtime-params-estimator/res/75220100-75220101.s1.io_trace
  runtime/runtime-params-estimator/res/75220100-75220101.s2.io_trace
  runtime/runtime-params-estimator/res/75220100-75220101.s3.io_trace
  runtime/runtime-params-estimator/src/replay.rs
Labels: S-automerge

#8613 feat: Adding SplitDB and refactoring ColdDB
  core/store/src/cold_storage.rs
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/refcount.rs
  core/store/src/db/splitdb.rs
  core/store/src/lib.rs
  core/store/src/test_utils.rs
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/cold_storage.rs
Labels: S-automerge

#8620 feat: neard init can initialize only node and validator keys if both Config and Genesis exist
  chain/indexer/src/lib.rs
  nearcore/src/config.rs
  neard/src/cli.rs
Labels: S-automerge

#8581 feat: Prober for black-box monitoring of archival nodes
  pytest/lib/configured_logger.py
  pytest/tools/prober/prober.py
Labels: S-automerge

#8623 Dump state part tool to support part ranges
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8625 Fuzz 1.32.0
  nightly/fuzz.toml
Labels: S-automerge

#8626 feat(state-viewer): exit w nonzero code on bad apply result
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#8607 Cold store migration in neard run
  core/store/src/cold_storage.rs
  core/store/src/metrics.rs
  integration-tests/src/tests/client/cold_storage.rs
  nearcore/src/cold_storage.rs
  tools/cold-store/src/cli.rs
Labels: S-automerge, A-cold-storage

#8561 Implemented Scope & Ctx
  Cargo.lock
  Cargo.toml
  chain/network/Cargo.toml
  chain/network/src/concurrency/asyncfn.rs
  chain/network/src/concurrency/ctx/mod.rs
  chain/network/src/concurrency/ctx/tests.rs
  chain/network/src/concurrency/ctx/time.rs
  chain/network/src/concurrency/mod.rs
  chain/network/src/concurrency/rayon.rs
  chain/network/src/concurrency/scope/mod.rs
  chain/network/src/concurrency/scope/tests.rs
  chain/network/src/concurrency/signal.rs
  chain/network/src/concurrency/tests.rs
  chain/network/src/lib.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/testonly/mod.rs
  chain/network/src/time.rs
  tools/chainsync-loadtest/src/concurrency/ctx.rs
  tools/chainsync-loadtest/src/concurrency/ctx_test.rs
  tools/chainsync-loadtest/src/concurrency/mod.rs
  tools/chainsync-loadtest/src/concurrency/rate_limiter.rs
  tools/chainsync-loadtest/src/concurrency/scope.rs
  tools/chainsync-loadtest/src/concurrency/scope_test.rs
  tools/chainsync-loadtest/src/fetch_chain.rs
  tools/chainsync-loadtest/src/main.rs
  tools/chainsync-loadtest/src/network.rs
Labels: S-automerge

#8629 fix(mocknet): use a different key for each validator
  pytest/lib/mocknet.py
  pytest/tests/mocknet/helpers/genesis_updater.py
  pytest/tests/mocknet/load_test_spoon.py
Labels: S-automerge

#8636 feat: Export `near-primtives` from `near-indexer-primtives`
  chain/indexer-primitives/src/lib.rs
Labels: S-automerge

#8638 [TestLoop] (7/n) Provide Clock from the TestLoop API.
  Cargo.lock
  core/async/Cargo.toml
  core/async/src/examples/async_component_test.rs
  core/async/src/examples/multi_instance_test.rs
  core/async/src/examples/sum_numbers_test.rs
  core/async/src/examples/timed_component_test.rs
  core/async/src/test_loop.rs
  core/async/src/test_loop/delay_sender.rs
  core/async/src/test_loop/event_handler.rs
  core/async/src/test_loop/futures.rs
  core/async/src/test_loop/multi_instance.rs
Labels: S-automerge

#8640 Script for migration to split storage
  scripts/split_storage_migration.sh
Labels: S-automerge, A-cold-storage

#8645 refactor: Util function to derive an implicit PK
  core/crypto/src/errors.rs
  core/crypto/src/test_utils.rs
  core/crypto/src/util.rs
  integration-tests/src/tests/client/features/delegate_action.rs
  runtime/runtime/src/actions.rs
  tools/mirror/src/key_mapping.rs
  tools/mirror/src/lib.rs
Labels: C-housekeeping, S-automerge

#8646 fix(cold-store): tail type
  nearcore/src/cold_storage.rs
Labels: S-automerge

#8639 downgraded PermitDrop error from panic to regular error
  chain/network/src/peer_manager/connection/mod.rs
Labels: S-automerge

#8657 doc: describe corner cases of meta transactions
  docs/architecture/how/meta-tx.md
Labels: C-docs

#8643 [TestLoop] (8/n) Use Clock for ShardsManager. Also remove SealsManager.
  chain/chunks/src/lib.rs
  chain/chunks/src/shards_manager_actor.rs
  chain/chunks/src/test_utils.rs
  chain/client/src/test_utils.rs
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge
