Repository near/nearcore, pull requests merged in 2023-01, with the labels that each got.

#8277 runtime: introduce PublicKeyBuffer to avoid memory allocation
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/receipt_manager.rs
Labels: S-automerge

#8276 runtime: introduce MemoryLike::view_memory to avoid memcpy
  runtime/near-vm-logic/src/dependencies.rs
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_memory.rs
  runtime/near-vm-logic/src/vmstate.rs
  runtime/near-vm-runner/src/memory.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#8273 refactor: fix clippy issues in near-vm-errors
  runtime/near-vm-errors/src/lib.rs
Labels: S-automerge

#8286 refactor: avoid code code duplication when locking TrieCache
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/trie_storage.rs
Labels: S-automerge

#8236 Minor refactoring around ‘let … = if …’ and ‘let … = match …’ statements
  chain/chunks/src/lib.rs
  chain/network/src/broadcast/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm-runner/src/wasmer_runner.rs
  tools/chainsync-loadtest/src/concurrency/weak_map.rs
Labels: S-automerge

#8287 feat: try reading shard_cache if prefetcher blocking_get returns None
  core/store/src/metrics.rs
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/trie_storage.rs
Labels: S-automerge

#8281 Fuzz 1.31.0
  nightly/fuzz.toml
Labels: S-automerge

#8285 fix: Deterministic tx size in estimation
  genesis-tools/genesis-populate/src/lib.rs
  runtime/runtime-params-estimator/src/action_costs.rs
Labels: S-automerge

#8283 Update changelog for 1.30 and 1.31
  CHANGELOG.md
Labels: S-automerge

#8246 refactor: fix clippy issues in near-primitives-core
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives-core/src/hash.rs
  core/primitives-core/src/serialize.rs
  core/primitives-core/src/types.rs
Labels: S-automerge

#8289 fix(integration-tests): fix tests after tx status RPC changes
  integration-tests/src/tests/runtime/deployment.rs
  integration-tests/src/tests/runtime/sanity_checks.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nondeterministic.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_status_nondeterministic.snap
  integration-tests/src/tests/runtime/test_evil_contracts.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/user/runtime_user.rs
Labels: S-automerge

#8235 o11y: avoid temporary String allocations when formatting log messages
  chain/chain/src/blocks_delay_tracker.rs
  chain/client/src/client_actor.rs
  chain/client/src/info.rs
  core/o11y/src/io_tracer.rs
  core/primitives/src/utils.rs
Labels: S-automerge

#8284 chore: upgrade rust-version to 1.66.0
  Cargo.toml
  chain/chain/src/missing_chunks.rs
  chain/chunks/src/lib.rs
  chain/jsonrpc/jsonrpc-tests/tests/rpc_transactions.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
Labels: S-automerge

#8291 refactor: fix clippy issues for near-o11y
  core/o11y/benches/metrics.rs
  core/o11y/src/lib.rs
  core/o11y/src/pretty.rs
Labels: S-automerge

#8294 refactor: Sort state-viewer commands and add missing documentation
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
Labels: S-automerge

#8302 fix(pytest): fix assert in switch_node_key.py
  pytest/tests/sanity/switch_node_key.py
Labels: S-automerge

#8297 fix: estimator generates too long account names
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#8290 chore: remove outdated constant ATTO_NEAR
  nearcore/src/config.rs
Labels: S-automerge

#8300 refactor: remove noop code around abusive peer banning
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#8309 chore: tokio patch version update to 1.18.4
  Cargo.lock
  Cargo.toml
Labels: S-automerge, C-dependencies

#7960 [Debug UI] Last blocks: Fix rendering of genesis block
  chain/client/src/debug.rs
Labels: S-automerge

#8305 fix: only add '-Ctarget-feature=+sse4.1,+sse4.2' flags for x86_64
  .cargo/config.toml
Labels: S-automerge

#8317 Update logo to invert colors when in dark mode
  docs/images/logo.svg
Labels: S-automerge

#8319 chore: update paperclip deps
  Cargo.lock
Labels: S-automerge

#8316 Added docs on how to run localnet on many machines
  docs/SUMMARY.md
  docs/practices/workflows/localnet_on_many_machines.md
Labels: S-automerge

#8299 feat: enable clippy::correctness as part of CI
  .buildkite/pipeline.yml
  chain/chain/src/store_validator/validate.rs
  chain/chunks/src/lib.rs
  chain/network/src/concurrency/rate.rs
  core/store/src/trie/mod.rs
  scripts/run_clippy.sh
  tools/state-viewer/src/apply_chunk.rs
Labels: S-automerge, A-CI

#8330 feat: enable clippy suspicious as part of CI
  integration-tests/src/test_helpers.rs
  scripts/run_clippy.sh
Labels: S-automerge, A-CI

#8310 refactor: Migrate parameter configs to YAML
  Cargo.lock
  Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/res/README.md
  core/primitives/res/runtime_configs/42.txt
  core/primitives/res/runtime_configs/42.yaml
  core/primitives/res/runtime_configs/48.txt
  core/primitives/res/runtime_configs/48.yaml
  core/primitives/res/runtime_configs/49.txt
  core/primitives/res/runtime_configs/49.yaml
  core/primitives/res/runtime_configs/50.txt
  core/primitives/res/runtime_configs/50.yaml
  core/primitives/res/runtime_configs/52.txt
  core/primitives/res/runtime_configs/52.yaml
  core/primitives/res/runtime_configs/53.txt
  core/primitives/res/runtime_configs/53.yaml
  core/primitives/res/runtime_configs/57.txt
  core/primitives/res/runtime_configs/57.yaml
  core/primitives/res/runtime_configs/parameters.yaml
  core/primitives/res/runtime_configs/parameters_testnet.yaml
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/parameter_table.rs
  docs/architecture/gas/parameter_definition.md
Labels: S-automerge

#8313 feat: add db operation for removing range of keys
  core/store/src/db.rs
  core/store/src/db/colddb.rs
  core/store/src/db/rocksdb.rs
  core/store/src/db/testdb.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
Labels: S-automerge, T-storage

#8148 feat: gas profile by parameter
  CHANGELOG.md
  Cargo.lock
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile.rs
  core/primitives-core/src/profile/profile_v2.rs
  core/primitives-core/src/profile/snapshots/near_primitives_core__profile__profile_v2__test__profile_data_debug.snap
  core/primitives-core/src/snapshots/near_primitives_core__profile__profile_v1__test__profile_data_debug.snap
  core/primitives-core/src/snapshots/near_primitives_core__profile__test__profile_data_debug.snap
  core/primitives/src/snapshots/near_primitives__views__tests__exec_metadata_v1_view.snap
  core/primitives/src/snapshots/near_primitives__views__tests__exec_metadata_v2_view.snap
  core/primitives/src/snapshots/near_primitives__views__tests__exec_metadata_v3_view.snap
  core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
  core/primitives/src/transaction.rs
  core/primitives/src/views.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile.snap
  integration-tests/src/tests/runtime/snapshots/integration_tests__tests__runtime__sanity_checks__receipts_gas_profile_nightly.snap
  runtime/near-vm-logic/src/gas_counter.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#8278 Remove field `Client::me`
  chain/client/src/client.rs
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#8325 Remove superfluous layer tag from logo.svg
  docs/images/logo.svg
Labels: S-automerge

#8336 toolchain: update to 1.66.1
  Cargo.toml
  rust-toolchain.toml
Labels: S-automerge

#8331 doc: gas profiles
  docs/architecture/gas/gas_profile.md
Labels: S-automerge

#8335 scripts: maintain clippy lints in a bash array
  scripts/run_clippy.sh
Labels: S-automerge

#8342 docs: comments for check_triggers
  chain/client/src/client_actor.rs
Labels: S-automerge

#8262 refactor: move background flat storage creaton to Client
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/lib.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/test_utils.rs
  core/chain-configs/src/client_config.rs
  core/store/src/config.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/config.rs
Labels: S-automerge, T-storage

#8301 fix(store-validator): fix outcome_indexed_by_block_hash() logic
  chain/chain/src/store_validator/validate.rs
Labels: S-automerge

#8345 Fix contract deployment detection command to avoid greedy match
  docs/misc/database.md
Labels: S-automerge

#8298 runtime: use an allocated slice to represent mocked memory
  runtime/near-vm-logic/src/lib.rs
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/mocks/mock_memory.rs
  runtime/near-vm-logic/src/test_utils.rs
  runtime/near-vm-logic/src/tests/alt_bn128.rs
  runtime/near-vm-logic/src/tests/context.rs
  runtime/near-vm-logic/src/tests/ed25519_verify.rs
  runtime/near-vm-logic/src/tests/fixtures.rs
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-logic/src/tests/promises.rs
  runtime/near-vm-logic/src/tests/registers.rs
  runtime/near-vm-logic/src/tests/storage_read_write.rs
  runtime/near-vm-logic/src/tests/storage_usage.rs
  runtime/near-vm-logic/src/tests/vm_logic_builder.rs
  runtime/near-vm-logic/src/vmstate.rs
  runtime/near-vm-runner/src/memory.rs
  runtime/near-vm-runner/src/tests.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: S-automerge

#8307 dump-state-parts can store state parts on S3
  Cargo.lock
  Cargo.toml
  deny.toml
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/dump_state_parts.rs
Labels: S-automerge

#8344 refactor: Get rid of JSON in parameter_table
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8360 bumped protocol version
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/jsonrpc-tests/res/genesis_config.json
  core/primitives/src/version.rs
Labels: S-automerge

#8366 fix: fix block_refcount_final validation
  chain/chain/src/store_validator/validate.rs
Labels: S-automerge

#8225 store: extend test_encode_decode RawTrieNode test
  core/store/src/trie/mod.rs
Labels: S-automerge

#8359 near-vm-logic: test log methods behaviour when memory access is violated
  runtime/near-vm-logic/src/tests/logs.rs
  runtime/near-vm-logic/src/tests/miscs.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-logic/src/tests/vm_logic_builder.rs
Labels: S-automerge

#8368 wasmtime: upgrade to 4.0
  Cargo.lock
  Cargo.toml
  deny.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/near-vm-runner/src/wasmtime_runner.rs
Labels: S-automerge

#8327 don't ban peers if the block timestamp is in the future
  chain/client/src/client.rs
Labels: S-automerge

#8371 feat(state-viewer): list accounts with contracts
  Cargo.lock
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/contract_accounts.rs
  tools/state-viewer/src/lib.rs
Labels: S-automerge

#8377 added back support for receiving StateResponse
  chain/network/src/network_protocol/mod.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
Labels: S-automerge

#8391 fix(pytest): don't rely on log line format in malicious_chain.py
  pytest/tests/adversarial/malicious_chain.py
Labels: S-automerge

#8384 feature: Structured parameters config
  core/primitives-core/src/parameter.rs
  core/primitives/res/runtime_configs/parameters.yaml
  core/primitives/res/runtime_configs/parameters_testnet.yaml
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8240 feat(dynamic config): Refactor and make several config fields reloadable at runtime
  Cargo.lock
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/config_updater.rs
  chain/client/src/info.rs
  chain/client/src/lib.rs
  chain/client/src/test_utils.rs
  core/chain-configs/Cargo.toml
  core/chain-configs/src/client_config.rs
  core/chain-configs/src/lib.rs
  core/chain-configs/src/metrics.rs
  core/chain-configs/src/updateable_config.rs
  core/dyn-configs/Cargo.toml
  core/dyn-configs/README.md
  core/dyn-configs/src/lib.rs
  core/dyn-configs/src/metrics.rs
  core/o11y/src/lib.rs
  core/o11y/src/log_config.rs
  integration-tests/src/tests/network/runner.rs
  nearcore/src/config.rs
  nearcore/src/dyn_config.rs
  nearcore/src/lib.rs
  nearcore/src/metrics.rs
  neard/Cargo.toml
  neard/src/cli.rs
  neard/src/main.rs
  neard/src/watchers/dyn_config_watcher.rs
  neard/src/watchers/log_config_watcher.rs
  neard/src/watchers/mod.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#8390 chore: Bump insta from 1.14.0 to 1.26.0
  Cargo.lock
  Cargo.toml
Labels: C-housekeeping, S-automerge

#8348 fix: flat storage methods readability
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/flat_storage.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge, T-storage

#8367 feat: more flat storage creation tests
  chain/chain/src/flat_storage_creator.rs
  core/store/src/flat_state.rs
  integration-tests/src/tests/client/flat_storage.rs
Labels: T-storage

#8385 feat: draft implementation of NEP-366 (fork)
  chain/chain/src/tests/simple_chain.rs
  chain/jsonrpc/res/rpc_errors_schema.json
  chain/rosetta-rpc/Cargo.toml
  chain/rosetta-rpc/src/adapters/mod.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/parameter.rs
  core/primitives-core/src/runtime/fees.rs
  core/primitives/Cargo.toml
  core/primitives/res/runtime_configs/parameters.yaml
  core/primitives/res/runtime_configs/parameters_testnet.yaml
  core/primitives/src/errors.rs
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__57.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_57.json.snap
  core/primitives/src/transaction.rs
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
  runtime/runtime/src/balance_checker.rs
  runtime/runtime/src/config.rs
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#8387 added io::ErrorKind::TimedOut as an expected connection error
  chain/network/src/peer/peer_actor.rs
Labels: S-automerge

#8374 near-vm-logic: avoid memory copy in get_utf16_string
  Cargo.lock
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/vmstate.rs
  runtime/runtime/Cargo.toml
Labels: S-automerge

#8392 chore: Bump paperclip from 0.7.0 to 0.8.0
  Cargo.lock
  Cargo.toml
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8393 refactor: Migrate to Rational32 in parameter config
  core/primitives-core/src/runtime/fees.rs
  core/primitives/src/runtime/parameter_table.rs
  core/primitives/src/views.rs
  runtime/runtime/src/config.rs
  runtime/runtime/tests/runtime_group_tools/random_config.rs
Labels: S-automerge

#8132 test: test all actions for out-of-gas results
  runtime/near-vm-logic/src/tests/gas_counter.rs
  runtime/near-vm-logic/src/tests/helpers.rs
Labels: S-automerge

#8394 Added pytest support for meta transactions (and a new sanity test)
  nightly/pytest-sanity.txt
  pytest/lib/messages/tx.py
  pytest/lib/serializer.py
  pytest/lib/transaction.py
  pytest/tests/sanity/meta_tx.py
Labels: S-automerge

#8414 improved column documentation
  core/store/src/columns.rs
Labels: S-automerge

#8411 [nayduck] revamp of the rpc finality test.
  pytest/tests/sanity/rpc_finality.py
Labels: S-automerge

#8403 Nayduck - broken tests cleanup
  integration-tests/src/tests/client/chunks_management.rs
  nightly/pytest-sanity.txt
  pytest/tests/sanity/rpc_finality.py
Labels: S-automerge

#8412 fix: disable integration tests that are broken on mac
  integration-tests/src/tests/client/features/wasmer2.rs
  integration-tests/src/tests/client/process_blocks.rs
Labels: S-automerge

#8404 Fixing state_sync_routed nayduck test
  pytest/lib/utils.py
  pytest/tests/sanity/state_sync_routed.py
Labels: S-automerge

#8409 refactor: Add ParameterValue::as_u128
  core/primitives/src/runtime/parameter_table.rs
Labels: C-housekeeping, S-automerge

#8418 arbitrary: upgrade to 1.2.3
  Cargo.lock
  Cargo.toml
  runtime/near-test-contracts/Cargo.toml
Labels: S-automerge

#8357 [Runtime Epoch Split] (1/n) Split RuntimeAdapter to separate trait, and rename combined trait to RuntimeAndEpochManagerAdapter
  chain/chain/src/blocks_delay_tracker.rs
  chain/chain/src/chain.rs
  chain/chain/src/flat_storage_creator.rs
  chain/chain/src/lib.rs
  chain/chain/src/lightclient.rs
  chain/chain/src/migrations.rs
  chain/chain/src/store.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/chain/src/validate.rs
  chain/chunks/src/lib.rs
  chain/chunks/src/logic.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/debug.rs
  chain/client/src/sync/state.rs
  chain/client/src/test_utils.rs
  chain/client/src/view_client.rs
  chain/epoch-manager/src/adapter.rs
  docs/architecture/README.md
  docs/practices/testing/README.md
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/tests/client/features/access_key_nonce_for_implicit_accounts.rs
  integration-tests/src/tests/client/features/account_id_in_function_call_permission.rs
  integration-tests/src/tests/client/features/adversarial_behaviors.rs
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/features/increase_deployment_cost.rs
  integration-tests/src/tests/client/features/limit_contract_functions_number.rs
  integration-tests/src/tests/client/features/lower_storage_key_limit.rs
  integration-tests/src/tests/client/features/restore_receipts_after_fix_apply_chunks.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/runtimes.rs
  integration-tests/src/tests/client/sandbox.rs
  nearcore/benches/store.rs
  nearcore/src/runtime/mod.rs
  nearcore/tests/economics.rs
  test-utils/store-validator/src/main.rs
  tools/mirror/src/offline.rs
  tools/mock-node/src/lib.rs
  tools/mock-node/src/setup.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/dump_state_parts.rs
  tools/state-viewer/src/epoch_info.rs
  tools/state-viewer/src/state_dump.rs
Labels: S-automerge

#8378 feat: add zero balance accounts
  chain/chain/src/tests/simple_chain.rs
  core/primitives/Cargo.toml
  core/primitives/src/runtime/mod.rs
  core/primitives/src/version.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/features.rs
  integration-tests/src/tests/client/features/zero_balance_account.rs
  integration-tests/src/tests/standard_cases/mod.rs
  nearcore/Cargo.toml
  runtime/runtime/Cargo.toml
  runtime/runtime/src/lib.rs
  runtime/runtime/src/verifier.rs
Labels: S-automerge

#8098 stabilizing ed25519_verify host function
  CHANGELOG.md
  core/primitives-core/Cargo.toml
  core/primitives-core/src/config.rs
  core/primitives-core/src/profile/profile_v2.rs
  core/primitives-core/src/snapshots/near_primitives_core__profile__test__profile_data_debug.snap
  core/primitives/Cargo.toml
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__57.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_0.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_42.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_48.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_49.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_50.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_52.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_53.json.snap
  core/primitives/src/runtime/snapshots/near_primitives__runtime__config_store__tests__testnet_57.json.snap
  core/primitives/src/snapshots/near_primitives__views__tests__exec_metadata_v2_view.snap
  core/primitives/src/snapshots/near_primitives__views__tests__exec_metadata_v3_view.snap
  core/primitives/src/snapshots/near_primitives__views__tests__runtime_config_view.snap
  core/primitives/src/version.rs
  core/primitives/src/views.rs
  runtime/near-test-contracts/estimator-contract/Cargo.toml
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/near-vm-logic/Cargo.toml
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/mod.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/imports.rs
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/costs_to_runtime_config.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
Labels: S-automerge

#8370 refactor: fix clippy::integer_arithmetic in core packages
  core/account-id/src/lib.rs
  core/crypto/src/lib.rs
  core/crypto/src/signature.rs
  core/o11y/src/lib.rs
  core/o11y/src/pretty.rs
  core/primitives/src/utils.rs
  core/primitives/src/views.rs
  utils/stdx/src/lib.rs
Labels: S-automerge

#8369 docs: Add a section to style on integer arithmetic
  docs/practices/style.md
Labels: S-automerge

#8428 refactor: Use structured Fee parameter value
  core/primitives-core/src/parameter.rs
  core/primitives/res/runtime_configs/48.yaml
  core/primitives/res/runtime_configs/53.yaml
  core/primitives/res/runtime_configs/parameters.yaml
  core/primitives/res/runtime_configs/parameters_testnet.yaml
  core/primitives/src/runtime/parameter_table.rs
Labels: C-housekeeping, S-automerge

#8429 [nayduck] comment out the test contents and not the test
  integration-tests/src/tests/client/chunks_management.rs
Labels: S-automerge

#8407 fixed broadcasting AccountData after node restart.
  chain/network/src/accounts_data/mod.rs
  chain/network/src/accounts_data/tests.rs
  chain/network/src/config.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/proto_conv/account_key.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/network_protocol/tests.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/tier1.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/accounts_data.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/stats/metrics.rs
  chain/network/src/time.rs
Labels: S-automerge

#8424 near-store: extend state dump file to include FlatState
  core/store/src/lib.rs
  core/store/src/trie/mod.rs
  genesis-tools/genesis-populate/src/state_dump.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#8434 [nayduck] Fix gc after sync
  pytest/tests/sanity/gc_after_sync.py
Labels: S-automerge

#8413 Fix for skip_epoch nayduck test
  chain/chain/src/chain.rs
Labels: S-automerge

#8440 Rollforward "deprecating AnnounceAccount (#8182)"
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#8444 fix: protocol_feature_nep366_delegate_action feature for runtime-params-estimator
  runtime/runtime-params-estimator/Cargo.toml
Labels: S-automerge

#8441 doc: clarify process for becoming a code owner
  CONTRIBUTING.md
Labels: S-automerge

#8443 feature: Store latest parameter snapshot
  core/primitives/res/runtime_configs/parameters.snap
  core/primitives/src/runtime/config_store.rs
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8448 refactor: use typed list of estimations in CLI
  runtime/runtime-params-estimator/src/config.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/cost_table.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/main.rs
Labels: S-automerge

#8417 feat: add flat state support for genesis-populate
  genesis-tools/genesis-populate/Cargo.toml
  genesis-tools/genesis-populate/src/lib.rs
  nightly/pytest-sanity.txt
Labels: A-storage, S-automerge, T-storage

#8432 feat: implemented the cold store loop
  CHANGELOG.md
  chain/client-primitives/src/types.rs
  chain/client/src/lib.rs
  chain/client/src/view_client.rs
  chain/jsonrpc-primitives/src/types/mod.rs
  chain/jsonrpc-primitives/src/types/split_storage.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/api/split_storage.rs
  chain/jsonrpc/src/lib.rs
  core/store/src/lib.rs
  nearcore/src/cold_storage.rs
  nearcore/src/lib.rs
  neard/src/cli.rs
  nightly/pytest-sanity.txt
  pytest/README.md
  pytest/lib/cluster.py
  pytest/tests/sanity/split_storage.py
Labels: S-automerge

#8397 chore: remove `ActionCreationConfig` et al.
  core/primitives-core/src/runtime/fees.rs
Labels: S-automerge

#8431 added a ListenerAddr struct which "owns" a TCP port
  chain/jsonrpc/fuzz/fuzz_targets/fuzz_target_1.rs
  chain/jsonrpc/jsonrpc-tests/src/lib.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/config.rs
  chain/network/src/network_protocol/peer.rs
  chain/network/src/network_protocol/testonly.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/peer_manager/testonly.rs
  chain/network/src/peer_manager/tests/routing.rs
  chain/network/src/peer_manager/tests/tier1.rs
  chain/network/src/raw/tests.rs
  chain/network/src/tcp.rs
  chain/network/src/test_utils.rs
  integration-tests/src/node/process_node.rs
  integration-tests/src/node/thread_node.rs
  integration-tests/src/tests/nearcore/node_cluster.rs
  integration-tests/src/tests/nearcore/stake_nodes.rs
  integration-tests/src/tests/nearcore/sync_nodes.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  integration-tests/src/tests/network/peer_handshake.rs
  integration-tests/src/tests/network/runner.rs
  integration-tests/src/tests/network/stress_network.rs
  integration-tests/src/tests/test_errors.rs
  nearcore/src/config.rs
  neard/src/cli.rs
  tools/mock-node/src/setup.rs
Labels: S-automerge

#8453 doc: storage request flow
  docs/SUMMARY.md
  docs/architecture/storage.md
  docs/architecture/storage/database.md
  docs/architecture/storage/flat_storage.md
  docs/architecture/storage/flow.md
  docs/architecture/storage/trie.md
Labels: S-automerge

#8452 test: sanity check storage setup in estimator
  runtime/runtime-params-estimator/Cargo.toml
  runtime/runtime-params-estimator/src/main.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: S-automerge

#8454 Fix Nayduck test repro_2916.py.
  pytest/lib/cluster.py
  pytest/tests/sanity/repro_2916.py
Labels: S-automerge

#8433 fix!(vm-logic): Remove error from attached deposit for view calls
  runtime/near-vm-logic/src/logic.rs
  runtime/near-vm-logic/src/tests/context.rs
  runtime/near-vm-logic/src/tests/view_method.rs
Labels: S-automerge

#8460 jsonrpc: simplify params representation
  chain/jsonrpc-primitives/src/message.rs
  chain/jsonrpc/client/src/lib.rs
  chain/jsonrpc/src/api/blocks.rs
  chain/jsonrpc/src/api/changes.rs
  chain/jsonrpc/src/api/chunks.rs
  chain/jsonrpc/src/api/config.rs
  chain/jsonrpc/src/api/gas_price.rs
  chain/jsonrpc/src/api/light_client.rs
  chain/jsonrpc/src/api/maintenance.rs
  chain/jsonrpc/src/api/mod.rs
  chain/jsonrpc/src/api/query.rs
  chain/jsonrpc/src/api/receipts.rs
  chain/jsonrpc/src/api/sandbox.rs
  chain/jsonrpc/src/api/split_storage.rs
  chain/jsonrpc/src/api/transactions.rs
  chain/jsonrpc/src/api/validator.rs
  chain/jsonrpc/src/lib.rs
Labels: S-automerge

#8449 refactor: Remove `remove_prefix` from `yaml_map`
  core/primitives/src/runtime/parameter_table.rs
Labels: S-automerge

#8399 feat(dynamic config): Changelog for #8240
  CHANGELOG.md
Labels: S-automerge

#8312 Add a command to apply state parts
  Cargo.lock
  Cargo.toml
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/dump_state_parts.rs
  tools/state-viewer/src/lib.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#8462 Patched Fix Rust's regex crate vulnerable to regular expression denial of service
  pytest/tests/loadtest/contract/Cargo.lock
Labels: S-automerge

#8463 fix: temporary disable state sync nightly nayduck tests
  nightly/pytest-sanity.txt
Labels: S-automerge

#8465 refactor: Fix typo in the function name
  runtime/runtime/tests/runtime_group_tools/mod.rs
Labels: S-automerge

#8464 refactor: replace TrieNodesCount sub with checked_sub
  core/primitives/src/types.rs
  core/store/src/trie/trie_tests.rs
  runtime/near-vm-logic/src/logic.rs
Labels: C-housekeeping, S-automerge

#8466 fix(amend-genesis): write account records before code records
  tools/amend-genesis/src/lib.rs
Labels: S-automerge

#8099 docs: improve formatting consistency
  docs/advanced_configuration/networking.md
  docs/architecture/README.md
  docs/architecture/gas/README.md
  docs/architecture/gas/estimator.md
  docs/architecture/gas/gas_profile.md
  docs/architecture/gas/parameter_definition.md
  docs/architecture/how/README.md
  docs/architecture/how/cross-shard.md
  docs/architecture/how/epoch.md
  docs/architecture/how/proofs.md
  docs/architecture/how/sync.md
  docs/architecture/how/tx_receipts.md
  docs/architecture/how/tx_routing.md
  docs/architecture/network.md
  docs/architecture/storage/trie.md
  docs/misc/README.md
  docs/practices/docs.md
  docs/practices/fast_builds.md
  docs/practices/protocol_upgrade.md
  docs/practices/rust.md
  docs/practices/security_vulnerabilities.md
  docs/practices/style.md
  docs/practices/testing/README.md
  docs/practices/testing/python_tests.md
  docs/practices/testing/test_utils.md
  docs/practices/tracking_issues.md
  docs/practices/workflows/README.md
  docs/practices/workflows/deploy_a_contract.md
  docs/practices/workflows/gas_estimations.md
  docs/practices/workflows/run_a_node.md
Labels: S-automerge

#8212 feat(zero storage) Set storage costs to zero
  chain/indexer/Cargo.toml
  core/primitives/Cargo.toml
  core/primitives/src/runtime/config_store.rs
  integration-tests/Cargo.toml
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge, T-node
