Repository near/nearcore, pull requests merged in 2023-07, with the labels that each got.

#9270 remove near-stable-hasher dep from near-vm-runner
  Cargo.lock
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/lib.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/utils.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
Labels: C-housekeeping, S-automerge

#9257 feat(loadtest): improve error handling
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9258 refactor(loadtest): function call tx abstraction
  pytest/lib/key.py
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
Labels: S-automerge

#9275 fix(state-sync): Finalize state sync using flat storage
  chain/chain/src/chain.rs
Labels: S-automerge

#9288 bump proc-macro2 to fix fuzzers build
  Cargo.lock
  Cargo.toml
Labels: C-housekeeping, S-automerge

#9281 feat(loadtest): Sweat user class
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/congestion.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
  pytest/tests/loadtest/locust/common/sweat.py
  pytest/tests/loadtest/locust/download_contracts.sh
  pytest/tests/loadtest/locust/locustfiles/sweat.py
  pytest/tests/loadtest/locust/res/sweat.wasm
Labels: S-automerge

#9274 feat: simple nightshade v2 - shard layout with 5 shards
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/version.rs
  core/primitives/Cargo.toml
  core/primitives/src/epoch_manager.rs
  core/primitives/src/shard_layout.rs
  nearcore/Cargo.toml
  neard/Cargo.toml
Labels: S-automerge

#9296 refactor: small refactorings and improvements
  Cargo.lock
  chain/chain/src/block_processing_utils.rs
  chain/chain/src/chain.rs
  chain/chain/src/store.rs
  core/o11y/Cargo.toml
  core/o11y/src/log_config.rs
  docs/architecture/how/resharding.md
  docs/architecture/how/sync.md
  nearcore/src/config.rs
  nearcore/src/dyn_config.rs
  runtime/near-vm-runner/src/utils.rs
Labels: S-automerge

#9295 near-vm-runner: move protocol-sensitive error schemas to near-primitives
  Cargo.lock
  chain/jsonrpc/res/rpc_errors_schema.json
  core/primitives/src/errors.rs
  integration-tests/src/tests/client/features/limit_contract_functions_number.rs
  integration-tests/src/tests/runtime/test_evil_contracts.rs
  integration-tests/src/tests/standard_cases/mod.rs
  runtime/near-vm-runner/Cargo.toml
  runtime/near-vm-runner/src/logic/errors.rs
  runtime/near-vm-runner/src/logic/tests/promises.rs
  runtime/runtime/Cargo.toml
  runtime/runtime/src/actions.rs
Labels: S-automerge

#9302 rust: 1.70.0 -> 1.71.0
  Cargo.toml
  chain/chunks/src/lib.rs
  core/crypto/src/lib.rs
  core/crypto/src/vrf.rs
  core/o11y/src/lib.rs
  core/store/src/trie/split_state.rs
  core/store/src/trie/trie_storage.rs
  runtime/near-vm-runner/src/logic/tests/context.rs
  runtime/near-vm-runner/src/near_vm_runner.rs
  runtime/near-vm-runner/src/tests/cache.rs
  runtime/near-vm-runner/src/wasmer2_runner.rs
  runtime/near-vm/compiler-singlepass/src/codegen_x64.rs
  runtime/near-vm/test-api/src/sys/import_object.rs
  runtime/near-vm/vm/src/table.rs
  runtime/runtime-params-estimator/emu-cost/Dockerfile
  rust-toolchain.toml
  tools/rpctypegen/core/src/lib.rs
  utils/stdx/src/lib.rs
Labels: S-automerge

#9311 fix(state-sync): Always use flat storage when catching up
  chain/chain/src/chain.rs
  chain/chain/src/metrics.rs
  core/store/src/flat/inlining_migration.rs
  tools/state-viewer/src/apply_chain_range.rs
Labels: S-automerge

#9308 fix(state-snapshot): Tool to make DB snapshots
  Cargo.lock
  core/store/src/opener.rs
  tools/database/Cargo.toml
  tools/database/README.md
  tools/database/src/commands.rs
  tools/database/src/lib.rs
  tools/database/src/make_snapshot.rs
Labels: S-automerge

#9307 chore(estimator): remove TTN read estimation
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/transaction_builder.rs
  runtime/runtime-params-estimator/src/trie.rs
Labels: S-automerge

#9279 feat: expose more RocksDB properties
  core/store/src/db/rocksdb.rs
Labels: A-storage, S-automerge

#9312 chain: remove deprecated near_peer_message_received_total metric
  chain/network/src/peer/peer_actor.rs
  chain/network/src/stats/metrics.rs
Labels: S-automerge

#9309 refactor: improvements to logging
  chain/chain/src/types.rs
  chain/client/src/client.rs
  core/o11y/src/testonly.rs
  integration-tests/src/tests/client/sharding_upgrade.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime/src/lib.rs
Labels: S-automerge

#9315 nearcore: remove old deprecation notice about network.external_address
  nearcore/src/config.rs
Labels: S-automerge

#9294 fix(state-sync): Test showing that state sync can't always generate state parts
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
Labels: S-automerge

#9289 fix(state-sync): Simplify storage format of state sync dump progress
  chain/chain/src/store.rs
  nearcore/src/state_sync.rs
  tools/state-viewer/src/scan_db.rs
Labels: S-automerge

#9314 Fix proxy-based nayduck tests so that they can run on non-unix systems.
  nightly/pytest-sanity.txt
  pytest/tests/sanity/block_chunk_signature.py
  pytest/tests/sanity/network_drop_package.py
  pytest/tests/sanity/proxy_example.py
  pytest/tests/sanity/proxy_restart.py
  pytest/tests/sanity/proxy_simple.py
  pytest/tests/sanity/sync_ban.py
Labels: S-automerge

#9320 fix: fixed nayduck test state_sync_fail.py for nightly build
  pytest/lib/cluster.py
  pytest/tests/sanity/state_sync_fail.py
Labels: S-automerge

#9276 feat: add database tool subcommand for State read perf testing
  Cargo.lock
  tools/database/Cargo.toml
  tools/database/README.md
  tools/database/src/adjust_database.rs
  tools/database/src/analyse_data_size_distribution.rs
  tools/database/src/commands.rs
  tools/database/src/lib.rs
  tools/database/src/state_perf.rs
  tools/database/src/utils.rs
Labels: A-storage, S-automerge, A-benchmark

#9187 RoutingTable V2: Distance Vector Routing
  chain/network/src/network_protocol/borsh_conv.rs
  chain/network/src/network_protocol/edge.rs
  chain/network/src/network_protocol/mod.rs
  chain/network/src/network_protocol/network.proto
  chain/network/src/network_protocol/proto_conv/peer_message.rs
  chain/network/src/peer/peer_actor.rs
  chain/network/src/peer_manager/network_state/mod.rs
  chain/network/src/peer_manager/network_state/routing.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge_cache/mod.rs
  chain/network/src/routing/edge_cache/testonly.rs
  chain/network/src/routing/edge_cache/tests.rs
  chain/network/src/routing/graph_v2/mod.rs
  chain/network/src/routing/graph_v2/testonly.rs
  chain/network/src/routing/graph_v2/tests.rs
  chain/network/src/routing/mod.rs
  chain/network/src/types.rs
Labels: S-automerge

#9250 refactor: todo to remove flat storage creation parameters
  core/store/src/config.rs
Labels: S-automerge

#9323 refactor(loadtest): backwards compatible type hints
  pytest/tests/loadtest/locust/common/base.py
  pytest/tests/loadtest/locust/common/ft.py
  pytest/tests/loadtest/locust/common/social.py
  pytest/tests/loadtest/locust/common/sweat.py
Labels: S-automerge

#9318 feat(state-sync): Add config for number of downloads during catchup
  chain/client/src/client.rs
  chain/client/src/sync/state.rs
  chain/client/src/sync/state_sync_actor.rs
  core/chain-configs/src/client_config.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
Labels: S-automerge

#9298 chore: Update RocksDB to 0.21
  Cargo.lock
  Cargo.toml
  core/store/src/db/rocksdb.rs
Labels: A-storage, S-automerge

#9328 [resharding] Refactor `build_state_for_split_shards` and related functions in one file
  chain/chain/src/chain.rs
  chain/chain/src/lib.rs
  chain/chain/src/resharding.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/client/src/client.rs
  chain/client/src/client_actor.rs
  chain/client/src/sync/state.rs
  chain/client/src/sync_jobs_actor.rs
  chain/client/src/test_utils.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge

#9300 [genesis] Initialize genesis outside runtime
  chain/chain/src/chain.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  core/primitives/src/runtime/config_store.rs
  core/store/src/genesis/initialization.rs
  core/store/src/genesis/mod.rs
  core/store/src/genesis/state_applier.rs
  core/store/src/lib.rs
  genesis-tools/genesis-populate/src/lib.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/runtime_utils.rs
  integration-tests/src/tests/client/process_blocks.rs
  integration-tests/src/tests/client/state_dump.rs
  integration-tests/src/tests/client/utils.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  nearcore/src/lib.rs
  nearcore/src/runtime/mod.rs
  nearcore/tests/economics.rs
  runtime/runtime/tests/runtime_group_tools/mod.rs
  test-utils/runtime-tester/src/run_test.rs
  tools/state-viewer/src/apply_chain_range.rs
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/commands.rs
  tools/state-viewer/src/state_dump.rs
  tools/storage-usage-delta-calculator/src/main.rs
Labels: S-automerge

#9316 Introduce block header V4 format to simplify block body verification.
  chain/chain/Cargo.toml
  chain/chain/src/chain.rs
  chain/chain/src/tests/simple_chain.rs
  chain/client/Cargo.toml
  chain/client/src/client.rs
  chain/client/src/tests/process_blocks.rs
  chain/epoch-manager/src/adapter.rs
  core/primitives-core/Cargo.toml
  core/primitives-core/src/version.rs
  core/primitives/Cargo.toml
  core/primitives/src/block.rs
  core/primitives/src/block_header.rs
  core/primitives/src/test_utils.rs
  core/primitives/src/views.rs
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/challenges.rs
  integration-tests/src/tests/client/process_blocks.rs
  pytest/lib/messages/block.py
  pytest/lib/proxy.py
  pytest/tests/sanity/block_chunk_signature.py
  pytest/tests/sanity/network_drop_package.py
  pytest/tests/sanity/proxy_simple.py
  pytest/tests/sanity/rpc_hash.py
  pytest/tests/sanity/staking2.py
  test-utils/testlib/src/process_blocks.rs
Labels: S-automerge

#9336 [doc] Update link to rewards calculation
  chain/epoch-manager/src/reward_calculator.rs
Labels: C-housekeeping, S-automerge

#9282 Adding ExternalConnection::GCS
  Cargo.lock
  Cargo.toml
  chain/client/Cargo.toml
  chain/client/src/sync/external.rs
  chain/client/src/sync/state.rs
  core/chain-configs/src/client_config.rs
  deny.toml
  docs/misc/state_sync_dump.md
  docs/misc/state_sync_from_s3.md
  nearcore/Cargo.toml
  nearcore/src/config_validate.rs
  nearcore/src/state_sync.rs
  tools/state-viewer/Cargo.toml
  tools/state-viewer/src/cli.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#9330 Add Routing Table view to debug UI
  chain/jsonrpc-primitives/src/types/status.rs
  chain/jsonrpc/src/api/status.rs
  chain/jsonrpc/src/lib.rs
  chain/network/src/debug.rs
  chain/network/src/peer_manager/peer_manager_actor.rs
  chain/network/src/routing/edge_cache/mod.rs
  chain/network/src/routing/graph_v2/mod.rs
  core/primitives/src/views.rs
  tools/debug-ui/src/NetworkInfoView.tsx
  tools/debug-ui/src/RoutingTableView.scss
  tools/debug-ui/src/RoutingTableView.tsx
  tools/debug-ui/src/api.tsx
Labels: S-automerge

#9334 [resharding] Remove progress counters from resharding as they are not used.
  Cargo.lock
  chain/chain/src/resharding.rs
  chain/client-primitives/Cargo.toml
  chain/client-primitives/src/types.rs
  chain/client/src/sync/state.rs
  chain/client/src/sync_jobs_actor.rs
  chain/client/src/test_utils.rs
Labels: S-automerge

#9333 fix(db-tool): Tool to run DB migrations
  tools/database/README.md
  tools/database/src/commands.rs
  tools/database/src/lib.rs
  tools/database/src/run_migrations.rs
Labels: S-automerge

#9342 [resharding] Move resharding tests to resharding.rs
  chain/chain/src/resharding.rs
  core/store/src/test_utils.rs
  core/store/src/trie/split_state.rs
Labels: S-automerge

#9340 fix(state-viewer): Scan db columns for incoming and outgoing receipts
  tools/state-viewer/src/scan_db.rs
Labels: S-automerge

#9238 update the CHANGELOG for 1.35.0
  CHANGELOG.md
Labels: S-automerge

#9348 Add borsh support for PeerMessage::DistanceVector
  chain/network/src/network_protocol/borsh.rs
  chain/network/src/network_protocol/borsh_conv.rs
Labels: S-automerge

#9345 feat: adding an integration test for the V1->V2 resharding
  integration-tests/Cargo.toml
  integration-tests/src/tests/client/sharding_upgrade.rs
Labels: S-automerge

#9351 fix(state-viewer): use hashes to determine scanning range
  tools/state-viewer/src/apply_chunk.rs
  tools/state-viewer/src/cli.rs
Labels: S-automerge

#9222 Stop accepting transactions when number of delayed receipts is large
  integration-tests/src/tests/client/process_blocks.rs
  nearcore/src/runtime/mod.rs
Labels: S-automerge, A-congestion

#9325 fix(loadtest): display better error on RpcError
  pytest/tests/loadtest/locust/common/base.py
Labels: S-automerge

#9366 doc: Add a changelog note about delayed receipts limit
  CHANGELOG.md
Labels: S-automerge, A-congestion

#9350 Restructure TrieStorage and implement correct semantics for state proofs
  chain/chain/src/flat_storage_creator.rs
  core/primitives/src/types.rs
  core/store/src/metrics.rs
  core/store/src/test_utils.rs
  core/store/src/trie/accounting_cache.rs
  core/store/src/trie/iterator.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/prefetching_trie_storage.rs
  core/store/src/trie/state_parts.rs
  core/store/src/trie/trie_recording.rs
  core/store/src/trie/trie_storage.rs
  core/store/src/trie/trie_tests.rs
  core/store/src/trie/update.rs
  docs/architecture/storage/trie.md
  docs/practices/workflows/io_trace.md
  integration-tests/src/tests/client/features/chunk_nodes_cache.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/standard_cases/mod.rs
  integration-tests/src/tests/standard_cases/runtime.rs
  nearcore/src/entity_debug.rs
  nearcore/src/runtime/mod.rs
  runtime/runtime-params-estimator/README.md
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/replay.rs
  runtime/runtime-params-estimator/src/replay/cache_stats.rs
  runtime/runtime-params-estimator/src/trie.rs
  runtime/runtime/src/prefetch.rs
  tools/state-viewer/src/contract_accounts.rs
  tools/state-viewer/src/state_parts.rs
Labels: S-automerge

#9338 fix(flat-storage and state-sync): Delay updating Flat Head to let us obtain state parts from a state snapshot
  chain/chain/src/chain.rs
  chain/chain/src/state_snapshot_actor.rs
  chain/client/src/test_utils.rs
  core/o11y/src/metrics.rs
  core/store/src/flat/delta.rs
  core/store/src/flat/metrics.rs
  core/store/src/flat/storage.rs
  core/store/src/flat/store_helper.rs
  core/store/src/flat/types.rs
  core/store/src/metadata.rs
  core/store/src/metrics.rs
  core/store/src/migrations.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/src/tests/client/flat_storage.rs
  integration-tests/src/tests/nearcore/sync_state_nodes.rs
  nearcore/src/migrations.rs
  nearcore/src/runtime/mod.rs
  neard/src/cli.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  tools/flat-storage/src/commands.rs
Labels: S-automerge

#9368 fix(flat-storage): Initiailze Flat Storage respecting the shards that the node will care about
  chain/chain/src/flat_storage_creator.rs
  core/chain-configs/src/client_config.rs
  nightly/pytest-sanity.txt
  pytest/lib/cluster.py
  pytest/tests/sanity/block_sync_flat_storage.py
Labels: S-automerge

#9349 Enable TIER1 outbound by default
  chain/network/src/config_json.rs
Labels: S-automerge

#9343 fix(state-sync): save to BlockMisc:STATE_SNAPSHOT_KEY the latest snapshot's hash
  core/store/src/db.rs
  core/store/src/lib.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/src/tests/nearcore/mod.rs
  integration-tests/src/tests/nearcore/state_snapshot.rs
Labels: S-automerge

#9372 Update CHANGELOG.md
  CHANGELOG.md
Labels: S-automerge
