Repository near/nearcore, pull requests merged in 2024-03, with the labels that each got.

#10690 refactor: use NightshadeRuntime in store_validator tests
  chain/chain/src/store_validator.rs
Labels: C-housekeeping

#10770 [Memtrie] Test to fix for trie recording bug.
  core/store/src/test_utils.rs
  core/store/src/trie/trie_tests.rs
Labels: A-stateless-validation

#10819 fix lychee lints
  chain/chunks/README.md
Labels: C-housekeeping, A-CI

#10764 yield/resume: gas fee estimations
  core/parameters/res/runtime_configs/139.yaml
  core/parameters/src/snapshots/near_parameters__config_store__tests__139.json.snap
  core/parameters/src/snapshots/near_parameters__config_store__tests__testnet_139.json.snap
  runtime/near-test-contracts/estimator-contract/src/lib.rs
  runtime/runtime-params-estimator/src/cost.rs
  runtime/runtime-params-estimator/src/estimator_context.rs
  runtime/runtime-params-estimator/src/lib.rs
  runtime/runtime-params-estimator/src/utils.rs
Labels: A-contract-runtime, A-params-estimator

#10880 Upgrade the 'insta' dependency to version 1.37.0 to fix cargo audit warning
  Cargo.lock
  Cargo.toml
  chain/chain/src/tests/simple_chain.rs
  core/parameters/src/config_store.rs
  core/store/src/db/colddb.rs
Labels: C-housekeeping

#10820 Enable in-memory trie when state sync
  chain/chain/src/chain.rs
  chain/chain/src/resharding.rs
  chain/chain/src/runtime/mod.rs
  chain/chain/src/runtime/tests.rs
  chain/chain/src/store_validator.rs
  chain/chain/src/test_utils.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/chunks/src/logic.rs
  chain/client/src/client.rs
  chain/client/src/client_actions.rs
  chain/client/src/info.rs
  chain/client/src/sync_jobs_actions.rs
  chain/client/src/test_utils/setup.rs
  core/store/src/config.rs
  core/store/src/test_utils.rs
  core/store/src/trie/config.rs
  core/store/src/trie/mem/loading.rs
  core/store/src/trie/shard_tries.rs
  integration-tests/src/genesis_helpers.rs
  integration-tests/src/tests/client/features/multinode_test_loop_example.rs
  integration-tests/src/tests/client/state_snapshot.rs
  tools/fork-network/src/cli.rs
  tools/speedy_sync/src/main.rs
Labels: A-stateless-validation

#10904 Fix gas charging when using recorded_storage + recording_reads(), bring back always recording storage
  chain/chain/src/chain.rs
  chain/chain/src/chain_update.rs
  chain/chain/src/runtime/mod.rs
  chain/chain/src/runtime/tests.rs
  chain/chain/src/test_utils/kv_runtime.rs
  chain/chain/src/types.rs
  chain/chain/src/update_shard.rs
  chain/client/src/client.rs
  chain/client/src/stateless_validation/chunk_validator/mod.rs
  chain/client/src/stateless_validation/shadow_validate.rs
  core/store/src/trie/mod.rs
  core/store/src/trie/trie_recording.rs
Labels: A-stateless-validation
